force-app/main/default/objects/Endesa_API__mdt/Endesa_API__mdt.object-meta.xml
<CustomObject>
    <description>Contient les infos permettant la connexion à l&apos;API Endesa</description>
    <label>Endesa API</label>
    <pluralLabel>Endesa APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Endesa_API__mdt/fields/Access_token__c.field-meta.xml
<CustomField>
    <fullName>Access_token__c</fullName>
    <label>Access token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endesa_API__mdt/fields/Refresh_token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_token__c</fullName>
    <label>Refresh token</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endesa_API__mdt/fields/Sandboxe__c.field-meta.xml
<CustomField>
    <fullName>Sandboxe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sandboxe ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateCustomMetadata.cls
public without sharing class UpdateCustomMetadata  {

    public static Boolean updateMetadata(String refresh, String access) {
        try {

            Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;

            // Recup des identifiants
            Endesa_API__mdt config = [
                SELECT DeveloperName
                FROM Endesa_API__mdt 
                WHERE Sandboxe__c = :isSandbox 
                LIMIT 1
            ];

            if(config != null)  {
                String fullName = 'Endesa_API.' + config.DeveloperName;
                asyncUpdateMetadata(fullName, refresh, access);
                return true;
            }

        } catch (Exception e) {
            System.debug(e.getMessage());
            return false;
        }

        return false;
    }


    @future
    public static void asyncUpdateMetadata(String fullName, String refresh, String access) {

        List<Metadata.Metadata> metadataretrieve = Metadata.Operations.retrieve(
            Metadata.MetadataType.CustomMetadata,
            new List<String>{ fullName }
        );

        Metadata.CustomMetadata customMetadataRecord = (Metadata.CustomMetadata) metadataretrieve.get(0);

        Metadata.CustomMetadataValue refreshvalue = new Metadata.CustomMetadataValue();
        refreshvalue.field = 'Refresh_token__c';
        refreshvalue.value = refresh;
        customMetadataRecord.values.add(refreshvalue);

        Metadata.CustomMetadataValue accessvalue = new Metadata.CustomMetadataValue();
        accessvalue.field = 'Access_token__c';
        accessvalue.value = access;
        customMetadataRecord.values.add(accessvalue);

        Metadata.DeployContainer myContainer = new Metadata.DeployContainer();
        myContainer.addMetadata(customMetadataRecord);

        CustomMetadataCallback callback = new CustomMetadataCallback();

        Id jobId = Metadata.Operations.enqueueDeployment(myContainer, callback);

        System.debug('JobId: ' + jobId);
    }


    public class CustomMetadataCallback implements Metadata.DeployCallback {
        public void handleResult(Metadata.DeployResult result,
                                Metadata.DeployCallbackContext context) {
                                
            if (result.status == Metadata.DeployStatus.Succeeded) {
                System.debug('success: '+ result);
            } else {
                System.debug('fail: '+ result);
            }
            
        }
    }

}