force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Opportunit__c.field-meta.xml
<CustomField>
    <fullName>Opportunit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>l_ments_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP008_AddPriceFTAFournisseur_TEST.cls
@isTest
private class AP008_AddPriceFTAFournisseur_TEST {
    
    @testSetup
    static void makeData(){
        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);
    }

    @isTest
    static void getPriceBookEntry() {

        Test.startTest();
        PricebookEntry pbEntrey = AP008_AddPriceFTAFournisseurController.getPriceBookEntry();
        Test.stopTest();

        Assert.isTrue(pbEntrey != null);
    }

    @isTest
    static void getOPRDetails() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        List<OpportunityPDERelation__c> oprList = AP008_AddPriceFTAFournisseurController.getOPRDetails(opp.Id);
        Test.stopTest();

        Assert.isTrue(oprList.size() != 0);
    }

    @isTest
    static void getQuoteWrappers() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        List<AP008_AddPriceFTAFournisseurController.QuoteWrapper> quoteList = AP008_AddPriceFTAFournisseurController.getQuoteWrappers(opp.Id);
        Test.stopTest();

        Assert.isTrue(quoteList.size() != 0);
    }

    @isTest
    static void insertListQLI() {
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        PricebookEntry pbEntrey = AP008_AddPriceFTAFournisseurController.getPriceBookEntry();
        Quote quote = [SELECT Id FROM Quote LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        for (OpportunityPDERelation__c opr  : AP008_AddPriceFTAFournisseurController.getOPRDetails(opp.Id)) {
            QuoteLineItem qli = new QuoteLineItem();
            qli.Product2Id = pbEntrey.Product2Id;
            qli.QuoteId = quote.Id;
            qli.PriceBookEntryId = pbEntrey.Id;
            qli.Quantity = 1;
            qli.UnitPrice = 0;
            qli.PDE__c = opr.pde__r.Id;
            qli.DureeEngagement__c = 34;
            qli.DebutdeFourniture__c = Date.today();
            qli.Opportunit__c = opp.Id;
            listQLI.add(qli);
        }

        Test.startTest();
        Boolean success = AP008_AddPriceFTAFournisseurController.insertListQLI(ListQLI);
        Test.stopTest();

        Assert.isTrue(success);
    }
    @isTest
    static void updateListQLI() {
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        PricebookEntry pbEntrey = AP008_AddPriceFTAFournisseurController.getPriceBookEntry();
        Quote quote = [SELECT Id FROM Quote LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        for (OpportunityPDERelation__c opr  : AP008_AddPriceFTAFournisseurController.getOPRDetails(opp.Id)) {
            QuoteLineItem qli = new QuoteLineItem();
            qli.Product2Id = pbEntrey.Product2Id;
            qli.QuoteId = quote.Id;
            qli.PriceBookEntryId = pbEntrey.Id;
            qli.Quantity = 1;
            qli.UnitPrice = 0;
            qli.PDE__c = opr.pde__r.Id;
            qli.DureeEngagement__c = 34;
            qli.DebutdeFourniture__c = Date.today();
            qli.Opportunit__c = opp.Id;
            listQLI.add(qli);
        }
        AP008_AddPriceFTAFournisseurController.insertListQLI(ListQLI);
        Test.startTest();
        List<AP008_AddPriceFTAFournisseurController.QuoteWrapper> quoteList = AP008_AddPriceFTAFournisseurController.getQuoteWrappers(opp.Id);
        Test.stopTest();

        Assert.isTrue(quoteList.size() != 0);
    }
}