force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AP005_CreateOPRFromFlow.cls
public with sharing class AP005_CreateOPRFromFlow {

    @invocableMethod(label='Créer list OpportunityPDERelation depuis Apex')
    public static List<FlowOutput> createOPR(List<FlowInputs> params) {

        FlowInputs param = params[0];
        FlowOutput output = new FlowOutput();
        List<FlowOutput> outputs = new List<FlowOutput>();
        List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
        for(PDE__c pde : param.SelectedPDEs){
            listOPR.add(
                new OpportunityPDERelation__c(
                    PDE__c = pde.Id,
                    Opportunity__c = param.OpportunityId
                )
            );
        }

        List<Database.SaveResult> listSR = Database.insert(listOPR);
        for(Database.SaveResult sr : listSR){
            if (!sr.isSuccess()) {
                output.DMLSuccess = false;
                outputs.add(output);
                return outputs;
            }
        }
        output.DMLSuccess = true;
        outputs.add(output);
        return outputs;
    }

    public class FlowInputs {
        @invocableVariable public String OpportunityId;
        @invocableVariable public List<PDE__c> SelectedPDEs;
    }
    
    public class FlowOutput {
        @InvocableVariable
        public Boolean DMLSuccess;
    }
}