force-app/main/default/objects/Config_Enedis__c/Config_Enedis__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Config_Enedis</label>
</CustomObject>

force-app/main/default/objects/Config_Enedis__c/fields/CertificateName__c.field-meta.xml
<CustomField>
    <fullName>CertificateName__c</fullName>
    <label>CertificateName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config_Enedis__c/fields/Endpoint_ConsulterDonneeTech__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_ConsulterDonneeTech__c</fullName>
    <label>Endpoint_ConsulterDonneeTech</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config_Enedis__c/fields/Endpoint_ConsulterMesure__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_ConsulterMesure__c</fullName>
    <label>Endpoint_ConsulterMesure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Config_Enedis__c/fields/timeout__c.field-meta.xml
<CustomField>
    <fullName>timeout__c</fullName>
    <label>timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mapping_FTA__mdt/Mapping_FTA__mdt.object-meta.xml
<CustomObject>
    <label>Mapping FTA</label>
    <pluralLabel>Mappings FTA</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mapping_FTA__mdt/fields/SF_FTA__c.field-meta.xml
<CustomField>
    <fullName>SF_FTA__c</fullName>
    <label>Salesforce FTA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Date_signature_ACD__c.field-meta.xml
<CustomField>
    <fullName>Date_signature_ACD__c</fullName>
    <label>Date de signature de l&apos;ACD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PSMaxInductive__c.field-meta.xml
<CustomField>
    <fullName>PSMaxInductive__c</fullName>
    <label>PS Max Inductive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SGEManager_Test.cls
@isTest
private class SGEManager_Test {
    
    @TestSetup
    static void createPDE(){
        PDE__c site = new PDE__c(ReferencePointEnergie_Refonte__c ='123456789', Date_signature_ACD__c = System.today());
        insert site;
        Config_Enedis__c config = new Config_Enedis__c(CertificateName__c='CertificatComodo6Years', Endpoint_ConsulterDonneeTech__c='test', Endpoint_ConsulterMesure__c='test', timeout__c= 12000);
        insert config;
        //Mapping_FTA__mdt fta = new Mapping_FTA__mdt(Masterlabel = 'BTINFCUST',label = 'BTINFCUST', SF_FTA__c= 'BT <= 36Kva - CU 4 postes');
        //insert fta;
    }

    @isTest
    static void callConsulterMesureTest() {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseConsulterMesure());
            WrapPDEInfoEnedis info = new WrapPDEInfoEnedis();
            PDE__c site = [SELECT id, ReferencePointEnergie_Refonte__c From PDE__c Limit 1];
            Test.startTest();
            SGEManager.callConsulterMesure(site.ReferencePointEnergie_Refonte__c, info);
            Test.stopTest();
            SGEManager.checkReponseStatus(MockHttpResponseConsulterMesure.response);
            SGEManager.getConsoByPoste(info,MockHttpResponseConsulterMesure.response); 
            SGEManager.updateSite(site.id,info);
    }

    @isTest
    static void callConsulterPointTest() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseConsulterPoint());
        WrapPDEInfoEnedis info = new WrapPDEInfoEnedis();
        PDE__c site = [SELECT id, ReferencePointEnergie_Refonte__c From PDE__c Limit 1];
        Test.startTest();
        SGEManager.consulterPoint(site.ReferencePointEnergie_Refonte__c, info);
        Test.stopTest();
        SGEManager.checkReponseStatus(MockHttpResponseConsulterPoint.response);
        SGEManager.readTechnicalInfo(info,MockHttpResponseConsulterPoint.response); 
        SGEManager.updateSite(site.id,info);
        
    }
    
    @isTest
    static void batchPsMaxTest() {
    	Test.setMock(HttpCalloutMock.class, new MockHttpResponseConsulterMesureDetaillee());
        BatchCalculatePsMax b = new BatchCalculatePsMax();
        PDE__c site = [SELECT Id, ReferencePointEnergie_Refonte__c from PDE__c where ReferencePointEnergie_Refonte__c ='123456789'];
        Test.startTest();
        Database.executeBatch (b,1);
        Test.stopTest();
        SGEManager.calculatePsMaxForAYear(site);
        site = [SELECT Id, PSMaxInductive__c from PDE__c where ReferencePointEnergie_Refonte__c ='123456789'];
        //system.assertEquals (35,site.PSMaxInductive__c);
    }
}