force-app/main/default/objects/CEE_Fournisseur__mdt/CEE_Fournisseur__mdt.object-meta.xml
<CustomObject>
    <label>CEE Fournisseur</label>
    <pluralLabel>CEE Fournisseurs</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEE_Fournisseur__mdt/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <label>CEE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEE_Fournisseur__mdt/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dyneff</fullName>
                <default>true</default>
                <label>Dyneff</label>
            </value>
            <value>
                <fullName>Enovos</fullName>
            </value>
            <value>
                <fullName>Gaz Européen</fullName>
            </value>
            <value>
                <fullName>MET Energie</fullName>
            </value>
            <value>
                <fullName>OHM Energie</fullName>
            </value>
            <value>
                <fullName>SEFE Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Consommation_Annuelle_de_R_f_rence_Elec__c.field-meta.xml
<CustomField>
    <fullName>Consommation_Annuelle_de_R_f_rence_Elec__c</fullName>
    <label>CAR Elec</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <label>CEE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inclus</fullName>
            </value>
            <value>
                <fullName>Soumis</fullName>
            </value>
            <value>
                <fullName>Non Soumis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CoutDeCapacite__c.field-meta.xml
<CustomField>
    <fullName>CoutDeCapacite__c</fullName>
    <label>Cout De Capacité</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/T_QuoteCEE__c.field-meta.xml
<CustomField>
    <fullName>T_QuoteCEE__c</fullName>
    <description>Récupération CEE de la quote parent pour la LWC</description>
    <formula>TEXT(Quote.CEE__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>T_QuoteCEE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_CalendrierFournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalendrierFournisseur__c</fullName>
    <label>TECH_CalendrierFournisseur</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_fournisseur__c</fullName>
    <formula>Quote.Fournisseur__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fournisseur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_Tarif__c.field-meta.xml
<CustomField>
    <fullName>TECH_Tarif__c</fullName>
    <formula>TEXT(PDE__r.Tarif__c)</formula>
    <label>TECH_Tarif</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/Valeur_Annuelle__mdt.object-meta.xml
<CustomObject>
    <label>Valeur Annuelle</label>
    <pluralLabel>Valeurs Annuelles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceInfOuEgal36Kva__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceInfOuEgal36Kva__c</fullName>
    <label>CSPE_PuissanceInfOuEgal36Kva</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T1__c.field-meta.xml
<CustomField>
    <fullName>CTA_T1__c</fullName>
    <label>CTA T1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T2__c.field-meta.xml
<CustomField>
    <fullName>CTA_T2__c</fullName>
    <label>CTA T2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T3__c.field-meta.xml
<CustomField>
    <fullName>CTA_T3__c</fullName>
    <label>CTA T3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T4__c.field-meta.xml
<CustomField>
    <fullName>CTA_T4__c</fullName>
    <label>CTA T4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP029_UpdateQLIFromOpp.cls
public with sharing class AP029_UpdateQLIFromOpp {

    @InvocableMethod(label='Maj Opp QLI')
    public static List<FlowOutput> updateOppQli(List<FlowInputs> flowInputs) {

        List<FlowOutput> listOutput = new List<FlowOutput>();
        FlowOutput output = new FlowOutput();

        List<Quote> quotes = [SELECT Id FROM Quote WHERE OpportunityId = :flowInputs[0].OppId];

        List<Id> setQuoteIds = new List<Id>();

        for (Quote q : quotes) {
            setQuoteIds.add(q.Id);
        }
        
        List<QuoteLineItem> listQli = [
            SELECT Id, PDE__c, Puissance_souscrite__c,
                   Conso_Base__c, ConsoHC__c, Conso_HCE__c, Conso_HCH__c,
                   ConsoHP__c, Conso_HPE__c, Conso_HPH__c, Conso_Pointe__c,
                   DureeEngagement__c, DebutDeFourniture__c, Nouvelle_Echeance__c,
                   QuoteId, TECH_CalendrierFournisseur__c, TECH_Tarif__c,TECH_fournisseur__c,
                   CoutDeCapacite__c, T_QuoteCEE__c
            FROM QuoteLineItem
            WHERE QuoteId IN :setQuoteIds
        ];

        Set<Id> setPDEIds = new Set<Id>();
        for (QuoteLineItem qli : listQli) {
            if (qli.PDE__c != null) {
                setPDEIds.add(qli.PDE__c);
            }
        }

        List<PDE__c> pdes = [
            SELECT Id, Puissance_souscrite__c, Conso_Base__c, ConsoHC__c,
                   Conso_HCE__c, Conso_HCH__c, ConsoHP__c,
                   Conso_HPE__c, Conso_HPH__c, Conso_Pointe__c,
                   Consommation_Annuelle_de_R_f_rence_Elec__c, CARGaz__c,
                   DateEcheance__c, Calendrier_fournisseur__c, Tarif__c,
                   TypePDE__c
            FROM PDE__c
            WHERE Id IN :setPDEIds
        ];

        updateqli(listQli, pdes);

        output.message = listQli.size() + ' QLI mis à jour.';
        listOutput.add(output);
        return listOutput;
    }

    public class FlowInputs {
        @InvocableVariable public String OppId;
    }

    public class FlowOutput {
        @InvocableVariable public String message;
    }

    // Méthode utilitaire pour mettre à jour les QuoteLineItems avec les données des PDE
    public static void updateqli(List<QuoteLineItem> qlis, List<PDE__c> pdes) {
        Map<Id, PDE__c> mapPdeById = new Map<Id, PDE__c>();
        for (PDE__c pde : pdes) {
            mapPdeById.put(pde.Id, pde);
        }

        Valeur_Annuelle__mdt customMetadataRecord = [SELECT CTA_T1__c,
                                                    CTA_T2__c,
                                                    CTA_T3__c,
                                                    CTA_T4__c,
                                                    CSPE_PuissanceInfOuEgal36Kva__c,
                                                    CSPE_PuissanceSup36OuEgal250__c,
                                                    CSPE_PuissanceSup250__c,
                                                    TICGN__c,
                                                    Frais_Transport_Distribution_Capacite_T1__c,
                                                    Frais_Transport_Distribution_Capacite_T2__c,
                                                    Frais_Transport_Distribution_Capacite_T3__c,
                                                    Frais_Transport_Distribution_Capacite_T4__c
                                                 FROM 
                                                    Valeur_Annuelle__mdt
                                                 LIMIT 1];
        /*
        Enchere_de_capacite__mdt customMetadataEnchereCapacite = [SELECT Montant__c
                                                    FROM 
                                                        Enchere_de_capacite__mdt
                                                    LIMIT 1   
                                                ];
        */

        Map<String,Double> mapFournisseurCEEGaz = new Map<String,Double>();
        Map<String,Double> mapFournisseurCEEElec =  new Map<String,Double>();
        for(CEE_Fournisseur__mdt CEEFournisseur : [SELECT CEE__c, Fournisseur__c, Type_energie__c FROM CEE_Fournisseur__mdt]){
            if (CEEFournisseur.Type_energie__c == 'Gaz') {
                mapFournisseurCEEGaz.put(CEEFournisseur.Fournisseur__c, CEEFournisseur.CEE__c);
            } else { // For 'Elec' Energy Type
                mapFournisseurCEEElec.put(CEEFournisseur.Fournisseur__c, CEEFournisseur.CEE__c);
            }
        }

        for (QuoteLineItem qli : qlis) {
            PDE__c pde = mapPdeById.get(qli.PDE__c);
            /*
            update dans QuoteLineItemTriggerHandler (Trigger after insert and update)
            qli.CoutDeCapacite__c = customMetadataEnchereCapacite != null ? customMetadataEnchereCapacite.Montant__c : 0;
            */
            if (pde != null) {
                Boolean isTypePDEGaz = (pde.TypePDE__c == 'Gaz');
                Map<String, Double> CEEValByCEEFournisseur = isTypePDEGaz ? mapFournisseurCEEGaz : mapFournisseurCEEElec;
                qli.Puissance_souscrite__c        = pde.Puissance_souscrite__c;
                qli.Conso_Base__c                 = pde.Conso_Base__c;
                qli.ConsoHC__c                    = pde.ConsoHC__c;
                qli.Conso_HCE__c                  = pde.Conso_HCE__c;
                qli.Conso_HCH__c                  = pde.Conso_HCH__c;
                qli.ConsoHP__c                    = pde.ConsoHP__c;
                qli.Conso_HPE__c                  = pde.Conso_HPE__c;
                qli.Conso_HPH__c                  = pde.Conso_HPH__c;
                qli.Conso_Pointe__c               = pde.Conso_Pointe__c;
                qli.DebutDeFourniture__c          = pde.DateEcheance__c != null ? pde.DateEcheance__c  + 1 : null;
                //qli.TECH_CalendrierFournisseur__c = pde.Calendrier_fournisseur__c;
                // version in SM001_GestionDevis
                if(pde.Calendrier_fournisseur__c == 'HP/HC' || pde.Calendrier_fournisseur__c == 'Heures Pleines/Creuses'){
                    qli.TECH_CalendrierFournisseur__c = 'HP/HC';
                }
                else if(pde.Calendrier_fournisseur__c == 'Base' || pde.Calendrier_fournisseur__c != ''){
                    qli.TECH_CalendrierFournisseur__c = 'Base';
                }

                if(isTypePDEGaz) {
                    if(pde.Tarif__c == 'T1'){
                        qli.CTA__c = customMetadataRecord.CTA_T1__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T1__c;
                    } else if(pde.Tarif__c == 'T2'){
                        qli.CTA__c = customMetadataRecord.CTA_T2__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T2__c;
                    } else if(pde.Tarif__c == 'T3'){
                        qli.CTA__c = customMetadataRecord.CTA_T3__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T3__c;
                    } else if(pde.Tarif__c == 'T4'){
                        qli.CTA__c = customMetadataRecord.CTA_T4__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T4__c;
                    } else {
                        qli.CTA__c = 1;
                        qli.FraisTransportDistributionCapacite__c = 1;
                    }
                    qli.CARGaz__c = pde.CARGaz__c;
                    qli.TICGN__c = customMetadataRecord.TICGN__c; 
                }
                else{
                    if(pde.Puissance_souscrite__c <= 36){
                        qli.CSPE__c = customMetadataRecord.CSPE_PuissanceInfOuEgal36Kva__c;
                    }
                    else if (pde.Puissance_souscrite__c > 36 && pde.Puissance_souscrite__c <= 250 ){
                        qli.CSPE__c = customMetadataRecord.CSPE_PuissanceSup36OuEgal250__c;
                    }
                    else {
                        qli.CSPE__c = customMetadataRecord.CSPE_PuissanceSup250__c;
                    }
                    // update dans QuoteLineItemTriggerHandler
                    //qli.CAR_New__c = pde.Consommation_Annuelle_de_R_f_rence_Elec__c;
                }
                
                if (qli.T_QuoteCEE__c != 'Non Soumis' && CEEValByCEEFournisseur.containsKey(qli.TECH_fournisseur__c)) {
                    qli.CeeMwh__c = CEEValByCEEFournisseur.get(qli.TECH_fournisseur__c);
                }

                if(qli.TECH_fournisseur__c.equals('Situation Actuelle')) {
                    qli.Nouvelle_Echeance__c = qli.DebutDeFourniture__c.addDays(-1);
                }
            }
        }
        update qlis;
    }

}