force-app/main/default/objects/Appel_qualite__c/Appel_qualite__c.object-meta.xml
<CustomObject>
    <label>Appel qualité</label>
    <nameField>
        <displayFormat>AQ-{000000}</displayFormat>
        <label>Appel qualité Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appels qualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_qualite__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Appels qualités</relationshipLabel>
    <relationshipName>Appels_qualites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Appel_qualite__c/fields/elements_conformes__c.field-meta.xml
<CustomField>
    <fullName>elements_conformes__c</fullName>
    <label>Éléments conformes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Elements_conforme</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_qualite__c/fields/TECH_Score_conformite__c.field-meta.xml
<CustomField>
    <fullName>TECH_Score_conformite__c</fullName>
    <label>Score de conformité</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appel_qualite__c/fields/Type_vente__c.field-meta.xml
<CustomField>
    <fullName>Type_vente__c</fullName>
    <label>Type de vente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type_vente</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Budget_HTVA_annee__c.field-meta.xml
<CustomField>
    <fullName>Budget_HTVA_annee__c</fullName>
    <label>Budget HTVA sur l&apos;année</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Budget_TTC_annee__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC_annee__c</fullName>
    <label>Budget TTC sur l&apos;année</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_ADE__c.field-meta.xml
<CustomField>
    <fullName>Commission_ADE__c</fullName>
    <label>Commission ADE €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_globale__c.field-meta.xml
<CustomField>
    <fullName>Commission_globale__c</fullName>
    <inlineHelpText>Commission globale générée par le contrat (Part ADE + Part Fournisseur)</inlineHelpText>
    <label>Commission globale €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_echeance__c</fullName>
    <label>Date d&apos;échéance</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FournisseurPicklist__c.field-meta.xml
<CustomField>
    <fullName>FournisseurPicklist__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrats</relationshipLabel>
    <relationshipName>Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Type_offre__c.field-meta.xml
<CustomField>
    <fullName>Type_offre__c</fullName>
    <label>Type d&apos;offre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>Offre clique</fullName>
            </value>
            <value>
                <fullName>Prestation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Elements_conforme.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S’est présenté comme travaillant avec ADE</fullName>
    </customValue>
    <customValue>
        <fullName>Nom et Prénom signataire</fullName>
    </customValue>
    <customValue>
        <fullName>Numéro de téléphone signataire</fullName>
    </customValue>
    <customValue>
        <fullName>Mail signataire</fullName>
    </customValue>
    <customValue>
        <fullName>Raison Sociale</fullName>
    </customValue>
    <customValue>
        <fullName>Numéro de SIRET</fullName>
    </customValue>
    <customValue>
        <fullName>Fournisseur</fullName>
    </customValue>
    <customValue>
        <fullName>Nombre de compteurs</fullName>
    </customValue>
    <customValue>
        <fullName>Durée d&apos;engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Date de démarrage</fullName>
    </customValue>
    <customValue>
        <fullName>Date de fin</fullName>
    </customValue>
    <customValue>
        <fullName>Le client est informé que son contrat actuel doit être résilié</fullName>
    </customValue>
    <customValue>
        <fullName>Avez-vous un exemplaire du contrat ?</fullName>
    </customValue>
    <customValue>
        <fullName>Énergie</fullName>
        <isActive>false</isActive>
        <label>Énergie</label>
    </customValue>
    <masterLabel>Éléments conforme</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Type_vente.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vente en direct</fullName>
    </customValue>
    <customValue>
        <fullName>Vente à distance</fullName>
    </customValue>
    <masterLabel>Type de vente</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AppelQualiteTriggerHanlder_TEST.cls
@isTest
public class AppelQualiteTriggerHanlder_TEST {

    @testSetup
    static void setupData() {

        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        Contract contract = new Contract();
        contract.Name = 'Test';
        contract.AccountId = acc.Id;
        contract.Opportunity__c = opp.Id;
        contract.FournisseurPicklist__c = 'Engie';
        contract.Type_offre__c = 'PRIX FIXE';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Date_echeance__c = Date.today();
        contract.Budget_TTC_annee__c = 1000;
        contract.Budget_HTVA_annee__c = 1000;
        contract.Commission_ADE__c = 1000;
        contract.Commission_globale__c = 1000;
        insert contract;

        }

    // Test pour la méthode beforeInsert
    @isTest
    static void testBeforeInsert() {
        // Création d'un enregistrement Appel_qualite__c avec des valeurs dans elements_conformes__c

        Contract contrat = [SELECT Id FROM CONTRACT LIMIT 1];
        Appel_qualite__c appelQualite = new Appel_qualite__c();
        
        appelQualite.elements_conformes__c = 'Nom et Prénom signataire;Mail signataire;Date de fin';
        appelQualite.Type_vente__c = 'Vente en direct';
        appelQualite.Contract__c = contrat.Id;

        // Insertion de l'enregistrement pour déclencher le trigger
        insert appelQualite;

        // Récupération de l'enregistrement inséré pour vérifier le calcul du score
        Appel_qualite__c insertedAppel = [SELECT TECH_Score_conformite__c FROM Appel_qualite__c WHERE Id = :appelQualite.Id];
        
        // Vérification du score calculé
        System.assertEquals(2, insertedAppel.TECH_Score_conformite__c, 'Le score de conformité doit être 2.');
    }

    // Test pour la méthode beforeUpdate
    @isTest
    static void testBeforeUpdate() {

        Contract contrat = [SELECT Id FROM CONTRACT LIMIT 1];

        // Création et insertion d'un enregistrement Appel_qualite__c initial
        Appel_qualite__c appelQualite = new Appel_qualite__c();
        appelQualite.elements_conformes__c = 'Nom et Prénom signataire;Mail signataire;Date de fin';
        appelQualite.Type_vente__c = 'Vente en direct';
        appelQualite.Contract__c = contrat.Id;
        insert appelQualite;

        // Modification de elements_conformes__c pour déclencher le calcul du score
        appelQualite.elements_conformes__c = 'Nom et Prénom signataire;Mail signataire';
        update appelQualite;

        // Récupération de l'enregistrement mis à jour pour vérifier le nouveau score
        Appel_qualite__c updatedAppel = [SELECT TECH_Score_conformite__c FROM Appel_qualite__c WHERE Id = :appelQualite.Id];
        
        // Vérification que le score a été recalculé
        System.assertEquals(1, updatedAppel.TECH_Score_conformite__c, 'Le score de conformité mis à jour doit être 1.');
    }

    // Test pour vérifier que le score est 0 si elements_conformes__c est null
    @isTest
    static void testNullElementsConformes() {

        Contract contrat = [SELECT Id FROM CONTRACT LIMIT 1];

        // Création d'un enregistrement Appel_qualite__c sans valeur pour elements_conformes__c
        Appel_qualite__c appelQualite = new Appel_qualite__c();
        appelQualite.Type_vente__c = 'Vente en direct';
        appelQualite.Contract__c = contrat.Id;
        insert appelQualite;

        // Récupération de l'enregistrement pour vérifier que le score est bien 0
        Appel_qualite__c insertedAppel = [SELECT TECH_Score_conformite__c FROM Appel_qualite__c WHERE Id = :appelQualite.Id];
        
        // Vérification que le score est bien 0
        System.assertEquals(0, insertedAppel.TECH_Score_conformite__c, 'Le score de conformité doit être 0 lorsque elements_conformes__c est null.');
    }
}