force-app/main/default/objects/Appel_qualite__c/Appel_qualite__c.object-meta.xml
<CustomObject>
    <label>Appel qualité</label>
    <nameField>
        <displayFormat>AQ-{000000}</displayFormat>
        <label>Appel qualité Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appels qualités</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_qualite__c/fields/elements_conformes__c.field-meta.xml
<CustomField>
    <fullName>elements_conformes__c</fullName>
    <label>Éléments conformes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Elements_conforme</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_qualite__c/fields/TECH_Score_conformite__c.field-meta.xml
<CustomField>
    <fullName>TECH_Score_conformite__c</fullName>
    <label>Score de conformité</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Elements_conforme.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S’est présenté comme travaillant avec ADE</fullName>
    </customValue>
    <customValue>
        <fullName>Nom et Prénom signataire</fullName>
    </customValue>
    <customValue>
        <fullName>Numéro de téléphone signataire</fullName>
    </customValue>
    <customValue>
        <fullName>Mail signataire</fullName>
    </customValue>
    <customValue>
        <fullName>Raison Sociale</fullName>
    </customValue>
    <customValue>
        <fullName>Numéro de SIRET</fullName>
    </customValue>
    <customValue>
        <fullName>Fournisseur</fullName>
    </customValue>
    <customValue>
        <fullName>Nombre de compteurs</fullName>
    </customValue>
    <customValue>
        <fullName>Durée d&apos;engagement</fullName>
    </customValue>
    <customValue>
        <fullName>Date de démarrage</fullName>
    </customValue>
    <customValue>
        <fullName>Date de fin</fullName>
    </customValue>
    <customValue>
        <fullName>Le client est informé que son contrat actuel doit être résilié</fullName>
    </customValue>
    <customValue>
        <fullName>Avez-vous un exemplaire du contrat ?</fullName>
    </customValue>
    <customValue>
        <fullName>Énergie</fullName>
        <isActive>false</isActive>
        <label>Énergie</label>
    </customValue>
    <masterLabel>Éléments conforme</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AppelQualiteTriggerHandler.cls
public with sharing class AppelQualiteTriggerHandler extends TriggerHandler {

    List<Appel_qualite__c> appQualiteList = new List<Appel_qualite__c>();
    List<Appel_qualite__c> updateappQualiteList = new List<Appel_qualite__c>();


    private Double calculateScore(List<String> listValue)   {
        System.debug('calculateScore');
        Double score = 0;
        for(String l : listValue) {
            if(/*l != 'Énergie' && */l != 'S’est présenté comme travaillant avec ADE' && l != 'Numéro de téléphone signataire' && l != 'Mail signataire')  {
                score += 1;
            }
        }
        return score;
    }

    public override void beforeInsert(){
        for(Appel_qualite__c aq : (List<Appel_qualite__c>)Trigger.New) {
            System.debug('aq.elements_conformes__c '+ aq.elements_conformes__c);
            aq.TECH_Score_conformite__c = aq.elements_conformes__c == null ? 0 : calculateScore(aq.elements_conformes__c.split(';'));
        }
    }

    public override void beforeUpdate(){
        System.debug('beforeUpdate');
        for(Appel_qualite__c aq :  (List<Appel_qualite__c>)Trigger.New){
            if(aq.elements_conformes__c != ((Appel_qualite__c)Trigger.oldMap.get(aq.Id)).elements_conformes__c){
                aq.TECH_Score_conformite__c = aq.elements_conformes__c == null ? 0 : calculateScore(aq.elements_conformes__c.split(';'));
            }
        }
    }
}