force-app/main/default/objects/Quote/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <label>Date de fin de contrat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Numero_Offre_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Numero_Offre_API_Endesa_Elec__c</fullName>
    <label>Numero Offre API Endesa Elec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TypeOffre__c.field-meta.xml
<CustomField>
    <fullName>TypeOffre__c</fullName>
    <label>Type d&apos;Offre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
                <default>true</default>
                <label>PRIX FIXE</label>
            </value>
            <value>
                <fullName>ARENH</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>SWAP ARENH</fullName>
                <isActive>false</isActive>
                <label>SWAP ARENH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Abonnement_Endesa_Elec_Souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Abonnement_Endesa_Elec_Souhaitee__c</fullName>
    <label>Abonnement Endesa Elec souhaitée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Budget_TTC__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC__c</fullName>
    <label>Budget TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CAR_New__c.field-meta.xml
<CustomField>
    <fullName>CAR_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CAR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Commission_Endesa_Elec_Souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Commission_Endesa_Elec_Souhaitee__c</fullName>
    <label>Commission Endesa Elec souhaitée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Opportunit__c.field-meta.xml
<CustomField>
    <fullName>Opportunit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>l_ments_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_fournisseur__c</fullName>
    <formula>Quote.Fournisseur__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fournisseur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_IdentifiantPDE__c.field-meta.xml
<CustomField>
    <fullName>TECH_IdentifiantPDE__c</fullName>
    <formula>IF(ISBLANK( PCE__c ), IF(ISBLANK(TECH_PdeReference__c),&apos;&apos;,TECH_PdeReference__c), PCE__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Identifiant PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_PdeReference__c.field-meta.xml
<CustomField>
    <fullName>TECH_PdeReference__c</fullName>
    <formula>PDE__r.TECH_num_compteur__c</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_QLI_Remplie__c.field-meta.xml
<CustomField>
    <fullName>TECH_QLI_Remplie__c</fullName>
    <formula>IF(
    AND(
		ISPICKVAL(PDE__r.FTA__c, &quot;BT &lt;= 36 kVA - CU&quot;),
        NOT(ISNULL(Nouvelle_Echeance__c)),
        PrixBase__c != 0
    ),
    &apos;&lt;span style=&quot;border-radius: 15px;background:green; padding: 4px; font-weight: bold; color: #FFF&quot;&gt;√&lt;/span&gt;&apos;,
    IF(
        AND(
			ISPICKVAL(PDE__r.FTA__c, &quot;BT &lt;= 36 kVA - MU&quot;),
            PrixHP__c != 0,
            PrixHC__c != 0,
            NOT(ISNULL(Nouvelle_Echeance__c))
        ),
        &apos;&lt;span style=&quot;border-radius: 15px;background:green; padding: 4px; font-weight: bold; color: #FFF&quot;&gt;√&lt;/span&gt;&apos;,
            IF(
                AND(
                    OR(
						ISPICKVAL(PDE__r.FTA__c, &quot;BT &lt;= 36Kva - CU 4 postes&quot;),
						ISPICKVAL(PDE__r.FTA__c, &quot;BT &lt;= 36Kva - MU 4 postes&quot;),
						ISPICKVAL(PDE__r.FTA__c, &quot;BT &gt; 36 kVA - LU&quot;),
						ISPICKVAL(PDE__r.FTA__c, &quot;BT &gt; 36 kVA - CU&quot;)),
                    PrixHphMwh__c != 0,
                    PrixHchMwh__c != 0,
                    PrixHpeMwh__c != 0,
                    PrixHceMwh__c != 0,
                    NOT(ISNULL(Nouvelle_Echeance__c))
                ),
                &apos;&lt;span style=&quot;border-radius: 15px;background:green; padding: 4px; font-weight: bold; color: #FFF&quot;&gt;√&lt;/span&gt;&apos;,
                    IF(
                        AND(
                            OR( 
								ISPICKVAL(PDE__r.FTA__c, &quot;HTA - PF - CU&quot;),
								ISPICKVAL(PDE__r.FTA__c, &quot;HTA - PF - LU&quot;),
								ISPICKVAL(PDE__r.FTA__c, &quot;HTA - PM - CU&quot;),
								ISPICKVAL(PDE__r.FTA__c, &quot;HTA - PM - LU&quot;)),
                            PrixHphMwh__c != 0,
                            PrixHchMwh__c != 0,
                            PrixHpeMwh__c != 0,
                            PrixHceMwh__c != 0,
                            PointesMWh__c != 0,
                            NOT(ISNULL(Nouvelle_Echeance__c))
                        ),
                        &apos;&lt;span style=&quot;border-radius: 15px;background:green; padding: 4px; font-weight: bold; color: #FFF&quot;&gt;√&lt;/span&gt;&apos;,
                    IF(
                        AND(TECH_RT__c = &apos;PDE_Gaz&apos;,
                            AbonnementMois__c != 0,
                            PrixMolecule__c != 0,
                            NOT(ISNULL(Nouvelle_Echeance__c))),
                            &apos;&lt;span style=&quot;border-radius: 15px;background:green; padding: 4px; font-weight: bold; color: #FFF&quot;&gt;√&lt;/span&gt;&apos;,
                            &apos;&lt;span style=&quot;border-radius: 15px;background:red; padding: 4px; font-weight: bold; color: #FFF&quot;&gt;X&lt;/span&gt;&apos;
)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QLI Remplie</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_TypePDL__c.field-meta.xml
<CustomField>
    <fullName>TECH_TypePDL__c</fullName>
    <formula>PDE__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_TypePDL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP010_ShowRelatedRecordsController.cls
public without sharing class AP010_ShowRelatedRecordsController {

    @AuraEnabled
    public static List<Quote> getRelatedQuotes(Id recordId){
        Id oppId = [SELECT OpportunityId FROM Quote WHERE Id =: recordId LIMIT 1].OpportunityId;
        return [SELECT Name, Date_de_fin_de_contrat__c, toLabel(TypeOffre__c), GrandTotal, OpportunityId FROM Quote WHERE OpportunityId =: oppId AND Id != :recordId];
    }

    @AuraEnabled
    public static List<QuoteLineItem> getRelatedQLIs(Id recordId){
        Id oppId = [SELECT Opportunit__c FROM QuoteLineItem WHERE Id =: recordId LIMIT 1].Opportunit__c;
        return [SELECT Opportunit__c, TECH_IdentifiantPDE__c, DebutDeFourniture__c,toLabel(Quote.TypeOffre__c), Nouvelle_Echeance__c, TECH_fournisseur__c, Budget_TTC__c, CAR_New__c,CARGaz__c ,TECH_TypePDL__c,TECH_QLI_Remplie__c FROM QuoteLineItem WHERE Opportunit__c =: oppId AND Id != :recordId];
    }

    @AuraEnabled
    public static List<QuoteLineItem> getRelatedEndesaElecQLIs(Id recordId){
        return [SELECT TECH_PdeReference__c, Abonnement_Endesa_Elec_Souhaitee__c, Commission_Endesa_Elec_Souhaitee__c, Quote.Numero_Offre_API_Endesa_Elec__c FROM QuoteLineItem WHERE QuoteId =: recordId];
    }
}