force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Maximum_date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Maximum_date_de_fin__c</fullName>
    <label>Maximum date de fin</label>
    <summarizedField>QuoteLineItem.Nouvelle_Echeance__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Minimum_date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Minimum_date_de_debut__c</fullName>
    <label>Minimum date de début</label>
    <summarizedField>QuoteLineItem.DebutDeFourniture__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TECH_FournisseurLogo__c.field-meta.xml
<CustomField>
    <fullName>TECH_FournisseurLogo__c</fullName>
    <formula>CASE( Fournisseur__c,
&quot;Antargaz&quot;,&quot;antargaz.png&quot;,
&quot;Alterna&quot;,&quot;alterna.png&quot;,
&quot;Dyneff&quot;,&quot;dyneff.png&quot;,
&quot;EDF Entreprises&quot;,&quot;edf.png&quot;,
&quot;Ekwateur&quot;,&quot;ekwateur.png&quot;,
&quot;Electricité de Provence&quot;,&quot;electricitedeprovence.png&quot;,
&quot;Electricité de Strasbourg&quot;,&quot;electricitedestrasbourg.png&quot;,
&quot;Endesa&quot;,&quot;endesa.png&quot;,
&quot;Enercoop&quot;,&quot;enercoop.png&quot;,
&quot;Engie&quot;,&quot;engie.png&quot;,
&quot;Eni&quot;,&quot;eni.png&quot;,
&quot;Enovos&quot;,&quot;enovos.png&quot;,
&quot;Dalkia&quot;,&quot;dalkia.png&quot;,
&quot;Gaz de Bordeaux&quot;,&quot;gazdebordeaux.png&quot;,
&quot;Gaz Européen&quot;,&quot;gazeuropeen.png&quot;,
&quot;Gazel Energie&quot;,&quot;gazelenergie.png&quot;,
&quot;GEG&quot;,&quot;geg.png&quot;,
&quot;Iberdrola&quot;,&quot;iberdrola.png&quot;,
&quot;Ilek&quot;,&quot;ilek.png&quot;,
&quot;La Bellenergie&quot;,&quot;labellenergie.png&quot;,
&quot;LLUM&quot;,&quot;llum.png&quot;,
&quot;MET Energie&quot;,&quot;metenergie.png&quot;,
&quot;OHM Energie&quot;,&quot;ohmenergie.png&quot;,
&quot;Picoty&quot;,&quot;picoty.png&quot;,
&quot;Planete OUI&quot;,&quot;planeteoui.png&quot;,
&quot;Primeo Energie&quot;,&quot;primeoenergie.png&quot;,
&quot;Save Energies&quot;,&quot;saveenergies.png&quot;,
&quot;SEFE Energy&quot;,&quot;SEFE.png&quot;,
&quot;Situation Actuelle&quot;, &quot;Situation_Actuelle.png&quot;,
&quot;Proposition Renouvellement&quot;, &quot;Proposition_Renouvellement.png&quot;,
&quot;Selia&quot;,&quot;selia.png&quot;,
&quot;TotalEnergies&quot;,&quot;totalenergies.png&quot;,
&quot;Total&quot;,&quot;totalenergies.png&quot;,
&quot;Vattenfall&quot;,&quot;vattenfall.png&quot;,
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Fournisseur Logo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalBudgetTTC__c.field-meta.xml
<CustomField>
    <fullName>TotalBudgetTTC__c</fullName>
    <label>Total Budget TTC</label>
    <summarizedField>QuoteLineItem.Budget_TTC__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TypeOffre__c.field-meta.xml
<CustomField>
    <fullName>TypeOffre__c</fullName>
    <label>Type d&apos;Offre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
                <default>true</default>
                <label>PRIX FIXE</label>
            </value>
            <value>
                <fullName>ARENH</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>SWAP ARENH</fullName>
                <isActive>false</isActive>
                <label>SWAP ARENH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WrapFournisseur.cls
public with sharing class WrapFournisseur implements Comparable{
  public String NomFournisseur {get;set;}
  public String logo {get;set;}
  public Integer numberOfQLI {get;set;}
  public Decimal TotalBudgetTTC {get;set;}
  public String typeOffre {get;set;}
  public List<WrapLigneDeDevis> listQLI {get;set;}
  public Map<String,WrapLigneDeDevis> mapQLI {get;set;}
  public Integer minDateYear {get;set;}
  public Integer maxDateYear {get;set;}

  public Decimal prixMoyenParAn {
    get{
        return TotalBudgetTTC / numberOfQLI;
    }set;
  }

  
  public WrapFournisseur(Quote quote, List<WrapLigneDeDevis> qlis){
    typeOffre = quote.TypeOffre__c;
    NomFournisseur = quote.Fournisseur__c;
    logo = quote.TECH_FournisseurLogo__c;
    numberOfQLI = quote.LineItemCount;
    TotalBudgetTTC = quote.TotalBudgetTTC__c;
    listQLI = qlis;
  }

  public WrapFournisseur(Quote quote, Map<String,WrapLigneDeDevis> mapQLIs, List<WrapLigneDeDevis> qlis){
    typeOffre = quote.TypeOffre__c;
    NomFournisseur = quote.Fournisseur__c;
    logo = quote.TECH_FournisseurLogo__c;
    numberOfQLI = quote.LineItemCount;
    TotalBudgetTTC = quote.TotalBudgetTTC__c;
    mapQLI = mapQLIs;
    minDateYear = quote.Minimum_date_de_debut__c.year();
    maxDateYear = quote.Maximum_date_de_fin__c.year();
    listQLI = qlis;
  }

  public Integer compareTo(Object compareTo) {
    WrapFournisseur compareToWF = (WrapFournisseur)compareTo;
    
    // The return value of 0 indicates that both elements are equal.
    Integer returnValue = 0;
    if ((this.prixMoyenParAn == null) && (compareToWF.prixMoyenParAn == null)) {
        // both wrappers have null prixMoyenParAns
        returnValue = 0;
    } else if ((this.prixMoyenParAn == null) && (compareToWF.prixMoyenParAn != null)){
        // nulls-first implementation
        returnValue = -1;
    } else if ((this.prixMoyenParAn != null) && (compareToWF.prixMoyenParAn == null)){
        // nulls-first implementation
        returnValue = 1;
    } else if (this.prixMoyenParAn > compareToWF.prixMoyenParAn) {
        // Set return value to a positive value.
        returnValue = 1;
    } else if (this.prixMoyenParAn < compareToWF.prixMoyenParAn) {
        // Set return value to a negative value.
        returnValue = -1;
    } 
    return returnValue;
  }
}