force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/AppelEnCours__c.field-meta.xml
<CustomField>
    <fullName>AppelEnCours__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</description>
    <inlineHelpText>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</inlineHelpText>
    <label>Appel en cours ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/BudgetTotalActuel__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalActuel__c</fullName>
    <label>Budget Total Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/BudgetTotalOptimal__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalOptimal__c</fullName>
    <label>Budget Total Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DatePremierAppel__c.field-meta.xml
<CustomField>
    <fullName>DatePremierAppel__c</fullName>
    <description>Date du Premier Appel effectué à Homeys</description>
    <inlineHelpText>Date du Premier Appel effectué à Homeys</inlineHelpText>
    <label>Date du Premier Appel</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DepassementActuel__c.field-meta.xml
<CustomField>
    <fullName>DepassementActuel__c</fullName>
    <label>Dépassement Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DepassementOptimal__c.field-meta.xml
<CustomField>
    <fullName>DepassementOptimal__c</fullName>
    <label>Dépassement Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EconomieIdentifie__c.field-meta.xml
<CustomField>
    <fullName>EconomieIdentifie__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Economie identifiée (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCEActuel__c.field-meta.xml
<CustomField>
    <fullName>HCEActuel__c</fullName>
    <label>HCE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCEOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCEOptimal__c</fullName>
    <label>HCE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCHActuel__c.field-meta.xml
<CustomField>
    <fullName>HCHActuel__c</fullName>
    <label>HCH Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCHOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCHOptimal__c</fullName>
    <label>HCH Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPEActuel__c.field-meta.xml
<CustomField>
    <fullName>HPEActuel__c</fullName>
    <label>HPE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPEOptimal__c.field-meta.xml
<CustomField>
    <fullName>HPEOptimal__c</fullName>
    <label>HPE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPHActuel__c.field-meta.xml
<CustomField>
    <fullName>HPHActuel__c</fullName>
    <label>HPH Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPHOptimal__c.field-meta.xml
<CustomField>
    <fullName>HPHOptimal__c</fullName>
    <label>HPH Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdAnalyse__c.field-meta.xml
<CustomField>
    <fullName>IdAnalyse__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Analyse</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdBuilding__c.field-meta.xml
<CustomField>
    <fullName>IdBuilding__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Building</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdSource__c.field-meta.xml
<CustomField>
    <fullName>IdSource__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <label>Id Source</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartFixeCSActuel__c.field-meta.xml
<CustomField>
    <fullName>PartFixeCSActuel__c</fullName>
    <label>Part Fixe de la CS Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartFixeCSOptimal__c.field-meta.xml
<CustomField>
    <fullName>PartFixeCSOptimal__c</fullName>
    <label>Part Fixe de la CS Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartVariableCSActuel__c.field-meta.xml
<CustomField>
    <fullName>PartVariableCSActuel__c</fullName>
    <label>Part Variable de la CS Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartVariableCSOptimal__c.field-meta.xml
<CustomField>
    <fullName>PartVariableCSOptimal__c</fullName>
    <label>Part Variable de la CS Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/POINTEActuel__c.field-meta.xml
<CustomField>
    <fullName>POINTEActuel__c</fullName>
    <label>POINTE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/POINTEOptimal__c.field-meta.xml
<CustomField>
    <fullName>POINTEOptimal__c</fullName>
    <label>POINTE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PSMaxActive__c.field-meta.xml
<CustomField>
    <fullName>PSMaxActive__c</fullName>
    <label>PS Max Active</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SignataireACD__c.field-meta.xml
<CustomField>
    <fullName>SignataireACD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signataire ACD</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Points d&apos;énergie (Signataire ACD)</relationshipLabel>
    <relationshipName>PointEnergies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TaxeCTAActuel__c.field-meta.xml
<CustomField>
    <fullName>TaxeCTAActuel__c</fullName>
    <label>Taxe CTA Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TaxeCTAOptimal__c.field-meta.xml
<CustomField>
    <fullName>TaxeCTAOptimal__c</fullName>
    <label>Taxe CTA Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C3_C4.recordType-meta.xml
<RecordType>
    <fullName>Elec_C3_C4</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C3 à C4</description>
    <label>Elec C3 à C4</label>
</RecordType>

force-app/main/default/classes/AP034_TURPEOptimisationController_TEST.cls
@isTest
private class AP034_TURPEOptimisationController_TEST {
    @testSetup
    static void setupData() {
        TestDataFactory.createDataForComparatifElec();
    }

    private static Id getEligibleRecordTypeId() {
        return [
            SELECT Id
            FROM RecordType
            WHERE SObjectType = 'PDE__c' AND DeveloperName = 'Elec_C3_C4'
            LIMIT 1
        ]
        .Id;
    }

    private static PDE__c loadBasePDE() {
        return [
            SELECT
                Id,
                EntiteJuridique__c,
                SignataireACD__c,
                AppelEnCours__c,
                IdAnalyse__c,
                IdSource__c,
                IdBuilding__c,
                DatePremierAppel__c,
                Puissance_souscrite__c,
                PSMaxActive__c,
                RecordTypeId,
                HCEActuel__c,
                HPEActuel__c,
                HCHActuel__c,
                HPHActuel__c,
                POINTEActuel__c,
                HCEOptimal__c,
                HPEOptimal__c,
                HCHOptimal__c,
                HPHOptimal__c,
                POINTEOptimal__c,
                PartFixeCSActuel__c,
                PartVariableCSActuel__c,
                DepassementActuel__c,
                TaxeCTAActuel__c,
                PartFixeCSOptimal__c,
                PartVariableCSOptimal__c,
                DepassementOptimal__c,
                TaxeCTAOptimal__c,
                BudgetTotalActuel__c,
                BudgetTotalOptimal__c,
                EconomieIdentifie__c,
                Conso_HCE__c,
                Conso_HPE__c,
                Conso_HCH__c,
                Conso_HPH__c,
                Conso_Pointe__c
            FROM PDE__c
            LIMIT 1
        ];
    }

    @isTest
    static void testGetInfos_MonoSite() {
        PDE__c p = loadBasePDE();
        p.BudgetTotalActuel__c = 12000;
        p.BudgetTotalOptimal__c = 10000;
        p.EconomieIdentifie__c = 2000;

        p.Conso_HCE__c = 100;
        p.Conso_HPE__c = 200;
        p.Conso_HCH__c = 300;
        p.Conso_HPH__c = 400;
        p.Conso_Pointe__c = 500;
        update p;

        Test.startTest();
        Map<String, Object> res = AP034_TURPEOptimisationController.getInfosTurpeByAccount(
            p.EntiteJuridique__c
        );
        Test.stopTest();

        Assert.areEqual(true, res.get('isMonoSite'));
        Assert.areEqual(12000, res.get('totalBudgetActuel'));
        Assert.areEqual(10000, res.get('totalBudgetOptimal'));
        Assert.areEqual(2000, res.get('totalEconomie'));
        Assert.areNotEqual(null, res.get('noteDateText'));
        Assert.isTrue(((String) res.get('noteConsoText')).contains('HCE'));
    }

    @isTest
    static void testGetInfos_MultiSite() {
        PDE__c p1 = loadBasePDE();
        PDE__c p2 = p1.clone(false, false, false, false);
        p2.Name = 'PDE CLONE';
        insert p2;

        for (PDE__c p : new List<PDE__c>{ p1, p2 }) {
            p.BudgetTotalActuel__c = 10000;
            p.BudgetTotalOptimal__c = 8000;
            p.EconomieIdentifie__c = 2000;
        }
        update new List<PDE__c>{ p1, p2 };

        Test.startTest();
        Map<String, Object> res = AP034_TURPEOptimisationController.getInfosTurpeByAccount(
            p1.EntiteJuridique__c
        );
        Test.stopTest();

        Assert.areEqual(false, res.get('isMonoSite'));
        Assert.areEqual(20000, res.get('totalBudgetActuel'));
        Assert.areEqual(16000, res.get('totalBudgetOptimal'));
        Assert.areEqual(4000, res.get('totalEconomie'));
        Assert.areEqual(null, res.get('noteConsoText'));
    }

    @isTest
    static void testGetInfos_NoPDE() {
        Account acc = new Account(Name = 'EMPTY');
        insert acc;

        Test.startTest();
        Map<String, Object> res = AP034_TURPEOptimisationController.getInfosTurpeByAccount(
            acc.Id
        );
        Test.stopTest();

        Assert.areEqual(true, res.get('isMonoSite'));
        Assert.areEqual(0, res.get('totalBudgetActuel'));
        Assert.areEqual(0, res.get('totalEconomie'));
        Assert.areEqual(null, res.get('noteConsoText'));
    }

    @isTest
    static void test_NotEligible_AppelEnCours() {
        PDE__c p = loadBasePDE();
        p.RecordTypeId = getEligibleRecordTypeId();
        p.AppelEnCours__c = true;
        update p;

        Test.startTest();
        AP034_TURPEOptimisationController.invokeTURPEIfEligible(p.Id);
        Test.stopTest();

        Assert.isTrue(true);
    }

    @isTest
    static void test_OPTIMISATION_RENEW() {
        PDE__c p = loadBasePDE();

        p.RecordTypeId = getEligibleRecordTypeId();
        p.SignataireACD__c = getAnyContactId(); // 🔑 CLÉ
        p.Puissance_souscrite__c = 100;
        p.PSMaxActive__c = 50; // taux = 50 %

        p.IdAnalyse__c = 'ANA_RENEW';
        p.IdSource__c = 'SRC';
        p.IdBuilding__c = 'BUILD';
        p.DatePremierAppel__c = Date.today().addMonths(-4);

        update p;

        Test.startTest();
        AP034_TURPEOptimisationController.invokeTURPEIfEligible(p.Id);
        Test.stopTest();

        Assert.isTrue(true);
    }

    @isTest
    static void test_RENOUVELLEMENT_missingFields() {
        PDE__c p = loadBasePDE();

        p.RecordTypeId = getEligibleRecordTypeId();
        p.SignataireACD__c = getAnyContactId(); // 🔑
        p.Puissance_souscrite__c = 100;
        p.PSMaxActive__c = 50;

        p.IdAnalyse__c = 'ANA_MISS';
        p.IdSource__c = 'SRC';
        p.IdBuilding__c = 'BUILD';
        p.DatePremierAppel__c = Date.today();

        // Déclenche la formule
        p.HCEActuel__c = null;

        update p;

        Test.startTest();
        AP034_TURPEOptimisationController.invokeTURPEIfEligible(p.Id);
        Test.stopTest();

        Assert.isTrue(true);
    }

    @isTest
    static void test_OPTIMISATION_default() {
        PDE__c p = loadBasePDE();

        p.RecordTypeId = getEligibleRecordTypeId();
        p.SignataireACD__c = getAnyContactId(); // 🔑
        p.Puissance_souscrite__c = 100;
        p.PSMaxActive__c = 50;

        p.IdAnalyse__c = 'ANA_OK';
        p.IdSource__c = 'SRC_OK';
        p.IdBuilding__c = 'BUILD';
        p.DatePremierAppel__c = Date.today();

        // Champs complets → formule = false
        p.HCEActuel__c = 1;
        p.HPEActuel__c = 1;
        p.HCHActuel__c = 1;
        p.HPHActuel__c = 1;
        p.POINTEActuel__c = 1;

        p.HCEOptimal__c = 1;
        p.HPEOptimal__c = 1;
        p.HCHOptimal__c = 1;
        p.HPHOptimal__c = 1;
        p.POINTEOptimal__c = 1;

        p.PartFixeCSActuel__c = 1;
        p.PartVariableCSActuel__c = 1;
        p.DepassementActuel__c = 1;
        p.TaxeCTAActuel__c = 1;

        p.PartFixeCSOptimal__c = 1;
        p.PartVariableCSOptimal__c = 1;
        p.DepassementOptimal__c = 1;
        p.TaxeCTAOptimal__c = 1;

        p.BudgetTotalActuel__c = 100;
        p.BudgetTotalOptimal__c = 80;
        p.EconomieIdentifie__c = 20;

        update p;

        Test.startTest();
        AP034_TURPEOptimisationController.invokeTURPEIfEligible(p.Id);
        Test.stopTest();

        Assert.isTrue(true);
    }

    @isTest
    static void test_NullId_NoCrash() {
        Test.startTest();
        AP034_TURPEOptimisationController.invokeTURPEIfEligible(null);
        Test.stopTest();
        Assert.isTrue(true);
    }

    private static Id getAnyContactId() {
        return [SELECT Id FROM Contact LIMIT 1].Id;
    }
}