force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/AppelEnCours__c.field-meta.xml
<CustomField>
    <fullName>AppelEnCours__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</description>
    <inlineHelpText>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</inlineHelpText>
    <label>Appel en cours ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/BudgetTotalActuel__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalActuel__c</fullName>
    <label>Budget Total Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/BudgetTotalOptimal__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalOptimal__c</fullName>
    <label>Budget Total Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DatePremierAppel__c.field-meta.xml
<CustomField>
    <fullName>DatePremierAppel__c</fullName>
    <description>Date du Premier Appel effectué à Homeys</description>
    <inlineHelpText>Date du Premier Appel effectué à Homeys</inlineHelpText>
    <label>Date du Premier Appel</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DepassementActuel__c.field-meta.xml
<CustomField>
    <fullName>DepassementActuel__c</fullName>
    <label>Dépassement Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DepassementOptimal__c.field-meta.xml
<CustomField>
    <fullName>DepassementOptimal__c</fullName>
    <label>Dépassement Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EconomieIdentifie__c.field-meta.xml
<CustomField>
    <fullName>EconomieIdentifie__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Economie identifiée (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCEActuel__c.field-meta.xml
<CustomField>
    <fullName>HCEActuel__c</fullName>
    <label>HCE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCEOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCEOptimal__c</fullName>
    <label>HCE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCHActuel__c.field-meta.xml
<CustomField>
    <fullName>HCHActuel__c</fullName>
    <label>HCH Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCHOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCHOptimal__c</fullName>
    <label>HCH Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPEActuel__c.field-meta.xml
<CustomField>
    <fullName>HPEActuel__c</fullName>
    <label>HPE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPEOptimal__c.field-meta.xml
<CustomField>
    <fullName>HPEOptimal__c</fullName>
    <label>HPE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPHActuel__c.field-meta.xml
<CustomField>
    <fullName>HPHActuel__c</fullName>
    <label>HPH Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HPHOptimal__c.field-meta.xml
<CustomField>
    <fullName>HPHOptimal__c</fullName>
    <label>HPH Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdAnalyse__c.field-meta.xml
<CustomField>
    <fullName>IdAnalyse__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Analyse</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdBuilding__c.field-meta.xml
<CustomField>
    <fullName>IdBuilding__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Building</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdSource__c.field-meta.xml
<CustomField>
    <fullName>IdSource__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <label>Id Source</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/InterventionPEPS__c.field-meta.xml
<CustomField>
    <fullName>InterventionPEPS__c</fullName>
    <label>Intervention PEP&apos;S (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartFixeCSActuel__c.field-meta.xml
<CustomField>
    <fullName>PartFixeCSActuel__c</fullName>
    <label>Part Fixe de la CS Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartFixeCSOptimal__c.field-meta.xml
<CustomField>
    <fullName>PartFixeCSOptimal__c</fullName>
    <label>Part Fixe de la CS Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartVariableCSActuel__c.field-meta.xml
<CustomField>
    <fullName>PartVariableCSActuel__c</fullName>
    <label>Part Variable de la CS Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PartVariableCSOptimal__c.field-meta.xml
<CustomField>
    <fullName>PartVariableCSOptimal__c</fullName>
    <label>Part Variable de la CS Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/POINTEActuel__c.field-meta.xml
<CustomField>
    <fullName>POINTEActuel__c</fullName>
    <label>POINTE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/POINTEOptimal__c.field-meta.xml
<CustomField>
    <fullName>POINTEOptimal__c</fullName>
    <label>POINTE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PSMaxActive__c.field-meta.xml
<CustomField>
    <fullName>PSMaxActive__c</fullName>
    <label>PS Max Active</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SignataireACD__c.field-meta.xml
<CustomField>
    <fullName>SignataireACD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signataire ACD</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Points d&apos;énergie (Signataire ACD)</relationshipLabel>
    <relationshipName>PointEnergies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Taux_puissance_souscrite_utilisee__c.field-meta.xml
<CustomField>
    <fullName>Taux_puissance_souscrite_utilisee__c</fullName>
    <formula>IF(
    Puissance_souscrite__c = 0,
    0,
    (PSMaxActive__c / Puissance_souscrite__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taux puissance souscrite utilisée</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TaxeCTAActuel__c.field-meta.xml
<CustomField>
    <fullName>TaxeCTAActuel__c</fullName>
    <label>Taxe CTA Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TaxeCTAOptimal__c.field-meta.xml
<CustomField>
    <fullName>TaxeCTAOptimal__c</fullName>
    <label>Taxe CTA Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_num_compteur__c.field-meta.xml
<CustomField>
    <fullName>TECH_num_compteur__c</fullName>
    <formula>IF( NOT(ISBLANK(PCE_Refonte__c)) , PCE_Refonte__c, ReferencePointEnergie_Refonte__c)</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_OptimisationFieldsMissing__c.field-meta.xml
<CustomField>
    <fullName>TECH_OptimisationFieldsMissing__c</fullName>
    <formula>OR(
    ISBLANK(HCEActuel__c),
    ISBLANK(HPEActuel__c),
    ISBLANK(HCHActuel__c),
    ISBLANK(HPHActuel__c),
    ISBLANK(POINTEActuel__c),

    ISBLANK(HCEOptimal__c),
    ISBLANK(HPEOptimal__c),
    ISBLANK(HCHOptimal__c),
    ISBLANK(HPHOptimal__c),
    ISBLANK(POINTEOptimal__c),

    ISBLANK(PartFixeCSActuel__c),
    ISBLANK(PartVariableCSActuel__c),
    ISBLANK(DepassementActuel__c),
    ISBLANK(TaxeCTAActuel__c),

    ISBLANK(PartFixeCSOptimal__c),
    ISBLANK(PartVariableCSOptimal__c),
    ISBLANK(DepassementOptimal__c),
    ISBLANK(TaxeCTAOptimal__c),

    ISBLANK(BudgetTotalActuel__c),
    ISBLANK(BudgetTotalOptimal__c),

    ISBLANK(EconomieIdentifie__c)
)</formula>
    <label>TECH Champ Optimisation manquant ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/PDE_ElecC5.recordType-meta.xml
<RecordType>
    <fullName>PDE_ElecC5</fullName>
    <active>true</active>
    <description>Point d&apos;énergie C5</description>
    <label>Elec C5</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_Gaz.recordType-meta.xml
<RecordType>
    <fullName>PDE_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/classes/AP034_TURPEOptimisationController.cls
public without sharing class AP034_TURPEOptimisationController {

    /**
     * Récupère les informations TURPE depuis les PDE du compte
     */
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getInfosTurpeByAccount(Id accountId) {
        System.debug('Récupération des infos TURPE pour le compte : ' + accountId);
        Map<String, Object> result = new Map<String, Object>();
        List<PDE__c> lstPDE = new List<PDE__c>();

        // Récupération des PDE liés à l'entité juridique (compte)
        try {
            lstPDE = [
                SELECT Id,
                    Name,
                    BudgetTotalActuel__c, BudgetTotalOptimal__c, EconomieIdentifie__c,
                    HCEActuel__c, HPEActuel__c, HCHActuel__c, HPHActuel__c, POINTEActuel__c,
                    HCEOptimal__c, HPEOptimal__c, HCHOptimal__c, HPHOptimal__c, POINTEOptimal__c,
                    PartFixeCSActuel__c, PartVariableCSActuel__c, DepassementActuel__c, TaxeCTAActuel__c,
                    PartFixeCSOptimal__c, PartVariableCSOptimal__c, DepassementOptimal__c, TaxeCTAOptimal__c, InterventionPEPS__c,
                    Conso_HCE__c, Conso_HPE__c, Conso_HCH__c, Conso_HPH__c, Conso_Pointe__c,TECH_num_compteur__c
                FROM PDE__c
                WHERE EntiteJuridique__c = :accountId
                AND EconomieIdentifie__c > 0
                WITH SECURITY_ENFORCED
                ORDER BY Name
            ];
        } catch (System.QueryException e) {
            lstPDE = [
                SELECT Id,
                    Name,
                    BudgetTotalActuel__c, BudgetTotalOptimal__c, EconomieIdentifie__c,
                    HCEActuel__c, HPEActuel__c, HCHActuel__c, HPHActuel__c, POINTEActuel__c,
                    HCEOptimal__c, HPEOptimal__c, HCHOptimal__c, HPHOptimal__c, POINTEOptimal__c,
                    PartFixeCSActuel__c, PartVariableCSActuel__c, DepassementActuel__c, TaxeCTAActuel__c,
                    PartFixeCSOptimal__c, PartVariableCSOptimal__c, DepassementOptimal__c, TaxeCTAOptimal__c, InterventionPEPS__c,
                    Conso_HCE__c, Conso_HPE__c, Conso_HCH__c, Conso_HPH__c, Conso_Pointe__c,TECH_num_compteur__c
                FROM PDE__c
                WHERE EntiteJuridique__c = :accountId
                AND EconomieIdentifie__c > 0
                ORDER BY Name
            ];
            for (PDE__c p : lstPDE) {
                p.HCEOptimal__c = 00;
                p.HPEOptimal__c = 00;
                p.HCHOptimal__c = 00;
                p.HPHOptimal__c = 00;
                p.POINTEOptimal__c = 00;
            }
            result.put('blurPuissanceOptimal', true);
        }


        // Si aucun PDE trouvé 
        if (lstPDE.isEmpty()) {
            result.put('lstPDE', new List<PDE__c>());
            result.put('isMonoSite', true);
            result.put('totalBudgetActuel', 0);
            result.put('totalBudgetOptimal', 0);
            result.put('totalEconomie', 0);
            result.put('noteDateText', null);
            result.put('noteConsoText', null);
            return result;
        }

        // Sommes globales 
        Decimal totalBudgetActuel  = 0;
        Decimal totalBudgetOptimal = 0;
        Decimal totalEconomie      = 0;

        for (PDE__c p : lstPDE) {
            totalBudgetActuel  += (p.BudgetTotalActuel__c  != null ? p.BudgetTotalActuel__c  : 0);
            totalBudgetOptimal += (p.BudgetTotalOptimal__c != null ? p.BudgetTotalOptimal__c : 0);
            totalEconomie      += (p.EconomieIdentifie__c  != null ? p.EconomieIdentifie__c  : 0);
        }

        Boolean isMonoSite = (lstPDE.size() == 1);
        Date endDate   = Date.today().addDays(-1);
        Date startDate = endDate.addYears(-1);
        String startStr = DateTime.newInstance(startDate, Time.newInstance(0, 0, 0, 0)).format('dd/MM/yyyy');
        String endStr   = DateTime.newInstance(endDate, Time.newInstance(0, 0, 0, 0)).format('dd/MM/yyyy');

        String noteDateText = 'Note : l\'optimisation se base sur les consommations du ' + startStr +
            ' au ' + endStr + ' et suppose qu\'elles seront similaires à l\'avenir.';

        // Texte de consommation (uniquement pour monosite)
        String noteConsoText = null;
        if (isMonoSite) {
            PDE__c pde = lstPDE[0];
            noteConsoText =
                'HCE : ' + (pde.Conso_HCE__c != null ? String.valueOf(pde.Conso_HCE__c) : '—') + ' kWh — ' +
                'HPE : ' + (pde.Conso_HPE__c != null ? String.valueOf(pde.Conso_HPE__c) : '—') + ' kWh — ' +
                'HCH : ' + (pde.Conso_HCH__c != null ? String.valueOf(pde.Conso_HCH__c) : '—') + ' kWh — ' +
                'HPH : ' + (pde.Conso_HPH__c != null ? String.valueOf(pde.Conso_HPH__c) : '—') + ' kWh — ' +
                'Pointe : ' + (pde.Conso_Pointe__c != null ? String.valueOf(pde.Conso_Pointe__c) : '—') + ' kWh';
        }

        // Ajout au résultat renvoyé au LWC
        result.put('lstPDE', lstPDE);
        result.put('isMonoSite', isMonoSite);
        result.put('totalBudgetActuel', totalBudgetActuel);
        result.put('totalBudgetOptimal', totalBudgetOptimal);
        result.put('totalEconomie', totalEconomie);
        result.put('noteDateText', noteDateText);
        result.put('noteConsoText', noteConsoText);
        
        return result;
    }

    /**
    * Applique les regles TURPE : verifie l'eligibilite du PDE et declenche OPTIMISATION ou RENOUVELLEMENT
    */
    public static void invokeTURPEIfEligible(Id pdeId) {
        try {
            PDE__c pde = [
                SELECT
                    Id,
                    Name,
                    IdSource__c,
                    IdAnalyse__c,
                    IdBuilding__c,
                    RecordType.DeveloperName,
                    Taux_puissance_souscrite_utilisee__c,
                    Puissance_souscrite__c,
                    PSMaxActive__c,
                    DatePremierAppel__c,
                    TECH_OptimisationFieldsMissing__c,
                    AppelEnCours__c,
                    SignataireACD__c
                FROM PDE__c
                WHERE Id = :pdeId
            ];

            // Sortie immediate si record type non eligible ou taux hors plage
            if (
                pde.AppelEnCours__c ||
                pde.SignataireACD__c == null || 
                pde.RecordType.DeveloperName == 'PDE_Gaz' ||
                pde.RecordType.DeveloperName == 'PDE_ElecC5' ||
                (pde.Taux_puissance_souscrite_utilisee__c >= 80 &&
                pde.Taux_puissance_souscrite_utilisee__c <= 120)
            ) {
                return;
            }

            Boolean hasAnalyse = (pde.IdAnalyse__c != null);
            // Si hasAnalyse != null et que DatePremierAppel__c > 3 mois → OPTIMISATION
            if (hasAnalyse && datePremierAppelExceeds3Months(pde)) {
                AP034_TURPEOptimisationService.invokeTURPECallFromApex(
                    'PDE_OPTIMISATION_RENEW', 
                    (String) pde.Id,
                    (String) pde.IdSource__c,
                    (String) pde.IdAnalyse__c,
                    (String) pde.IdBuilding__c
                );
                return;
            }
            // Si hasAnalyse != null → verifier si champs optimisation manquants
            if (hasAnalyse && pde.TECH_OptimisationFieldsMissing__c) {
                AP034_TURPEOptimisationService.invokeTURPECallFromApex(
                    'PDE_RENOUVELLEMENT',
                    (String) pde.Id,
                    (String) pde.IdSource__c,
                    (String) pde.IdAnalyse__c,
                    (String) pde.IdBuilding__c
                );
            }
            // Cas par defaut
            AP034_TURPEOptimisationService.invokeTURPECallFromApex(
                'PDE_OPTIMISATION',
                (String) pde.Id,
                (String) pde.IdSource__c,
                (String) pde.IdAnalyse__c,
                (String) pde.IdBuilding__c
            );
        } catch (Exception e) {
            System.debug('Erreur lors du declenchement TURPE : ' + e.getMessage());
        }
    }

    /**
     * Indique si la date du premier appel TURPE dépasse 3 mois
     */
    private static Boolean datePremierAppelExceeds3Months(PDE__c pde) {
        if (pde.DatePremierAppel__c == null) return false;
        return pde.DatePremierAppel__c.addMonths(3) < Date.today();
    }
}