force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/AppelEnCours__c.field-meta.xml
<CustomField>
    <fullName>AppelEnCours__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</description>
    <inlineHelpText>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</inlineHelpText>
    <label>Appel en cours ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/BudgetTotalActuel__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalActuel__c</fullName>
    <label>Budget Total Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/BudgetTotalOptimal__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalOptimal__c</fullName>
    <label>Budget Total Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateAppel__c.field-meta.xml
<CustomField>
    <fullName>DateAppel__c</fullName>
    <description>Date à laquelle un appel Homeys a été effectué</description>
    <inlineHelpText>Date à laquelle un appel Homeys a été effectué</inlineHelpText>
    <label>Date de l&apos;Appel</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EconomieIdentifie__c.field-meta.xml
<CustomField>
    <fullName>EconomieIdentifie__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Economie identifiée (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCEActuel__c.field-meta.xml
<CustomField>
    <fullName>HCEActuel__c</fullName>
    <label>HCE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCEOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCEOptimal__c</fullName>
    <label>HCE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCHActuel__c.field-meta.xml
<CustomField>
    <fullName>HCHActuel__c</fullName>
    <label>HCH Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/HCHOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCHOptimal__c</fullName>
    <label>HCH Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdAnalyse__c.field-meta.xml
<CustomField>
    <fullName>IdAnalyse__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Analyse</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdBuilding__c.field-meta.xml
<CustomField>
    <fullName>IdBuilding__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Building</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/IdSource__c.field-meta.xml
<CustomField>
    <fullName>IdSource__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <label>Id Source</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PDE__c/fields/NumeroVoie__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/POINTEActuel__c.field-meta.xml
<CustomField>
    <fullName>POINTEActuel__c</fullName>
    <label>POINTE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/POINTEOptimal__c.field-meta.xml
<CustomField>
    <fullName>POINTEOptimal__c</fullName>
    <label>POINTE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SiteConsommation__c.field-meta.xml
<CustomField>
    <fullName>SiteConsommation__c</fullName>
    <label>Site de Consommation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <label>Date de fin de contrat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IsOptimisationTURPE__c.field-meta.xml
<CustomField>
    <fullName>IsOptimisationTURPE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Optimisation TURPE ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/AppelEnCours__c.field-meta.xml
<CustomField>
    <fullName>AppelEnCours__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</description>
    <inlineHelpText>Définit si un appel vers Homeys est en cours pour l&apos;optimisation TURPE</inlineHelpText>
    <label>Appel en cours ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetTotalActuel__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalActuel__c</fullName>
    <label>Budget Total Actuel (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetTotalOptimal__c.field-meta.xml
<CustomField>
    <fullName>BudgetTotalOptimal__c</fullName>
    <label>Budget Total Optimal (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DateAppel__c.field-meta.xml
<CustomField>
    <fullName>DateAppel__c</fullName>
    <label>Date de l&apos;Appel</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/EconomieIdentifie__c.field-meta.xml
<CustomField>
    <fullName>EconomieIdentifie__c</fullName>
    <label>Economie identifiée (€HT/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/HCEActuel__c.field-meta.xml
<CustomField>
    <fullName>HCEActuel__c</fullName>
    <label>HCE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/HCEOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCEOptimal__c</fullName>
    <label>HCE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/HCHActuel__c.field-meta.xml
<CustomField>
    <fullName>HCHActuel__c</fullName>
    <label>HCH Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/HCHOptimal__c.field-meta.xml
<CustomField>
    <fullName>HCHOptimal__c</fullName>
    <label>HCH Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IdAnalyse__c.field-meta.xml
<CustomField>
    <fullName>IdAnalyse__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Analyse</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IdBuilding__c.field-meta.xml
<CustomField>
    <fullName>IdBuilding__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <inlineHelpText>ID Externe utilisé par les process Homeys pour le TURPE</inlineHelpText>
    <label>Id Building</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IdSource__c.field-meta.xml
<CustomField>
    <fullName>IdSource__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID Externe utilisé par les process Homeys pour le TURPE</description>
    <externalId>true</externalId>
    <label>Id Source</label>
    <length>24</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/POINTEActuel__c.field-meta.xml
<CustomField>
    <fullName>POINTEActuel__c</fullName>
    <label>POINTE Actuel</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/POINTEOptimal__c.field-meta.xml
<CustomField>
    <fullName>POINTEOptimal__c</fullName>
    <label>POINTE Optimal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AP034_TURPEWebhookHandler_TEST.cls
@isTest
private class AP034_TURPEWebhookHandler_TEST {

    private static final String HOMEYS_JSON =
        '{'+
        '  "event" : "optimturpe_finished",'+
        '  "data": {'+
        '  "_id_source": "SRC_MAIN",'+
        '    "_id": "ANALYSE_001",'+
        '    "_id_analyse_optimturpe": "ANALYSE_001",'+
        '    "_id_building": "BUILD_001",'+
        '    "status": "SUCCESS",'+
        '    "error" : {'+
        '      "message" : "",'+
        '      "code" : ""'+
        '    },'+
        '    "inputs": {'+
        '      "source": {'+
        '        "_id_source": "SRC_MAIN"'+
        '      },'+
        '      "data": {'+
        '        "date_from": "2024-01-01",'+
        '        "date_to": "2024-12-31"'+
        '      },'+
        '      "comptage" : null,'+
        '      "structure_tarifaire" : null,'+
        '      "optimisation" : null'+
        '    },'+
        '    "outputs": {'+
        '      "actuelle": {'+
        '        "structure_tarifaire": {'+
        '          "puissance_souscrite_soutirage": {'+
        '            "denivele": {'+
        '              "HCB": 1,'+
        '              "HPB": 2,'+
        '              "HCH": 3,'+
        '              "HPH": 4,'+
        '              "PTE": 5'+
        '            }'+
        '          }'+
        '        },'+
        '        "data": {'+
        '          "periode": {'+
        '            "prixHTT_elecsoutirage_turpeCSF": { "sum": 10 },'+
        '            "prixHTT_elecsoutirage_turpeCSV": { "sum": 20 },'+
        '            "prixHTT_elecsoutirage_turpeCMDPS": { "sum": 30 },'+
        '            "prixHTVA_elecsoutirage_cta": { "sum": 40 }'+
        '          }'+
        '        }'+
        '      },'+
        '      "meilleure": {'+
        '        "structure_tarifaire": {'+
        '          "puissance_souscrite_soutirage": {'+
        '            "denivele": {'+
        '              "HCB": 6,'+
        '              "HPB": 7,'+
        '              "HCH": 8,'+
        '              "HPH": 9,'+
        '              "PTE": 10'+
        '            }'+
        '          }'+
        '        },'+
        '        "data": {'+
        '          "periode": {'+
        '            "prixHTT_elecsoutirage_turpeCSF": { "sum": 15 },'+
        '            "prixHTT_elecsoutirage_turpeCSV": { "sum": 25 },'+
        '            "prixHTT_elecsoutirage_turpeCMDPS": { "sum": 35 },'+
        '            "prixHTVA_elecsoutirage_cta": { "sum": 45 }'+
        '          }'+
        '        }'+
        '      }'+
        '    },'+
        '    "created_at" : "2026-02-17T11:08:04.888000",'+
        '    "updated_at" : "2026-02-17T11:08:10.876000"'+
        '  }'+
        '}';


    @testSetup
    static void setupData() {
        TestDataFactory.createDataForComparatifElec();
    }

    private static AP034_TURPEOptimisationService.TurpeDataExtractor buildTurpeData() {

        AP034_TURPEOptimisationService.TurpeDataExtractor d =
            new AP034_TURPEOptimisationService.TurpeDataExtractor();

        d.idAnalyse  = 'ANALYSE_001';
        d.idBuilding = 'BUILD_001';
        d.dateFrom   = Date.newInstance(2024, 1, 1);
        d.dateTo     = Date.newInstance(2024, 12, 31);

        // ACTUEL
        d.HCEActuel = 1;
        d.HPEActuel = 2;
        d.HCHActuel = 3;
        d.HPHActuel = 4;
        d.POINTEActuel = 5;

        d.PartFixeCSActuel = 10;
        d.PartVariableCSActuel = 20;
        d.actuelleTurpeCMDPS = 30;
        d.TaxeCTAActuel = 40;

        // OPTIMAL
        d.HCEOptimal = 6;
        d.HPEOptimal = 7;
        d.HCHOptimal = 8;
        d.HPHOptimal = 9;
        d.POINTEOptimal = 10;

        d.PartFixeCSOptimal = 15;
        d.PartVariableCSOptimal = 25;
        d.meilleureTurpeCMDPS = 35;
        d.TaxeCTAOptimal = 45;

        return d;
    }

    private static PDE__c createPDEWithIdSource(String idSource) {
        PDE__c p = new PDE__c(
            Name = 'PDE_TURPE',
            SiteConsommation__c = 'TEST',
            NumeroVoie__c = '90',
            Voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            CARGaz__c = 1234,
            DateEcheance__c = Date.today().addMonths(1),
            PCE_Refonte__c = '12345478900',
            ReferencePointEnergie_Refonte__c = '12345678980',
            IdSource__c = idSource
        );
        insert p;
        return p;
    }

    private static QuoteLineItem createQLIWithIdSource(PDE__c p, String idSource) {

        Product2 prod = [
            SELECT Id
            FROM Product2
            WHERE Name = 'ELEC'
            LIMIT 1
        ];

        PricebookEntry pbe = [
            SELECT Id, Pricebook2Id
            FROM PricebookEntry
            WHERE Product2Id = :prod.Id
            AND IsActive = true
            LIMIT 1
        ];

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Quote q = new Quote(
            Name = 'Q TURPE',
            Pricebook2Id = pbe.Pricebook2Id,
            OpportunityId = opp.Id,
            IsOptimisationTURPE__c = true,
            Date_de_fin_de_contrat__c = Date.today().addMonths(12)
        );
        insert q;

        QuoteLineItem qli = new QuoteLineItem(
            QuoteId = q.Id,
            PDE__c = p.Id,
            Product2Id = prod.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            UnitPrice = 1,
            IdSource__c = idSource
        );
        insert qli;

        return qli;
    }

    private static RestRequest buildRequest() {
        RestRequest req = new RestRequest();
        req.requestBody = Blob.valueOf(HOMEYS_JSON);
        return req;
    }

    @isTest
    static void test_PDE_and_QLI() {

        PDE__c p = createPDEWithIdSource('SRC_EXEC');
        QuoteLineItem qli = createQLIWithIdSource(p, 'SRC_EXEC');

        RestRequest req = buildRequest();
        AP034_TURPEWebhookHandler handler = new AP034_TURPEWebhookHandler();

        Test.startTest();
        handler.handle(req);
        Test.stopTest();

        PDE__c updatedPDE = [
            SELECT AppelEnCours__c, DateAppel__c,
                   HCEActuel__c, HCEOptimal__c,
                   POINTEActuel__c, POINTEOptimal__c,
                   BudgetTotalActuel__c, BudgetTotalOptimal__c,
                   EconomieIdentifie__c
            FROM PDE__c
            WHERE Id = :p.Id
        ];

        QuoteLineItem updatedQLI = [
            SELECT AppelEnCours__c, DateAppel__c,
                   HCEActuel__c, HCEOptimal__c,
                   POINTEActuel__c, POINTEOptimal__c,
                   BudgetTotalActuel__c, BudgetTotalOptimal__c,
                   EconomieIdentifie__c
            FROM QuoteLineItem
            WHERE Id = :qli.Id
        ];

        Assert.isTrue(true);
    }

    @isTest
    static void test_PDE_only() {

        PDE__c p = createPDEWithIdSource('SRC_EXEC');

        RestRequest req = buildRequest();
        AP034_TURPEWebhookHandler handler = new AP034_TURPEWebhookHandler();

        Test.startTest();
        handler.handle(req);
        Test.stopTest();

        PDE__c updated = [
            SELECT HCEActuel__c, HCEOptimal__c, AppelEnCours__c
            FROM PDE__c
            WHERE Id = :p.Id
        ];

        Assert.isTrue(true);
    }

    @isTest
    static void test_QLI_only() {

        PDE__c p = createPDEWithIdSource('OTHER_SRC');
        QuoteLineItem qli = createQLIWithIdSource(p, 'SRC_EXEC');

        RestRequest req = buildRequest();
        AP034_TURPEWebhookHandler handler = new AP034_TURPEWebhookHandler();

        Test.startTest();
        handler.handle(req);
        Test.stopTest();

        QuoteLineItem updated = [
            SELECT HCHActuel__c, HCHOptimal__c, AppelEnCours__c
            FROM QuoteLineItem
            WHERE Id = :qli.Id
        ];

        Assert.isTrue(true);
    }

    @isTest
    static void test_updateRecordWithTurpeData_PDE() {

        PDE__c pde = [
            SELECT Id
            FROM PDE__c
            LIMIT 1
        ];

        AP034_TURPEOptimisationService.TurpeDataExtractor data =
            buildTurpeData();

        Test.startTest();
        AP034_TURPEWebhookHandler.updateRecordWithTurpeData(pde, data);
        Test.stopTest();

        PDE__c updated = [
            SELECT
                IdAnalyse__c,
                IdBuilding__c,
                AppelEnCours__c,
                BudgetTotalActuel__c,
                BudgetTotalOptimal__c,
                EconomieIdentifie__c
            FROM PDE__c
            WHERE Id = :pde.Id
        ];

        Assert.areEqual(100, updated.BudgetTotalActuel__c);
        Assert.areEqual(120, updated.BudgetTotalOptimal__c);
        Assert.areEqual(-20, updated.EconomieIdentifie__c);
        Assert.areEqual(false, updated.AppelEnCours__c);
        Assert.areEqual('ANALYSE_001', updated.IdAnalyse__c);
        Assert.areEqual('BUILD_001', updated.IdBuilding__c);
    }

    @isTest
    static void test_updateRecordWithTurpeData_QLI() {
        QuoteLineItem qli = [
            SELECT Id
            FROM QuoteLineItem
            LIMIT 1
        ];

        AP034_TURPEOptimisationService.TurpeDataExtractor data =
            buildTurpeData();

        Test.startTest();
        AP034_TURPEWebhookHandler.updateRecordWithTurpeData(qli, data);
        Test.stopTest();

        QuoteLineItem updated = [
            SELECT
                IdAnalyse__c,
                IdBuilding__c,
                AppelEnCours__c,
                BudgetTotalActuel__c,
                BudgetTotalOptimal__c,
                EconomieIdentifie__c,
                HCHActuel__c,
                HCHOptimal__c
            FROM QuoteLineItem
            WHERE Id = :qli.Id
        ];

        Assert.areEqual(3, updated.HCHActuel__c);
        Assert.areEqual(8, updated.HCHOptimal__c);
        Assert.areEqual(100, updated.BudgetTotalActuel__c);
        Assert.areEqual(120, updated.BudgetTotalOptimal__c);
        Assert.areEqual(-20, updated.EconomieIdentifie__c);
        Assert.areEqual(false, updated.AppelEnCours__c);
        Assert.areEqual('ANALYSE_001', updated.IdAnalyse__c);
        Assert.areEqual('BUILD_001', updated.IdBuilding__c);
    }
}