force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_fournisseur__c</fullName>
    <formula>Quote.Fournisseur__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fournisseur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>TECH_OpportunityId__c</fullName>
    <formula>CASESAFEID(Quote.Opportunity.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_OpportunityId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_RT__c.field-meta.xml
<CustomField>
    <fullName>TECH_RT__c</fullName>
    <formula>PDE__r.RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_RT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_TypeOffre__c.field-meta.xml
<CustomField>
    <fullName>TECH_TypeOffre__c</fullName>
    <formula>TEXT( Quote.TypeOffre__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type d&apos;offre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShowQLIOnOpportController.cls
public with sharing class ShowQLIOnOpportController {
  @AuraEnabled
  public static List<QuoteLineItem> retrieveQLI(String recordId) {
    return [
      SELECT
        Id,
        LineNumber,
        PDE__r.ReferencePointEnergie_Refonte__c,
        PDE__r.PCE_Refonte__c,
        TECH_TypeOffre__c,
        TECH_fournisseur__c,
        QuoteId,
        Quote.Name,
        TECH_RT__c,
        UnitPrice,
        DebutDeFourniture__c,
        Nouvelle_Echeance__c
      FROM QuoteLineItem
      WHERE TECH_OpportunityId__c = :recordId
    ];
  }
}