force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/FTA__c.field-meta.xml
<CustomField>
    <fullName>FTA__c</fullName>
    <description>ELEC</description>
    <label>FTA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BT &lt;= 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - MU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - LU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - CU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - MU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - LU EP</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <label>CEE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inclus</fullName>
            </value>
            <value>
                <fullName>Soumis</fullName>
            </value>
            <value>
                <fullName>Non Soumis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Date_Validite_Offre_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Date_Validite_Offre_API_Endesa_Elec__c</fullName>
    <label>Date Validité Offre API Endesa Elec</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Numero_Dossier_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Numero_Dossier_API_Endesa_Elec__c</fullName>
    <label>Numero Dossier API Endesa Elec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Numero_Offre_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Numero_Offre_API_Endesa_Elec__c</fullName>
    <label>Numero Offre API Endesa Elec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/AbonnementMois__c.field-meta.xml
<CustomField>
    <fullName>AbonnementMois__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Abonnement (€/mois)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_Base__c.field-meta.xml
<CustomField>
    <fullName>Capa_Base__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité Base (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HC__c.field-meta.xml
<CustomField>
    <fullName>Capa_HC__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HC (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HCE__c.field-meta.xml
<CustomField>
    <fullName>Capa_HCE__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HCE (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HCH__c.field-meta.xml
<CustomField>
    <fullName>Capa_HCH__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HCH (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HP__c.field-meta.xml
<CustomField>
    <fullName>Capa_HP__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HP (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HPE__c.field-meta.xml
<CustomField>
    <fullName>Capa_HPE__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HPE (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HPH__c.field-meta.xml
<CustomField>
    <fullName>Capa_HPH__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HPH (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_Pointes__c.field-meta.xml
<CustomField>
    <fullName>Capa_Pointes__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité Pointes (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CeeMwh__c.field-meta.xml
<CustomField>
    <fullName>CeeMwh__c</fullName>
    <defaultValue>0.000</defaultValue>
    <label>CEE (en €/MWh)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PointesMWh__c.field-meta.xml
<CustomField>
    <fullName>PointesMWh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pointes (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixBase__c.field-meta.xml
<CustomField>
    <fullName>PrixBase__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix Base (en €/MWh)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHC__c.field-meta.xml
<CustomField>
    <fullName>PrixHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HC (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHceMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHceMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HCE (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHchMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHchMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HCH (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHP__c.field-meta.xml
<CustomField>
    <fullName>PrixHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HP (en €/MWh)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHpeMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHpeMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HPE (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHphMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHphMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HPH (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_PdeReference__c.field-meta.xml
<CustomField>
    <fullName>TECH_PdeReference__c</fullName>
    <formula>PDE__r.TECH_num_compteur__c</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP022_GetCallBack.cls
@RestResource(urlMapping='/callback/endesa')
global without sharing class AP022_GetCallBack {

@HttpPost
    global static void receiveCallback() {
        System.debug('receiveCallback');
        try {
            RestRequest req = RestContext.request;
            String body = req.requestBody.toString();
            System.debug('Body reçu : ' + body);

            // Test rapide si la réponse contient des erreurs
            if (body.containsIgnoreCase('"errors"')) {
                System.debug('errors found');
                Map<String, Object> parsed = (Map<String, Object>) JSON.deserializeUntyped(body);
                handleErrorCallback(parsed); //Revoir le parsing des erreurs ne pas utiliser chatgpt + Envoyer un mail pour demander si un JSON type pour les erreurs existes
                                             // Si pas de moyen simple de parser les messages d'erreur on l'affiche directement dans le mail
            }
            else {
                CallbackResponse response = (CallbackResponse) JSON.deserialize(body, CallbackResponse.class);
                //Inclure le code de handleSuuccessCallBack dans le if
                //String quoteUrl = 'https://alliancedesenergies--devbb.sandbox.lightning.force.com/lightning/r/Quote/' + quote.Id + '/view';
                Quote quote = updateQuoteLineItems(response, response.num_dossier);

                // Get the Id for our custom notification type
                CustomNotificationType notificationType = 
                    [SELECT Id, DeveloperName 
                    FROM CustomNotificationType 
                    WHERE DeveloperName='Endesa_Elec_Prix'];
                
                // Create a new custom notification
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
                // Set the contents for the notification
                notification.setTitle('API ENDESA / Prix Endesa Elec récupérés pour la Quote : ' + quote.Name);

                body = 'Les prix ont été récupérés avec succès pour la Quote ' + quote.Name;
                notification.setBody(body);
                // Set the notification type and target
                notification.setNotificationTypeId(notificationType.Id);
                notification.setTargetId(quote.Id);
                
                // Actually send the notification
                try {
                    Set<String> recipients = new Set<String>();
                    recipients.add(quote.Owner.Id);
                    notification.send(recipients);
                }
                catch (Exception e) {
                    System.debug('Problem sending notification: ' + e.getMessage());
                }
            }     

        } catch (Exception e) {
            System.debug('Exception dans receiveCallback: ' + e.getMessage());
            throw new CalloutException('Exception REST Callback : ' + e.getMessage());
        }
    }

    public static Quote updateQuoteLineItems(CallbackResponse response, String numero_dossier) {

        System.debug('response in updateQuoteLineItems : ' + response);
        System.debug('num_dossier in updateQuoteLineItems : ' + numero_dossier);

        List<Quote> quotes = [Select Id From Quote Where Numero_Dossier_API_Endesa_Elec__c =: numero_dossier];
        
        List<QuoteLineItem> qlis = [
            SELECT Id, TECH_PdeReference__c, QuoteId, Quote.Owner.Email, PDE__r.Segment__c,
                    PDE__r.FTA__c, PDE__r.Calendrier_fournisseur__c, Quote.CEE__c
            FROM QuoteLineItem
            WHERE Quote.Numero_Dossier_API_Endesa_Elec__c =: numero_dossier
        ];

        List<QuoteLineItem> qliToUpdate = new List<QuoteLineItem>();

        for (QuoteLineItem qli : qlis) {
            SiteResponse site = response.sites.get(qli.TECH_PdeReference__c);
            if (site == null) continue;

            String segment = qli.PDE__r.Segment__c;
            Boolean is4Postes = qli.PDE__r.FTA__c != null && qli.PDE__r.FTA__c.contains('4 postes');
            String calendrierFournisseur = qli.PDE__r.Calendrier_fournisseur__c;

            QuoteLineItem newQLI = new QuoteLineItem();
            newQLI.Id = qli.Id;
            if (site.commission != null) {
                newQLI.UnitPrice = Decimal.valueOf(site.commission).setScale(2);
            }

            newQLI.AbonnementMois__c = site.abonnement;
            newQLI.PrixBase__c = site.prix_energie_base ?? 0;
            newQLI.PrixHP__c = site.prix_energie_hp ?? 0;
            newQLI.PrixHC__c = site.prix_energie_hc ?? 0;

            if (segment == 'C5' && is4Postes) {
                if (calendrierFournisseur == 'Heures Pleines/Creuses' || calendrierFournisseur == 'HP/HC') {
                    newQLI.PrixHchMwh__c = site.prix_energie_hc ?? 0;
                    newQLI.PrixHceMwh__c = site.prix_energie_hc ?? 0;
                    newQLI.PrixHphMwh__c = site.prix_energie_hp ?? 0;
                    newQLI.PrixHpeMwh__c = site.prix_energie_hp ?? 0;
                } else {
                    newQLI.PrixHchMwh__c = site.prix_energie_base ?? 0;
                    newQLI.PrixHceMwh__c = site.prix_energie_base ?? 0;
                    newQLI.PrixHphMwh__c = site.prix_energie_base ?? 0;
                    newQLI.PrixHpeMwh__c = site.prix_energie_base ?? 0;
                }
            } else {
                newQLI.PrixHchMwh__c = site.prix_energie_hch ?? 0;
                newQLI.PrixHceMwh__c = site.prix_energie_hce ?? 0;
                newQLI.PrixHphMwh__c = site.prix_energie_hph ?? 0;
                newQLI.PrixHpeMwh__c = site.prix_energie_hpe ?? 0;
            }

            newQLI.PointesMWh__c = site.categorie == 'C4' ? site.prix_energie_hph : 0;
            newQLI.CeeMwh__c = qli.Quote.CEE__c == 'Soumis' ? Decimal.valueOf(site.cee).setScale(2, RoundingMode.DOWN) : 0;

            newQLI.Capa_Base__c = site.capacite ?? 0;
            newQLI.Capa_HP__c = site.capacite ?? 0;
            newQLI.Capa_HC__c = site.capacite ?? 0;
            newQLI.Capa_HCH__c = site.capacite ?? 0;
            newQLI.Capa_HPH__c = site.capacite ?? 0;
            newQLI.Capa_HPE__c = site.capacite ?? 0;
            newQLI.Capa_HCE__c = site.capacite ?? 0;
            newQLI.Capa_Pointes__c = site.capacite ?? 0;

            qliToUpdate.add(newQLI);
        }

        Quote quoteToUpdate = [SELECT Id, Name, Owner.Email, Owner.Id From Quote WHERE Id =: qlis[0].QuoteId];
        

        quoteToUpdate.Date_Validite_Offre_API_Endesa_Elec__c = Date.parse(response.date_fin_validite);
        quoteToUpdate.Numero_Offre_API_Endesa_Elec__c = response.numero_offre;

        // Update QLI
        List<Database.SaveResult> listSRQLI = Database.update(qliToUpdate, false);
        for (Database.SaveResult sr : listSRQLI) {
            if (!sr.isSuccess()) {
                for (Database.Error err : sr.getErrors()) {
                    System.debug(err);
                }
                throw new CalloutException('Erreur Update QLI');
            }
        }

        // Update Quote
        Database.SaveResult srQuote = Database.update(quoteToUpdate);
        if (!srQuote.isSuccess()) {
            for(Database.Error err : srQuote.getErrors()){
                System.debug(err);
            }
            throw new CalloutException('Erreur Update Quote');
        }

        return quoteToUpdate;

    }

    private static void sendEmail(String subject, List<String> toAddresses, String bodyHtml) {
        OrgWideEmailAddress[] owea = [
            SELECT Id FROM OrgWideEmailAddress 
            WHERE Address = 'tech@alliancedesenergies.fr' 
            LIMIT 1
        ];

        if (owea.isEmpty()) {
            System.debug('Aucune adresse OrgWideEmailAddress trouvée.');
            return;
        }

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);
        mail.setOrgWideEmailAddressId(owea[0].Id);
        mail.setSubject(subject);
        mail.setHtmlBody(bodyHtml);

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        System.debug('E-mail envoyé avec sujet : ' + subject);
    }

    private static void handleErrorCallback(Map<String, Object> parsed) {
        System.debug('handleErrorCallback');
        String parsedString = String.valueOf(parsed);
        String numdossier = '';
        if (parsed.containsKey('num_dossier')) {
                numdossier = String.valueOf(parsed.get('num_dossier'));
                List<Quote> quotes = [
                    SELECT Id, Name, Numero_Dossier_API_Endesa_Elec__c, Owner.Email, Owner.Id
                    FROM Quote
                    WHERE Numero_Dossier_API_Endesa_Elec__c =: numdossier
                    Limit 1
                ];

                if(!quotes.isEmpty())   {


                    // Get the Id for our custom notification type
                    CustomNotificationType notificationType = 
                        [SELECT Id, DeveloperName 
                        FROM CustomNotificationType 
                        WHERE DeveloperName='Endesa_Elec_Prix'];
                    
                    // Create a new custom notification
                    Messaging.CustomNotification notification = new Messaging.CustomNotification();

                    // Set the contents for the notification
                    notification.setTitle('API ENDESA / Prix Endesa Elec, erreurs survenue pour la Quote : ' + quotes[0].Name);
                    String body = 'Erreurs survenue lors de la récupération des prix : ' + parsedString;
                    notification.setBody(body);

                    // Set the notification type and target
                    notification.setNotificationTypeId(notificationType.Id);
                    notification.setTargetId(quotes[0].Id);
                    
                    // Actually send the notification
                    try {
                        Set<String> recipients = new Set<String>();
                        recipients.add(quotes[0].Owner.Id);
                        notification.send(recipients);
                    }
                    catch (Exception e) {
                        System.debug('Problem sending notification: ' + e.getMessage());
                    }
                }
                else {
                    System.debug('No Quote found for dossier number : ' + numdossier);
                    System.debug('quote : ' + quotes);
                }

        }
    }

    private class ErrorItem {
        public String code_error;
        public String message;
        public String num_dossier;

        public ErrorItem(String code, String msg, String dossier) {
            this.code_error = code;
            this.message = msg;
            this.num_dossier = dossier;
        }
    }

    private class CallbackResponse {
        public String numero_offre;
        public String num_dossier;
        public String date_fin_validite;
        public Map<String, SiteResponse> sites;
    }

    private class SiteResponse  {
        public Double commission;
        public Double abonnement;
        public Double cee;
        public String categorie;
        public Double consommation;
        public Double capacite;
        public Double prix_energie_base;
        public Double prix_energie_hp;
        public Double prix_energie_hc;
        public Double prix_energie_hch;
        public Double prix_energie_hph;
        public Double prix_energie_hpe;
        public Double prix_energie_hce;
    }

}