force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/FTA__c.field-meta.xml
<CustomField>
    <fullName>FTA__c</fullName>
    <description>ELEC</description>
    <label>FTA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BT &lt;= 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - MU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - LU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - CU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - MU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - LU EP</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/NumeroVoie__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Premiere_mise_en_service__c.field-meta.xml
<CustomField>
    <fullName>Premiere_mise_en_service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Première mise en service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SiteConsommation__c.field-meta.xml
<CustomField>
    <fullName>SiteConsommation__c</fullName>
    <label>Site de Consommation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TECH_FournisseurLogo__c.field-meta.xml
<CustomField>
    <fullName>TECH_FournisseurLogo__c</fullName>
    <formula>CASE( Fournisseur__c,
&quot;Antargaz&quot;,&quot;antargaz.png&quot;,
&quot;Alterna&quot;,&quot;alterna.png&quot;,
&quot;Dyneff&quot;,&quot;dyneff.png&quot;,
&quot;EDF Entreprises&quot;,&quot;edf.png&quot;,
&quot;Ekwateur&quot;,&quot;ekwateur.png&quot;,
&quot;Electricité de Provence&quot;,&quot;electricitedeprovence.png&quot;,
&quot;Electricité de Strasbourg&quot;,&quot;electricitedestrasbourg.png&quot;,
&quot;Endesa&quot;,&quot;endesa.png&quot;,
&quot;Enercoop&quot;,&quot;enercoop.png&quot;,
&quot;Engie&quot;,&quot;engie.png&quot;,
&quot;Eni&quot;,&quot;eni.png&quot;,
&quot;Enovos&quot;,&quot;enovos.png&quot;,
&quot;Dalkia&quot;,&quot;dalkia.png&quot;,
&quot;Gaz de Bordeaux&quot;,&quot;gazdebordeaux.png&quot;,
&quot;Gaz Européen&quot;,&quot;gazeuropeen.png&quot;,
&quot;Gazel Energie&quot;,&quot;gazelenergie.png&quot;,
&quot;GEG&quot;,&quot;geg.png&quot;,
&quot;Iberdrola&quot;,&quot;iberdrola.png&quot;,
&quot;Ilek&quot;,&quot;ilek.png&quot;,
&quot;La Bellenergie&quot;,&quot;labellenergie.png&quot;,
&quot;LLUM&quot;,&quot;llum.png&quot;,
&quot;MET Energie&quot;,&quot;metenergie.png&quot;,
&quot;OHM Energie&quot;,&quot;ohmenergie.png&quot;,
&quot;Picoty&quot;,&quot;picoty.png&quot;,
&quot;Planete OUI&quot;,&quot;planeteoui.png&quot;,
&quot;Primeo Energie&quot;,&quot;primeoenergie.png&quot;,
&quot;Save Energies&quot;,&quot;saveenergies.png&quot;,
&quot;SEFE Energy&quot;,&quot;SEFE.png&quot;,
&quot;Situation Actuelle&quot;, &quot;Situation_Actuelle.png&quot;,
&quot;Proposition Renouvellement&quot;, &quot;Proposition_Renouvellement.png&quot;,
&quot;Selia&quot;,&quot;selia.png&quot;,
&quot;TotalEnergies&quot;,&quot;totalenergies.png&quot;,
&quot;Total&quot;,&quot;totalenergies.png&quot;,
&quot;Vattenfall&quot;,&quot;vattenfall.png&quot;,
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Fournisseur Logo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TypeOffre__c.field-meta.xml
<CustomField>
    <fullName>TypeOffre__c</fullName>
    <label>Type d&apos;Offre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
                <default>true</default>
                <label>PRIX FIXE</label>
            </value>
            <value>
                <fullName>ARENH</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>SWAP ARENH</fullName>
                <isActive>false</isActive>
                <label>SWAP ARENH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/AbonnementMois__c.field-meta.xml
<CustomField>
    <fullName>AbonnementMois__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Abonnement (€/mois)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Budget_TTC__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC__c</fullName>
    <label>Budget TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetFourniture__c.field-meta.xml
<CustomField>
    <fullName>BudgetFourniture__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Budget Fourniture (€/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetHTTan__c.field-meta.xml
<CustomField>
    <fullName>BudgetHTTan__c</fullName>
    <formula>BudgetFourniture__c +BudgetObligationsMWH__c + Budget_Acheminement_Annuel_HTT__c + Budget_Taxes_annuel_HTVA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Annuel Estimé + Obligations(€/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CAR_New__c.field-meta.xml
<CustomField>
    <fullName>CAR_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CAR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CoutDeCapacite__c.field-meta.xml
<CustomField>
    <fullName>CoutDeCapacite__c</fullName>
    <label>Cout De Capacité</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CSPE__c.field-meta.xml
<CustomField>
    <fullName>CSPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CSPE</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CTA__c.field-meta.xml
<CustomField>
    <fullName>CTA__c</fullName>
    <label>CTA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CTA_Mensuel_ELEC__c.field-meta.xml
<CustomField>
    <fullName>CTA_Mensuel_ELEC__c</fullName>
    <label>CTA Mensuel ELEC</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/FraisTransportDistributionCapacite__c.field-meta.xml
<CustomField>
    <fullName>FraisTransportDistributionCapacite__c</fullName>
    <label>Frais de distribution variable</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PointesMWh__c.field-meta.xml
<CustomField>
    <fullName>PointesMWh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pointes (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixBase__c.field-meta.xml
<CustomField>
    <fullName>PrixBase__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix Base (en €/MWh)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHC__c.field-meta.xml
<CustomField>
    <fullName>PrixHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HC (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHceMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHceMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HCE (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHchMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHchMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HCH (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHP__c.field-meta.xml
<CustomField>
    <fullName>PrixHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HP (en €/MWh)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHpeMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHpeMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HPE (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixHphMwh__c.field-meta.xml
<CustomField>
    <fullName>PrixHphMwh__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix HPH (en €/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixMolecule__c.field-meta.xml
<CustomField>
    <fullName>PrixMolecule__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix molécule (€/MWH)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Taxes__c.field-meta.xml
<CustomField>
    <fullName>Taxes__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Taxes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_Budget__c.field-meta.xml
<CustomField>
    <fullName>TECH_Budget__c</fullName>
    <label>Budget HTVA</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_TCFE__c.field-meta.xml
<CustomField>
    <fullName>TECH_TCFE__c</fullName>
    <formula>TCCFE__c +  TDCFE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_TCFE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TICGN__c.field-meta.xml
<CustomField>
    <fullName>TICGN__c</fullName>
    <defaultValue>$CustomMetadata.Valeur_Annuelle__mdt.Valeur.TICGN__c</defaultValue>
    <label>TICGN (€/MWh)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TURPE_Fixe__c.field-meta.xml
<CustomField>
    <fullName>TURPE_Fixe__c</fullName>
    <label>TURPE Fixe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TURPE_Variable__c.field-meta.xml
<CustomField>
    <fullName>TURPE_Variable__c</fullName>
    <label>TURPE Variable</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TVA__c.field-meta.xml
<CustomField>
    <fullName>TVA__c</fullName>
    <label>TVA</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/WrapLigneDeDevis.cls
public class WrapLigneDeDevis implements Comparable {

  public enum SortField{siteDeConsoEnum, DateFinEnum}
  public static SortField SORT_FIELD = SortField.siteDeConsoEnum;
  public Integer DateFinInt{
      get{
          if(DateFin != null){
            return Integer.valueOf(DateFin.year());
          }return 0;
      }set;
  }
  public Date DateDebut { get; set; }
  public Date DateFin{get;set;}
  public Decimal BudgetTTC;
  public Decimal carElec { get; set; }
  public Decimal displayabonnement { get; set; }
  public Decimal displayBudgetAnnuel { get; set; }
  public Decimal displayBudgetAnnuelEstime { get; set; }
  public Decimal displayBudgetHT { get; set; }
  public Decimal displayBudgetTTC { get; set; }
  public String  displayCEE { get; set; }
  public Decimal displayCoutDeCapacite { get; set; }
  public Decimal displayCSPE { get; set; }
  public Decimal displayCTA { get; set; }
  public Decimal displayCTAGaz { get; set; }
  public Decimal displayDistribution { get; set; }
  public Decimal displayPrixBase { get; set; }
  public Decimal displayPrixHC { get; set; }
  public Decimal displayPrixHCE { get; set; }
  public Decimal displayPrixHCH { get; set; }
  public Decimal displayPrixHP { get; set; }
  public Decimal displayPrixHPE { get; set; }
  public Decimal displayPrixHPH { get; set; }
  public Decimal displayPrixMolecule { get; set; }
  public Decimal displayPrixpointes { get; set; }
  public Decimal displayTCFE { get; set; }
  public Decimal displayTICGN { get; set; }
  public Decimal displayTURPE { get; set; }
  public Decimal displayTVA { get; set; }
  public String periodeCouverture { get; set; }
  public String SITE_DE_CONSOMMATION{get;set;}
  public String fournisseurLogo {get;set;}
  public String identifiantSite {get;set;}
  public String TECHOdreAlpha {get;set;}
  public String typeOffre {get;set;}
  public String dateEchancePDE {get;set;}
  public Decimal displayConsoHP_Base {get;set;}
  public Decimal displayPrixHP_Base {get;set;}

  public WrapLigneDeDevis(QuoteLineItem qli){
    SITE_DE_CONSOMMATION = '';
    SITE_DE_CONSOMMATION += qli.pde__r.SiteConsommation__c != null
      ? qli.pde__r.SiteConsommation__c + ' ' + '-' + ' '
      : '';
    SITE_DE_CONSOMMATION += qli.pde__r.NumeroVoie__c != null
      ? qli.pde__r.NumeroVoie__c + ' '
      : '';
    SITE_DE_CONSOMMATION += qli.pde__r.voie__c != null
      ? qli.pde__r.voie__c + ' '
      : '';
    SITE_DE_CONSOMMATION += qli.pde__r.Code_Postal__c != null
      ? qli.pde__r.Code_Postal__c + ' '
      : '';
    SITE_DE_CONSOMMATION += qli.pde__r.Ville__c != null
      ? qli.pde__r.Ville__c
      : '';
    
    Boolean isCU;
    if(qli.PDE__r?.FTA__c == null){
      isCU = false;
    }else{
      isCU = qli.PDE__r.FTA__c.contains('CU');
    }
    Decimal tupeVariable = qli.TURPE_Variable__c != null ? qli.TURPE_Variable__c : 0;
    Decimal tupeFixe = qli.TURPE_Fixe__c != null ? qli.TURPE_Fixe__c : 0;
    BudgetTTC = qli.Budget_TTC__c;
    if (qli.CAR_New__c == null) {
      carElec = 1;
    } else {
      carElec = qli.CAR_New__c == 0 ? 1 : qli.CAR_New__c;
    }
    DateDebut = qli.DebutDeFourniture__c;
    DateFin = qli.Nouvelle_Echeance__c;
    if(qli.PDE__r.DateEcheance__c == null){
      if(qli.PDE__r.Premiere_mise_en_service__c){
        dateEchancePDE = 'Première MES';
      }
      else {
        dateEchancePDE = 'Pas de date d\'échéance';
      }
    } else{
      dateEchancePDE = qli.pde__r.DateEcheance__c.format();
    }


    displayabonnement = qli.AbonnementMois__c;
    displayBudgetAnnuel = qli.BudgetFourniture__c;
    displayBudgetAnnuelEstime = qli.BudgetFourniture__c;
    // displayBudgetHT = qli.BudgetHTTan__c;
    displayBudgetHT = qli.TECH_Budget__c;
    displayBudgetTTC = qli.Budget_TTC__c;
    displayCoutDeCapacite = qli.CoutDeCapacite__c == null ? 0.0 : qli.CoutDeCapacite__c  ;
    displayCSPE = qli?.Taxes__c ? qli?.CSPE__c : null;
    displayCTA = qli.CTA_Mensuel_ELEC__c;
    displayCTAGaz = qli.CTA__c;
    displayDistribution = qli.FraisTransportDistributionCapacite__c;
    displayPrixHCE = qli.PrixHceMwh__c;
    displayPrixHCH = qli.PrixHchMwh__c;
    displayPrixHPE = qli.PrixHpeMwh__c;
    displayPrixHPH = qli.PrixHphMwh__c;
    displayPrixMolecule = qli.PrixMolecule__c;
    displayPrixBase = qli.PrixBase__c;
    displayPrixHC = qli.PrixHC__c == null ? 0.0 : qli.PrixHC__c ;
    displayPrixHP = qli.PrixHP__c;
    displayTCFE = qli?.Taxes__c ? qli?.TECH_TCFE__c : null;
    displayTICGN = qli.TICGN__c;
    displayTURPE = (tupeFixe * 12 + tupeVariable * carElec) / carElec;
    displayTVA = qli.TVA__c;
    displayPrixpointes = qli.PointesMWh__c;
    fournisseurLogo = qli.Quote.TECH_FournisseurLogo__c;
    typeOffre = qli.Quote.TypeOffre__c;
    identifiantSite = qli.PDE__r.ReferencePointEnergie_Refonte__c != null ? qli.PDE__r.ReferencePointEnergie_Refonte__c : qli.PDE__r.PCE_Refonte__c;
    PeriodeCouverture = String.valueOf(DateDebut.format()) + '<br> - <br>' + String.valueOf(DateFin.format());

    TECHOdreAlpha = SITE_DE_CONSOMMATION + String.valueOf(DateFin.year()) + String.valueOf(DateDebut.year());
    displayConsoHP_Base = isCU ? qli.pde__r.Conso_Base__c : qli.pde__r.ConsoHP__c; 
    displayPrixHP_Base  = isCU ? displayPrixBase : displayPrixHP; 

    if (qli.T_QuoteCEE__c == 'Non Soumis') {
      displayCEE = 'Non Soumis';
    } else if (qli.T_QuoteCEE__c == 'Inclus') {
      displayCEE = 'Inclus';
    } else if (qli.T_QuoteCEE__c == 'Soumis' || qli.T_QuoteCEE__c == null) {
      displayCEE = Utils.toCurrency(qli.CeeMwh__c);
    }
  }

  public Integer compareTo(Object compareTo) {
    WrapLigneDeDevis compareToWF = (WrapLigneDeDevis)compareTo;
    // The return value of 0 indicates that both elements are equal.
    Integer returnValue = 0;
    if ((this.TECHOdreAlpha == null) && (compareToWF.TECHOdreAlpha == null)) {
        // both wrappers have null TECHOdreAlphas
        returnValue = 0;
    } else if ((this.TECHOdreAlpha == null) && (compareToWF.TECHOdreAlpha != null)){
        // nulls-first implementation
        returnValue = -1;
    } else if ((this.TECHOdreAlpha != null) && (compareToWF.TECHOdreAlpha == null)){
        // nulls-first implementation
        returnValue = 1;
    } else if (this.TECHOdreAlpha > compareToWF.TECHOdreAlpha) {
        // Set return value to a positive value.
        returnValue = 1;
    } else if (this.TECHOdreAlpha < compareToWF.TECHOdreAlpha) {
        // Set return value to a negative value.
        returnValue = -1;
    } 
    return returnValue;
  }


  // public Integer compareTo(Object other) {
  //     if(SORT_FIELD == SortField.siteDeConsoEnum)
  //         return compareToSiteDeConsommation(other);
  //     else if (SORT_FIELD == SortField.DateFinEnum)
  //         return compareToDateFin(other);
  //     else
  //         return 0;
  // }
  
  // public Integer compareToDateFin(Object compareTo){
  //     WrapLigneDeDevis compareToModel = (WrapLigneDeDevis)compareTo;
  //     // Ascending Order comparison.
  //     if(DateFinInt > compareToModel.DateFinInt)
  //         return 1;
  //     else if(DateFinInt == compareToModel.DateFinInt)
  //         return 0;
  //     else
  //         return -1;
  // }
  
  // public Integer compareToSiteDeConsommation(Object compareTo){
  //   WrapLigneDeDevis compareToModel = (WrapLigneDeDevis)compareTo;
  //     // Ascending Order comparison.
  //     if(SITE_DE_CONSOMMATION > compareToModel.SITE_DE_CONSOMMATION)
  //         return 1;
  //     else if(SITE_DE_CONSOMMATION == compareToModel.SITE_DE_CONSOMMATION)
  //         return 0;
  //     else
  //         return -1;
  // }
}