force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/ACD_valide__c.field-meta.xml
<CustomField>
    <fullName>ACD_valide__c</fullName>
    <description>Calcul si on se trouve à moins de 12 mois de la date de signature de l&apos;ACD</description>
    <formula>TODAY() &lt; ADDMONTHS(Date_signature_ACD__c,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACD valide ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateCalculPsMaxSansErreur__c.field-meta.xml
<CustomField>
    <fullName>DateCalculPsMaxSansErreur__c</fullName>
    <label>Date calcul des PS Max (Sans erreur)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/X12_mois_consommation_SGE__c.field-meta.xml
<CustomField>
    <fullName>X12_mois_consommation_SGE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>12 mois de consommation sur SGE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchCalculatePsMax.cls
global class BatchCalculatePsMax implements Database.batchable<sObject>, Database.AllowsCallouts, Schedulable {
    
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id, ReferencePointEnergie_Refonte__c from PDE__c where ACD_valide__c = true AND X12_mois_consommation_SGE__c = true  AND Recordtype.Name != 'Gaz' AND Segment__c != 'C5' and (DateCalculPsMaxSansErreur__c = null OR DateCalculPsMaxSansErreur__c < LAST_N_Days:7)]);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope){
        List<PDE__c> sitesToUpdate = new List<PDE__c>();
        for(sobject s : scope){
            PDE__c site = (PDE__c) s;
            site = SGEManager.calculatePsMaxForAYear(site);
        	sitesToUpdate.add(site);
        }
        update sitesToUpdate;      
    }
    
    public void finish(Database.BatchableContext bc){

    }
    
    global void execute(SchedulableContext SC) {
        BatchCalculatePsMax b = new BatchCalculatePsMax();
        Database.executeBatch (b,1);
    }
    
}