force-app/main/default/objects/Contract/fields/Date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_echeance__c</fullName>
    <label>Date d&apos;échéance</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>FournisseurTODELETE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FournisseurPicklist__c.field-meta.xml
<CustomField>
    <fullName>FournisseurPicklist__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Ancienne_date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Ancienne_date_echeance__c</fullName>
    <description>Date d&apos;échéance du contrat précédent</description>
    <label>Ancienne date d&apos;échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheanceContract__c.field-meta.xml
<CustomField>
    <fullName>DateEcheanceContract__c</fullName>
    <description>Date d&apos;échéance du contrat actuel</description>
    <label>Date échéance contrat actuel</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/Prix_contrat_PDE__c.object-meta.xml
<CustomObject>
    <label>Prix contrat PDE</label>
    <nameField>
        <label>Nom de Prix contrat PDE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prix contrat PDE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Prix contrat PDE</relationshipLabel>
    <relationshipName>Prix_contrat_PDE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/Date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_echeance__c</fullName>
    <label>Date d&apos;échéance</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/Point_energie__c.field-meta.xml
<CustomField>
    <fullName>Point_energie__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Prix contrat PDE</relationshipLabel>
    <relationshipName>Prix_contrat_PDE</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP018_UpdatePDEAfterValidateContrat.cls
public with sharing class AP018_UpdatePDEAfterValidateContrat {
    
    @invocableMethod(label='Mise à jour des PDE')
    public static List<FlowOutput> updatePDE(List<FlowInputs> params) {
        FlowOutput output = new FlowOutput();
        List<FlowOutput> outputs = new List<FlowOutput>();
        List<PDE__c> listPDEToUpdate = new List<PDE__c>();
        List<Id> listPDEIds = new List<Id>();
        Map<Id, Date> mapPDEWithContract = new Map<Id, Date>();
        String fournisseur = [SELECT fournisseurPicklist__c FROM Contract WHERE Id = :params[0].ContractId].fournisseurPicklist__c;

        //On extrait les  Ids des PDE à partir des Prix_contrat_PDE__c
        for (Prix_contrat_PDE__c pcpde : params[0].listPCPDEFromFlow) {
            listPDEIds.add(pcpde.Point_energie__c);
        }

        //On récupère les PDE qui sont déjà liés à un contrat différent de celui en cours
        for(PDE__c pde : [SELECT Id, DateEcheance__c FROM PDE__c WHERE Id IN (SELECT Point_energie__c FROM Prix_contrat_PDE__c WHERE Contract__c <> :params[0].ContractId AND Point_energie__c IN :listPDEIds)]) {
            mapPDEWithContract.put(pde.Id, pde.DateEcheance__c);
        }
        
        for (Prix_contrat_PDE__c pcpde : params[0].listPCPDEFromFlow) {

            PDE__c pde = new PDE__c();
            pde.Id = pcpde.Point_energie__c;
            //Si le PDE est déjà lié à un contrat, on enregistre l'ancienne date d'échéance pour le calcul du taux de renouvellment
            if(mapPDEWithContract.containsKey(pcpde.Point_energie__c)) {
                pde.ancienne_date_echeance__c = mapPDEWithContract.get(pcpde.Point_energie__c);
                System.debug('PDE déjà lié à un contrat, ancienne date d\'échéance: ' + pde.ancienne_date_echeance__c);
            }
            pde.DateEcheance__c = pcpde.Date_echeance__c;
            pde.DateEcheanceContract__c = pcpde.Date_echeance__c;
            pde.fournisseur__c = fournisseur;

            listPDEToUpdate.add(pde);
        }

        List<Database.SaveResult> listSRPDE = Database.update(listPDEToUpdate);
        for(Database.SaveResult sr : listSRPDE){
            if (!sr.isSuccess()) {
                System.debug(sr.getErrors());
                output.success = false;
                output.message = 'Erreur Update Date échéance sur PDE';
                outputs.add(output);
                return outputs;
            }
        }

        output.success = true;
        outputs.add(output);
        return outputs;
    }


    public class FlowInputs {
        @invocableVariable public Id ContractId;
        @invocableVariable public List<Prix_contrat_PDE__c> listPCPDEFromFlow;
    }
    
    public class FlowOutput {
        @InvocableVariable public Boolean success;
        @InvocableVariable public String message;
    }
}