force-app/main/default/objects/Account/fields/Activite__c.field-meta.xml
<CustomField>
    <fullName>Activite__c</fullName>
    <formula>Code_NAF__r.Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Activité</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Commentaire_Comparatif__c.field-meta.xml
<CustomField>
    <fullName>Commentaire_Comparatif__c</fullName>
    <label>Template Commentaire</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsableCotation__c.field-meta.xml
<CustomField>
    <fullName>ResponsableCotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable de la cotation</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Section_acheminement__c.field-meta.xml
<CustomField>
    <fullName>Section_acheminement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section acheminement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Section_contribution__c.field-meta.xml
<CustomField>
    <fullName>Section_contribution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section contribution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Section_TTC__c.field-meta.xml
<CustomField>
    <fullName>Section_TTC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section TTC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WrapOpport.cls
public class WrapOpport {
  public String Template { get; set; }
  public String Courtier { get; set; }
  public String CourtierTelephone { get; set; }
  public String CourtierEmail { get; set; }
  public String Commentaire { get; set; }
  public String Raison_sociale { get; set; }
  public String SIREN { get; set; }
  public String Prenom_NOM { get; set; }
  public String Telephone { get; set; }
  public String Email { get; set; }
  public String Activite { get; set; }

  public Boolean displayContribution { get; set; }
  public Boolean displayAcheminement { get; set; }
  public Boolean displayTTC { get; set; }

  public WrapOpport(OpportunitycontactRole ocr) {
    Template = ocr.opportunity.TemplateCotation__c;
    String courtierPrenom = ocr.opportunity.responsableCotation__r.FirstName == null ? '' : ocr.opportunity.responsableCotation__r.FirstName;
    String clientPrenom =  ocr.Contact.FirstName == null ? ''  : ocr.Contact.FirstName;
    Courtier = courtierPrenom + ' ' + ocr.opportunity.responsableCotation__r.LastName.toUpperCase();
    CourtierTelephone = ocr.opportunity.responsableCotation__r.phone;
    CourtierEmail = ocr.opportunity.responsableCotation__r.Email;
    Commentaire = ocr.opportunity.Commentaire_Comparatif__c;
    Raison_sociale = ocr.opportunity.Account.Name;
    Activite = ocr.opportunity.Account.activite__c;
    SIREN = ocr.opportunity.Account.Siren__c;
    Prenom_NOM = clientPrenom + ' ' + ocr.Contact.LastName.toUpperCase();
    Telephone = ocr.Contact.Phone;
    Email = ocr.Contact.Email;
    displayContribution = ocr.opportunity.Section_contribution__c;
    displayAcheminement = ocr.opportunity.section_Acheminement__c;
    displayTTC = ocr.opportunity.section_TTC__c;
  }
}