force-app/main/default/objects/Account/fields/Adresse__c.field-meta.xml
<CustomField>
    <fullName>Adresse__c</fullName>
    <formula>Numero_voie__c &amp;&quot; &quot;&amp; Voie__c &amp;&quot; &quot;&amp; Code_postal__c &amp;&quot; &quot;&amp; Ville__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Adresse</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ShowCoproController.cls
public with sharing class ShowCoproController {
  @AuraEnabled
  public static List<Account> retrieveCopro(String syndicId) {
    return [
      SELECT
        Id,
        Name,
        Adresse__c,
        Statut__c,
        (
          SELECT Id,ContactId, Roles, Numero_de_telephone__c, ContactName__c
          FROM AccountContactRelations
          WHERE Roles includes ('Gestionnaire de la copropriété')
        )
      FROM Account
      WHERE Syndic__c = :syndicId
    ];
  }

  @AuraEnabled
  public static Boolean deleteCoproRowAction(List<String> listCoproId) {
    if (listCoproId.size() > 0) {
      Database.DeleteResult[] srList = Database.delete(listCoproId, false);
      for (Database.DeleteResult sr : srList) {
        if (!sr.isSuccess()) {
          return false;
        }
      }
      return true;
    }
    return false;
  }
}