force-app/main/default/objects/Account/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <formula>TEXT(Code_NAF__r.CEE__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/bypassGrill__c.field-meta.xml
<CustomField>
    <fullName>bypassGrill__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Variable pour bypasser le Trigger qui cree automatiquement les Quotes</description>
    <label>bypassGrill</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionPropositionRenouvellement__c.field-meta.xml
<CustomField>
    <fullName>SectionPropositionRenouvellement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Proposition de renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TECH_FTA__c.field-meta.xml
<CustomField>
    <fullName>TECH_FTA__c</fullName>
    <label>TECH_FTA</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/**
 * @author Abdellah Boussaidi
 * @date Creation 03/12/2019
 * @description Opportunity Trigger Handler
 */

public with sharing class OpportunityTriggerHandler extends TriggerHandler {
  //private static final String CLASS_NAME = OpportunityTriggerHandler.class.getName();

  public override void afterUpdate() {
    Set<Id> oppIds = new Set<Id>();

    for (SObject sob : Trigger.new) {

      Opportunity opp = (Opportunity) sob;

      if (!opp.bypassGrill__c) {
          oppIds.add(opp.Id);
      }
  }

    if (oppIds.isEmpty()) {
        return;
    }

    List<Opportunity> listOppSimpleRT = new List<Opportunity>([SELECT Id,Liste_Fournisseurs__c,Name,CloseDate,SectionPropositionRenouvellement__c,SectionSituationActuelle__c,TECH_FTA__c, Account.CEE__c FROM Opportunity WHERE REcordType.DeveloperName like '%Simple%' and Id IN :oppIds]);
    List<Opportunity> listOppMasseRT = new List<Opportunity>([SELECT Id,Liste_Fournisseurs__c,Name,CloseDate,SectionPropositionRenouvellement__c,SectionSituationActuelle__c,TECH_FTA__c, Account.CEE__c FROM Opportunity WHERE REcordType.DeveloperName like '%Masse%' and Id IN :oppIds]);
    
    if(!listOppSimpleRT.isEmpty()){

      List<Opportunity> listOppToUpdateQuote = new List<Opportunity>();
      Map<Opportunity,List<String>> mapOppFournisseurToCreate = new Map<Opportunity,List<String>>();
      List<String> listQuoteOppIdFournisseurToDelete = new List<String>();
      Map<Opportunity,List<String>> mapOppListFournisseurToAdd = new Map<Opportunity,List<String>>();
      Set<Id> setOppIdToDeleteAllQuote = new Set<Id>();
      List<Opportunity> listOppIdSAToAdd = new List<Opportunity>();    
      List<Opportunity> listOppIdPRToAdd = new List<Opportunity>();
      List<String> listOppIdSAToDelete = new List<String>();
      List<String> listOppIdPRToDelete = new List<String>();
      Map<Id,List<String>> mapOppIdFournisseurNew = new Map<Id,List<String>>();
      Map<Id,List<String>> mapOppIdFournisseurOld = new Map<Id,List<String>>();
  
      // Pour chaque opp mise à jour
      for(Opportunity opp  : listOppSimpleRT){
        // Check changement fournisseurs
        
        if (opp.Liste_Fournisseurs__c == null && ((Opportunity)Trigger.oldMap.get(opp.Id)).Liste_Fournisseurs__c != null) { // Tous les fournisseurs ont été retirés
          setOppIdToDeleteAllQuote.add(opp.Id);
        } else if(opp.Liste_Fournisseurs__c != ((Opportunity)Trigger.oldMap.get(opp.Id)).Liste_Fournisseurs__c){ // Les fournisseurs ont été modifiés
          if(((Opportunity)Trigger.oldMap.get(opp.Id)).Liste_Fournisseurs__c == null){ // Les fournisseurs étaient vide avant
            mapOppFournisseurToCreate.put(opp,opp.Liste_Fournisseurs__c.split(';'));
          }else{ // Les fournisseurs ont changé (ajout et/ou suppression)
            listOppToUpdateQuote.add(opp);
            mapOppIdFournisseurNew.put(opp.Id,((Opportunity)Trigger.newMap.get(opp.Id)).Liste_Fournisseurs__c.split(';'));
            mapOppIdFournisseurOld.put(opp.Id,((Opportunity)Trigger.oldMap.get(opp.Id)).Liste_Fournisseurs__c.split(';'));
          }
        }
  
        // Check Changement Situation Actuelle
        if(opp.SectionSituationActuelle__c != ((Opportunity)Trigger.oldMap.get(opp.Id)).SectionSituationActuelle__c){
          if(opp.SectionSituationActuelle__c){
            listOppIdSAToAdd.add(opp);
          }else{
            listOppIdSAToDelete.add(opp.Id);
          }
        }
  
        // Check Changement Proposition de Renouvellement
        if(opp.SectionPropositionRenouvellement__c != ((Opportunity)Trigger.oldMap.get(opp.Id)).SectionPropositionRenouvellement__c){
          if(opp.SectionPropositionRenouvellement__c){
            listOppIdPRToAdd.add(opp);
          }else{
            listOppIdPRToDelete.add(opp.Id);
          }
        }
      }
  
      // Si nouveaux fournisseurs
      if(!mapOppFournisseurToCreate.isEmpty()){
        SM001_GestionDevis.createLigneDevisFournisseur(mapOppFournisseurToCreate);
      }
  
      // Si plus de fournisseurs
      if(!setOppIdToDeleteAllQuote.isEmpty()){
        SM001_GestionDevis.deleteAllFournisseurQuote(setOppIdToDeleteAllQuote);
      }
  
      // Si changement de fournisseurs détecté
      if(!listOppToUpdateQuote.isEmpty()){
        // Pour chaque opp où les fournisseurs ont changés
        for(Opportunity opportunity : listOppToUpdateQuote){
          // Pour chaque fournisseurs de l'ancienne liste
          for(String fournisseur : ((Opportunity)Trigger.oldMap.get(opportunity.Id)).Liste_Fournisseurs__c.split(';')){
            // Si la nouvelle liste ne contient plus ce fournisseur
            if(!mapOppIdFournisseurNew.get(opportunity.Id).contains(fournisseur)){
              // Alors on l'ajoute dans la liste des fournisseurs a supprimer en se basant sur son TECH_Id
              listQuoteOppIdFournisseurToDelete.add(opportunity.Id+'_'+fournisseur);
            }
          }
          // Pour chaque fournisseurs de la nouvelle liste
          for(String fournisseur : mapOppIdFournisseurNew?.get(opportunity.Id)){
            // Si l'ancienne liste ne contenait pas ce fournisseur
            if(!mapOppIdFournisseurOld.get(opportunity.Id).contains(fournisseur)){
              // Alors on l'ajoute dans la map des fournisseurs à ajouter
              if(mapOppListFournisseurToAdd.get(opportunity) != null){
                mapOppListFournisseurToAdd.get(opportunity).add(fournisseur);
              } else{
                mapOppListFournisseurToAdd.put(opportunity,new List<String>{fournisseur});
              }
            }
          }
        }
  
        if(!listQuoteOppIdFournisseurToDelete.isEmpty()){
          SM001_GestionDevis.deleteLigneDevisFournisseur(listQuoteOppIdFournisseurToDelete);
        }
  
        if(!mapOppListFournisseurToAdd.isEmpty()){
          SM001_GestionDevis.addLigneDevisFournisseur(mapOppListFournisseurToAdd);
        }
      }
  
      // Si ajout Situation Actuelle / Proposition Renouvellement
      if(!listOppIdSAToAdd.isEmpty() || !listOppIdPRToAdd.isEmpty()){
        SM001_GestionDevis.addLigneDevisParticulier(listOppIdSAToAdd,listOppIdPRToAdd);
      }
  
      // SI Suppression Situation Actuelle / Proposition Renouvellement
      if(!listOppIdSAToDelete.isEmpty() || !listOppIdPRToDelete.isEmpty()){
        SM001_GestionDevis.deleteLigneDevisParticulier(listOppIdSAToDelete, listOppIdPRToDelete);
      }
    }

    if(!listOppMasseRT.isEmpty()){
      List<Opportunity> listOppMasseToUpdate = new List<Opportunity>();
      List<Opportunity> listOppDeleteAllDevis = new List<Opportunity>();
      for(Opportunity opp : listOppMasseRT){
        //Si on a ni fournisseur ni sections particulières
        if (opp.Liste_Fournisseurs__c != ((Opportunity)Trigger.oldMap.get(opp.Id)).Liste_Fournisseurs__c
            && opp.Liste_Fournisseurs__c == null
            && !opp.SectionSituationActuelle__c
            && !opp.SectionPropositionRenouvellement__c){
              listOppDeleteAllDevis.add(opp);
          //Vérifier aussi les section 
        }
        if(opp.Liste_Fournisseurs__c != ((Opportunity)Trigger.oldMap.get(opp.Id)).Liste_Fournisseurs__c
            || !opp.SectionSituationActuelle__c != !((Opportunity)Trigger.oldMap.get(opp.Id)).SectionSituationActuelle__c
            || !opp.SectionPropositionRenouvellement__c != !((Opportunity)Trigger.oldMap.get(opp.Id)).SectionPropositionRenouvellement__c ){
          listOppMasseToUpdate.add(opp);
        }
      }
      if(!listOppMasseToUpdate.isEmpty()){
        //Si la nouvelle map est null alors faire que de la suppression
        SM002_GestionDevisMasse.generateDevis(listOppMasseToUpdate);
      }

      if(!listOppDeleteAllDevis.isEmpty()){
       SM002_GestionDevisMasse.deleteAllDevis(listOppDeleteAllDevis);
      }
    }
  }
}