force-app/main/default/objects/Account/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <formula>TEXT(Code_NAF__r.CEE__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEE_Fournisseur__mdt/CEE_Fournisseur__mdt.object-meta.xml
<CustomObject>
    <label>CEE Fournisseur</label>
    <pluralLabel>CEE Fournisseurs</pluralLabel>
</CustomObject>

force-app/main/default/objects/CEE_Fournisseur__mdt/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <label>CEE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CEE_Fournisseur__mdt/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Dyneff</fullName>
                <default>true</default>
                <label>Dyneff</label>
            </value>
            <value>
                <fullName>Enovos</fullName>
            </value>
            <value>
                <fullName>Gaz Européen</fullName>
            </value>
            <value>
                <fullName>MET Energie</fullName>
            </value>
            <value>
                <fullName>OHM Energie</fullName>
            </value>
            <value>
                <fullName>SEFE Energy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CEE_Fournisseur__mdt/fields/Type_energie__c.field-meta.xml
<CustomField>
    <fullName>Type_energie__c</fullName>
    <label>Type d&apos;énergie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elec</fullName>
                <default>true</default>
                <label>Elec</label>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TECH_FTA__c.field-meta.xml
<CustomField>
    <fullName>TECH_FTA__c</fullName>
    <label>TECH_FTA</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <label>CEE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inclus</fullName>
            </value>
            <value>
                <fullName>Soumis</fullName>
            </value>
            <value>
                <fullName>Non Soumis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <label>Date de fin de contrat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TECH_PropositionRenouvellement__c.field-meta.xml
<CustomField>
    <fullName>TECH_PropositionRenouvellement__c</fullName>
    <formula>CONTAINS(Name,&apos;PROPOSITION DE RENOUVELLEMENT&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Proposition De Renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tech_situationActuelle__c.field-meta.xml
<CustomField>
    <fullName>Tech_situationActuelle__c</fullName>
    <formula>CONTAINS(Name,&apos;SITUATION ACTUELLE&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech situation actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote_Elec.recordType-meta.xml
<RecordType>
    <fullName>Quote_Elec</fullName>
    <active>true</active>
    <label>Elec</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Quote_Gaz.recordType-meta.xml
<RecordType>
    <fullName>Quote_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Opportunit__c.field-meta.xml
<CustomField>
    <fullName>Opportunit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>l_ments_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_FTA__c.field-meta.xml
<CustomField>
    <fullName>TECH_FTA__c</fullName>
    <formula>TEXT(PDE__r.FTA__c)</formula>
    <label>TECH_FTA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/Valeur_Annuelle__mdt.object-meta.xml
<CustomObject>
    <label>Valeur Annuelle</label>
    <pluralLabel>Valeurs Annuelles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceInfOuEgal36Kva__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceInfOuEgal36Kva__c</fullName>
    <label>CSPE_PuissanceInfOuEgal36Kva</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceSup250__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceSup250__c</fullName>
    <label>CSPE_PuissanceSup250</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceSup36OuEgal250__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceSup36OuEgal250__c</fullName>
    <label>CSPE_PuissanceSup36OuEgal250</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T1__c.field-meta.xml
<CustomField>
    <fullName>CTA_T1__c</fullName>
    <label>CTA T1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T2__c.field-meta.xml
<CustomField>
    <fullName>CTA_T2__c</fullName>
    <label>CTA T2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T3__c.field-meta.xml
<CustomField>
    <fullName>CTA_T3__c</fullName>
    <label>CTA T3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T4__c.field-meta.xml
<CustomField>
    <fullName>CTA_T4__c</fullName>
    <label>CTA T4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T1__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T1__c</fullName>
    <label>Frais Transport Distribution Capacite T1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T2__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T2__c</fullName>
    <label>Frais Transport Distribution Capacite T2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T3__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T3__c</fullName>
    <label>Frais Transport Distribution Capacite T3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T4__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T4__c</fullName>
    <label>Frais Transport Distribution Capacite T4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM001_GestionDevis.cls
public with sharing class SM001_GestionDevis {
 
  public static void createLigneDevisFournisseur(Map<Opportunity,List<String>> mapOppFournisseurToCreate ){

    Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
    RecordType RtElec = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Elec' AND SobjectType = 'Quote' LIMIT 1];
    RecordType RtGaz = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Gaz' AND SobjectType = 'Quote' LIMIT 1];

    List<Quote> listQuoteToCreate = new List<Quote>();
    for(Opportunity opp: mapOppFournisseurToCreate.keySet()){
      for(String fournisseur : mapOppFournisseurToCreate.get(opp)){
        Quote quote = new Quote();
        quote.OpportunityId = opp.Id;
        // quote.UniqueId__c = fournisseur.toUpperCase() + '-' + opp.Id;
        quote.ExpirationDate = opp.CloseDate;
        quote.Name = fournisseur.toUpperCase() + ' - ' + opp.Name;
        quote.Fournisseur__c = fournisseur;
        quote.RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id;
        quote.Pricebook2Id = pb.Id;
        quote.Date_de_fin_de_contrat__c = Date.TODAY();
        quote.CEE__c = opp.Account.CEE__c;
        listQuoteToCreate.add(quote);
      }
    }

    try {
      Database.insert(listQuoteToCreate, true);
      createQLIfromQuote(listQuoteToCreate);
    } catch (Exception e) {
      System.debug('Error '+e.getMessage());
    }
  }

  public static void addLigneDevis(Map<Id, OpportunityPDERelation__c> mapNewOPR) {

    Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
    RecordType RtElec = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Elec' AND SobjectType = 'Quote' LIMIT 1];
    RecordType RtGaz = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Gaz' AND SobjectType = 'Quote' LIMIT 1];
    PricebookEntry entryGaz = [SELECT Id, Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Name = 'GAZ' AND Pricebook2Id = :pb.Id LIMIT 1];
    PricebookEntry entryElec = [SELECT Id, Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Name = 'ELEC' AND Pricebook2Id = :pb.Id LIMIT 1];
    Valeur_Annuelle__mdt customMetadataRecord = [SELECT CTA_T1__c,
                                                    CTA_T2__c,
                                                    CTA_T3__c,
                                                    CTA_T4__c,
                                                    CSPE_PuissanceInfOuEgal36Kva__c,
                                                    CSPE_PuissanceSup36OuEgal250__c,
                                                    CSPE_PuissanceSup250__c,
                                                    Frais_Transport_Distribution_Capacite_T1__c,
                                                    Frais_Transport_Distribution_Capacite_T2__c,
                                                    Frais_Transport_Distribution_Capacite_T3__c,
                                                    Frais_Transport_Distribution_Capacite_T4__c
                                                 FROM 
                                                    Valeur_Annuelle__mdt
                                                 LIMIT 1];

    Map<String,Double> mapFournisseurCEEGaz = new Map<String,Double>();
    Map<String,Double> mapFournisseurCEEElec =  new Map<String,Double>();
    for(CEE_Fournisseur__mdt CEEFournisseur : [SELECT CEE__c, Fournisseur__c, Type_energie__c FROM CEE_Fournisseur__mdt]){
      if(CEEFournisseur.Type_energie__c == 'Gaz'){
        mapFournisseurCEEGaz.put(CEEFournisseur.Fournisseur__c,CEEFournisseur.CEE__c);
      } else {
        mapFournisseurCEEElec.put(CEEFournisseur.Fournisseur__c,CEEFournisseur.CEE__c);
      }
    }

    List<Id> listOpportunityId = new List<Id>();
    List<QuoteLineItem> listQLIToInsert = new List<QuoteLineItem>();
    Map<Id, list<Quote>> mapOppIdListQuote = new Map<Id, list<Quote>>();

    for (OpportunityPDERelation__c opr : mapNewOPR.values()) {
      listOpportunityId.add(opr.Opportunity__c);
    }

    for (Quote quote : [SELECT Id, CEE__c,Fournisseur__c, OpportunityId, TECH_PropositionRenouvellement__c, TECH_SituationActuelle__c FROM Quote WHERE OpportunityId IN :listOpportunityId]) {
      if (mapOppIdListQuote.get(quote.OpportunityId) != null) {
        mapOppIdListQuote.get(quote.OpportunityId).add(quote);
      } else {
        List<Quote> tmpListQuote = new List<Quote>();
        tmpListQuote.add(quote);
        mapOppIdListQuote.put(quote.OpportunityId, tmpListQuote);
      }
    }

    for (OpportunityPDERelation__c opr : mapNewOPR.values()) {
      if (mapOppIdListQuote.get(opr.Opportunity__c) != null) {
        for (Quote quote : mapOppIdListQuote.get(opr.Opportunity__c)) {
          if (quote.TECH_PropositionRenouvellement__c) {
            QuoteLineItem qliPropositionRenouvellement = new QuoteLineItem();
            qliPropositionRenouvellement.Product2Id = entryElec.Product2Id;
            qliPropositionRenouvellement.QuoteId = quote.Id;
            qliPropositionRenouvellement.PriceBookEntryId = opr.pde__r.TypePDE__c == 'Gaz' ? entryGaz.Id : entryElec.id;
            qliPropositionRenouvellement.Quantity = 1;
            qliPropositionRenouvellement.UnitPrice = 0;
            qliPropositionRenouvellement.PDE__c = opr.pde__c;
            qliPropositionRenouvellement.Opportunit__c = quote.OpportunityId;
            qliPropositionRenouvellement.DebutdeFourniture__c = opr.pde__r.DateEcheance__c != null ? opr.pde__r.DateEcheance__c  + 1 : null;
            qliPropositionRenouvellement.ConsoHC__c = opr.pde__r.ConsoHC__c;
            qliPropositionRenouvellement.ConsoHP__c = opr.pde__r.ConsoHP__c;
            qliPropositionRenouvellement.Conso_Base__c = opr.pde__r.Conso_Base__c;
            qliPropositionRenouvellement.Conso_HCE__c = opr.pde__r.Conso_HCE__c;
            qliPropositionRenouvellement.Conso_HCH__c = opr.pde__r.Conso_HCH__c;
            qliPropositionRenouvellement.Conso_HPE__c = opr.pde__r.Conso_HPE__c;
            qliPropositionRenouvellement.Conso_HPH__c = opr.pde__r.Conso_HPH__c;
            qliPropositionRenouvellement.Conso_Pointe__c = opr.pde__r.Conso_Pointe__c;
            qliPropositionRenouvellement.Puissance_souscrite__c = opr.pde__r.Puissance_souscrite__c;
            if(opr.pde__r.Calendrier_fournisseur__c == 'HP/HC' || opr.pde__r.Calendrier_fournisseur__c == 'Heures Pleines/Creuses'){
              qliPropositionRenouvellement.TECH_CalendrierFournisseur__c = 'HP/HC';
            }
            else if(opr.pde__r.Calendrier_fournisseur__c == 'Base' || opr.pde__r.Calendrier_fournisseur__c != ''){
              qliPropositionRenouvellement.TECH_CalendrierFournisseur__c = 'Base';
            }

            qliPropositionRenouvellement.CARGaz__c = opr.pde__r.CARGaz__c;
            if (opr.pde__r.TypePDE__c == 'Gaz') {
              if(opr.pde__r.Tarif__c == 'T1'){
                qliPropositionRenouvellement.CTA__c = customMetadataRecord.CTA_T1__c;
                qliPropositionRenouvellement.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T1__c;
              } else if(opr.pde__r.Tarif__c == 'T2'){
                qliPropositionRenouvellement.CTA__c = customMetadataRecord.CTA_T2__c;
                qliPropositionRenouvellement.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T2__c;
              } else if(opr.pde__r.Tarif__c == 'T3'){
                qliPropositionRenouvellement.CTA__c = customMetadataRecord.CTA_T3__c;
                qliPropositionRenouvellement.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T3__c;
              } else if(opr.pde__r.Tarif__c == 'T4'){
                qliPropositionRenouvellement.CTA__c = customMetadataRecord.CTA_T4__c;
                qliPropositionRenouvellement.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T4__c;
              } else {
                qliPropositionRenouvellement.CTA__c = 1;
                qliPropositionRenouvellement.FraisTransportDistributionCapacite__c = 1;
              }
            }
            else{

              if(opr.PDE__r.Puissance_souscrite__c <= 36){
                qliPropositionRenouvellement.CSPE__c = customMetadataRecord.CSPE_PuissanceInfOuEgal36Kva__c;
              }
              else if (opr.PDE__r.Puissance_souscrite__c > 36 && opr.PDE__r.Puissance_souscrite__c <= 250 ){
                qliPropositionRenouvellement.CSPE__c = customMetadataRecord.CSPE_PuissanceSup36OuEgal250__c;
              }
              else {
                qliPropositionRenouvellement.CSPE__c = customMetadataRecord.CSPE_PuissanceSup250__c;
              }
            }
            listQLIToInsert.add(qliPropositionRenouvellement);
          }

          if (quote.TECH_SituationActuelle__c) {
            QuoteLineItem qliSituationActuelle = new QuoteLineItem();
            qliSituationActuelle.Product2Id = entryElec.Product2Id;
            qliSituationActuelle.QuoteId = quote.Id;
            qliSituationActuelle.PriceBookEntryId = opr.pde__r.TypePDE__c == 'Gaz' ? entryGaz.Id : entryElec.id;
            qliSituationActuelle.Quantity = 1;
            qliSituationActuelle.UnitPrice = 0;
            qliSituationActuelle.PDE__c = opr.pde__c;
            qliSituationActuelle.Opportunit__c = quote.OpportunityId;
            qliSituationActuelle.DebutdeFourniture__c = opr.pde__r.DateEcheance__c != null ? opr.pde__r.DateEcheance__c  + 1 : null;
            qliSituationActuelle.ConsoHC__c = opr.pde__r.ConsoHC__c;
            qliSituationActuelle.ConsoHP__c = opr.pde__r.ConsoHP__c;
            qliSituationActuelle.Conso_Base__c = opr.pde__r.Conso_Base__c;
            qliSituationActuelle.Conso_HCE__c = opr.pde__r.Conso_HCE__c;
            qliSituationActuelle.Conso_HCH__c = opr.pde__r.Conso_HCH__c;
            qliSituationActuelle.Conso_HPE__c = opr.pde__r.Conso_HPE__c;
            qliSituationActuelle.Conso_HPH__c = opr.pde__r.Conso_HPH__c;
            qliSituationActuelle.Conso_Pointe__c = opr.pde__r.Conso_Pointe__c;
            qliSituationActuelle.Puissance_souscrite__c = opr.pde__r.Puissance_souscrite__c;
            if(opr.pde__r.Calendrier_fournisseur__c == 'HP/HC' || opr.pde__r.Calendrier_fournisseur__c == 'Heures Pleines/Creuses'){
              qliSituationActuelle.TECH_CalendrierFournisseur__c = 'HP/HC';
            }
            else if(opr.pde__r.Calendrier_fournisseur__c == 'Base' || opr.pde__r.Calendrier_fournisseur__c != ''){
              qliSituationActuelle.TECH_CalendrierFournisseur__c = 'Base';
            }
            qliSituationActuelle.CARGaz__c = opr.pde__r.CARGaz__c;
            if (opr.pde__r.TypePDE__c == 'Gaz') {
              if(opr.pde__r.Tarif__c == 'T1'){
                qliSituationActuelle.CTA__c = customMetadataRecord.CTA_T1__c;
                qliSituationActuelle.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T1__c;
              } else if(opr.pde__r.Tarif__c == 'T2'){
                qliSituationActuelle.CTA__c = customMetadataRecord.CTA_T2__c;
                qliSituationActuelle.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T2__c;
              } else if(opr.pde__r.Tarif__c == 'T3'){
                qliSituationActuelle.CTA__c = customMetadataRecord.CTA_T3__c;
                qliSituationActuelle.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T3__c;
              } else if(opr.pde__r.Tarif__c == 'T4'){
                qliSituationActuelle.CTA__c = customMetadataRecord.CTA_T4__c;
                qliSituationActuelle.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T4__c;
              } else {
                qliSituationActuelle.CTA__c = 1;
                qliSituationActuelle.FraisTransportDistributionCapacite__c = 1;
              }
            }
            else{

              if(opr.PDE__r.Puissance_souscrite__c <= 36){
                qliSituationActuelle.CSPE__c = customMetadataRecord.CSPE_PuissanceInfOuEgal36Kva__c;
              }
              else if (opr.PDE__r.Puissance_souscrite__c > 36 && opr.PDE__r.Puissance_souscrite__c <= 250 ){
                qliSituationActuelle.CSPE__c = customMetadataRecord.CSPE_PuissanceSup36OuEgal250__c;
              }
              else {
                qliSituationActuelle.CSPE__c = customMetadataRecord.CSPE_PuissanceSup250__c;
              }

            }
            listQLIToInsert.add(qliSituationActuelle);
          }

          if (!quote.TECH_PropositionRenouvellement__c && !quote.TECH_SituationActuelle__c){
            QuoteLineItem qliToInsert = new QuoteLineItem();
            qliToInsert.Product2Id = entryElec.Product2Id;
            qliToInsert.QuoteId = quote.Id;
            qliToInsert.PriceBookEntryId = opr.pde__r.TypePDE__c == 'Gaz' ? entryGaz.Id : entryElec.id;
            qliToInsert.Quantity = 1;
            qliToInsert.UnitPrice = 0;
            qliToInsert.PDE__c = opr.pde__c;
            qliToInsert.Opportunit__c = quote.OpportunityId;
            qliToInsert.DebutdeFourniture__c = opr.pde__r.DateEcheance__c != null ? opr.pde__r.DateEcheance__c  + 1 : null;
            qliToInsert.ConsoHC__c = opr.pde__r.ConsoHC__c;
            qliToInsert.ConsoHP__c = opr.pde__r.ConsoHP__c;
            qliToInsert.Conso_Base__c = opr.pde__r.Conso_Base__c;
            qliToInsert.Conso_HCE__c = opr.pde__r.Conso_HCE__c;
            qliToInsert.Conso_HCH__c = opr.pde__r.Conso_HCH__c;
            qliToInsert.Conso_HPE__c = opr.pde__r.Conso_HPE__c;
            qliToInsert.Conso_HPH__c = opr.pde__r.Conso_HPH__c;
            qliToInsert.Conso_Pointe__c = opr.pde__r.Conso_Pointe__c;
            qliToInsert.Puissance_souscrite__c = opr.pde__r.Puissance_souscrite__c;
            if(opr.pde__r.Calendrier_fournisseur__c == 'HP/HC' || opr.pde__r.Calendrier_fournisseur__c == 'Heures Pleines/Creuses'){
              qliToInsert.TECH_CalendrierFournisseur__c = 'HP/HC';
            }
            else if(opr.pde__r.Calendrier_fournisseur__c == 'Base' || opr.pde__r.Calendrier_fournisseur__c != ''){
              qliToInsert.TECH_CalendrierFournisseur__c = 'Base';
            }

            qliToInsert.CARGaz__c = opr.pde__r.CARGaz__c;
            if(quote.CEE__c == 'Soumis'){
              if(opr.pde__r.TypePDE__c == 'Gaz'){
                qliToInsert.CeeMwh__c = mapFournisseurCEEGaz.get(quote.Fournisseur__c) == null ? 0 : mapFournisseurCEEGaz.get(quote.Fournisseur__c); 
              }
              else{
                qliToInsert.CeeMwh__c = mapFournisseurCEEElec.get(quote.Fournisseur__c) == null ? 0 : mapFournisseurCEEElec.get(quote.Fournisseur__c); 
              }
            }
            if (opr.pde__r.TypePDE__c == 'Gaz') {
              if(opr.pde__r.Tarif__c == 'T1'){
                qliToInsert.CTA__c = customMetadataRecord.CTA_T1__c;
                qliToInsert.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T1__c;
              } else if(opr.pde__r.Tarif__c == 'T2'){
                qliToInsert.CTA__c = customMetadataRecord.CTA_T2__c;
                qliToInsert.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T2__c;
              } else if(opr.pde__r.Tarif__c == 'T3'){
                qliToInsert.CTA__c = customMetadataRecord.CTA_T3__c;
                qliToInsert.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T3__c;
              } else if(opr.pde__r.Tarif__c == 'T4'){
                qliToInsert.CTA__c = customMetadataRecord.CTA_T4__c;
                qliToInsert.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T4__c;
              } else {
                qliToInsert.CTA__c = 1;
                qliToInsert.FraisTransportDistributionCapacite__c = 1;
              }
            }
            else{
              if(opr.PDE__r.Puissance_souscrite__c <= 36){
                qliToInsert.CSPE__c = customMetadataRecord.CSPE_PuissanceInfOuEgal36Kva__c;
              }
              else if (opr.PDE__r.Puissance_souscrite__c > 36 && opr.PDE__r.Puissance_souscrite__c <= 250 ){
                qliToInsert.CSPE__c = customMetadataRecord.CSPE_PuissanceSup36OuEgal250__c;
              }
              else {
                qliToInsert.CSPE__c = customMetadataRecord.CSPE_PuissanceSup250__c;
              }
            }
            listQLIToInsert.add(qliToInsert);
          }
        }
      }
    }

    if (!listQLIToInsert.isEmpty()) {
      insert listQLIToInsert;
    }
  }

  public static void addLigneDevisFournisseur(Map<Opportunity,List<String>> mapOppIdListFournisseurToAdd ){

    Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
    RecordType RtElec = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Elec' AND SobjectType = 'Quote' LIMIT 1];
    RecordType RtGaz = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Gaz' AND SobjectType = 'Quote' LIMIT 1];
    List<Quote> listQuoteToInsert = new list<Quote>();
    
    for(Opportunity opp : mapOppIdListFournisseurToAdd.keySet()){
      for(String fournisseur : mapOppIdListFournisseurToAdd.get(opp)){
        listQuoteToInsert.add(
          new Quote(
            OpportunityId = opp.Id,
            ExpirationDate = opp.CloseDate,
            Name = fournisseur.toUpperCase() + ' - ' + opp.Name,
            Fournisseur__c = fournisseur,
            RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id,
            Pricebook2Id = pb.Id,
            Date_de_fin_de_contrat__c = Date.TODAY(),
            CEE__c = opp.Account.CEE__c
          )
        );
      }
    }

    try {
      Database.insert(listQuoteToInsert, true);
      createQLIfromQuote(listQuoteToInsert);
    } catch (Exception e) {
      system.debug('addLigneDevisFournisseur Error '+ e.getCause());
    }
  }

  public static void addLigneDevisParticulier(List<Opportunity> listOppIdSAToAdd,List<Opportunity> listOppIdPRToAdd){
    
    Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
    RecordType RtElec = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Elec' AND SobjectType = 'Quote' LIMIT 1];
    RecordType RtGaz = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Gaz' AND SobjectType = 'Quote' LIMIT 1];
    List<Quote> listQuoteToInsert = new List<Quote>();
    List<Quote> listQLIToInsert = new List<Quote>();

    if(!listOppIdSAToAdd.isEmpty()){
      for(Opportunity opp: listOppIdSAToAdd){
        listQuoteToInsert.add(
          new Quote(
            OpportunityId = opp.Id,
            ExpirationDate = opp.CloseDate,
            Name = 'SITUATION ACTUELLE' + ' - ' + opp.Name,
            RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id,
            Pricebook2Id = pb.Id,
            Date_de_fin_de_contrat__c = Date.TODAY(),
            Fournisseur__c = 'Situation Actuelle',
            CEE__c = opp.Account.CEE__c
          )
        );
      }
    }

    if(!listOppIdPRToAdd.isEmpty()){
      for(Opportunity opp: listOppIdPRToAdd){
        listQuoteToInsert.add(
          new Quote(
            OpportunityId = opp.Id,
            ExpirationDate = opp.CloseDate,
            Name = 'PROPOSITION DE RENOUVELLEMENT' + ' - ' + opp.Name,
            RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id,
            Pricebook2Id = pb.Id,
            Date_de_fin_de_contrat__c = Date.TODAY(),
            Fournisseur__c = 'Proposition Renouvellement',
            CEE__c = opp.Account.CEE__c
          )
        );
      }
    }

    try {
      Database.insert(listQuoteToInsert, true);
      createQLIfromQuote(listQuoteToInsert);
    } catch (Exception e) {
      System.debug('Error '+e.getMessage());
    }
  }

  public static void deleteLigneDevisFournisseur(List<String> listQuoteOppIdFournisseurToDelete){
    try {
      delete [SELECT Id FROM Quote WHERE TECH_OppId_fournisseur__c IN : listQuoteOppIdFournisseurToDelete];
    } catch (Exception e) {
      System.debug('Error '+e.getMessage());
    }
  }

  public static void deleteLigneDevisParticulier(List<Id> listOppIdSAToDelete, List<Id> listOppIdPRToDelete){

    try {
      if(listOppIdSAToDelete != null) {
        delete [SELECT Id FROM Quote WHERE OpportunityId IN : listOppIdSAToDelete AND Tech_situationActuelle__c = True];
      } 
      if(listOppIdPRToDelete != null) {
        delete [SELECT Id FROM Quote WHERE OpportunityId IN : listOppIdPRToDelete AND TECH_PropositionRenouvellement__c = True];
      }
    } catch (Exception e) {
      System.debug('Error '+e.getMessage());
    }
  }

  public static void deleteLigneDevis(Map<Id, OpportunityPDERelation__c> mapOldOPR) {
    List<Id> listOpportunityId = new List<Id>();
    List<QuoteLineItem> listQLIToDelete = new List<QuoteLineItem>();
    Map<Id, list<QuoteLineItem>> mapOppIdListQLI = new Map<Id, list<QuoteLineItem>>();

    for (OpportunityPDERelation__c opr : mapOldOPR.values()) {
      listOpportunityId.add(opr.Opportunity__c);
    }

    for (QuoteLineItem qli : [SELECT Id, PDE__c, TECH_OpportunityId__c FROM QuoteLineItem WHERE TECH_OpportunityId__c IN :listOpportunityId]) {
      if (mapOppIdListQLI.get(qli.TECH_OpportunityId__c) != null) {
        mapOppIdListQLI.get(qli.TECH_OpportunityId__c).add(qli);
      } else {
        List<QuoteLineItem> tmpListQuoteLineItem = new List<QuoteLineItem>();
        tmpListQuoteLineItem.add(qli);
        mapOppIdListQLI.put(qli.TECH_OpportunityId__c, tmpListQuoteLineItem);
      }
    }

    for (OpportunityPDERelation__c opr : mapOldOPR.values()) {
      for (QuoteLineItem qli : mapOppIdListQLI.get(opr.Opportunity__c)) {
        if (qli.PDE__c == opr.PDE__c) {
          listQLIToDelete.add(qli);
        }
      }
    }
    if (!listQLIToDelete.isEmpty()) {
      delete listQLIToDelete;
    }
  }

  public static void deleteAllFournisseurQuote(Set<Id> oppIds) {
    try {
      delete [SELECT Id FROM Quote WHERE OpportunityId IN : oppIds AND Tech_situationActuelle__c = false AND TECH_PropositionRenouvellement__c = false];
    } catch (Exception e) {
      System.debug('Error '+e.getMessage());
    }
  }

  private static void createQLIfromQuote(List<Quote> ListQuote){

    Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
    PricebookEntry entryGaz = [SELECT Id, Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Name = 'GAZ' AND Pricebook2Id = :pb.Id LIMIT 1];
    PricebookEntry entryElec = [SELECT Id, Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Name = 'ELEC' AND Pricebook2Id = :pb.Id LIMIT 1];
    Valeur_Annuelle__mdt customMetadataRecord = [SELECT CTA_T1__c,
                                                        CTA_T2__c,
                                                        CTA_T3__c,
                                                        CTA_T4__c,
                                                 		CSPE_PuissanceInfOuEgal36Kva__c,
                                                    	CSPE_PuissanceSup36OuEgal250__c,
                                                    	CSPE_PuissanceSup250__c,
                                                        Frais_Transport_Distribution_Capacite_T1__c,
                                                        Frais_Transport_Distribution_Capacite_T2__c,
                                                        Frais_Transport_Distribution_Capacite_T3__c,
                                                        Frais_Transport_Distribution_Capacite_T4__c
                                                    FROM 
                                                      Valeur_Annuelle__mdt
                                                    LIMIT 1];

    Map<String,Double> mapFournisseurCEEGaz = new Map<String,Double>();
    Map<String,Double> mapFournisseurCEEElec =  new Map<String,Double>();
    for(CEE_Fournisseur__mdt CEEFournisseur : [SELECT CEE__c, Fournisseur__c, Type_energie__c FROM CEE_Fournisseur__mdt]){
      if(CEEFournisseur.Type_energie__c == 'Gaz'){
        mapFournisseurCEEGaz.put(CEEFournisseur.Fournisseur__c,CEEFournisseur.CEE__c);
      } else {
        mapFournisseurCEEElec.put(CEEFournisseur.Fournisseur__c,CEEFournisseur.CEE__c);
      }
    }
    Set<Id> oppId = new Set<Id>();
    Map<Id,List<OpportunityPDERelation__c>> mapOppIdListOPR = new Map<Id,List<OpportunityPDERelation__c>>();
    List<QuoteLineItem> listQLIToInsert = new list<QuoteLineItem>();

    // On récupère les OppId depuis la liste des quotes
    for (Quote quote : ListQuote) {
      oppId.add(quote.OpportunityId);
    }

    // On récupère les OPR et on les stock dans une map avec l'oppID
    for (OpportunityPDERelation__c opr : [SELECT  PDE__r.Id, 
                                                  Opportunity__c, 
                                                  PDE__r.TypePDE__c, 
                                                  PDE__r.DateEcheance__c,
                                                  PDE__r.Calendrier_fournisseur__c,
                                                  PDE__r.ConsoHC__c,
                                                  PDE__r.ConsoHP__c,
                                                  PDE__r.Conso_Base__c,
                                                  PDE__r.Conso_HCE__c,
                                                  PDE__r.Conso_HCH__c,
                                                  PDE__r.Conso_HPE__c,
                                                  PDE__r.Conso_HPH__c,
                                                  PDE__r.Conso_Pointe__c,
                                                  PDE__r.Segment__c,
                                                  PDE__r.Puissance_souscrite__c,
                                                  PDE__r.CARGaz__c ,
                                                  PDE__r.Tarif__c
                                          FROM OpportunityPDERelation__c 
                                          WHERE Opportunity__c 
                                          IN :oppId]) {
      if(mapOppIdListOPR.get(opr.Opportunity__c) != null) {
        mapOppIdListOPR.get(opr.Opportunity__c).add(opr);
      } else {
        List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
        listOPR.add(opr);
        mapOppIdListOPR.put(opr.Opportunity__c, listOPR);
      }
    }

    // Pour chaque Quote insert
    for (Quote quote : ListQuote) {
      // On parcours les OPR de l'opp associée
      if (mapOppIdListOPR.get(quote.OpportunityId) != null) {
        for (OpportunityPDERelation__c opr : mapOppIdListOPR.get(quote.OpportunityId)) {
          // On créer les QLI correspondantes
          QuoteLineItem qli = new QuoteLineItem();
          qli.Product2Id = entryElec.Product2Id;
          qli.QuoteId = quote.Id;
          qli.PriceBookEntryId = opr.pde__r.TypePDE__c == 'Gaz'? entryGaz.Id: entryElec.id;
          qli.Quantity = 1;
          qli.UnitPrice = 0;
          qli.PDE__c = opr.pde__r.Id;
          qli.DebutdeFourniture__c = opr.pde__r.DateEcheance__c != null ? opr.pde__r.DateEcheance__c  + 1 : null;
          qli.Opportunit__c = quote.OpportunityId;
          qli.ConsoHC__c = opr.pde__r.ConsoHC__c;
          qli.ConsoHP__c = opr.pde__r.ConsoHP__c;
          qli.Conso_Base__c = opr.pde__r.Conso_Base__c;
          qli.Conso_HCE__c = opr.pde__r.Conso_HCE__c;
          qli.Conso_HCH__c = opr.pde__r.Conso_HCH__c;
          qli.Conso_HPE__c = opr.pde__r.Conso_HPE__c;
          qli.Conso_HPH__c = opr.pde__r.Conso_HPH__c;
          qli.Conso_Pointe__c = opr.pde__r.Conso_Pointe__c;
          qli.Puissance_souscrite__c = opr.pde__r.Puissance_souscrite__c;

          if(opr.pde__r.Calendrier_fournisseur__c == 'HP/HC' || opr.pde__r.Calendrier_fournisseur__c == 'Heures Pleines/Creuses'){
            qli.TECH_CalendrierFournisseur__c = 'HP/HC';
          }
          else if(opr.pde__r.Calendrier_fournisseur__c == 'Base' || opr.pde__r.Calendrier_fournisseur__c != ''){
            qli.TECH_CalendrierFournisseur__c = 'Base';
          }
          
          qli.CARGaz__c = opr.pde__r.CARGaz__c;
          
          if(quote.CEE__c == 'Soumis'){
            if(opr.pde__r.TypePDE__c == 'Gaz'){
              qli.CeeMwh__c = mapFournisseurCEEGaz.get(quote.Fournisseur__c) == null ? 0 : mapFournisseurCEEGaz.get(quote.Fournisseur__c); 
            }
            else{
              qli.CeeMwh__c = mapFournisseurCEEElec.get(quote.Fournisseur__c) == null ? 0 : mapFournisseurCEEElec.get(quote.Fournisseur__c); 
            }
          }
          if (opr.pde__r.TypePDE__c == 'Gaz') {
            if(opr.pde__r.Tarif__c == 'T1'){
              qli.CTA__c = customMetadataRecord.CTA_T1__c;
              qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T1__c;
            } else if(opr.pde__r.Tarif__c == 'T2'){
              qli.CTA__c = customMetadataRecord.CTA_T2__c;
              qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T2__c;
            } else if(opr.pde__r.Tarif__c == 'T3'){
              qli.CTA__c = customMetadataRecord.CTA_T3__c;
              qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T3__c;
            } else if(opr.pde__r.Tarif__c == 'T4'){
              qli.CTA__c = customMetadataRecord.CTA_T4__c;
              qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T4__c;
            } else {
              qli.CTA__c = 1;
              qli.FraisTransportDistributionCapacite__c = 1;
            }
          }
          else{

            if(opr.PDE__r.Puissance_souscrite__c <= 36){
              qli.CSPE__c = customMetadataRecord.CSPE_PuissanceInfOuEgal36Kva__c;
            }
            else if (opr.PDE__r.Puissance_souscrite__c > 36 && opr.PDE__r.Puissance_souscrite__c <= 250 ){
              qli.CSPE__c = customMetadataRecord.CSPE_PuissanceSup36OuEgal250__c;
            }
            else {
              qli.CSPE__c = customMetadataRecord.CSPE_PuissanceSup250__c;
            }
          }
          listQLIToInsert.add(qli);
        }
      }
    }
    System.debug('listQLIToInsert '+listQLIToInsert);

    try {
      Database.insert(listQLIToInsert, true);
    } catch (Exception e) {
      System.debug('createQLIfromQuote Error '+e.getMessage());
    }
  }
}