force-app/main/default/objects/Account/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <formula>TEXT(Code_NAF__r.CEE__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionPropositionRenouvellement__c.field-meta.xml
<CustomField>
    <fullName>SectionPropositionRenouvellement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Proposition de renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TECH_FTA__c.field-meta.xml
<CustomField>
    <fullName>TECH_FTA__c</fullName>
    <label>TECH_FTA</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <label>CEE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inclus</fullName>
            </value>
            <value>
                <fullName>Soumis</fullName>
            </value>
            <value>
                <fullName>Non Soumis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <label>Date de fin de contrat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote_Elec.recordType-meta.xml
<RecordType>
    <fullName>Quote_Elec</fullName>
    <active>true</active>
    <label>Elec</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Quote_Gaz.recordType-meta.xml
<RecordType>
    <fullName>Quote_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM002_GestionDevisMasse.cls
public with sharing class SM002_GestionDevisMasse {

    public static void generateDevis(List<Opportunity> listOpp){

        Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
        RecordType RtElec = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Elec' AND SobjectType = 'Quote' LIMIT 1];
        RecordType RtGaz = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Gaz' AND SobjectType = 'Quote' LIMIT 1];
        List<Id> listOppId = new List<Id>();
        List<Quote> listQuoteToCreate = new List<Quote>();
        for(Opportunity opp : listOpp){
            listOppId.add(opp.Id);
        }
        try {
            Database.delete([SELECT Id from Quote where OpportunityId in :listOppId],true);
        } catch (Exception e) {
            System.debug('Error '+e.getMessage());
        }

        for(Opportunity opp: listOpp){
            if(opp.Liste_Fournisseurs__c != null){
                for(String fournisseur : opp.Liste_Fournisseurs__c.split(';')){
                    Quote quote = new Quote();
                    quote.OpportunityId = opp.Id;
                    // quote.UniqueId__c = fournisseur.toUpperCase() + '-' + opp.Id;
                    quote.ExpirationDate = opp.CloseDate;
                    quote.Name = fournisseur.toUpperCase() + ' - ' + opp.Name;
                    quote.Fournisseur__c = fournisseur;
                    quote.RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id;
                    quote.Pricebook2Id = pb.Id;
                    quote.Date_de_fin_de_contrat__c = Date.TODAY();
                    quote.CEE__c = opp.Account.CEE__c;
                    listQuoteToCreate.add(quote);
                }
            }
            if(opp.SectionPropositionRenouvellement__c){
                listQuoteToCreate.add(
                    new Quote(
                      OpportunityId = opp.Id,
                      ExpirationDate = opp.CloseDate,
                      Name = 'PROPOSITION DE RENOUVELLEMENT' + ' - ' + opp.Name,
                      RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id,
                      Pricebook2Id = pb.Id,
                      CEE__c = opp.Account.CEE__c,
                      Date_de_fin_de_contrat__c = Date.TODAY(),
                      Fournisseur__c = 'Proposition Renouvellement'
                    )
                  );
            }
            if(opp.SectionSituationActuelle__c){
                listQuoteToCreate.add(
                    new Quote(
                      OpportunityId = opp.Id,
                      ExpirationDate = opp.CloseDate,
                      Name = 'SITUATION ACTUELLE' + ' - ' + opp.Name,
                      RecordTypeId = opp.TECH_FTA__c == 'Gaz' ? RTGaz.Id : RTElec.Id,
                      Pricebook2Id = pb.Id,
                      CEE__c = opp.Account.CEE__c,
                      Date_de_fin_de_contrat__c = Date.TODAY(),
                      Fournisseur__c = 'Situation Actuelle'
                    )
                  );
            }
        }

        try {
            Database.insert(listQuoteToCreate, true);
        } catch (Exception e) {
            System.debug('Error SM002_GestionDevisMasse generateDevis '+e.getMessage());
        }
    }

    public static void deleteAllDevis(List<Opportunity> listOpp){
        List<Id> listOppId = new List<Id>();
        for(Opportunity opp : listOpp){
            listOppId.add(opp.Id);
        }
        try {
            Database.delete([SELECT Id from Quote where OpportunityId in :listOppId],true);
        } catch (Exception e) {
            System.debug('Error SM002_GestionDevisMasse deleteAllDevis '+e.getMessage());
        }
    }
}