force-app/main/default/objects/Account/fields/CEE__c.field-meta.xml
<CustomField>
    <fullName>CEE__c</fullName>
    <formula>TEXT(Code_NAF__r.CEE__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CEE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TECH_FTA__c.field-meta.xml
<CustomField>
    <fullName>TECH_FTA__c</fullName>
    <label>TECH_FTA</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Calcul_grille__c.field-meta.xml
<CustomField>
    <fullName>Calcul_grille__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calcul grille</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote_Elec.recordType-meta.xml
<RecordType>
    <fullName>Quote_Elec</fullName>
    <active>true</active>
    <label>Elec</label>
</RecordType>

force-app/main/default/objects/Quote/recordTypes/Quote_Gaz.recordType-meta.xml
<RecordType>
    <fullName>Quote_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_FTA__c.field-meta.xml
<CustomField>
    <fullName>TECH_FTA__c</fullName>
    <formula>TEXT(PDE__r.FTA__c)</formula>
    <label>TECH_FTA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/Valeur_Annuelle__mdt.object-meta.xml
<CustomObject>
    <label>Valeur Annuelle</label>
    <pluralLabel>Valeurs Annuelles</pluralLabel>
</CustomObject>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceInfOuEgal36Kva__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceInfOuEgal36Kva__c</fullName>
    <label>CSPE_PuissanceInfOuEgal36Kva</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceSup250__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceSup250__c</fullName>
    <label>CSPE_PuissanceSup250</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CSPE_PuissanceSup36OuEgal250__c.field-meta.xml
<CustomField>
    <fullName>CSPE_PuissanceSup36OuEgal250__c</fullName>
    <label>CSPE_PuissanceSup36OuEgal250</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T1__c.field-meta.xml
<CustomField>
    <fullName>CTA_T1__c</fullName>
    <label>CTA T1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T2__c.field-meta.xml
<CustomField>
    <fullName>CTA_T2__c</fullName>
    <label>CTA T2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T3__c.field-meta.xml
<CustomField>
    <fullName>CTA_T3__c</fullName>
    <label>CTA T3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/CTA_T4__c.field-meta.xml
<CustomField>
    <fullName>CTA_T4__c</fullName>
    <label>CTA T4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T1__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T1__c</fullName>
    <label>Frais Transport Distribution Capacite T1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T2__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T2__c</fullName>
    <label>Frais Transport Distribution Capacite T2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T3__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T3__c</fullName>
    <label>Frais Transport Distribution Capacite T3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Valeur_Annuelle__mdt/fields/Frais_Transport_Distribution_Capacite_T4__c.field-meta.xml
<CustomField>
    <fullName>Frais_Transport_Distribution_Capacite_T4__c</fullName>
    <label>Frais Transport Distribution Capacite T4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <customValue>
        <fullName>GEG</fullName>
    </customValue>
    <customValue>
        <fullName>Ilek</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP021_CreateQuoteQLIGrille.cls
global with sharing class AP021_CreateQuoteQLIGrille {

    @InvocableMethod(label='Créer Quote depuis Wrapper')
    public static List<FlowOutput> creationQuoteQLI(List<FlowInput> inputs) {
        List<FlowOutput> outputs = new List<FlowOutput>();
        FlowOutput output = new FlowOutput();
        Id oppId = inputs[0].opportunityId;

        // --- SUPPRESSION DES DOUBLONS ---
        Set<String> fournisseursCibles = new Set<String>();
        Set<String> dureesCibles = new Set<String>();

        for(FlowInput input : inputs) {
            for (WrapCreationQuoteGrille w : input.wrappers) {
                if (String.isNotBlank(w.fournisseurs)) fournisseursCibles.add(w.fournisseurs);
                if (String.isNotBlank(w.duree)) {
                    for(String d : w.duree.split(';')) {
                        String cleanDuree = d.split('_')[0].trim();
                        dureesCibles.add(cleanDuree); 
                    }
                }
            }
        }

        // On récupère les quotes et leurs Qli pour avoir la durée
        List<Quote> quotesToDelete = [SELECT Id, Name, Fournisseur__c, 
                                    (SELECT DureeEngagement__c FROM QuoteLineItems LIMIT 1) 
                                    FROM Quote 
                                    WHERE OpportunityId = :oppId 
                                    AND Fournisseur__c IN :fournisseursCibles
                                    AND Calcul_grille__c = true];

        List<Quote> toDelete = new List<Quote>();

        for(Quote oldQ : quotesToDelete) {

            if (oldQ.Fournisseur__c == 'Ekwateur' || oldQ.Fournisseur__c == 'Ilek') {

                toDelete.add(oldQ);
                continue; 
            }

            if (!oldQ.QuoteLineItems.isEmpty()) {
                Decimal existingDuree = oldQ.QuoteLineItems[0].DureeEngagement__c;
                
                if (existingDuree != null) {
                    String existingDureeStr = String.valueOf(existingDuree.intValue());

                    // Vérification de la correspondance
                    if (dureesCibles.contains(existingDureeStr)) {
                        toDelete.add(oldQ);
                    } else {
                    }
                } else {
                    System.debug('ATTENTION : DureeEngagement__c est NULL sur la QLI de cette Quote.');
                }
            } else {
                System.debug(' ATTENTION : Aucun QuoteLineItem trouvé pour cette Quote.');
            }
        }

        if(!toDelete.isEmpty()) {
            delete toDelete;
        }  
       
        Integer dureeEngagement = 0;
        List<Quote> allQuotesToInsert = new List<Quote>();
        List<QuoteLineItem> allQLIToInsert = new List<QuoteLineItem>();
        List<QuoteContext> contexts = new List<QuoteContext>();

        // Requête PDE
        Valeur_Annuelle__mdt customMetadataRecord = [SELECT CTA_T1__c,
                                                    CTA_T2__c,
                                                    CTA_T3__c,
                                                    CTA_T4__c,
                                                    CSPE_PuissanceInfOuEgal36Kva__c,
                                                    CSPE_PuissanceSup36OuEgal250__c,
                                                    CSPE_PuissanceSup250__c,
                                                    Frais_Transport_Distribution_Capacite_T1__c,
                                                    Frais_Transport_Distribution_Capacite_T2__c,
                                                    Frais_Transport_Distribution_Capacite_T3__c,
                                                    Frais_Transport_Distribution_Capacite_T4__c
                                                FROM 
                                                    Valeur_Annuelle__mdt
                                                LIMIT 1];

        List<OpportunityPDERelation__c> pdeRelations = [
            SELECT PDE__c,
                Opportunity__r.Name,
                Opportunity__r.Id,
                Opportunity__r.TECH_FTA__c,
                Opportunity__r.Liste_fournisseurs__c,
                PDE__r.RecordType.Name,
                PDE__r.Puissance_souscrite__c,
                PDE__r.Tarif__c,
                PDE__r.TypePDE__c,
                PDE__r.ConsoHC__c,
                PDE__r.ConsoHP__c,
                PDE__r.Conso_Base__c,
                PDE__r.Conso_HCE__c,
                PDE__r.Conso_HCH__c,
                PDE__r.Conso_HPE__c,
                PDE__r.Conso_HPH__c,
                PDE__r.Conso_Pointe__c,
                PDE__r.EntiteJuridique__c,
                PDE__r.EntiteJuridique__r.CEE__c,
                PDE__r.EntiteJuridique__r.TECH_last_credit_score__c, 
                PDE__r.Segment__c, 
                PDE__r.EntiteJuridique__r.ELLISPHERE__Elli_code_ape08__c, 
                PDE__r.Fournisseur__c, 
                PDE__r.DateEcheance__c,
                PDE__r.Calendrier_fournisseur__c,
                PDE__r.Consommation_Annuelle_de_R_f_rence_Elec__c,
                PDE__r.CARGaz__c
            FROM OpportunityPDERelation__c 
            WHERE Opportunity__c = :oppId
        ];
        Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
        RecordType RtElec = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Elec' AND SobjectType = 'Quote' LIMIT 1];
        RecordType RtGaz = [SELECT id, DeveloperName, SobjectType FROM RecordType WHERE DeveloperName = 'Quote_Gaz' AND SobjectType = 'Quote' LIMIT 1];
        PricebookEntry entryGaz = [SELECT Id, Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Name = 'GAZ' AND Pricebook2Id = :pb.Id LIMIT 1];
        PricebookEntry entryElec = [SELECT Id, Name, Pricebook2Id, Product2Id FROM PricebookEntry WHERE Name = 'ELEC' AND Pricebook2Id = :pb.Id LIMIT 1];

        if(pdeRelations.isEmpty()) {
            System.debug('ATTENTION : Aucune PDE trouvée pour l\'opportunité ' + oppId);
        } 

        if (!pdeRelations.isEmpty()) {
            // Récupérer l'opportunité à jour
            Opportunity oppToUpdate = new Opportunity(Id = oppId);
            
            // Récupérer la liste existante des fournisseurs
            Set<String> existingFournisseurs = new Set<String>();
            if (pdeRelations[0].Opportunity__r.Liste_fournisseurs__c != null) {
                String existingList = pdeRelations[0].Opportunity__r.Liste_fournisseurs__c;
                // Splitter la liste existante si elle contient des séparateurs
                if (existingList.contains(';')) {
                    existingFournisseurs.addAll(existingList.split(';'));
                } else {
                    existingFournisseurs.add(existingList);
                }
            }
            
            
            // Ajouter les nouveaux fournisseurs du wrapper
            for (WrapCreationQuoteGrille w : inputs[0].wrappers) {
                if (String.isNotBlank(w.fournisseurs)) {
                    existingFournisseurs.add(w.fournisseurs);
                }
            }
            
            
            // Reconstruire la liste avec séparateur point-virgule
            List<String> fournisseursList = new List<String>(existingFournisseurs);
            oppToUpdate.Liste_fournisseurs__c = String.join(fournisseursList, ';');
            oppToUpdate.bypassGrill__c = true;

            
            // Mettre à jour l'opportunité
            update oppToUpdate;
        }

        for(FlowInput input : inputs) {
            
            List<WrapCreationQuoteGrille> wrappers = input.wrappers;
            
            // On boucle sur chaque ligne du wrapper (chaque fournisseur)
            for (WrapCreationQuoteGrille w : input.wrappers) {

                // Si la durée est vide , on peut décider de l'ignorer ou de gérer un cas par défaut
                if (String.isBlank(w.duree) ) {
                    System.debug('Durée vide ou nulle pour fournisseur ' + w.fournisseurs + ' - IGNORÉ');
                    continue; 
                }
                
                // On split la chaîne "12;24;36" en une liste ['12', '24', '36']
                List<String> durees = w.duree.split(';');


                for (String d : durees) {
                    String quoteName = '';

                    Quote q = new Quote();
                    q.OpportunityId = input.opportunityId;
                    // Nom de la quote dynamique
                    quoteName = w.fournisseurs.toUpperCase() + ' - ' + pdeRelations[0].Opportunity__r.Name;
                    //q.RecordTypeId = pdeRelations[0].Opportunity__r.TECH_FTA__c == 'Gaz' ? RtGaz.Id : RtElec.Id;
                    q.Pricebook2Id = pb.Id;
                    q.Name = quoteName;
                    q.Calcul_grille__c = true;
                    if (pdeRelations[0].PDE__r.EntiteJuridique__r.CEE__c == 'Soumis' && (w.fournisseurs == 'Engie' || w.fournisseurs == 'TotalEnergies'||w.fournisseurs == 'Vattenfall'|| w.fournisseurs == 'Ilek'|| w.fournisseurs == 'Ekwateur')) {
                        q.CEE__c = 'Inclus';
                    }else {
                        q.CEE__c = pdeRelations[0].PDE__r.EntiteJuridique__r.CEE__c;

                    }

                    
                    if (w.fournisseurs == 'Ilek') {
                        q.CAPA__c = 'Inclus'; 
                        q.TURPE__c = 'Inclus';
                    }
                    q.Fournisseur__c = w.fournisseurs; 
                    q.Date_de_fin_de_contrat__c = date.today();

                    
                    if (String.isNotBlank(w.marge)) {
                        System.debug('Marge avant conversion : ' + w.marge);
                        //mapQuoteToMarge.put(q, w.marge);
                    }

                    QuoteContext ctx = new QuoteContext();
                    ctx.quote = q;
                    ctx.duree = d;
                    ctx.marge = w.marge;

                    contexts.add(ctx);
                    allQuotesToInsert.add(q);
                }
                
            }
        }
        
        if (!allQuotesToInsert.isEmpty()) {

            for (Database.SaveResult sr : Database.insert(allQuotesToInsert)) {
                if (!sr.isSuccess()) {
                    output.success = false;
                    output.message = sr.getErrors().get(0).getMessage();
                    outputs.add(output);    
                    return outputs;  
                }
            }
                // contexts va contenir pour chaque quote  la quote elle même, la durée associée et la marge associée
            for (QuoteContext ctx : contexts) {
            
                
                Quote newQuote = ctx.quote;
                String dureeInfo = ctx.duree;
                String margeInfo = ctx.marge;


                for (OpportunityPDERelation__c pdeRel : pdeRelations) {

                    QuoteLineItem qli = new QuoteLineItem();
                    String labelCode = '';
                    qli.QuoteId = newQuote.Id; // Liaison à la Quote fraîchement créée
                    qli.PDE__c = pdeRel.PDE__c; // Liaison au PDE
                    System.debug('Date de debut FOURNITURE : ' + pdeRel.PDE__r.DateEcheance__c.addDays(1));
                    qli.DebutDeFourniture__c = pdeRel.PDE__r.DateEcheance__c.addDays(1);



                    if (!String.isBlank(dureeInfo)) {

                        List<String> parts = dureeInfo.trim().split('_');

                        if (!parts.isEmpty() && String.isNotBlank(parts[0])) {
                            dureeEngagement = Integer.valueOf(parts[0]);
                        }
                    }                    

                    if (ctx.quote.Fournisseur__c == 'Ekwateur') {
                        if (pdeRel.PDE__r.RecordType.Name == 'Gaz') {
                             labelCode = 'T1T2T3_' + Date.today().year() + '_' + ctx.marge;
                        } else if ((pdeRel.PDE__r.RecordType.Name.contains('Elec'))) {
                             labelCode = 'C5_' + Date.today().year() + '_' + ctx.marge;
                        }

                        Grille_Ekwateur__mdt grilleEkwateur = Grille_Ekwateur__mdt.getinstance(labelCode);
                        
                        Integer moisEcheance = (pdeRel.PDE__r.DateEcheance__c.monthsBetween(grilleEkwateur.Date_fin__c)) -1 ;
                        if (grilleEkwateur != null) {
                            qli.Nouvelle_Echeance__c = grilleEkwateur.Date_fin__c;
                            qli.DureeEngagement__c = moisEcheance;
                        } 
                    }else{
                        Date Nouvelle_Echeance = pdeRel.PDE__r.DateEcheance__c.addMonths(dureeEngagement == null ? 0 : Integer.valueOf(dureeEngagement));
                        qli.Nouvelle_Echeance__c = Nouvelle_Echeance;

                        if ((ctx.quote.Fournisseur__c == 'Engie'|| ctx.quote.Fournisseur__c == 'GEG') && (pdeRel.PDE__r.DateEcheance__c.addDays(1).day() != 1) ) {

                            qli.Nouvelle_Echeance__c = Nouvelle_Echeance.toStartOfMonth().addDays(-1);
                        }


                        qli.DureeEngagement__c = dureeEngagement;                   
                    }

                    
                    qli.Product2Id = entryElec.Product2Id;
                    qli.PricebookEntryId= entryElec.Id;
                    qli.UnitPrice = 0;
                    qli.Quantity = 1;
                    qli.Opportunit__c = pdeRel.Opportunity__r.Id;
                    qli.ConsoHC__c = pdeRel.PDE__r.ConsoHC__c;
                    qli.ConsoHP__c = pdeRel.PDE__r.ConsoHP__c;
                    qli.Conso_Base__c = pdeRel.PDE__r.Conso_Base__c;
                    qli.Conso_HCE__c = pdeRel.PDE__r.Conso_HCE__c;
                    qli.Conso_HCH__c = pdeRel.PDE__r.Conso_HCH__c;
                    qli.Conso_HPE__c = pdeRel.PDE__r.Conso_HPE__c;
                    qli.Conso_HPH__c = pdeRel.PDE__r.Conso_HPH__c;
                    qli.Conso_Pointe__c = pdeRel.PDE__r.Conso_Pointe__c;
                    qli.Puissance_souscrite__c = pdeRel.PDE__r.Puissance_souscrite__c;
                    qli.CAR_New__c = pdeRel.PDE__r.Consommation_Annuelle_de_R_f_rence_Elec__c;
                    qli.CARGaz__c = pdeRel.PDE__r.CARGaz__c;
                    if(pdeRel.PDE__r.Calendrier_fournisseur__c == 'HP/HC' || pdeRel.PDE__r.Calendrier_fournisseur__c == 'Heures Pleines/Creuses'){
                        qli.TECH_CalendrierFournisseur__c = 'HP/HC';
                    }
                    else if(pdeRel.PDE__r.Calendrier_fournisseur__c == 'Base' || pdeRel.PDE__r.Calendrier_fournisseur__c != ''){
                        qli.TECH_CalendrierFournisseur__c = 'Base';
                    }
                    if (pdeRel.PDE__r.TypePDE__c == 'Gaz') {
                        if(pdeRel.PDE__r.Tarif__c == 'T1'){
                        qli.CTA__c = customMetadataRecord.CTA_T1__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T1__c;
                        } else if(pdeRel.PDE__r.Tarif__c == 'T2'){
                        qli.CTA__c = customMetadataRecord.CTA_T2__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T2__c;
                        } else if(pdeRel.PDE__r.Tarif__c == 'T3'){
                        qli.CTA__c = customMetadataRecord.CTA_T3__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T3__c;
                        } else if(pdeRel.PDE__r.Tarif__c == 'T4'){
                        qli.CTA__c = customMetadataRecord.CTA_T4__c;
                        qli.FraisTransportDistributionCapacite__c = customMetadataRecord.Frais_Transport_Distribution_Capacite_T4__c;
                        } else {
                        qli.CTA__c = 1;
                        qli.FraisTransportDistributionCapacite__c = 1;
                        }
                    }
                    else{

                        if(pdeRel.PDE__r.Puissance_souscrite__c <= 36){
                        qli.CSPE__c = customMetadataRecord.CSPE_PuissanceInfOuEgal36Kva__c;
                        }
                        else if (pdeRel.PDE__r.Puissance_souscrite__c > 36 && pdeRel.PDE__r.Puissance_souscrite__c <= 250 ){
                        qli.CSPE__c = customMetadataRecord.CSPE_PuissanceSup36OuEgal250__c;
                        }
                        else {
                        qli.CSPE__c = customMetadataRecord.CSPE_PuissanceSup250__c;
                        }
                    }

                    allQLIToInsert.add(qli);
                }
                
            }

            
            if (!allQLIToInsert.isEmpty()) {
                for (Database.SaveResult sr : Database.insert(allQLIToInsert)) {
                    if (!sr.isSuccess()) {
                        output.success = false;
                        output.message = sr.getErrors().get(0).getMessage();
                        outputs.add(output);    
                        return outputs;
                    }
                }
                Opportunity oppToUpdate = new Opportunity(Id = oppId);

                oppToUpdate.bypassGrill__c = false;
                update oppToUpdate;


                Boolean hasErrors = false;
                String errorMessages = '';

                for ( QuoteContext ctx : contexts) {
                   
                    try {
                        List<AP021_GrilleFournisseur.FlowInput> inputList = new List<AP021_GrilleFournisseur.FlowInput>();
                        AP021_GrilleFournisseur.FlowInput inputPourCalcul = new AP021_GrilleFournisseur.FlowInput();
                        Decimal margeValue = String.isNotBlank(ctx.marge) ? Decimal.valueOf(ctx.marge.replace(',', '.')) : 0;

                        inputPourCalcul.recordId = ctx.quote.Id;
                        inputPourCalcul.fournisseur = ctx.quote.Fournisseur__c;
                        inputPourCalcul.dureeOffre = ctx.duree;
                        inputPourCalcul.margeMwh = margeValue;
                        inputList.add(inputPourCalcul);
                        List<AP021_GrilleFournisseur.FlowOutput> results = AP021_GrilleFournisseur.GET_Prix(inputList);
                        if (results != null && !results.isEmpty()) {
                             if (results.get(0).success != true) {
                                output.success = false;
                                output.message = results.get(0).message;
                            }
                        }
                            
                    
                    } catch (Exception e) {

                        hasErrors = true;
                        errorMessages += 'Exception pour ' + ctx.quote.Fournisseur__c + ' : ' + e.getMessage() + '\n';                    }                          
                }
                if (hasErrors) {
                    output.success = false;
                    output.message = 'Des erreurs sont survenues lors du calcul des prix :\n' + errorMessages;
                } else {
                    output.success = true;
                    output.message = 'Les devis et QLI compatibles ont été mis à jour avec succès';
                }

            } else {
                output.success = false;
                output.message = 'ATTENTION : Aucun QLI à insérer' ;
            }
        }else {
            output.success = false;
            output.message = 'ATTENTION : Aucun devis à insérer' ;
        }
        outputs.add(output);
        return outputs;
    }

    
    global class FlowInput {
        @InvocableVariable(required=true)
        public Id opportunityId;
        @InvocableVariable(required=true)
        public List<WrapCreationQuoteGrille> wrappers;
    }
    public class FlowOutput {
        @InvocableVariable public Boolean success;
        @InvocableVariable public String message;
    }

      class QuoteContext {
        public Quote quote;
        public String duree;
        public String marge;
    }

}