force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account_EntiteJuridiquePrincipale.recordType-meta.xml
<RecordType>
    <fullName>Account_EntiteJuridiquePrincipale</fullName>
    <active>true</active>
    <label>Entité Juridique Principale</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Syndic.recordType-meta.xml
<RecordType>
    <fullName>Syndic</fullName>
    <active>true</active>
    <label>Syndic</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsableCotation__c.field-meta.xml
<CustomField>
    <fullName>ResponsableCotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable de la cotation</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Opportunity_Sales.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <label>Sales</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Simple_C5.recordType-meta.xml
<RecordType>
    <fullName>Simple_C5</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie C5</description>
    <label>Simple C5</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Simple_Gaz.recordType-meta.xml
<RecordType>
    <fullName>Simple_Gaz</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie Gaz</description>
    <label>Simple Gaz</label>
</RecordType>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Consommation_Annuelle_de_R_f_rence_Elec__c.field-meta.xml
<CustomField>
    <fullName>Consommation_Annuelle_de_R_f_rence_Elec__c</fullName>
    <label>CAR Elec</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/FTA__c.field-meta.xml
<CustomField>
    <fullName>FTA__c</fullName>
    <description>ELEC</description>
    <label>FTA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BT &lt;= 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - MU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - LU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - CU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - MU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - LU EP</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/NumeroVoie__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SiteConsommation__c.field-meta.xml
<CustomField>
    <fullName>SiteConsommation__c</fullName>
    <label>Site de Consommation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C1C2.recordType-meta.xml
<RecordType>
    <fullName>Elec_C1C2</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C1 à C2</description>
    <label>Elec C1 à C2</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C3_C4.recordType-meta.xml
<RecordType>
    <fullName>Elec_C3_C4</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C3 à C4</description>
    <label>Elec C3 à C4</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_ElecC5.recordType-meta.xml
<RecordType>
    <fullName>PDE_ElecC5</fullName>
    <active>true</active>
    <description>Point d&apos;énergie C5</description>
    <label>Elec C5</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_Gaz.recordType-meta.xml
<RecordType>
    <fullName>PDE_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <label>Date de fin de contrat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Budget_TTC__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC__c</fullName>
    <label>Budget TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CAR_New__c.field-meta.xml
<CustomField>
    <fullName>CAR_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CAR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_CalendrierFournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalendrierFournisseur__c</fullName>
    <label>TECH_CalendrierFournisseur</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
  public static List<Account> createAccountsWithOppsAndPointDenergie(Integer numAccts, Integer numOppsPerAcct, Integer numPdesGazPerAcct, Integer numPdesElec1PerAcct, Integer numPdesElec2PerAcct) {
    Id EntiteJuridiquePrincipaleRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Account_EntiteJuridiquePrincipale'
      ]
      .get(0)
      .Id;
    List<Account> accts = new List<Account>();

    for (Integer i = 0; i < numAccts; i++) {
      Account a = new Account(
        Name = 'TestAccount' + i,
        Industry = 'Résidentiel',
        Siren__c = '12345678' + i,
        Siret__c = '1234567890123' + i,
        RecordTypeId = EntiteJuridiquePrincipaleRecordTypeId
      );
      accts.add(a);
    }
    insert accts;

    Pricebook2 priceBook = new Pricebook2(
      Name = 'AllianceDesEnergies',
      IsActive = true
    );
    insert priceBook;

    List<Product2> products = new List<Product2>();
    Product2 p1 = new Product2(Name = 'ELEC', IsActive = true);
    Product2 p2 = new Product2(Name = 'GAZ', IsActive = true);
    products.add(p1);
    products.add(p2);
    insert products;

    Id standardPricebookId = Test.getStandardPricebookId();
    List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p1.Id,
        Pricebook2Id = standardPricebookId
      )
    );
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p2.Id,
        Pricebook2Id = standardPricebookId
      )
    );
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p1.Id,
        Pricebook2Id = priceBook.Id
      )
    );
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p2.Id,
        Pricebook2Id = priceBook.Id
      )
    );
    insert priceBookEntries;

    Id salesRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Opportunity_Sales'
      ]
      .get(0)
      .Id;
    List<Opportunity> opps = new List<Opportunity>();
    for (Integer j = 0; j < numAccts; j++) {
      Account acct = accts[j];
      // For each account just inserted, add opportunities
      for (Integer k = 0; k < numOppsPerAcct; k++) {
        opps.add(
          new Opportunity(
            Name = acct.Name + ' Opportunity ' + k,
            StageName = 'Conditionné',
            CloseDate = System.today().addMonths(1),
            Liste_Fournisseurs__c = 'Alterna;Antargaz',
            TemplateCotation__c = 'C5',
            SectionSituationActuelle__c = true,
            AccountId = acct.Id,
            responsableCotation__c = UserInfo.getUserId(),
            RecordTypeId = salesRecordTypeId
          )
        );
      }
    }
    // Insert all opportunities for all accounts.
    insert opps;

    Map<Id, Opportunity> mapAccountOpportunity = new Map<Id, Opportunity>();

    for (Opportunity opp : opps) {
      mapAccountOpportunity.put(opp.AccountId, opp);
    }

    Id gazRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'PDE_Gaz'
      ]
      .get(0)
      .Id;
    Id elec1RecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Elec_C1C2'
      ]
      .get(0)
      .Id;
    Id elec2RecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'PDE_ElecC5'
      ]
      .get(0)
      .Id;
    List<PDE__c> pdes = new List<PDE__c>();
    for (Integer l = 0; l < numAccts; l++) {
      Account acct = accts[l];
      // For each account just inserted, add point d'energies
      for (Integer m = 0; m < numPdesGazPerAcct; m++) {
        pdes.add(
          new PDE__c(
            Name = acct.Name + ' PDEGaz ' + m,
            SiteConsommation__c = 'TEST ',
            NumeroVoie__c = '90',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            CARGaz__c = 1234,
            DateEcheance__c = System.today().addMonths(1),
            PCE_Refonte__c = '123456789' + m,
            ReferencePointEnergie_Refonte__c = '123456789' + m,
            EntiteJuridique__c = acct.Id,
            RecordTypeId = gazRecordTypeId,
            FTA__c = 'HTA - PF - CU',
            Calendrier_fournisseur__c = 'Base'
          )
        );
      }
      for (Integer n = 0; n < numPdesElec1PerAcct; n++) {
        pdes.add(
          new PDE__c(
            Name = acct.Name + ' PDEElec1 ' + n,
            SiteConsommation__c = 'TEST ',
            NumeroVoie__c = '91',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            Consommation_Annuelle_de_R_f_rence_Elec__c = 1234,
            DateEcheance__c = System.today().addMonths(1),
            Segment__c = 'C1',
            ReferencePointEnergie_Refonte__c = '12345678' + n,
            EntiteJuridique__c = acct.Id,
            RecordTypeId = elec1RecordTypeId,
            FTA__c = 'BT <= 36 kVA - CU',
            Calendrier_fournisseur__c = 'Base'
          )
        );
      }
      for (Integer o = 0; o < numPdesElec2PerAcct; o++) {
        pdes.add(
          new PDE__c(
            Name = acct.Name + ' PDEElec2 ' + o,
            SiteConsommation__c = 'TEST ',
            NumeroVoie__c = '84',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            Consommation_Annuelle_de_R_f_rence_Elec__c = 1234,
            DateEcheance__c = System.today().addMonths(1),
            Segment__c = 'C5',
            ReferencePointEnergie_Refonte__c = '1234567' + o,
            EntiteJuridique__c = acct.Id,
            RecordTypeId = elec2RecordTypeId,
            FTA__c = 'BT <= 36Kva - CU 4 postes',
            Calendrier_fournisseur__c = 'Base'
          )
        );
      }
    }
    // Insert all point d'energie for all accounts.
    insert pdes;
    //Insert All pde to all opportunities
    List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
    for (PDE__c pde : pdes) {
      listOPR.add(
        new OpportunityPDERelation__c(
          Opportunity__c = mapAccountOpportunity.get(pde.EntiteJuridique__c).Id,
          PDE__c = pde.Id
        )
      );
    }

    insert listOPR;
    List<Quote> quotes = new List<Quote>();
    Quote q1 = new Quote(
      Name = 'QUOTE 1',
      Pricebook2Id = priceBook.Id,
      OpportunityId = opps.get(0).Id,
      Date_de_fin_de_contrat__c = Date.today()
    );
    Quote q2 = new Quote(
      Name = 'QUOTE 2',
      Pricebook2Id = priceBook.Id,
      OpportunityId = opps.get(0).Id,
      Date_de_fin_de_contrat__c = Date.today()
    );
    quotes.add(q1);
    quotes.add(q2);
    insert quotes;

    List<QuoteLineItem> qlis = new List<QuoteLineItem>();
    QuoteLineItem qli1 = new QuoteLineItem(
      Product2Id = products.get(0).Id,
      PDE__c = pdes.get(1).Id,
      QuoteId = quotes.get(0).Id,
      PricebookEntryId = priceBookEntries.get(2).Id,
      Quantity = 1,
      UnitPrice = 1,
      DebutDeFourniture__c = Date.today(),
      Nouvelle_Echeance__c = Date.today(),
      DureeEngagement__c = 24,
      Budget_TTC__c = 2,
      CARGaz__c = 1234,
      CAR_New__c = 1234,
      TECH_CalendrierFournisseur__c = pdes.get(1).Calendrier_fournisseur__c
    );
    QuoteLineItem qli2 = new QuoteLineItem(
      Product2Id = products.get(1).Id,
      PDE__c = pdes.get(0).Id,
      QuoteId = quotes.get(1).Id,
      PricebookEntryId = priceBookEntries.get(3).Id,
      Quantity = 1,
      UnitPrice = 1,
      DebutDeFourniture__c = Date.today(),
      Nouvelle_Echeance__c = Date.today(),
      DureeEngagement__c = 24,
      Budget_TTC__c = 2,
      CARGaz__c = 1234,
      CAR_New__c = 1234,
      TECH_CalendrierFournisseur__c = pdes.get(0).Calendrier_fournisseur__c
    );
    QuoteLineItem qli3 = new QuoteLineItem(
      Product2Id = products.get(0).Id,
      PDE__c = pdes.get(2).Id,
      QuoteId = quotes.get(0).Id,
      PricebookEntryId = priceBookEntries.get(2).Id,
      Quantity = 1,
      UnitPrice = 1,
      DebutDeFourniture__c = Date.today(),
      Nouvelle_Echeance__c = Date.today(),
      DureeEngagement__c = 24,
      Budget_TTC__c = 2,
      CARGaz__c = 1234,
      CAR_New__c = 1234,
      TECH_CalendrierFournisseur__c = pdes.get(2).Calendrier_fournisseur__c
    );
    qlis.add(qli1);
    qlis.add(qli2);
    qlis.add(qli3);
    insert qlis;

    List<Contact> cons = new List<Contact>();
    for (Integer j = 0; j < numAccts; j++) {
      Account acct = accts[j];
      Contact con1 = new Contact(
        LastName = 'Signataire1',
        FirstName = 'Opportunity',
        Phone = '0611223344',
        Email = 'contact1@test.com',
        accountId = acct.id
      );

      Contact con2 = new Contact(
        LastName = 'Signataire2',
        FirstName = 'Opportunity',
        Phone = '0711223344',
        Email = 'contact2@test.com',
        accountId = acct.id
      );
      cons.add(con1);
      cons.add(con2);
    }
    insert cons;

    List<OpportunityContactRole> oppCTs = new List<OpportunityContactRole>();
    OpportunityContactRole oppCT1 = new OpportunityContactRole(
      ContactId = cons.get(0).Id,
      OpportunityId = opps.get(0).Id,
      Role = 'Signataire'
    );

    OpportunityContactRole oppCT2 = new OpportunityContactRole(
      ContactId = cons.get(0).Id,
      OpportunityId = opps.get(0).Id,
      Role = 'Signataire'
    );
    oppCTs.add(oppCT1);
    oppCTs.add(oppCT2);
    insert oppCTs;

    return accts;
  }

  public static List<Account> createSyndicsWithCoprosAndPointDenergie(Integer numSyndics, Integer numCoproPerSyndic, Integer numPdesGazPerCopro, Integer numPdesElecPerCopro) {
    Id syndicRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Syndic'
      ]
      .get(0)
      .Id;
    Id CoproprieteRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Copropriete'
      ]
      .get(0)
      .Id;

    List<Account> listAccount = new List<Account>();

    for (Integer i = 0; i < numSyndics; i++) {
      Account a = new Account(
        Name = 'TestAccount' + i,
        Industry = 'Résidentiel',
        Siren__c = '12345678' + i,
        Siret__c = '1234567890123' + i,
        RecordTypeId = syndicRecordTypeId
      );
      listAccount.add(a);
    }
    insert listAccount;

    List<Account> listCopro = new List<Account>();
    for (Integer j = 0; j < numSyndics; j++) {
      Account acct = listAccount[j];
      // For each Syndic insert copro
      for (Integer k = 0; k < numCoproPerSyndic; k++) {
        listCopro.add(
          new Account(
            Name = 'TestAccount' + k,
            Industry = 'Résidentiel',
            Siren__c = '12345674' + k,
            Siret__c = '1234567890125' + k,
            syndic__c = acct.Id,
            RecordTypeId = CoproprieteRecordTypeId
          )
        );
      }
    }
    insert listCopro;

    Id gazRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'PDE_Gaz'
      ]
      .get(0)
      .Id;
    Id elec1RecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Elec_C1C2'
      ]
      .get(0)
      .Id;
    List<PDE__c> pdes = new List<PDE__c>();
    for (Integer l = 0; l < listCopro.size(); l++) {
      // For each copro just inserted, add point d'energies
      for (Integer m = 0; m < numPdesGazPerCopro; m++) {
        pdes.add(
          new PDE__c(
            Name = listCopro.get(0).Name + ' PDEGaz ' + m,
            SiteConsommation__c = 'TEST ',
            NumeroVoie__c = '90',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            DateEcheance__c = System.today().addMonths(1),
            PCE_Refonte__c = '123457789' + m,
            ReferencePointEnergie_Refonte__c = '123456789' + m,
            EntiteJuridique__c = listCopro.get(l).Id,
            RecordTypeId = gazRecordTypeId
          )
        );
      }
      for (Integer n = 0; n < numPdesElecPerCopro; n++) {
        pdes.add(
          new PDE__c(
            Name = listCopro.get(0).Name + ' PDEElec1 ' + n,
            SiteConsommation__c = 'TEST ',
            NumeroVoie__c = '91',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            DateEcheance__c = System.today().addMonths(1),
            Segment__c = 'C1',
            ReferencePointEnergie_Refonte__c = '12345678' + n,
            EntiteJuridique__c = listCopro.get(l).Id,
            RecordTypeId = elec1RecordTypeId
          )
        );
      }
    }
    // Insert all point d'energie for all copros.
    insert pdes;
    return listAccount;
  }

  public static void createPriceBooks(){
    Pricebook2 priceBook = new Pricebook2(Name = 'AllianceDesEnergies',IsActive = true);
    insert priceBook;

    List<Product2> products = new List<Product2>();
    Product2 p1 = new Product2(Name = 'ELEC', IsActive = true);
    Product2 p2 = new Product2(Name = 'GAZ', IsActive = true);
    products.add(p1);
    products.add(p2);
    insert products;

    Id standardPricebookId = Test.getStandardPricebookId();
    List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p1.Id,
        Pricebook2Id = standardPricebookId
      )
    );
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p2.Id,
        Pricebook2Id = standardPricebookId
      )
    );
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p1.Id,
        Pricebook2Id = priceBook.Id
      )
    );
    priceBookEntries.add(
      new PricebookEntry(
        IsActive = true,
        UnitPrice = 1.00,
        Product2Id = p2.Id,
        Pricebook2Id = priceBook.Id
      )
    );
    insert priceBookEntries;
  }

  public static Account createDataForComparatifGaz() {

    // Create Account
    Id EntiteJuridiquePrincipaleRecordTypeId = [ SELECT Id FROM RecordType WHERE DeveloperName = 'Account_EntiteJuridiquePrincipale'].get(0).Id;
    Account a = new Account(Name = 'TestAccountGaz', Industry = 'Résidentiel', Siren__c = '12345678', Siret__c = '1234567890122', RecordTypeId = EntiteJuridiquePrincipaleRecordTypeId);
    insert a;

    // Create PriceBook
    Pricebook2 priceBook = new Pricebook2(Name = 'AllianceDesEnergies', IsActive = true);
    insert priceBook;

    // Create Product Gaz
    Product2 p2 = new Product2(Name = 'GAZ', IsActive = true);
    insert p2;

    // Create priceBookEntries
    Id standardPricebookId = Test.getStandardPricebookId();
    List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
    priceBookEntries.add(new PricebookEntry(IsActive = true, UnitPrice = 1.00, Product2Id = p2.Id, Pricebook2Id = standardPricebookId));
    priceBookEntries.add(new PricebookEntry(IsActive = true, UnitPrice = 1.00, Product2Id = p2.Id, Pricebook2Id = priceBook.Id));
    insert priceBookEntries;

    // Create Contact
    Contact contact = new Contact(LastName = 'Signataire1', FirstName = 'Opportunity', Phone = '0611223344', Email = 'contact1@test.com', AccountId = a.id);
    insert contact;

    // Create Demande de cotation
    Demande_Cotation__c dc = new Demande_Cotation__c();
    dc.Name = a.Name;
    dc.Account__c = a.Id;
    dc.Date_RDV_Client__c = null;
    dc.Signataire__c = contact.Id;
    dc.Charge_affaire__c = UserInfo.getUserId();
    dc.Infos_complementaires__c = '';
    dc.Statut__c = 'En attente de traitement';
    dc.Date_demande_cotation__c = Datetime.now();
    insert dc;

    // Create Opp
    Id oppRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_Gaz'].get(0).Id;
    Opportunity opp = new Opportunity(AccountId= a.Id, Name = a.Name + ' Opportunity ', StageName = 'Conditionné', CloseDate = System.today().addMonths(1), Liste_Fournisseurs__c = 'Alterna;Antargaz', TemplateCotation__c = 'GAZ', SectionSituationActuelle__c = true, responsableCotation__c = UserInfo.getUserId(), RecordTypeId = oppRecordTypeId,Demande_Cotation__c = dc.Id);
    insert opp;

    // Create PDEs
    Id gazRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_Gaz'].get(0).Id;
    List<PDE__c> pdes = new List<PDE__c>();
    pdes.add(new PDE__c(Name = a.Name + ' PDEGaz', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '1234567890', ReferencePointEnergie_Refonte__c = '1234567890', EntiteJuridique__c = a.Id, RecordTypeId = gazRecordTypeId, Tarif__c = 'T1', Profil__c = 'P011'));
    pdes.add(new PDE__c(Name = a.Name + ' PDEGaz', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '1234567891', ReferencePointEnergie_Refonte__c = '1234567891', EntiteJuridique__c = a.Id, RecordTypeId = gazRecordTypeId, Tarif__c = 'T2', Profil__c = 'P011'));
    pdes.add(new PDE__c(Name = a.Name + ' PDEGaz', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '1234567892', ReferencePointEnergie_Refonte__c = '1234567892', EntiteJuridique__c = a.Id, RecordTypeId = gazRecordTypeId, Tarif__c = 'T3', Profil__c = 'P011'));
    pdes.add(new PDE__c(Name = a.Name + ' PDEGaz', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '1234567893', ReferencePointEnergie_Refonte__c = '1234567893', EntiteJuridique__c = a.Id, RecordTypeId = gazRecordTypeId, Tarif__c = 'T4', Profil__c = 'P011'));
    insert pdes;

    // Create OPRs
    List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
    for (PDE__c pde : pdes) {
      listOPR.add(new OpportunityPDERelation__c(Opportunity__c = opp.Id, PDE__c = pde.Id));
    }
    insert listOPR;

    // Create Quotes
    List<Quote> quotes = new List<Quote>();
    quotes.add(new Quote(Name = 'Quote Engie', Fournisseur__c = 'Engie', Pricebook2Id = priceBook.Id, OpportunityId = opp.Id, Date_de_fin_de_contrat__c = Date.today()));
    quotes.add(new Quote(Name = 'Quote Situation Actuelle', Fournisseur__c = 'Situation Actuelle', Pricebook2Id = priceBook.Id, OpportunityId = opp.Id, Date_de_fin_de_contrat__c = Date.today()));
    insert quotes;

    // Create QLIs
    List<QuoteLineItem> qlis = new List<QuoteLineItem>();
    // QLI Engie
    for (PDE__c pde : pdes) {
      qlis.add(new QuoteLineItem(Product2Id = p2.Id, PDE__c = pde.Id, QuoteId = quotes.get(0).Id, Opportunit__c = opp.Id, PricebookEntryId = priceBookEntries.get(1).Id, Quantity = 1, UnitPrice = 1, DebutDeFourniture__c = Date.today(), Nouvelle_Echeance__c = Date.today(), DureeEngagement__c = 24, Budget_TTC__c = 2, CARGaz__c = 1234, CAR_New__c = 1234));
    }
    // QLI Situation Actuelle
    for (PDE__c pde : pdes) {
      qlis.add(new QuoteLineItem(Product2Id = p2.Id, PDE__c = pde.Id, QuoteId = quotes.get(1).Id, Opportunit__c = opp.Id, PricebookEntryId = priceBookEntries.get(1).Id, Quantity = 1, UnitPrice = 1, DebutDeFourniture__c = Date.today(), Nouvelle_Echeance__c = Date.today(), DureeEngagement__c = 24, Budget_TTC__c = 2, CARGaz__c = 1234, CAR_New__c = 1234));
    }
    insert qlis;


    // Create OCR
    OpportunityContactRole ocr = new OpportunityContactRole(ContactId = contact.Id,  OpportunityId = opp.Id, Role = 'Signataire');
    insert ocr;

    return a;
  }

  public static Account createDataForComparatifElec() {

    // Create Account
    Id EntiteJuridiquePrincipaleRecordTypeId = [ SELECT Id FROM RecordType WHERE DeveloperName = 'Account_EntiteJuridiquePrincipale'].get(0).Id;
    Account a = new Account(Name = 'TestAccount', Industry = 'Résidentiel', Siren__c = '12345678', Siret__c = '1234567890123', RecordTypeId = EntiteJuridiquePrincipaleRecordTypeId);
    insert a;

    // Create PriceBook
    Pricebook2 priceBook = new Pricebook2(Name = 'AllianceDesEnergies', IsActive = true);
    insert priceBook;

    // Create Product Elec
    Product2 p2 = new Product2(Name = 'ELEC', IsActive = true);
    insert p2;

    // Create priceBookEntries
    Id standardPricebookId = Test.getStandardPricebookId();
    List<PricebookEntry> priceBookEntries = new List<PricebookEntry>();
    priceBookEntries.add(new PricebookEntry(IsActive = true, UnitPrice = 1.00, Product2Id = p2.Id, Pricebook2Id = standardPricebookId));
    priceBookEntries.add(new PricebookEntry(IsActive = true, UnitPrice = 1.00, Product2Id = p2.Id, Pricebook2Id = priceBook.Id));
    insert priceBookEntries;

    // Create Contact
    Contact contact = new Contact(LastName = 'Signataire2', FirstName = 'Opportunity', Phone = '0711223345', Email = 'contact2@test.com', AccountId = a.id);
    insert contact;

    // Create Demande de cotation
    Demande_Cotation__c dc = new Demande_Cotation__c();
    dc.Name = a.Name;
    dc.Account__c = a.Id;
    dc.Date_RDV_Client__c = null;
    dc.Signataire__c = contact.Id;
    dc.Charge_affaire__c = UserInfo.getUserId();
    dc.Infos_complementaires__c = '';
    dc.Statut__c = 'En attente de traitement';
    dc.Date_demande_cotation__c = Datetime.now();
    insert dc;

    // Create Opp
    Id oppRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_C5'].get(0).Id;
    Opportunity opp = new Opportunity(AccountId= a.Id, Name = a.Name + ' Opportunity ', StageName = 'Conditionné', CloseDate = System.today().addMonths(1), Liste_Fournisseurs__c = 'Engie', TemplateCotation__c = 'C5', SectionSituationActuelle__c = true, responsableCotation__c = UserInfo.getUserId(), RecordTypeId = oppRecordTypeId, Demande_Cotation__c = dc.Id);
    insert opp;

    // Create PDEs
    Id c1c2RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Elec_C1C2'].get(0).Id;
    Id c4RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Elec_C3_C4'].get(0).Id;
    Id c5RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_ElecC5'].get(0).Id;
    List<PDE__c> pdes = new List<PDE__c>();
    pdes.add(new PDE__c(Name = a.Name + ' PDEC1C2', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678900', ReferencePointEnergie_Refonte__c = '12345678900', EntiteJuridique__c = a.Id, RecordTypeId = c1c2RecordTypeId, FTA__c = 'HTA - PF - CU', Segment__c = 'C1'));
    pdes.add(new PDE__c(Name = a.Name + ' PDEC4', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678911', ReferencePointEnergie_Refonte__c = '12345678911', EntiteJuridique__c = a.Id, RecordTypeId = c4RecordTypeId, FTA__c = 'BT > 36 kVA - CU', Segment__c = 'C4'));
    pdes.add(new PDE__c(Name = a.Name + ' PDEC5Base', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678922', ReferencePointEnergie_Refonte__c = '12345678922', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36 kVA - MU', Segment__c = 'C5'));
    pdes.add(new PDE__c(Name = a.Name + ' PDEC54Postes', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678933', ReferencePointEnergie_Refonte__c = '12345678933', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36Kva - CU 4 postes', Segment__c = 'C5'));
    insert pdes;

    // Create OPRs
    List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
    for (PDE__c pde : pdes) {
      listOPR.add(new OpportunityPDERelation__c(Opportunity__c = opp.Id, PDE__c = pde.Id));
    }
    insert listOPR;

    // Create Quotes
    List<Quote> quotes = new List<Quote>();
    quotes.add(new Quote(Name = 'Quote Engie', Fournisseur__c = 'Engie', Pricebook2Id = priceBook.Id, OpportunityId = opp.Id, Date_de_fin_de_contrat__c = Date.today()));
    quotes.add(new Quote(Name = 'Quote Situation Actuelle', Fournisseur__c = 'Situation Actuelle', Pricebook2Id = priceBook.Id, OpportunityId = opp.Id, Date_de_fin_de_contrat__c = Date.today()));
    insert quotes;

    // Create QLIs
    List<QuoteLineItem> qlis = new List<QuoteLineItem>();
    // QLI Engie
    for (PDE__c pde : pdes) {
      qlis.add(new QuoteLineItem(Product2Id = p2.Id, PDE__c = pde.Id, QuoteId = quotes.get(0).Id, Opportunit__c = opp.Id, PricebookEntryId = priceBookEntries.get(1).Id, Quantity = 1, UnitPrice = 1, DebutDeFourniture__c = Date.today(), Nouvelle_Echeance__c = Date.today(), DureeEngagement__c = 24, Budget_TTC__c = 2, CARGaz__c = 1234, CAR_New__c = 1234));
    }
    // QLI Situation Actuelle
    for (PDE__c pde : pdes) {
      qlis.add(new QuoteLineItem(Product2Id = p2.Id, PDE__c = pde.Id, QuoteId = quotes.get(1).Id, Opportunit__c = opp.Id, PricebookEntryId = priceBookEntries.get(1).Id, Quantity = 1, UnitPrice = 1, DebutDeFourniture__c = Date.today(), Nouvelle_Echeance__c = Date.today(), DureeEngagement__c = 24, Budget_TTC__c = 2, CARGaz__c = 1234, CAR_New__c = 1234));
    }
    insert qlis;

    // Create OCR
    OpportunityContactRole ocr = new OpportunityContactRole(ContactId = contact.Id,  OpportunityId = opp.Id, Role = 'Signataire');
    insert ocr;

    return a;
  }
}