force-app/main/default/objects/Account/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code NAF</label>
    <referenceTo>CodeNAF__c</referenceTo>
    <relationshipLabel>Entités Juridiques</relationshipLabel>
    <relationshipName>EntitesJuridiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CodeNAF__c/CodeNAF__c.object-meta.xml
<CustomObject>
    <label>Code NAF</label>
    <nameField>
        <label>NAF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codes NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Formula_plus_10_compteurs__c.field-meta.xml
<CustomField>
    <fullName>Formula_plus_10_compteurs__c</fullName>
    <formula>Nombre_PDE__c &gt;= 10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plus de 10 compteurs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Infos_complementaires__c.field-meta.xml
<CustomField>
    <fullName>Infos_complementaires__c</fullName>
    <label>Infos complémentaires</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Plus_1_Giga__c.field-meta.xml
<CustomField>
    <fullName>Plus_1_Giga__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plus 1 Giga</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ELLISPHERE__Elli_Assessement__c/ELLISPHERE__Elli_Assessement__c.object-meta.xml
<CustomObject>
    <description>Bloc Score et Avis de crédit</description>
    <label>Score et Avis de crédit</label>
    <nameField>
        <label>Date du score</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scores et Avis de crédit</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ELLISPHERE__Elli_Assessement__c/fields/credit_score_date__c.field-meta.xml
<CustomField>
    <fullName>credit_score_date__c</fullName>
    <formula>DATE(VALUE(MID(Name,7,4)),VALUE(MID(Name,4,2)),VALUE(MID(Name,0,2)))</formula>
    <label>Credit score date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP016_SendEmailChargeAffaireCreationDDC.cls
public without sharing class AP016_SendEmailChargeAffaireCreationDDC {
    //Class de test : AP003_DemandeCotationFromFlow_TEST
    @invocableMethod(label='Envoie email chargé d\'affaire')
    public static void sendEmailChargeAffaire(List<FlowInputs> params) {
        FlowInputs param = params[0];
        sendMailFutureMethod(params.get(0).recordId);
    }

    @future(callout=true)
    public static void sendMailFutureMethod(Id recordId){
        // Skip email sending during test execution
        if (Test.isRunningTest()) {
            return;
        }

        String segment,heureRDV,dateRDV;
        Integer numberOfC1 = 0, numberOfC2 = 0, numberOfC3 = 0, numberOfC4 = 0,numberOfC5 = 0, numberOfGaz = 0;
        Demande_Cotation__c dc = [  SELECT 
                                        Account__c,
                                        Account__r.Name,
                                        Account__r.Siret__c,
                                        Account__r.Code_NAF__r.Name,
                                        Charge_affaire__r.email,
                                        Charge_affaire__r.Manager.Email,
                                        Date_RDV_Client__c,
                                        Id,
                                        Infos_complementaires__c,
                                        Name,
                                        Plus_1_Giga__c,
                                        Formula_plus_10_compteurs__c,
                                        Owner.Name,
                                        Signataire__r.LastName,
                                        Signataire__r.FirstName,
                                        Signataire__r.Phone,
                                        Signataire__r.Email,
                                        Signataire__r.Title
                                    FROM Demande_Cotation__c 
                                    WHERE 
                                        Id =: recordId];
        AggregateResult[] listAR = [  SELECT Segment__c,count(Id)
                                FROM 
                                    PDE__c
                                WHERE
                                    Demande_Cotation__c =: recordId
                                GROUP BY
                                    Segment__c];
        System.debug('listAR '+listAR);

        for(AggregateResult ar : listAR){
            segment = String.valueOf(ar.get('Segment__c'));
            switch on segment {
                when 'C1' {
                    numberOfC1 = Integer.valueOf(ar.get('expr0'));
                }
                when 'C2' {
                    numberOfC2 = Integer.valueOf(ar.get('expr0'));
                }
                when 'C3' {
                    numberOfC3 = Integer.valueOf(ar.get('expr0'));
                }
                when 'C4' {
                    numberOfC4 = Integer.valueOf(ar.get('expr0'));
                }
                when 'C5' {
                    numberOfC5 = Integer.valueOf(ar.get('expr0'));
                }
                when null {
                    numberOfGaz = Integer.valueOf(ar.get('expr0'));
                }
            }
        }
        Integer nmbrOfSites = numberOfC1 + numberOfC2 + numberOfC3 + numberOfC4 + numberOfC5 + numberOfGaz;

        String multiOrMono = (numberOfC1 + numberOfC2 + numberOfC3 + numberOfC4 + numberOfC5 + numberOfGaz) > 1 ? 'MULTI' : 'MONO';
        List<ELLISPHERE__Elli_Assessement__c> elliScore = new List<ELLISPHERE__Elli_Assessement__c>([SELECT ELLISPHERE__Elli_Tch_Score__c FROM ELLISPHERE__Elli_Assessement__c WHERE ELLISPHERE__Elli_Score_account__c =: dc.Account__c Order by credit_score_date__c DESC LIMIT 1]);
        String lastCreditScore = elliScore.size() == 0 ? 'NaN' : elliScore.get(0).ELLISPHERE__Elli_Tch_Score__c;
        dateRDV = dc.Date_RDV_Client__c == null ? '' : dc.Date_RDV_Client__c.format();
        Messaging.reserveSingleEmailCapacity(3);
        Messaging.SingleEmailMessage mymail = new Messaging.SingleEmailMessage();
        String[] toaddresses = new String[] {dc.Charge_affaire__r.email == null ? 'nomail@alliancedesenergies.fr' :dc.Charge_affaire__r.email}; 
        System.debug('toaddresses '+toaddresses);
        mymail.setToAddresses(toAddresses);
        mymail.setSenderDisplayName('Nouvelle demande de cotation');
        mymail.setSubject('Nouvelle demande de cotation '+multiOrMono+' de '+dc.Owner.Name+' pour '+dc.Account__r.Name);
        String htmlBody = '<p>'+dc.Owner.Name+' vous a assigné en tant que chargé d\'affaire sur sa demande de cotation <strong>'+dc.Name+'</strong> pour le <strong>'+dateRDV+'</strong> .</p>' +
                          '<p>Pour accéder à cette demande de cotation cliquez&nbsp;<a href="https://alliancedesenergies.lightning.force.com/lightning/r/Demande_Cotation__c/'+dc.Id+'/view">ici</a></p>' +
                          '<p>&nbsp;</p><p>Informations concernant la demande de cotation :&nbsp;</p>'+
                          '<strong>SOCIETE</strong>'+
                          '<ul><li>Raison sociale :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Account__r.Name+'</strong></span></li>'+
                          '<li>SIRET :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Account__r.Siret__c+'</strong></span></li>' +
                          '<li>Code NAF :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Account__r.Code_NAF__r.Name+'</strong></span></li>' +
                          '<li>Dernier avis de crédit :&nbsp;<span style="color: #ff0000;"><strong>'+lastCreditScore+'/10</strong></span></li></ul>' +
                          '<p>&nbsp;</p><strong>SIGNATAIRE</strong>'+//
                          '<ul><li>Nom du signataire :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Signataire__r.LastName+'</strong></span></li>' +
                          '<li>Prénom du signataire :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Signataire__r.FirstName+'</strong></span></li>' +
                          '<li>Tel du signataire :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Signataire__r.Phone+'</strong></span></li>' +
                          '<li>Email du signataire :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Signataire__r.Email+'</strong></span></li>'+
                          '<li>Fonction :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Signataire__r.Title+'</strong></span></li></ul>'+
                          '<p>&nbsp;</p><strong>SITES</strong>'+//
                          '<ul><li>Nombre de site par typologie :<ul>' +
                          '<li>C1 :&nbsp;<span style="color: #ff0000;"><strong>'+numberOfC1+'</strong></span></li>'+
                          '<li>C2 :&nbsp;<span style="color: #ff0000;"><strong>'+numberOfC2+'</strong></span></li>'+
                          '<li>C3 :&nbsp;<span style="color: #ff0000;"><strong>'+numberOfC3+'</strong></span></li>'+
                          '<li>C4 :&nbsp;<span style="color: #ff0000;"><strong>'+numberOfC4+'</strong></span></li>'+
                          '<li>C5 :&nbsp;<span style="color: #ff0000;"><strong>'+numberOfC5+'</strong></span></li>'+
                          '<li>Gaz :&nbsp;<span style="color: #ff0000;"><strong>'+numberOfGaz+'</strong></span></li></ul></li>'+
                          '<li>Nombre total de compteur :&nbsp;<span style="color: #ff0000;"><strong>'+nmbrOfSites+'</strong></span></li></ul>'+
                          '<p>&nbsp;</p> <ul><li>Commentaire :&nbsp;<span style="color: #ff0000;"><strong>'+dc.Infos_complementaires__c+'</strong></span></li></ul>'+
                          '<p>&nbsp;</p><strong>Cahier des charges</strong><ul>';// 
                          if (dc.Plus_1_Giga__c) {
                            htmlBody += '<li>Plus de CAR : +1Gwh ? :&nbsp;<span style="color: #ff0000;"><strong>Attention, le dossier fait plus de 1 GWh </strong></span></li>';
                          }
                         if (dc.Formula_plus_10_compteurs__c) {
                            htmlBody += '<li>Plus de 10 Compteurs ? :&nbsp;<span style="color: #ff0000;"><strong>Attention, le dossier contient plus de 10 compteurs</strong></span></li></ul>';
                         }
                        htmlBody += '</ul>';
                        
        mymail.setHtmlBody(htmlBody);
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mymail });
    }

    public class FlowInputs {
        @invocableVariable public Id recordId;
    } 
}