force-app/main/default/objects/Account/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code NAF</label>
    <referenceTo>CodeNAF__c</referenceTo>
    <relationshipLabel>Entités Juridiques</relationshipLabel>
    <relationshipName>EntitesJuridiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Syndic.recordType-meta.xml
<RecordType>
    <fullName>Syndic</fullName>
    <active>true</active>
    <label>Syndic</label>
</RecordType>

force-app/main/default/objects/CodeNAF__c/CodeNAF__c.object-meta.xml
<CustomObject>
    <label>Code NAF</label>
    <nameField>
        <label>NAF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Codes NAF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Departement_syndic__c/Departement_syndic__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Liste des départements pour lesquels les doublons de syndic sont interdit</description>
    <label>Département Syndic</label>
</CustomObject>

force-app/main/default/objects/Departement_syndic__c/fields/Departement__c.field-meta.xml
<CustomField>
    <fullName>Departement__c</fullName>
    <label>Département</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/AbonnementMois__c.field-meta.xml
<CustomField>
    <fullName>AbonnementMois__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Abonnement (€/mois)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetFourniture__c.field-meta.xml
<CustomField>
    <fullName>BudgetFourniture__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Budget Fourniture (€/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetHTTan__c.field-meta.xml
<CustomField>
    <fullName>BudgetHTTan__c</fullName>
    <formula>BudgetFourniture__c +BudgetObligationsMWH__c + Budget_Acheminement_Annuel_HTT__c + Budget_Taxes_annuel_HTVA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Budget Annuel Estimé + Obligations(€/an)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/BudgetObligationsMWH__c.field-meta.xml
<CustomField>
    <fullName>BudgetObligationsMWH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Budget CEE + Capacité</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CAR_New__c.field-meta.xml
<CustomField>
    <fullName>CAR_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CAR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DM000_QueryManager.cls
public without sharing class DM000_QueryManager {
  /*** *** QUERY ON OPPORTUNITY OBJECT *** ***/
  public static Opportunity getOpportunityById(String opportunityId) {
    Opportunity opportunityRecord = new Opportunity();
    opportunityRecord = [
      SELECT Id, AccountId, TemplateCotation__c
      FROM Opportunity
      WHERE Id = :opportunityId
    ];
    return opportunityRecord;
  }

  /*** *** QUERY ON QUOTE OBJECT *** ***/
  public static Quote getQuoteById(String quotId) {
    Quote quoteRecord = new Quote();
    quoteRecord = [SELECT Id, OpportunityId FROM Quote WHERE Id = :quotId];
    return quoteRecord;
  }

  public static List<Quote> getQuoteByOpportunity(String opportId) {
    List<Quote> quoteList = new List<Quote>();
    quoteList = [
      SELECT Id, Name, Status, OpportunityId
      FROM Quote
      WHERE OpportunityId = :opportId
    ];
    return quoteList;
  }

  /*** *** QUERY ON QUOTELINEITEM OBJECT *** ***/
  public static QuoteLineItem getQuoteLineItemById(String QuoteLineItemId) {
    QuoteLineItem quoteLineItemRecord = new QuoteLineItem();
    quoteLineItemRecord = [
      SELECT Id, QuoteId
      FROM QuoteLineItem
      WHERE Id = :QuoteLineItemId
    ];
    return quoteLineItemRecord;
  }

  public static List<QuoteLineItem> getQuoteLineItemByQuote(
    Set<String> quoteIds
  ) {
    List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();
    quoteLineItemList = [
      SELECT
        Id,
        LineNumber,
        AbonnementMois__c,
        BudgetHTTan__c,
        QuoteId,
        PDE__c,
        PDE__r.ReferencePointEnergie_Refonte__c,
        PDE__r.PCE_Refonte__c,
        PDE__r.TypePDE__c,
        CAR_New__c,
        CARGaz__c,
        BudgetFourniture__c,
        BudgetObligationsMWH__c
      FROM QuoteLineItem
      WHERE QuoteId IN :quoteIds
    ];
    return quoteLineItemList;
  }

  @AuraEnabled
  public static List<CodeNAF__c> getListCodeNaf(){
    return [SELECT Name,Description__c FROM CodeNAF__c ORDER BY Name];
  }

  @AuraEnabled
  public static List<Account> searchAccount(String accountName,String codeNaf){
      if(accountName != ''){
        String name = '%'+accountName+'%';
        return [SELECT Name,
                       Owner.Name,
                       Owner.Email,
                       Owner.Phone,
                       Code_NAF__r.Name,
                       Statut__c  
                FROM Account
                WHERE Name
                LIKE :name
                AND RecordType.DeveloperName != 'Copropriete'];
      } else {
        return [SELECT  Name,
                        Owner.Name,
                        Owner.Email,
                        Owner.Phone,
                        Code_NAF__r.Name,
                        Statut__c 
                FROM Account
                WHERE Code_NAF__r.Name = :codeNaf
                AND RecordType.DeveloperName != 'Copropriete'];
      }
  }

  @AuraEnabled(cacheable=true)
  public static Boolean isLeadAlreadyClient(String siret, String postalCode) {
    if (String.isBlank(siret)) {
        return false;
    }

    List<Account> matchingAccounts = [
        SELECT Id, RecordType.Name, Statut__c
        FROM Account
        WHERE SIRET__c = :siret
        AND (RecordType.DeveloperName = 'Syndic' 
        OR Owner.isActive = true)
    ];

    if (matchingAccounts.isEmpty()) {
        return false;
    }

    // Vérifie si le code postal de la piste est dans un département interdit pour les syndics
    Boolean isLeadInForbiddenDept = false;
    if (String.isNotBlank(postalCode)) {
        Map<String, Departement_syndic__c> mcs = Departement_syndic__c.getAll();
        for (Departement_syndic__c dep : mcs.values()) {
            if (postalCode.startsWith(dep.Departement__c)) {
                isLeadInForbiddenDept = true;
                break;
            }
        }
    }

    for (Account acc : matchingAccounts) {
        // Compte Syndic et la piste est dans un département interdit aux doublons
        if (acc.RecordType.Name == 'Syndic' && isLeadInForbiddenDept) {
            return true;
        }

        // Compte avec statut Client
        if (acc.Statut__c == 'Client') {
            return true;
        }
    }

    return false;
  }


}