force-app/main/default/objects/Account/fields/Code_partenaire__c.field-meta.xml
<CustomField>
    <fullName>Code_partenaire__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Code partenaire</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Convention_inactive__c.field-meta.xml
<CustomField>
    <fullName>Convention_inactive__c</fullName>
    <formula>Convention__r.Inactive__c</formula>
    <label>Convention inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Responsable_Leads__c.field-meta.xml
<CustomField>
    <fullName>Responsable_Leads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable Leads</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Lead.recordType-meta.xml
<RecordType>
    <fullName>Lead</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>Lead</label>
</RecordType>

force-app/main/default/classes/AP013_EspaceApporteurAffairesController.cls
public without sharing class AP013_EspaceApporteurAffairesController {
    
    @AuraEnabled
    public static Account verifyCodePartenaire(String codePartenaire){
        return [SELECT OwnerId, Responsable_Leads__c FROM Account WHERE Code_partenaire__c = :codePartenaire AND Convention_inactive__c = false LIMIT 1];
    }

    @AuraEnabled
    public static Boolean insertLead(Lead lead, String contentVersionId){
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Apporteur Affaires').getRecordTypeId();
        Database.DMLOptions dmlOptions = new Database.DMLOptions();
        dmlOptions.duplicateRuleHeader.allowSave = true;
        
        lead.RecordTypeId = recordTypeId;
        Database.SaveResult srLead = Database.insert(lead, dmlOptions);
        
        if (srLead.isSuccess()){
            // Attach the file to the iserted Lead
            ContentVersion cv = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersionId LIMIT 1];
            
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cv.ContentDocumentId;
            cdl.LinkedEntityId = lead.Id;

            Database.SaveResult srCDL = Database.insert(cdl);
            return srCDL.isSuccess();
        } else {
            return false;
        }
    }
}