force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account_EntiteJuridiquePrincipale.recordType-meta.xml
<RecordType>
    <fullName>Account_EntiteJuridiquePrincipale</fullName>
    <active>true</active>
    <label>Entité Juridique Principale</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsableCotation__c.field-meta.xml
<CustomField>
    <fullName>ResponsableCotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable de la cotation</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Simple_C5.recordType-meta.xml
<RecordType>
    <fullName>Simple_C5</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie C5</description>
    <label>Simple C5</label>
</RecordType>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/FTA__c.field-meta.xml
<CustomField>
    <fullName>FTA__c</fullName>
    <description>ELEC</description>
    <label>FTA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BT &lt;= 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - MU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - LU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - CU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - MU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - LU EP</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/NumeroVoie__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Profil__c.field-meta.xml
<CustomField>
    <fullName>Profil__c</fullName>
    <description>GAZ</description>
    <label>Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P011</fullName>
            </value>
            <value>
                <fullName>P012</fullName>
            </value>
            <value>
                <fullName>P013</fullName>
            </value>
            <value>
                <fullName>P014</fullName>
            </value>
            <value>
                <fullName>P015</fullName>
            </value>
            <value>
                <fullName>P016</fullName>
            </value>
            <value>
                <fullName>P017</fullName>
            </value>
            <value>
                <fullName>P018</fullName>
            </value>
            <value>
                <fullName>P019</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SiteConsommation__c.field-meta.xml
<CustomField>
    <fullName>SiteConsommation__c</fullName>
    <label>Site de Consommation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/X12_mois_consommation_SGE__c.field-meta.xml
<CustomField>
    <fullName>X12_mois_consommation_SGE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>12 mois de consommation sur SGE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C1C2.recordType-meta.xml
<RecordType>
    <fullName>Elec_C1C2</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C1 à C2</description>
    <label>Elec C1 à C2</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C3_C4.recordType-meta.xml
<RecordType>
    <fullName>Elec_C3_C4</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C3 à C4</description>
    <label>Elec C3 à C4</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_ElecC5.recordType-meta.xml
<RecordType>
    <fullName>PDE_ElecC5</fullName>
    <active>true</active>
    <description>Point d&apos;énergie C5</description>
    <label>Elec C5</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_Gaz.recordType-meta.xml
<RecordType>
    <fullName>PDE_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Date_de_fin_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin_de_contrat__c</fullName>
    <label>Date de fin de contrat</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Budget_TTC__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC__c</fullName>
    <label>Budget TTC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CAR_New__c.field-meta.xml
<CustomField>
    <fullName>CAR_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CAR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_CalendrierFournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_CalendrierFournisseur__c</fullName>
    <label>TECH_CalendrierFournisseur</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP029_UpdateQLIFromOpp_TEST.cls
@isTest
private class AP029_UpdateQLIFromOpp_TEST {

        @TestSetup
    static void makeData() {
        
        TestDataFactory.createPriceBooks();
        //Création de deux opportunités, une gaz et une ELEC avec tous les fournisseurs grilles inclu
        // Create Account
        Id EntiteJuridiquePrincipaleRecordTypeId = [ SELECT Id FROM RecordType WHERE DeveloperName = 'Account_EntiteJuridiquePrincipale'].get(0).Id;
        Account a = new Account(Name = 'TestAccountGaz', Industry = 'Résidentiel', Siren__c = '12345678', Siret__c = '1234567890122', RecordTypeId = EntiteJuridiquePrincipaleRecordTypeId);
        insert a;

        // Create Opp
        Id oppRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_C5'].get(0).Id;
        Opportunity opp = new Opportunity(AccountId= a.Id, Name = a.Name + ' Opportunity ', StageName = 'Conditionné', CloseDate = System.today().addMonths(1), TemplateCotation__c = 'C5', SectionSituationActuelle__c = true, responsableCotation__c = UserInfo.getUserId(), RecordTypeId = oppRecordTypeId);
        insert opp;

        // Create PDEs
        Id c1c2RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Elec_C1C2'].get(0).Id;
        Id c4RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Elec_C3_C4'].get(0).Id;
        Id c5RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_ElecC5'].get(0).Id;
        Id gazRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_Gaz'].get(0).Id;

        List<PDE__c> pdes = new List<PDE__c>();
        pdes.add(new PDE__c(Name = a.Name + ' PDEC1', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678900', ReferencePointEnergie_Refonte__c = '12345678900', EntiteJuridique__c = a.Id, RecordTypeId = c1c2RecordTypeId, FTA__c = 'HTA - PF - CU', X12_mois_consommation_SGE__c = true,Segment__c = 'C1'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC2', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678901', ReferencePointEnergie_Refonte__c = '12345678900', EntiteJuridique__c = a.Id, RecordTypeId = c1c2RecordTypeId, FTA__c = 'HTA - PF - CU', X12_mois_consommation_SGE__c = true,Segment__c = 'C2'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC4', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678911', ReferencePointEnergie_Refonte__c = '12345678911', EntiteJuridique__c = a.Id, RecordTypeId = c4RecordTypeId, FTA__c = 'BT > 36 kVA - CU', X12_mois_consommation_SGE__c = true,Segment__c = 'C4'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC4', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678911', ReferencePointEnergie_Refonte__c = '12345678912', EntiteJuridique__c = a.Id, RecordTypeId = c4RecordTypeId, FTA__c = 'BT > 36 kVA - LU', X12_mois_consommation_SGE__c = true,Segment__c = 'C4'));  
        pdes.add(new PDE__c(Name = a.Name + ' PDEC5Base', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678922', ReferencePointEnergie_Refonte__c = '12345678922', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36 kVA - MU', X12_mois_consommation_SGE__c = true,Segment__c = 'C5'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC5HPHC', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678987', ReferencePointEnergie_Refonte__c = '12345678922', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36 kVA - MU', X12_mois_consommation_SGE__c = true,Segment__c = 'C5',Calendrier_fournisseur__c = 'HP/HC'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC54Postes', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678933', ReferencePointEnergie_Refonte__c = '12345678933', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36Kva - CU 4 postes', X12_mois_consommation_SGE__c = true,Segment__c = 'C5'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEGaz', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '1234567893', ReferencePointEnergie_Refonte__c = '1234567893', EntiteJuridique__c = a.Id, RecordTypeId = gazRecordTypeId, Tarif__c = 'T4', Profil__c = 'P011'));
        insert pdes;
        
        List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
        for (PDE__c pde : pdes) {
        listOPR.add(new OpportunityPDERelation__c(Opportunity__c = opp.Id, PDE__c = pde.Id));
        }
        insert listOPR;

        opp.Liste_fournisseurs__c= 'TotalEnergies;Vattenfall;Dyneff;EDF Entreprises;Ekwateur;Engie;Ilek;GEG;Hellio;';
        update opp;

        Pricebook2 priceBook = [Select Id From Pricebook2 Limit 1];

        List<Quote> quotes = new List<Quote>();
        quotes.add(new Quote(Name = 'QUOTE 1', Pricebook2Id = priceBook.Id, OpportunityId = opp.Id, Date_de_fin_de_contrat__c = Date.today()));
        quotes.add(new Quote(Name = 'QUOTE 2', Pricebook2Id = priceBook.Id, OpportunityId = opp.Id, Date_de_fin_de_contrat__c = Date.today()));
        insert quotes;

        List<Product2> products = [Select id from Product2];

        List<PricebookEntry> priceBookEntries = [Select id from PriceBookEntry];

        List<QuoteLineItem> qlis = new List<QuoteLineItem>();
        qlis.add(new QuoteLineItem(Product2Id = products.get(0).Id,PDE__c = pdes.get(1).Id, QuoteId = quotes.get(0).Id, PricebookEntryId = priceBookEntries.get(2).Id,
                                    Quantity = 1, UnitPrice = 1, DebutDeFourniture__c = Date.today(), Nouvelle_Echeance__c = Date.today(), DureeEngagement__c = 24, Budget_TTC__c = 2, 
                                    CARGaz__c = 1234, CAR_New__c = 1234, TECH_CalendrierFournisseur__c = pdes.get(1).Calendrier_fournisseur__c));
    
    }

    @isTest
    static void UpdateOppQli() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        QuoteLineItem qliBefore = [SELECT Id, PDE__c, Conso_Base__c, DebutDeFourniture__c, Nouvelle_Echeance__c FROM QuoteLineItem LIMIT 1];

        PDE__c pdeToUpdate = [SELECT Id, Conso_Base__c, Puissance_souscrite__c, DateEcheance__c FROM PDE__c WHERE Id = :qliBefore.PDE__c];
        pdeToUpdate.Conso_Base__c = 555;
        pdeToUpdate.Puissance_souscrite__c = 99.9;
        pdeToUpdate.DateEcheance__c = System.today().addDays(15);
        update pdeToUpdate;

        AP029_UpdateQLIFromOpp.FlowInputs input = new AP029_UpdateQLIFromOpp.FlowInputs();
        input.OppId = opp.Id;

        Test.startTest();
        List<AP029_UpdateQLIFromOpp.FlowOutput> result = AP029_UpdateQLIFromOpp.updateOppQli(new List<AP029_UpdateQLIFromOpp.FlowInputs>{input});
        Test.stopTest();

        QuoteLineItem qliAfter = [SELECT Id, PDE__c, Conso_Base__c, Puissance_souscrite__c, DebutDeFourniture__c, Nouvelle_Echeance__c, DureeEngagement__c FROM QuoteLineItem WHERE Id = :qliBefore.Id];

        System.assertEquals(555, qliAfter.Conso_Base__c, 'Conso_Base__c should be updated from PDE');
        System.assertEquals(99.9, qliAfter.Puissance_souscrite__c, 'Puissance_souscrite__c should be updated');
    }

    // code duplicate because after update pde tarif in the same method i have "System.LimitException: Too many SOQL queries: 101"
    @isTest
    static void UpdateOppQliGazTarifT1() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        QuoteLineItem qliBefore = [SELECT Id, PDE__c, Conso_Base__c, DebutDeFourniture__c, Nouvelle_Echeance__c FROM QuoteLineItem WHERE TECH_TypePDL__c = 'PDE_Gaz' LIMIT 1];

        PDE__c pdeToUpdate = [SELECT Id, Conso_Base__c, Puissance_souscrite__c, DateEcheance__c, Tarif__c FROM PDE__c WHERE Id = :qliBefore.PDE__c];

        AP029_UpdateQLIFromOpp.FlowInputs input = new AP029_UpdateQLIFromOpp.FlowInputs();
        input.OppId = opp.Id;

        Test.startTest();
            pdeToUpdate.Tarif__c = 'T1';
            update pdeToUpdate;
            List<AP029_UpdateQLIFromOpp.FlowOutput> result = AP029_UpdateQLIFromOpp.updateOppQli(new List<AP029_UpdateQLIFromOpp.FlowInputs>{input});
        Test.stopTest();
    }

    @isTest
    static void UpdateOppQliGazTarifT2() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        QuoteLineItem qliBefore = [SELECT Id, PDE__c, Conso_Base__c, DebutDeFourniture__c, Nouvelle_Echeance__c FROM QuoteLineItem WHERE TECH_TypePDL__c = 'PDE_Gaz' LIMIT 1];

        PDE__c pdeToUpdate = [SELECT Id, Conso_Base__c, Puissance_souscrite__c, DateEcheance__c, Tarif__c FROM PDE__c WHERE Id = :qliBefore.PDE__c];

        AP029_UpdateQLIFromOpp.FlowInputs input = new AP029_UpdateQLIFromOpp.FlowInputs();
        input.OppId = opp.Id;

        Test.startTest();
            pdeToUpdate.Tarif__c = 'T2';
            update pdeToUpdate;
            List<AP029_UpdateQLIFromOpp.FlowOutput> result = AP029_UpdateQLIFromOpp.updateOppQli(new List<AP029_UpdateQLIFromOpp.FlowInputs>{input});
        Test.stopTest();
    }

    @isTest
    static void UpdateOppQliGazTarifT3() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        QuoteLineItem qliBefore = [SELECT Id, PDE__c, Conso_Base__c, DebutDeFourniture__c, Nouvelle_Echeance__c FROM QuoteLineItem WHERE TECH_TypePDL__c = 'PDE_Gaz' LIMIT 1];

        PDE__c pdeToUpdate = [SELECT Id, Conso_Base__c, Puissance_souscrite__c, DateEcheance__c, Tarif__c FROM PDE__c WHERE Id = :qliBefore.PDE__c];
        AP029_UpdateQLIFromOpp.FlowInputs input = new AP029_UpdateQLIFromOpp.FlowInputs();
        input.OppId = opp.Id;

        Test.startTest();
            pdeToUpdate.Tarif__c = 'T3';
            update pdeToUpdate;
            List<AP029_UpdateQLIFromOpp.FlowOutput> result = AP029_UpdateQLIFromOpp.updateOppQli(new List<AP029_UpdateQLIFromOpp.FlowInputs>{input});
        Test.stopTest();
    }
}