force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_voie__c.field-meta.xml
<CustomField>
    <fullName>Numero_voie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Syndic.recordType-meta.xml
<RecordType>
    <fullName>Syndic</fullName>
    <active>true</active>
    <label>Syndic</label>
</RecordType>

force-app/main/default/classes/ChargementEnMasseCoproController_TEST.cls
@isTest
public with sharing class ChargementEnMasseCoproController_TEST {
  @TestSetup
  static void createTestData() {
    Id syndicRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Syndic'
      ]
      .get(0)
      .Id;

    Account syndic = new Account(
      Name = 'TestAccount545',
      Industry = 'Résidentiel',
      Siren__c = '123756789',
      Siret__c = '12341678901239',
      RecordTypeId = syndicRecordTypeId
    );
    insert syndic;
  }

  @isTest
  static void insertCoproSuccessTest() {
    Id syndicId = [
      SELECT Id
      FROM Account
      WHERE RecordType.DeveloperName = 'Syndic'
      LIMIT 1
    ]
    .Id;
    Contact contact = new Contact();
    contact.FirstName = 'GestionnaireCopro23131';
    contact.LastName = 'GestionnaireCopro11132';
    contact.Phone = '0711223344';
    contact.Email = 'GestionnaireCopro@activ7.com';
    contact.accountId = syndicId;
    insert contact;
    String strCopro = JSON.serialize('COPRO 1;12345678909871;123456789;22/11/2022;22/11/2022;Non;123;RUE TEST;69008;LYON;'+contact.Id);
    String dataCopro = JSON.deserializeUntyped(strCopro).toString();
    list<String> csvFileLinesCopro = dataCopro.split('\n');
    Test.startTest();
    String strHeaderCopro = 'NOM DE LA COPROPRIETE;SIRET;SIREN;DATE DE RENDEZ-VOUS;DATE DE RECEPTION DE L\'OFFRE;ASAP;NUMERO VOIE;VOIE;CODE POSTAL;COMMUNE;IDENTIFIANT DU CONTACT';
    ChargementEnMasseCoproController.insertCopro(strHeaderCopro,csvFileLinesCopro, syndicId);
    Account insertedCopro = [
      SELECT
        Siret__c,
        Siren__c,
        Numero_voie__c,
        voie__c,
        Code_Postal__c,
        Ville__c
      FROM Account
      WHERE Name = 'COPRO 1'
    ];
    Test.stopTest();
    System.assertEquals('12345678909871', insertedCopro.Siret__c);
    System.assertEquals('123456789', insertedCopro.Siren__c);
    System.assertEquals('123', insertedCopro.Numero_voie__c);
    System.assertEquals('RUE TEST', insertedCopro.voie__c);
    System.assertEquals('69008', insertedCopro.Code_Postal__c);
    System.assertEquals('LYON', insertedCopro.Ville__c);
    System.assertEquals(
      contact.Id,
      [
        SELECT ContactId
        FROM AccountContactRelation
        WHERE AccountId = :insertedCopro.Id
      ][0]
      .ContactId
    );
  }
  
  @isTest
  static void insertCoproFailTest() {
    Id syndicId = [
      SELECT Id
      FROM Account
      WHERE RecordType.DeveloperName = 'Syndic'
      LIMIT 1
    ]
    .Id;
    String strCopro = JSON.serialize(
      'COPRO 1;12345678909876;123456789;;22/11/2022;Non;123;RUE TEST;69008;LYON;' +
      contact.Id
    );
    String dataCopro = JSON.deserializeUntyped(strCopro).toString();
    String strHeaderCopro = 'NOM DE LA COPROPRIETE;SIREN;SIRET;DATE DE RENDEZ-VOUS;DATE DE RECEPTION DE L\'OFFRE;ASAP;NUMERO VOIE;VOIE;CODE POSTAL;COMMUNE;IDENTIFIANT DU CONTACT';
    list<String> csvFileLinesCopro = dataCopro.split('\n');
    Test.startTest();
    try {
      ChargementEnMasseCoproController.insertCopro(strHeaderCopro,csvFileLinesCopro, syndicId);
    } catch (Exception e) {
      System.assertEquals(
        e.getMessage(),
        'Script-thrown exception'
      );
    }
    Test.stopTest();
  }

  @isTest
  static void retrieveCoprosTest(){
    Id coproRecordTypeId = [
        SELECT Id
        FROM RecordType
        WHERE DeveloperName = 'Copropriete'
        LIMIT 1
      ].Id;

    Id syndicId = [
      SELECT Id
      FROM Account
      WHERE RecordType.DeveloperName = 'Syndic'
      LIMIT 1
    ].Id;

    Account copro = new Account(Name = 'Copro',
    Industry = 'Copro',
    Siren__c = '123758559',
    Siret__c = '12341655901239',
    Syndic__c= syndicId,
    RecordTypeId = coproRecordTypeId);
    insert copro;
    List<Account> listCopro = ChargementEnMasseCoproController.retrieveCopros(syndicId);
    System.assertEquals(listCopro.get(0).Name, copro.Name);
  }
}