force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsableCotation__c.field-meta.xml
<CustomField>
    <fullName>ResponsableCotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable de la cotation</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionPropositionRenouvellement__c.field-meta.xml
<CustomField>
    <fullName>SectionPropositionRenouvellement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Proposition de renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Masse_GAZ.recordType-meta.xml
<RecordType>
    <fullName>Masse_GAZ</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant beaucoup de points d&apos;énergie Gaz</description>
    <label>Masse GAZ</label>
</RecordType>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/PDE_Gaz.recordType-meta.xml
<RecordType>
    <fullName>PDE_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SM002_GestionDevisMasse_TEST.cls
@isTest
private class SM002_GestionDevisMasse_TEST {
   
    @TestSetup
    static void makeData() {
        TestDataFactory.createPriceBooks();
        Id rtPDEGaz = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_Gaz'].get(0).Id;
        Id rtOppSimpleGaz = [SELECT Id FROM RecordType WHERE DeveloperName = 'Masse_Gaz'].get(0).Id;
        List<PDE__c> listPDEToInsert = new List<PDE__c>();
        List<OpportunityPDERelation__c> listOPRToInsert = new List<OpportunityPDERelation__c>();

        Account acc = new Account(Name= 'TEST');
        insert acc;
        
        PDE__c pde = new PDE__c(
            Name = acc.Name + ' PDEGaz ',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            DateEcheance__c = System.today().addMonths(1),
            PCE_Refonte__c = '1234567899',
            EntiteJuridique__c = acc.Id,
            RecordTypeId = rtPDEGaz
        );
        listPDEToInsert.add(pde);

        PDE__c pde2 = new PDE__c(
            Name = acc.Name + ' PDEGaz2 ',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            DateEcheance__c = System.today().addMonths(1),
            PCE_Refonte__c = '1234567891',
            EntiteJuridique__c = acc.Id,
            RecordTypeId = rtPDEGaz
        );
        listPDEToInsert.add(pde2);

        insert listPDEToInsert;

        Opportunity opp =  new Opportunity(
            Name = acc.Name + ' Opportunity',
            StageName = 'Conditionné',
            CloseDate = System.today().addMonths(1),
            TemplateCotation__c = 'Gaz',
            AccountId = acc.Id,
            responsableCotation__c = UserInfo.getUserId(),
            RecordTypeId = rtOppSimpleGaz
          );
          insert opp;

          OpportunityPDERelation__c opr1 = new OpportunityPDERelation__c(Opportunity__c = opp.id,PDE__c = pde.Id);
          OpportunityPDERelation__c opr2 = new OpportunityPDERelation__c(Opportunity__c = opp.id,PDE__c = pde2.Id);
          listOPRToInsert.add(opr1);
          listOPRToInsert.add(opr2);
          insert listOPRToInsert;
    }

    @isTest
    static void createThreeFournisseur(){
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
        Opportunity opp = [Select Id from Opportunity][0];
        opp.Liste_Fournisseurs__c = 'Antargaz;Alpiq;Engie';
        Test.startTest();
        update opp;
        Test.stopTest();
        Assert.areEqual(3, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM QuoteLineItem][0].get('expr0'));

    }

    @isTest
    static void deleteAllFournisseur(){
        Opportunity opp = [Select Id from Opportunity][0];
        opp.Liste_Fournisseurs__c = 'Alterna;Antargaz;Engie';

        Test.startTest();
        update opp;
        Assert.areEqual(3, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));

        opp.Liste_Fournisseurs__c = '';

        update opp;
        Test.stopTest();
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
    }

    @isTest
    static void addOneFournisseur(){
        Opportunity opp = [Select Id from Opportunity][0];
        opp.Liste_Fournisseurs__c = 'Alterna;Antargaz;Engie';
        Test.startTest();
        update opp;
        opp.Liste_Fournisseurs__c = 'Alterna;Antargaz;Engie;Alpiq';
        update opp;
        Test.stopTest();
        Assert.areEqual(4, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM QuoteLineItem][0].get('expr0'));
    }

    @isTest
    static void addOneAndDeleteOneFournisseur(){
        Opportunity opp = [Select Id from Opportunity][0];
        opp.Liste_Fournisseurs__c = 'Alterna;Antargaz;Engie';
        Test.startTest();
        update opp;
        opp.Liste_Fournisseurs__c = 'Alterna;Antargaz;Alpiq';
        update opp;
        Test.stopTest();
        Assert.areEqual(3, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM QuoteLineItem][0].get('expr0'));
    }

    @isTest
    static void addSpecialQuote(){
        Opportunity opp = [Select Id from Opportunity][0];
        opp.SectionPropositionRenouvellement__c = true;
        opp.SectionSituationActuelle__c = true;
        Test.startTest();
        update opp;
        Test.stopTest();
        Assert.areEqual(2, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM QuoteLineItem][0].get('expr0'));
    }

    @isTest
    static void deleteSpecialQuote(){
        Opportunity opp = [Select Id from Opportunity][0];
        opp.SectionPropositionRenouvellement__c = true;
        opp.SectionSituationActuelle__c = true;
        Test.startTest();
        update opp;
        opp.SectionPropositionRenouvellement__c = false;
        opp.SectionSituationActuelle__c = false;
        update opp;
        Test.stopTest();
        Assert.areEqual(0, (Integer)[SELECT count(id) FROM Quote][0].get('expr0'));
    }
}