force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsableCotation__c.field-meta.xml
<CustomField>
    <fullName>ResponsableCotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable de la cotation</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Simple_Gaz.recordType-meta.xml
<RecordType>
    <fullName>Simple_Gaz</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie Gaz</description>
    <label>Simple Gaz</label>
</RecordType>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/PDE_Gaz.recordType-meta.xml
<RecordType>
    <fullName>PDE_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/classes/AP005_CreateOPRFromFlow_TEST.cls
@isTest
private class AP005_CreateOPRFromFlow_TEST {
    
    @testSetup
    static void makeData(){
        TestDataFactory.createPriceBooks();
        Id rtPDEGaz = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_Gaz'].get(0).Id;
        Id rtOpp = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_Gaz'].get(0).Id;
        List<PDE__c> listPDEToInsert = new List<PDE__c>();
        List<OpportunityPDERelation__c> listOPRToInsert = new List<OpportunityPDERelation__c>();

        Account acc = new Account(Name= 'TEST');
        insert acc;

        Contact con1 = new Contact(
            LastName = 'Signataire1',
            FirstName = 'Opportunity',
            Phone = '0611223344',
            Email = 'contact1@test.com',
            accountId = acc.id
          );
        insert con1;

        Demande_Cotation__c demandeCotation = new Demande_Cotation__c(
            Name = 'XXXXXXXXXXX',
            Account__c = acc.Id,
            Statut__c = 'En cours de traitement',
            Date_demande_cotation__c = Date.today(),
            Signataire__c = con1.Id,
            Charge_affaire__c = UserInfo.getUserId()
            );
        insert demandeCotation;
        
        PDE__c pde = new PDE__c(
            Name = acc.Name + ' PDEGaz ',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            DateEcheance__c = System.today().addMonths(1),
            Demande_Cotation__c = demandeCotation.Id,
            PCE_Refonte__c = '1234567899',
            EntiteJuridique__c = acc.Id,
            RecordTypeId = rtPDEGaz
        );
        listPDEToInsert.add(pde);

        PDE__c pde2 = new PDE__c(
            Name = acc.Name + ' PDEGaz2 ',
            voie__c = 'Rue de la Villette',
            Code_Postal__c = '69003',
            Ville__c = 'Lyon',
            DateEcheance__c = System.today().addMonths(1),
            Demande_Cotation__c = demandeCotation.Id,
            PCE_Refonte__c = '1234567891',
            EntiteJuridique__c = acc.Id,
            RecordTypeId = rtPDEGaz
        );
        listPDEToInsert.add(pde2);

        insert listPDEToInsert;

        Opportunity opp =  new Opportunity(
            Name = acc.Name + ' Opportunity',
            StageName = 'Conditionné',
            CloseDate = System.today().addMonths(1),
            TemplateCotation__c = 'Gaz',
            AccountId = acc.Id,
            responsableCotation__c = UserInfo.getUserId(),
            RecordTypeId = rtOpp
          );
          insert opp;
    }

    @isTest
    static void creerOpportuniteFromFlow(){

        Id oppId = [SELECT Id FROM Opportunity LIMIT 1].Id;
        List<PDE__c> ListPDE = [SELECT Demande_Cotation__c FROM PDE__c];
        List<AP005_CreateOPRFromFlow.FlowInputs> params = new List<AP005_CreateOPRFromFlow.FlowInputs>();

        AP005_CreateOPRFromFlow.FlowInputs inputs = new AP005_CreateOPRFromFlow.FlowInputs();
        inputs.OpportunityId = oppId;
        inputs.SelectedPDEs = ListPDE;

        params.add(inputs);

        Test.startTest();
        List<AP005_CreateOPRFromFlow.FlowOutput> success = AP005_CreateOPRFromFlow.createOPR(params);
        Test.stopTest();

        Assert.isTrue(success[0].DMLSuccess);
    }
}