force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account_EntiteJuridiquePrincipale.recordType-meta.xml
<RecordType>
    <fullName>Account_EntiteJuridiquePrincipale</fullName>
    <active>true</active>
    <label>Entité Juridique Principale</label>
</RecordType>

force-app/main/default/objects/Grille_Dyneff__mdt/Grille_Dyneff__mdt.object-meta.xml
<CustomObject>
    <label>Grille Dyneff</label>
    <pluralLabel>Grilles Dyneff</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grille_Dyneff__mdt/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite (kVA)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsableCotation__c.field-meta.xml
<CustomField>
    <fullName>ResponsableCotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsable de la cotation</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Simple_C1C2C3C4.recordType-meta.xml
<RecordType>
    <fullName>Simple_C1C2C3C4</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie C1C2C3C4</description>
    <label>Simple C1C2C3C4</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Simple_C5.recordType-meta.xml
<RecordType>
    <fullName>Simple_C5</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie C5</description>
    <label>Simple C5</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Simple_Gaz.recordType-meta.xml
<RecordType>
    <fullName>Simple_Gaz</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie Gaz</description>
    <label>Simple Gaz</label>
</RecordType>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/FTA__c.field-meta.xml
<CustomField>
    <fullName>FTA__c</fullName>
    <description>ELEC</description>
    <label>FTA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BT &lt;= 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - MU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - LU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - CU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - MU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - LU EP</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/NumeroVoie__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Profil__c.field-meta.xml
<CustomField>
    <fullName>Profil__c</fullName>
    <description>GAZ</description>
    <label>Profil</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P011</fullName>
            </value>
            <value>
                <fullName>P012</fullName>
            </value>
            <value>
                <fullName>P013</fullName>
            </value>
            <value>
                <fullName>P014</fullName>
            </value>
            <value>
                <fullName>P015</fullName>
            </value>
            <value>
                <fullName>P016</fullName>
            </value>
            <value>
                <fullName>P017</fullName>
            </value>
            <value>
                <fullName>P018</fullName>
            </value>
            <value>
                <fullName>P019</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/SiteConsommation__c.field-meta.xml
<CustomField>
    <fullName>SiteConsommation__c</fullName>
    <label>Site de Consommation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/X12_mois_consommation_SGE__c.field-meta.xml
<CustomField>
    <fullName>X12_mois_consommation_SGE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>12 mois de consommation sur SGE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C1C2.recordType-meta.xml
<RecordType>
    <fullName>Elec_C1C2</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C1 à C2</description>
    <label>Elec C1 à C2</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/Elec_C3_C4.recordType-meta.xml
<RecordType>
    <fullName>Elec_C3_C4</fullName>
    <active>true</active>
    <description>Point d&apos;énergie de C3 à C4</description>
    <label>Elec C3 à C4</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_ElecC5.recordType-meta.xml
<RecordType>
    <fullName>PDE_ElecC5</fullName>
    <active>true</active>
    <description>Point d&apos;énergie C5</description>
    <label>Elec C5</label>
</RecordType>

force-app/main/default/objects/PDE__c/recordTypes/PDE_Gaz.recordType-meta.xml
<RecordType>
    <fullName>PDE_Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <customValue>
        <fullName>GEG</fullName>
    </customValue>
    <customValue>
        <fullName>Hellio</fullName>
    </customValue>
    <customValue>
        <fullName>Ilek</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP021_GrilleFournisseur_TEST.cls
@IsTest
private class AP021_GrilleFournisseur_TEST {
    
    @TestSetup
    static void makeData(){
        TestDataFactory.createPriceBooks();
        //Création de deux opportunités, une gaz et une ELEC avec tous les fournisseurs grilles inclu
        // Create Account
        Id EntiteJuridiquePrincipaleRecordTypeId = [ SELECT Id FROM RecordType WHERE DeveloperName = 'Account_EntiteJuridiquePrincipale'].get(0).Id;
        Account a = new Account(Name = 'TestAccountGaz', Industry = 'Résidentiel', Siren__c = '12345678', Siret__c = '1234567890122', RecordTypeId = EntiteJuridiquePrincipaleRecordTypeId);
        insert a;

        // Create Opp
        Id oppRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_C5'].get(0).Id;
        Opportunity opp = new Opportunity(AccountId= a.Id, Name = a.Name + ' Opportunity ', StageName = 'Conditionné', CloseDate = System.today().addMonths(1), TemplateCotation__c = 'C5', SectionSituationActuelle__c = true, responsableCotation__c = UserInfo.getUserId(), RecordTypeId = oppRecordTypeId);
        insert opp;

        // Create PDEs
        Id c1c2RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Elec_C1C2'].get(0).Id;
        Id c4RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Elec_C3_C4'].get(0).Id;
        Id c5RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_ElecC5'].get(0).Id;
        Id gazRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PDE_Gaz'].get(0).Id;

        List<PDE__c> pdes = new List<PDE__c>();
        pdes.add(new PDE__c(Name = a.Name + ' PDEC1', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678900', ReferencePointEnergie_Refonte__c = '12345678900', EntiteJuridique__c = a.Id, RecordTypeId = c1c2RecordTypeId, FTA__c = 'HTA - PF - CU', X12_mois_consommation_SGE__c = true,Segment__c = 'C1'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC2', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678901', ReferencePointEnergie_Refonte__c = '12345678900', EntiteJuridique__c = a.Id, RecordTypeId = c1c2RecordTypeId, FTA__c = 'HTA - PF - CU', X12_mois_consommation_SGE__c = true,Segment__c = 'C2'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC4', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678911', ReferencePointEnergie_Refonte__c = '12345678911', EntiteJuridique__c = a.Id, RecordTypeId = c4RecordTypeId, FTA__c = 'BT > 36 kVA - CU', X12_mois_consommation_SGE__c = true,Segment__c = 'C4'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC4', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678911', ReferencePointEnergie_Refonte__c = '12345678912', EntiteJuridique__c = a.Id, RecordTypeId = c4RecordTypeId, FTA__c = 'BT > 36 kVA - LU', X12_mois_consommation_SGE__c = true,Segment__c = 'C4'));  
        pdes.add(new PDE__c(Name = a.Name + ' PDEC5Base', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678922', ReferencePointEnergie_Refonte__c = '12345678922', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36 kVA - MU', X12_mois_consommation_SGE__c = true,Segment__c = 'C5'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC5HPHC', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678987', ReferencePointEnergie_Refonte__c = '12345678922', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36 kVA - MU', X12_mois_consommation_SGE__c = true,Segment__c = 'C5',Calendrier_fournisseur__c = 'HP/HC'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEC54Postes', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '12345678933', ReferencePointEnergie_Refonte__c = '12345678933', EntiteJuridique__c = a.Id, RecordTypeId = c5RecordTypeId, FTA__c = 'BT <= 36Kva - CU 4 postes', X12_mois_consommation_SGE__c = true,Segment__c = 'C5'));
        pdes.add(new PDE__c(Name = a.Name + ' PDEGaz', SiteConsommation__c = 'TEST ', NumeroVoie__c = '90', voie__c = 'Rue de la Villette', Code_Postal__c = '69003', Ville__c = 'Lyon', CARGaz__c = 1234, DateEcheance__c = System.today().addMonths(1), PCE_Refonte__c = '1234567893', ReferencePointEnergie_Refonte__c = '1234567893', EntiteJuridique__c = a.Id, RecordTypeId = gazRecordTypeId, Tarif__c = 'T4', Profil__c = 'P011'));
        insert pdes;
        
        List<OpportunityPDERelation__c> listOPR = new List<OpportunityPDERelation__c>();
        for (PDE__c pde : pdes) {
        listOPR.add(new OpportunityPDERelation__c(Opportunity__c = opp.Id, PDE__c = pde.Id));
        }
        insert listOPR;

        opp.Liste_fournisseurs__c= 'TotalEnergies;Vattenfall;Dyneff;EDF Entreprises;Ekwateur;Engie;Ilek;GEG;Hellio;';
        update opp;
    }

    @IsTest
    static void caculatePriceTotal(){
        
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'TotalEnergies'];
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        input.recordId = quote.Id;
        input.fournisseur = 'TotalEnergies';
        input.dureeOffre = '12';

        inputs.add(input);
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);

        // Upodate Opp
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Id oppGazRecordId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_Gaz'].get(0).Id;
        opp.RecordTypeId = oppGazRecordId;
        update opp;

        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();   
    }

    @IsTest
    static void caculatePriceVattenfall(){
        
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'Vattenfall']; 
        Grille_Vattenfall__mdt prixGrille = null;
        String labelCode;
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();

        for(QuoteLineItem qli : [SELECT Id,
                                        DebutDeFourniture__c,
                                        Nouvelle_Echeance__c,
                                        Puissance_souscrite__c,
                                        TECH_Segment__c,
                                        TECH_FTA__c,
                                        TECH_Tarif__c,
                                        TECH_CalendrierFournisseur__c
                                    FROM QuoteLineItem 
                                    WHERE QuoteId =: quote.Id
                                    AND TECH_Segment__c = 'C5']){
            
            if(qli.TECH_CalendrierFournisseur__c.contains('Base')){
                labelCode = 'Base_12_24';
            } else if (qli.TECH_CalendrierFournisseur__c.contains('HP/HC')){
                labelCode = 'HPHC_12_24';
            } else {
                labelCode = '';
            }

            prixGrille = Grille_Vattenfall__mdt.getInstance(labelCode);

            if(prixGrille != null) {
                qli.DebutDeFourniture__c = prixGrille.Date_debut_maximale__c;
                qli.Nouvelle_Echeance__c = prixGrille.Date_fin_maximale__c;
                qli.Puissance_souscrite__c = 12;
                listQLI.add(qli);
            }
        }


        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        input.recordId = quote.Id;
        input.fournisseur = 'Vattenfall';
        input.dureeOffre = '24';

        inputs.add(input);

        update listQLI;
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest(); 
    }

    @IsTest
    static void caculatePriceDyneff(){
        
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'Dyneff'];
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();
        String labelCode;
        Grille_Dyneff__mdt prixGrille = null;
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();

        for(QuoteLineItem qli : [SELECT Id,
                                        DebutDeFourniture__c,
                                        Nouvelle_Echeance__c,
                                        Puissance_souscrite__c,
                                        TECH_Segment__c,
                                        TECH_FTA__c,
                                        TECH_Tarif__c,
                                        TECH_CalendrierFournisseur__c
                                    FROM QuoteLineItem 
                                    WHERE QuoteId =: quote.Id
                                    AND TECH_Segment__c = 'C5']){
            
            if(qli.TECH_CalendrierFournisseur__c.contains('Base')){
                labelCode = 'Base_12';
            } else if (qli.TECH_CalendrierFournisseur__c.contains('HP/HC')){
                labelCode = 'HPHC_12';
            } else {
                labelCode = '';
            }

            prixGrille = Grille_Dyneff__mdt.getInstance(labelCode);

            if(prixGrille != null) {
                qli.Nouvelle_Echeance__c = prixGrille.Date_fin_maximale__c;
                qli.Puissance_souscrite__c = 12;
                listQLI.add(qli);
            }
        }



        input.recordId = quote.Id;
        input.fournisseur = 'Dyneff';
        input.dureeOffre = '12';

        inputs.add(input);

        update listQLI;
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();
    }

    @IsTest
    static void caculatePriceEDFEntreprises(){
        
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'EDF Entreprises'];
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();


        for(QuoteLineItem qli : [SELECT Id, Puissance_souscrite__c FROM QuoteLineItem WHERE Quote.Id = :quote.Id AND TECH_Segment__c = 'C5' ]){
            qli.Puissance_souscrite__c = 12;
            listQLI.add(qli);
        }

        input.recordId = quote.Id;
        input.fournisseur = 'EDF Entreprises';
        input.dureeOffre = '12';

        inputs.add(input);

        update listQLI;
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();  
    }
    
    @IsTest
    static void calculatePriceIlek() {
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'Ilek'];
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        for(QuoteLineItem qli : [SELECT Id, Puissance_souscrite__c FROM QuoteLineItem WHERE Quote.Id = :quote.Id AND TECH_Segment__c = 'C5' ]){
            qli.Puissance_souscrite__c = 12;
            listQLI.add(qli);
        }


        input.recordId = quote.Id;
        input.fournisseur = 'Ilek';
        input.dureeOffre = '12';

        inputs.add(input);

        update listQLI;
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();  
    }
    
    @IsTest
    static void calculatePriceGEG() {
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'GEG'];
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        for(Quotelineitem qli : [SELECT Id, DebutDeFourniture__c, Nouvelle_Echeance__c, Puissance_souscrite__c,
                   TECH_Segment__c, TECH_FTA__c, TECH_Tarif__c, TECH_CalendrierFournisseur__c,
                   CAR_New__c,CARGaz__c, PDE__r.X12_mois_consommation_SGE__c
            FROM QuoteLineItem
            WHERE QuoteId = :quote.Id
        ]){

            qli.Puissance_souscrite__c = 12;
            qli.CAR_New__c = 100;
            listQLI.add(qli);
        }

        input.recordId = quote.Id;
        input.fournisseur = 'GEG';
        input.dureeOffre = '12';
        input.margeMwh = 5;

        inputs.add(input);

        update listQLI;
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();  
    }

    @IsTest
    static void calculatePriceEkwateur() {
        Quote quote = [SELECT Id,OpportunityId From Quote WHERE Fournisseur__c = 'Ekwateur'];
        //Suppression des QLI autre que C4, C5 et T4
        delete [SELECT Id FROM QuoteLineItem WHERE quote.Id =:quote.ID AND TECH_Segment__c not in ('C4','C5')];
        String labelCode = 'C5';
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        Grille_Ekwateur__mdt dateMinMaxGrille = [SELECT Id, Date_debut_min1__c,Date_fin__c,Date_debut_max1__c,Date_debut_min2__c, Date_debut_max2__c FROM Grille_Ekwateur__mdt WHERE DeveloperName like :labelCode+'%' LIMIT 1];

        for(QuoteLineItem qli : [SELECT Id FROM QuoteLineItem WHERE quote.Id =: quote.Id]){
            qli.DebutDeFourniture__c = dateMinMaxGrille.Date_debut_min1__c;
            qli.DebutDeFourniture__c = dateMinMaxGrille.Date_debut_max1__c;
            qli.Nouvelle_Echeance__c = dateMinMaxGrille.Date_fin__c;
            listQLI.add(qli);
        }
        

        update listQLI;
        
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        input.recordId = quote.Id;
        input.fournisseur = 'Ekwateur';
        input.dureeOffre = '12';
        input.margeMwh = 15;

        inputs.add(input);
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);

        // Upodate Opp
        Id oppC4RecordId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_C1C2C3C4'].get(0).Id;
        Opportunity opp  = [SELECT Id from Opportunity LIMIT 1];
        opp.RecordTypeId = oppC4RecordId;
        update opp;

        AP021_GrilleFournisseur.GET_Prix(inputs);

        // Upodate Opp
        Id oppGazRecordId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_Gaz'].get(0).Id;
        opp.RecordTypeId = oppGazRecordId;
        delete [SELECT Id FROM QuoteLineItem WHERE quote.Id =:quote.ID AND TECH_Profil__c <> ''];
        update opp;

        AP021_GrilleFournisseur.GET_Prix(inputs);

        Test.stopTest();
    }

    @IsTest
    static void calculatePriceEngiePro() {
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'Engie'];
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();


        for(QuoteLineItem qli : [SELECT Id FROM QuoteLineItem WHERE Quote.Id =: quote.Id]){
            qli.DebutDeFourniture__c = DatE.today();
            qli.CARGaz__c = 20;
            qli.puissance_souscrite__c = 12;
            quote.Date_Validite_Offre__c = Date.today().addMonths(1);
            listQLI.add(qli);
        }


        input.recordId = quote.Id;
        input.fournisseur = 'Engie';
        input.dureeOffre = '12_fixe';

        inputs.add(input);

        update listQLI;        
        update quote;
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();
    }

    @isTest
    static void calculatePriceHellio(){
        Quote quote = [SELECT Id From Quote WHERE Fournisseur__c = 'Hellio'];
        List<QuoteLineItem> listQLI = new List<QuoteLineItem>();
        
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        for (QuoteLineItem qli : [SELECT Id, DebutDeFourniture__c, Nouvelle_Echeance__c, Puissance_souscrite__c,
                   TECH_Segment__c, TECH_FTA__c, TECH_Tarif__c, TECH_CalendrierFournisseur__c,
                   CAR_New__c,CARGaz__c, PDE__r.X12_mois_consommation_SGE__c
            FROM QuoteLineItem
            WHERE QuoteId = :quote.Id
              AND TECH_Segment__c IN ('C4', 'C2')]) {
            qli.CAR_New__c = 55;
            qli.Puissance_souscrite__c = 12;
            qli.DebutDeFourniture__c = Date.today();
            qli.Nouvelle_Echeance__c = Date.today().addYears(1);

            listQLI.add(qli);
        }

        input.recordId = quote.Id;
        input.fournisseur = 'Hellio';
        input.dureeOffre = '12';
        input.margeMwh = 5;

        inputs.add(input);

        update listQLI;        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest();
    }

    @IsTest
    static void caculatePriceError(){
        
        Quote quote = [SELECT Id From Quote LIMIT 1];
        List<AP021_GrilleFournisseur.FlowInput> inputs = new List<AP021_GrilleFournisseur.FlowInput>();
        AP021_GrilleFournisseur.FlowInput input = new AP021_GrilleFournisseur.FlowInput();

        input.recordId = quote.Id;
        input.fournisseur = 'Error';
        input.dureeOffre = '12';

        inputs.add(input);
        
        Test.startTest();
        AP021_GrilleFournisseur.GET_Prix(inputs);
        Test.stopTest(); 
    }
}