force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_voie__c.field-meta.xml
<CustomField>
    <fullName>Numero_voie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Endesa_API__mdt/Endesa_API__mdt.object-meta.xml
<CustomObject>
    <description>Contient les infos permettant la connexion à l&apos;API Endesa</description>
    <label>Endesa API</label>
    <pluralLabel>Endesa APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Endesa_API__mdt/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <label>token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endesa_API__mdt/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_num_compteur__c.field-meta.xml
<CustomField>
    <fullName>TECH_num_compteur__c</fullName>
    <formula>IF( NOT(ISBLANK(PCE_Refonte__c)) , PCE_Refonte__c, ReferencePointEnergie_Refonte__c)</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Date_Validite_Offre__c.field-meta.xml
<CustomField>
    <fullName>Date_Validite_Offre__c</fullName>
    <label>Date de validité de l&apos;offre</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Maximum_date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Maximum_date_de_fin__c</fullName>
    <label>Maximum date de fin</label>
    <summarizedField>QuoteLineItem.Nouvelle_Echeance__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Minimum_date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Minimum_date_de_debut__c</fullName>
    <label>Minimum date de début</label>
    <summarizedField>QuoteLineItem.DebutDeFourniture__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/url_offre_endesa__c.field-meta.xml
<CustomField>
    <fullName>url_offre_endesa__c</fullName>
    <description>Lien vers l&apos;offre Endesa</description>
    <label>Lien offre Endesa</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/AbonnementMois__c.field-meta.xml
<CustomField>
    <fullName>AbonnementMois__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Abonnement (€/mois)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CeeMwh__c.field-meta.xml
<CustomField>
    <fullName>CeeMwh__c</fullName>
    <defaultValue>0.000</defaultValue>
    <label>CEE (en €/MWh)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CTA__c.field-meta.xml
<CustomField>
    <fullName>CTA__c</fullName>
    <label>CTA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DebutDeFourniture__c.field-meta.xml
<CustomField>
    <fullName>DebutDeFourniture__c</fullName>
    <label>Début de fourniture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Opportunit__c.field-meta.xml
<CustomField>
    <fullName>Opportunit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>l_ments_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PrixMolecule__c.field-meta.xml
<CustomField>
    <fullName>PrixMolecule__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prix molécule (€/MWH)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AP014_APIEndesa.cls
global with sharing class AP014_APIEndesa {
    @invocableMethod(callout=true label='GET prix gaz Endesa')
    public static List<FlowOutput> GET_PrixGaz(List<FlowInput> params){
        Map<String,Object> mapJSONBody = new Map<String,Object>();
        Endesa_API__mdt endesaAPI;
        String token;
        String url;
        FlowInput input = params.get(0);
        FlowOutput output  = new FlowOutput();
        HttpResponse res;
        Boolean isCopro = isCopro(input.acc.Id);
        Boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        Account acc = [ SELECT  Id,
                                Code_Postal__c,
                                Name,
                                Numero_voie__c,
                                Siret__c,
                                Syndic__c,
                                Syndic__r.Name,
                                Voie__c,
                                Ville__c
                        FROM Account
                        WHERE Id =: input.acc.Id
                       ];                 
        Quote quote = [ SELECT  Id,
                                Maximum_date_de_fin__c,
                                Minimum_date_de_debut__c,
                                Opportunity.Demande_Cotation__c,
                                Opportunity.Demande_Cotation__r.signataire__r.LastName,
                                Opportunity.Demande_Cotation__r.signataire__r.FirstName,
                                Opportunity.Demande_Cotation__r.signataire__r.Salutation,
                                Opportunity.Demande_Cotation__r.signataire__r.Phone,
                                Opportunity.Demande_Cotation__r.signataire__r.Email
                        FROM Quote
                        WHERE Id =: input.recordId
                        ];
        
        String siret_siren = acc.Siret__c;
        if(Test.isRunningTest()){
            endesaAPI = new Endesa_API__mdt();
            endesaAPI.url__c = 'xxx';
            endesaAPI.token__c =  'xxx';
        }
        else{
            if(runningInASandbox){
                endesaAPI = Endesa_API__mdt.getInstance('Preprod');  
            }
            else{
                endesaAPI = Endesa_API__mdt.getInstance('Prod');  
            }
        }
        token = endesaAPI.token__c;
        url = endesaAPI.url__c;

        String type_prospect = isCopro ? 'Copropriete' : 'Entreprise';
        String date_debut = String.valueOf(quote.Minimum_date_de_debut__c.format());
        String date_fin = String.valueOf(quote.Maximum_date_de_fin__c.format());
        String type_offre = input.type_offre;
        String date_fin_validite = String.valueOf(Date.valueOf(input.duree_offre).format());
        List<WrapSitesAPIEndesa> sites = input.listSites;

        //Information Générales
        mapJSONBody.put('siret_siren',siret_siren);
        mapJSONBody.put('token',token);
        mapJSONBody.put('type_offre',type_offre);
        mapJSONBody.put('type_prospect',type_prospect);        
        mapJSONBody.put('type_paiement',input.type_paiement);        
        mapJSONBody.put('date_debut',date_debut);
        mapJSONBody.put('date_fin',date_fin);
        mapJSONBody.put('date_fin_validite',date_fin_validite);

        Map<String,String> entite_principale = new Map<String,String>();
        if(isCopro){
            //Information Entitée principale
            entite_principale.put('contact_commercial_titre', convertSalutation(quote.Opportunity.Demande_Cotation__r.Signataire__r.Salutation));
            entite_principale.put('contact_commercial_nom', quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName );
            entite_principale.put('contact_commercial_prenom', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName );
            entite_principale.put('contact_commercial_email', quote.Opportunity.Demande_Cotation__r.Signataire__r.Email );
            entite_principale.put('contact_commercial_phone', quote.Opportunity.Demande_Cotation__r.Signataire__r.Phone.deleteWhitespace() );
            entite_principale.put('representant_legal', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName + ' '+ quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName);
            entite_principale.put('forme_sociale','[9110] Syndicat de copropriété');
            entite_principale.put('secteur_activite','Tertiaire');
            entite_principale.put('raison_sociale',acc.Syndic__r.Name);

            //Information Entitée secondaire
            Map<String,String> entite_secondaire = new Map<String,String>();
            entite_secondaire.put('contact_commercial_titre', convertSalutation(quote.Opportunity.Demande_Cotation__r.Signataire__r.Salutation));
            entite_secondaire.put('contact_commercial_nom', quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName );
            entite_secondaire.put('contact_commercial_prenom', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName );
            entite_secondaire.put('contact_commercial_email', quote.Opportunity.Demande_Cotation__r.Signataire__r.Email );
            entite_secondaire.put('contact_commercial_phone', quote.Opportunity.Demande_Cotation__r.Signataire__r.Phone.deleteWhitespace() );
            entite_secondaire.put('representant_legal', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName + ' '+ quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName);
            entite_secondaire.put('adresse',acc.Numero_voie__c + ' '+ acc.Voie__c );
            entite_secondaire.put('ville',acc.Ville__c );
            entite_secondaire.put('code_postal',acc.Code_Postal__c );
            entite_secondaire.put('forme_sociale','[9110] Syndicat de copropriété');
            entite_secondaire.put('secteur_activite','Tertiaire');
            entite_secondaire.put('raison_sociale',acc.Name);

            mapJSONBody.put('entite_principale',entite_principale);
            mapJSONBody.put('entite_secondaire',entite_secondaire);
        }
        else{
            //Information Entitée principale
            entite_principale.put('contact_commercial_titre', convertSalutation(quote.Opportunity.Demande_Cotation__r.Signataire__r.Salutation));
            entite_principale.put('contact_commercial_nom', quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName );
            entite_principale.put('contact_commercial_prenom', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName );
            entite_principale.put('contact_commercial_email', quote.Opportunity.Demande_Cotation__r.Signataire__r.Email );
            entite_principale.put('contact_commercial_phone', quote.Opportunity.Demande_Cotation__r.Signataire__r.Phone.deleteWhitespace() );
            entite_principale.put('representant_legal', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName + ' ' + quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName);
            entite_principale.put('secteur_activite','Tertiaire');
            mapJSONBody.put('entite_principale',entite_principale);
        }

        //Information Sites
        mapJSONBody.put('sites',sites);
        String JSONBody =  JSON.serialize(mapJSONBody);

        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setTimeout(120000);
        req.setBody(JSONBody);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept','application/json');
        System.debug('JSONBody '+JSONBody);

        // Send the request, and return a response
        try {
            res = h.send(req);
        } catch (Exception e) {
            System.debug('erreur '+e.getMessage());
            output.StatusCode = 400;
            output.response = 'l\'API n\'a pas répondu à temps\n'+e.getMessage();
        }
        if(res.getStatusCode() == 200) {
            System.debug('200');
            WrapResponse200 body = (WrapResponse200) JSON.deserialize(res.getBody(), WrapResponse200.class);
            System.debug('body '+body);
            String updateErrorMessage = AP014_APIEndesa.updateRecords(body,input.recordId,sites,input.type_offre,Date.valueOf(input.duree_offre)); 
            if(updateErrorMessage == null){
                output.StatusCode = 200;
                output.response  = 'Les prix ont bien été mis à jour'; 
            }
            else{
                output.StatusCode = 400;
                output.response = 'Il y a eu un soucis interne lors de la mise à jour des prix : ' + updateErrorMessage;
            }
        }
        else{
            WrapResponse400 response400 = new WrapResponse400();
            System.Debug('response 400 res.getBody() '+res.getBody());
            Map<String,Object> body = (Map<String,Object>) JSON.deserializeUntyped(res.getBody());
            String fieldError =  new list<String>(body.KeySet()).get(0);
            System.Debug('response 400 body.get(fieldError) '+body.get(fieldError));
            try {
                response400 = (WrapResponse400) JSON.deserialize(JSON.serialize(body.get(fieldError)),WrapResponse400.class);
                response400.fieldError =  fieldError;
                output.StatusCode = 400;
                if(response400.errors != null && response400.fieldError != null){
                    output.response = 'L\'appel réseau n\'a pas abouti'+
                    '\nCode d\'erreur : '+response400.errors.get(0).code_error + 
                    '\nChamps concerné : '+ response400.fieldError + 
                    '\nMessage d\'erreur de Endesa : '+response400.errors.get(0).message;
                }
                else{
                    output.response = JSON.serialize(body.get(fieldError));
                }
            } catch (Exception e) {
                output.response = JSON.serialize(body.get(fieldError));
            }
            
            
        }
        List<FlowOutput> outputs = new List<FlowOutput>();
        outputs.add(output);
        return outputs;
    }
    
    private static Boolean isCopro(Id accId){
        Id syndicId = [SELECT Syndic__c FROM Account WHERE Id =:accId].Syndic__c;
        return syndicId != null;
    }

    private static String convertSalutation(String Salutation){
        if(Salutation == 'Monsieur' || Salutation == 'M'){
            return 'mr';
        }
        else if (Salutation == 'Madame' || Salutation == 'MME'){
            return 'mme';
        }
        return '';
    }

    private static String updateRecords(WrapResponse200 response, Id quoteId,list<WrapSitesAPIEndesa> listSitesWithCommission,String typeOffre, Date dateFinValidite){
        Map<String,QuoteLineItem> mapPDENameQLI = new Map<String,QuoteLineItem>();
        Map<String,WrapSitesAPIEndesa> mapPDENameCommission = new Map<String,WrapSitesAPIEndesa>();
        List<PDE__c> listPDEToUpdate = new List<PDE__c>();
        List<QuoteLineItem> listQLIToUpdate = new List<QuoteLineItem>();
        Quote quote = [SELECT Id,OpportunityId FROM Quote WHERE Id=:quoteId];
        List<QuoteLineItem> listQLIEndesa = new List<QuoteLineItem>([SELECT Id, PDE__c,pde__r.TECH_num_compteur__c,pde__r.CARGaz__c,DureeEngagement__c,DebutDeFourniture__c,Nouvelle_Echeance__c FROM QuoteLineItem WHERE QuoteId =:quoteId]);
        List<QuoteLineItem> listQLIAutreFournisseurs = new List<QuoteLineItem>([SELECT Id, PDE__c,pde__r.TECH_num_compteur__c FROM QuoteLineItem WHERE QuoteId <>:quoteId AND Opportunit__c=:quote.OpportunityId]);
        quote.url_offre_endesa__c = 'https://ppc-endesa.fr/offre/'+response.numero_offre.right(6);

        // Ajout DateTime fin de l'offre à 17h00
        Time targetTime = Time.newInstance(17, 0, 0, 0);
        DateTime finalDateTime = DateTime.newInstance(dateFinValidite, targetTime);
        quote.Date_Validite_Offre__c = finalDateTime;

        for(QuoteLineItem qli : listQLIEndesa){
            mapPDENameQLI.put(qli.pde__r.TECH_num_compteur__c,qli);
        }

        for(WrapSitesAPIEndesa site : listSitesWithCommission){
            mapPDENameCommission.put(site.pce,site);
        }

        for(String key : response.sites.keySet()){
            QuoteLineItem qli = mapPDENameQLI.get(key);
            if (typeOffre == 'B1' || typeOffre == 'B2'){
                qli.AbonnementMois__c = Decimal.valueOf(response.sites.get(key).atrd_fix/12).setScale(2);
            } else {
                qli.AbonnementMois__c = Decimal.valueOf((response.sites.get(key).atrd_fix + response.sites.get(key).stockage + response.sites.get(key).atrt) / 12).setScale(2);
            }
            qli.PrixMolecule__c = Decimal.valueOf(response.sites.get(key).prix_molecule).setScale(2);
            qli.CeeMwh__c  = Decimal.valueOf(response.sites.get(key).cee).setScale(2);
            qli.CTA__c = Decimal.valueOf(response.sites.get(key).cta/12).setScale(2);
            qli.CARGaz__c = Decimal.valueOf(response.sites.get(key).car).setScale(2);
            if(qli.DureeEngagement__c == null){
                qli.DureeEngagement__c = qli.DebutDeFourniture__c.monthsBetween(qli.Nouvelle_Echeance__c);
                qli.UnitPrice = Decimal.valueOf(mapPDENameCommission.get(qli.PDE__r.TECH_num_compteur__c).commission * (response.sites.get(key).car / 12) * (qli.DebutDeFourniture__c.monthsBetween(qli.Nouvelle_Echeance__c) + 1)).setScale(2);
            }
            else{
                qli.UnitPrice = (mapPDENameCommission.get(qli.PDE__r.TECH_num_compteur__c).commission * (response.sites.get(key).car / 12) * (qli.DureeEngagement__c + 1)).setScale(2) ;
            }

            listQLIToUpdate.add(qli);
            listPDEToUpdate.add(new PDE__c(Id = qli.PDE__c, CARGaz__c = Decimal.valueOf(response.sites.get(key).car).setScale(2)));
        }
        
        for(QuoteLineItem qli: listQLIAutreFournisseurs){
            qli.CARGaz__c = Decimal.valueOf(response.sites.get(qli.PDE__r.TECH_num_compteur__c).car).setScale(2);
            listQLIToUpdate.add(qli);
        }

        try {
            update listPDEToUpdate;
            update quote;
            update listQLIToUpdate;
            return null;
        } catch (Exception e) {
            System.debug('Exception '+ e);
            return e.getMessage();
        }
    }

    public class FlowInput {
        @invocableVariable public Quote quote;
        @invocableVariable public Account acc;
        @invocableVariable public Opportunity opp;
        @invocableVariable public List<OpportunityPDERelation__c> listOPR;
        @invocableVariable public List<WrapSitesAPIEndesa> listSites;
        @invocableVariable public String type_offre;
        @invocableVariable public String duree_offre;
        @invocableVariable public Integer type_paiement;
        @invocableVariable public Id recordId;
    }

    public class FlowOutput {
        @InvocableVariable public Integer StatusCode;
        @InvocableVariable public String response;
    }

    private class WrapResponse200 {
        String numero_offre;
        String date_fin_validite;
        Map<String,WrapSiteResponse> sites;
    }

    private class WrapResponse400{
        String fieldError;
        String value;
        List<WrapError> errors;
    }

    private class WrapError{
        String message;
        String code_error;
    }

    private class WrapSiteResponse{
        Double atrd_fix;
        Double atrd_variable;
        Double atrt;
        Double car;
        Double cee;
        Double cta;
        Double prix_molecule;
        Double stockage;
    }
}