force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Numero_voie__c.field-meta.xml
<CustomField>
    <fullName>Numero_voie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/classes/ChargementEnMasseCoproController.cls
public with sharing class ChargementEnMasseCoproController {
  public class FieldMissingException extends Exception {
  }

  @AuraEnabled
  public static void insertCopro(String csvHeader, List<String> csvFileLines, String recordId) {
    //Recup les champs prérempli
    String[] headers = csvHeader.split(';');
    List<Account> listCopro = new List<Account>();
    Integer indexNomCopro = headers.indexOf('NOM DE LA COPROPRIETE');
    Integer indexSiren = headers.indexOf('SIREN');
    Integer indexSiret = headers.indexOf('SIRET');
    Integer indexNumeroVoie = headers.indexOf('NUMERO VOIE');
    Integer indexVoie = headers.indexOf('VOIE');
    Integer indexCodePostal = headers.indexOf('CODE POSTAL');
    Integer indexCommune = headers.indexOf('COMMUNE');
    Integer indexIdentifiantDuContact = headers.indexOf('IDENTIFIANT DU CONTACT');
    List<AccountContactRelation> listACRToInsert = new List<AccountContactRelation>();
    Boolean asap;
    String recordIdCopro = [
      SELECT Id
      FROM RecordType
      WHERE DeveloperName = 'Copropriete'
      LIMIT 1
    ]
    .Id;
    try {
      for (Integer i = 0; i < csvFileLines.size(); i++) {
        String[] csvRecordData = csvFileLines[i].split(';');
        if (
          String.isBlank(csvRecordData[indexNomCopro]) ||
          String.isBlank(csvRecordData[indexSiren]) ||
          String.isBlank(csvRecordData[indexSiret]) ||
          String.isBlank(csvRecordData[indexNumeroVoie]) ||
          String.isBlank(csvRecordData[indexVoie]) ||
          String.isBlank(csvRecordData[indexCodePostal]) ||
          String.isBlank(csvRecordData[indexCommune])
        ) {
          throw new FieldMissingException(
            'Attention, tous les champs sont obligatoires (Hors IDENTIFIANT DU CONTACT).'
          );
        }
        Account copro = new Account();
        copro.Name = csvRecordData[indexNomCopro];
        copro.Siret__c = csvRecordData[indexSiret];
        copro.Siren__c = csvRecordData[indexSiren];
        copro.Numero_voie__c = csvRecordData[indexNumeroVoie];
        copro.voie__c = csvRecordData[indexVoie];
        copro.Code_Postal__c = csvRecordData[indexCodePostal];
        copro.Ville__c = csvRecordData[indexCommune];
        copro.Syndic__c = recordId;
        copro.RecordTypeId = recordIdCopro;
        listCopro.add(copro);
      }
    } catch (Exception e) {
      System.debug('Erreur '+ e.getMessage() + 'ligne '+e.getLineNumber());
      throw new AuraHandledException('Attention, tous les champs sont obligatoires (Hors IDENTIFIANT DU CONTACT).');
    }
    try{
      insert listCopro;
      for (Integer i = 0; i < csvFileLines.size(); i++) {
        String[] csvRecordData = csvFileLines[i].split(';');
        if (csvRecordData.size() == headers.size()) {
          AccountContactRelation acr = new AccountContactRelation();
          acr.AccountId = listCopro.get(i).Id;
          acr.contactId = csvRecordData[indexIdentifiantDuContact];
          acr.roles = 'Gestionnaire de la copropriété';
          listACRToInsert.add(acr);
        }
      }
      insert listACRToInsert;
    }
    catch(Exception dmlException){
        throw new AuraHandledException('Erreur lors de l\'enregistrement '+dmlException.getMessage());
      }
  }

  @AuraEnabled
  public static List<Account> retrieveCopros(String recordId) {
    System.debug('retrieveCopros Id received '+recordId);
    List<Account> listAccount = [
      SELECT Id, Name
      FROM Account
      WHERE RecordType.DeveloperName = 'Copropriete' AND Syndic__c = :recordId
    ];
    System.debug('listAccount '+listAccount);
    return listAccount;
  }
}