force-app/main/default/objects/Account/fields/Code_postal__c.field-meta.xml
<CustomField>
    <fullName>Code_postal__c</fullName>
    <label>Code postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Voie__c.field-meta.xml
<CustomField>
    <fullName>Voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Code_Postal__c.field-meta.xml
<CustomField>
    <fullName>Code_Postal__c</fullName>
    <label>Code Postal</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/FTA__c.field-meta.xml
<CustomField>
    <fullName>FTA__c</fullName>
    <description>ELEC</description>
    <label>FTA</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Segment__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>BT &lt;= 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - MU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - CU</fullName>
            </value>
            <value>
                <fullName>BT &gt; 36 kVA - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PF - LU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - CU</fullName>
            </value>
            <value>
                <fullName>HTA - PM - LU</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - CU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36Kva - MU 4 postes</fullName>
            </value>
            <value>
                <fullName>BT &lt;= 36 kVA - LU EP</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Nom_du_compte__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_compte__c</fullName>
    <formula>EntiteJuridique__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nom du compte</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/NumeroVoie__c.field-meta.xml
<CustomField>
    <fullName>NumeroVoie__c</fullName>
    <label>Numéro voie</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ReferencePointEnergie_Refonte__c.field-meta.xml
<CustomField>
    <fullName>ReferencePointEnergie_Refonte__c</fullName>
    <label>Référence point d&apos;énergie</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Siret_payeur__c.field-meta.xml
<CustomField>
    <fullName>Siret_payeur__c</fullName>
    <label>Siret payeur</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_CAR__c.field-meta.xml
<CustomField>
    <fullName>TECH_CAR__c</fullName>
    <formula>IF( NOT(ISBLANK(Consommation_Annuelle_de_R_f_rence_Elec__c)) , Consommation_Annuelle_de_R_f_rence_Elec__c, CARGaz__c)</formula>
    <label>CAR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Ville__c.field-meta.xml
<CustomField>
    <fullName>Ville__c</fullName>
    <label>Ville</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/voie__c.field-meta.xml
<CustomField>
    <fullName>voie__c</fullName>
    <label>Voie</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP019_GenerateDemandeGuichet_TEST.cls
@isTest
private class AP019_GenerateDemandeGuichet_TEST {
    
    @testSetup
    static void makeData() {

        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Contact contact = new Contact();
        contact.Title = 'Test Title';
        contact.LastName = 'Lastname';
        contact.Id = contact.Id;
        insert contact;

        // Demande de cotation
        Demande_Cotation__c ddc = new Demande_Cotation__c();
        ddc.Account__c = acc.Id;
        ddc.Signataire__c = contact.Id;
        ddc.Date_RDV_Client__c = Date.today();
        ddc.Charge_affaire__c = System.UserInfo.getUserId();
        ddc.Date_demande_cotation__c = Date.today();
        ddc.Statut__c = 'En attente de traitement';
        insert ddc;
        
        // ContentVersion 
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'a picture';
        contentVersion.PathOnClient = 'Pic.jpg';
        contentVersion.VersionData = Blob.valueOf('Test Content');
        contentVersion.IsMajorVersion = true;
        insert contentVersion;
    }

    @isTest
    static void createDemandeGuichet() {
        
        List<AP019_GenerateDemandeGuichet.FlowInputs> params = new List<AP019_GenerateDemandeGuichet.FlowInputs>();
        AP019_GenerateDemandeGuichet.FlowInputs inputs = new AP019_GenerateDemandeGuichet.FlowInputs();
        List<Id> contentDocumentIds = new List<Id>();

        for (ContentDocument cd : [SELECT Id FROM ContentDocument LIMIT 1]) {
            contentDocumentIds.add(cd.Id);
        }
        
        inputs.ContentDocumentIds = contentDocumentIds;
        inputs.DemandeCotation = [SELECT Id FROM Demande_Cotation__c LIMIT 1];
        inputs.DateRetourSouhaitee = Date.today();
        inputs.DureeFourniture = 'durée de fourniture maximale';
        inputs.DateDureeFourniture = Date.today();
        inputs.TypeDemande = 'demande de captation';
        inputs.TypeOffre = 'fixe';
        inputs.TypeEnergie = 'Elec';
        inputs.MargeSouhaitee = '20€';
        inputs.EmailFournisseur = 'test@test.fr';
        inputs.EmailCC1 = 'cc1@test.fr';
        inputs.EmailCC2 = 'cc2@test.fr';
        inputs.EmailCC3 = 'cc3@test.fr';
        inputs.EmailCC4 = 'cc4@test.fr';
        inputs.EmailCC5 = 'cc5@test.fr';
        inputs.SelectedPDEs = [SELECT Siret_payeur__c, ReferencePointEnergie_Refonte__c, TECH_CAR__c, PCE_Refonte__c, Nom_du_compte__c, Name, NumeroVoie__c, voie__c, Code_Postal__c, Ville__c, fournisseur__c, Segment__c, FTA__c, Puissance_souscrite__c, DateEcheance__c FROM PDE__c];

        params.add(inputs);

        Test.startTest();
        List<AP019_GenerateDemandeGuichet.FlowOutput> outputs = AP019_GenerateDemandeGuichet.createDemandeGuichet(params);
        Test.stopTest();

        Assert.isTrue(outputs[0].Success);
    }
}