force-app/main/default/objects/Account/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Code NAF</label>
    <referenceTo>CodeNAF__c</referenceTo>
    <relationshipLabel>Entités Juridiques</relationshipLabel>
    <relationshipName>EntitesJuridiques</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_last_credit_score__c.field-meta.xml
<CustomField>
    <fullName>TECH_last_credit_score__c</fullName>
    <label>Last credit score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Codes_NAF__mdt/Codes_NAF__mdt.object-meta.xml
<CustomObject>
    <description>cette custom Metadata contient les codeNaf  qui sont eligible par fournisseur</description>
    <label>Codes_NAF</label>
    <pluralLabel>Codes NAF</pluralLabel>
</CustomObject>

force-app/main/default/objects/Codes_NAF__mdt/fields/Code_NAF__c.field-meta.xml
<CustomField>
    <fullName>Code_NAF__c</fullName>
    <label>Code NAF</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Grille_Ekwateur__mdt/Grille_Ekwateur__mdt.object-meta.xml
<CustomObject>
    <label>Grille Ekwateur</label>
    <pluralLabel>Grilles Ekwateur</pluralLabel>
</CustomObject>

force-app/main/default/objects/Grille_Ekwateur__mdt/fields/Date_debut_max1__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_max1__c</fullName>
    <label>Date début maximale 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grille_Ekwateur__mdt/fields/Date_debut_max2__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_max2__c</fullName>
    <label>Date début maximale 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grille_Ekwateur__mdt/fields/Date_debut_max3__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_max3__c</fullName>
    <label>Date début maximale 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grille_Ekwateur__mdt/fields/Date_debut_min1__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_min1__c</fullName>
    <label>Date début minimal 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grille_Ekwateur__mdt/fields/Date_debut_min2__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_min2__c</fullName>
    <label>Date debut minimale 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Grille_Ekwateur__mdt/fields/Date_debut_min3__c.field-meta.xml
<CustomField>
    <fullName>Date_debut_min3__c</fullName>
    <label>Date debut minimale 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Consommation_Annuelle_de_R_f_rence_Elec__c.field-meta.xml
<CustomField>
    <fullName>Consommation_Annuelle_de_R_f_rence_Elec__c</fullName>
    <label>CAR Elec</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Entite_facturation__c.field-meta.xml
<CustomField>
    <fullName>Entite_facturation__c</fullName>
    <label>Entité de facturation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fournisseur__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENGIE E &amp; C</fullName>
            </value>
            <value>
                <fullName>ENGIE GC PRIVE</fullName>
            </value>
            <value>
                <fullName>ENGIE GC PUBLIC</fullName>
            </value>
            <value>
                <fullName>ENGIE PRO</fullName>
            </value>
            <value>
                <fullName>SEFE Energy</fullName>
            </value>
            <value>
                <fullName>SEFE INCUBATEUR</fullName>
            </value>
            <value>
                <fullName>PRIMEO ENERGIE PEF</fullName>
            </value>
            <value>
                <fullName>PRIMEO ENERGIE PEGC</fullName>
            </value>
            <value>
                <fullName>Endesa</fullName>
            </value>
            <value>
                <fullName>ENDESA GC</fullName>
            </value>
            <value>
                <fullName>TOTAL HORIZON</fullName>
            </value>
            <value>
                <fullName>TOTAL GC</fullName>
            </value>
            <value>
                <fullName>VATTENFALL BLEU PRO</fullName>
            </value>
            <value>
                <fullName>VATTENFALL GC</fullName>
            </value>
            <value>
                <fullName>OHM Grille</fullName>
            </value>
            <value>
                <fullName>OHM Mid Market</fullName>
            </value>
            <value>
                <fullName>OHM GC</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Paris</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Lyon</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Sud</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Sud-Ouest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/X12_mois_consommation_SGE__c.field-meta.xml
<CustomField>
    <fullName>X12_mois_consommation_SGE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>12 mois de consommation sur SGE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <customValue>
        <fullName>GEG</fullName>
    </customValue>
    <customValue>
        <fullName>Ilek</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP021_EligibilityChecker.cls
global with sharing class AP021_EligibilityChecker { 
    
    global class FlowInput {
        @invocableVariable public Id recordId;
    }

    global class FlowOutput {
        @InvocableVariable(label='Liste de résultats')
        public List<WrapFournisseursEligibleGrille> fournisseurs;

    }

    @InvocableMethod(callout=true label='Eligibilite fournisseurs')
    global static List<FlowOutput> checkEligibility(List<FlowInput> inputs) {
        
        List<WrapFournisseursEligibleGrille> results  = new List<WrapFournisseursEligibleGrille>();
        FlowOutput output = new FlowOutput();
        System.debug('Début de la méthode checkEligibility');
        Set<Id> recordIds = new Set<Id>();
        // Je recupere que l'id de l'opportunity
        for (FlowInput inpt : inputs) {
            if (inpt.recordId != null) {
                recordIds.add(inpt.recordId);
            }
        }
        List<OpportunityPDERelation__c> pdeRelations = [

        SELECT PDE__c, 
            PDE__r.EntiteJuridique__r.TECH_last_credit_score__c,
            PDE__r.X12_mois_consommation_SGE__c,
            PDE__r.Segment__c, 
            PDE__r.Tarif__c,
            PDE__r.Entite_facturation__c,
            PDE__r.EntiteJuridique__r.ELLISPHERE__Elli_code_ape08__c, 
            PDE__r.Fournisseur__c, 
            PDE__r.DateEcheance__c,
            PDE__r.Calendrier_fournisseur__c,
            PDE__r.Consommation_Annuelle_de_R_f_rence_Elec__c,
            PDE__r.CARGaz__c, 
            PDE__r.RecordType.Name
        FROM OpportunityPDERelation__c 
        WHERE Opportunity__c IN :recordIds
        ];

        System.debug('Nombre de PDE récupérées : ' + pdeRelations.size());

         Map<Id, OpportunityPDERelation__c> pdeMapById = new Map<Id, OpportunityPDERelation__c>();

        for (OpportunityPDERelation__c pde : pdeRelations) {
            // Clé = Id du PDE
            pdeMapById.put(pde.PDE__c, pde);
        }

        if (checkEligibiliteTotal(pdeMapById)) results.add(new WrapFournisseursEligibleGrille('TotalEnergies'));
        if (checkEligibiliteEkwateur(pdeMapById)) results.add(new WrapFournisseursEligibleGrille('Ekwateur'));
        if (checkEligibiliteVattenfall(pdeMapById)) results.add(new WrapFournisseursEligibleGrille('Vattenfall'));
        if (checkEligibiliteIlek(pdeMapById)) results.add(new WrapFournisseursEligibleGrille('Ilek'));
        if (checkEligibiliteGEG(pdeMapById)) results.add(new WrapFournisseursEligibleGrille('GEG'));
        if (checkEligibiliteEngiePro(pdeMapById)) results.add(new WrapFournisseursEligibleGrille('Engie'));
       
        output.fournisseurs = results;
        return new List<FlowOutput>{output};
    }

    // Méthodes d'éligibilité Forunisseur Total 
 public static Boolean checkEligibiliteTotal(Map<Id, OpportunityPDERelation__c> pdeMap) { 
    List<String> segmentsNonEligibles = new List<String>{'C2', 'C3', 'T3', 'T4'};
    
    for(Id pdeId : pdeMap.keySet()) {
        OpportunityPDERelation__c pde = pdeMap.get(pdeId);
        
        // Vérifie les conditions pour CETTE PDE
        Boolean isEligible = pde.PDE__r.EntiteJuridique__r.TECH_last_credit_score__c >= 3 && 
                            pde.PDE__r.Fournisseur__c != 'TotalEnergies' && 
                            !segmentsNonEligibles.contains(pde.PDE__r.Segment__c) && 
                            pde.PDE__r.DateEcheance__c <= Date.today().addMonths(12);
        
        // Si UNE SEULE PDE n'est pas éligible
        if(!isEligible) {
            System.debug('PDE ' + pdeId + ' non éligible pour Total → fournisseur non éligible');
            return false; 
        }
    }
        return true;
}

 public static Boolean checkEligibiliteEkwateur( Map<Id, OpportunityPDERelation__c> pdeMap) { 
    String labelCode = '';
    Boolean isEligible = false;
    Map<String, Grille_Ekwateur__mdt>  grilleEkwateur = Grille_Ekwateur__mdt.getAll();
    Grille_Ekwateur__mdt prixGrille = null; 

    List<String> segmentsEligibles = new List<String>{'C4', 'C5', 'T1', 'T2'};
    
    for(Id pdeId : pdeMap.keySet()) {

        OpportunityPDERelation__c pde = pdeMap.get(pdeId);

        // recuperation de la grille correspondante au segment
        for(String devName : grilleEkwateur.keySet()) {
            if (pde.PDE__r.Segment__c == 'C5' && devName.contains('C5')) {
                prixGrille = grilleEkwateur.get(devName);
                break;
            } else if (pde.PDE__r.Segment__c == 'C4' && devName.contains('C4')) {
                prixGrille = grilleEkwateur.get(devName);
                break;
            } else if (pde.PDE__r.RecordType.Name.contains('Gaz') && devName.contains('T1T2T3')) {  
                prixGrille = grilleEkwateur.get(devName);
                break;
            }
            }
            if (prixGrille == null) {
                //eligibilityMap.put(pdeId, false);
                continue; // Passe à la prochaine itération si aucune grille n'est trouvée
            }

        if((pde.PDE__r.DateEcheance__c.addDays(1) > prixGrille.Date_debut_min1__c && pde.PDE__r.DateEcheance__c.addDays(1) < prixGrille.Date_debut_max1__c) ||
        (pde.PDE__r.DateEcheance__c.addDays(1) > prixGrille.Date_debut_min2__c && pde.PDE__r.DateEcheance__c.addDays(1) < prixGrille.Date_debut_max2__c) ||
        (pde.PDE__r.DateEcheance__c.addDays(1) > prixGrille.Date_debut_min3__c && pde.PDE__r.DateEcheance__c.addDays(1) < prixGrille.Date_debut_max3__c)){
            
            isEligible = pde.PDE__r.EntiteJuridique__r.TECH_last_credit_score__c >= 5 && 
                                segmentsEligibles.contains(pde.PDE__r.Segment__c);
            
        }
        if (!isEligible) {
            System.debug('PDE ' + pdeId + ' non éligible pour Ekwateur → date d\'échéance non éligible');
            return false;
        }
            


    }
        return true;
 }

 public static Boolean checkEligibiliteVattenfall( Map<Id, OpportunityPDERelation__c> pdeMap) { 
    
    for(Id pdeId : pdeMap.keySet()) {
        OpportunityPDERelation__c pde = pdeMap.get(pdeId);
        
        // Conditions Vattenfall
        Boolean isEligible = pde.PDE__r.EntiteJuridique__r.TECH_last_credit_score__c >= 3 && 
                            pde.PDE__r.Segment__c == 'C5' &&
                            (
                                // Si fournisseur = Vattenfall
                                (pde.PDE__r.Fournisseur__c == 'Vattenfall' && 
                                pde.PDE__r.DateEcheance__c > Date.today().addMonths(4)&& pde.PDE__r.DateEcheance__c <= Date.today().addMonths(12)) ||
                                // Si fournisseur ≠ Vattenfall  
                                (pde.PDE__r.Fournisseur__c != 'Vattenfall' && 
                                pde.PDE__r.DateEcheance__c <= Date.today().addMonths(12))
                            );
        
        if(!isEligible) {
            System.debug('PDE ' + pdeId + ' non éligible pour Vattenfall → fournisseur non éligible');
            return false;       
        }
    
    }
    return true;
 }

public static Boolean checkEligibiliteIlek(Map<Id, OpportunityPDERelation__c> pdeMap) { 
    
    for(Id pdeId : pdeMap.keySet()) {
        OpportunityPDERelation__c pde = pdeMap.get(pdeId);
        
        // Conditions Ilek
        Boolean isEligible = pde.PDE__r.EntiteJuridique__r.TECH_last_credit_score__c >= 4 && 
                            pde.PDE__r.Segment__c == 'C5' &&  // C5 uniquement
                            pde.PDE__r.DateEcheance__c.addDays(1) <= Date.today().addMonths(6);
        
        if(!isEligible) {
            System.debug('PDE ' + pdeId + ' non éligible pour Ilek → fournisseur non éligible');
            return false;
    }
    }
    
    return true;
}

public static Boolean checkEligibiliteGEG(Map<Id, OpportunityPDERelation__c> pdeMap) { 

    
    for(Id pdeId : pdeMap.keySet()) {
        OpportunityPDERelation__c pde = pdeMap.get(pdeId);
        
        
        // Conditions GEG
        Boolean isEligible = pde.PDE__r.EntiteJuridique__r.TECH_last_credit_score__c >= 6 && 
                            (pde.PDE__r.Segment__c == 'C5' || pde.PDE__r.Segment__c == 'C4' || pde.PDE__r.Segment__c == 'C2') &&  // C5 ou C4 ou C2 uniquement
                            (pde.PDE__r.Consommation_Annuelle_de_R_f_rence_Elec__c > 30 ) && pde.PDE__r.X12_mois_consommation_SGE__c == true;
       
        if(!isEligible) {
            System.debug('PDE ' + pdeId + ' non éligible pour GEG → fournisseur non éligible');
            return false;
        }
    }
    
    return true;
}

public static Boolean checkEligibiliteEngiePro(Map<Id, OpportunityPDERelation__c> pdeMap) { 
    List<String> segmentsEligibles = new List<String>{'C4', 'C5', 'T1', 'T2'};

    Codes_NAF__mdt codeNaf = [SELECT Id, Code_NAF__c FROM Codes_NAF__mdt WHERE DeveloperName = 'EngiePro' LIMIT 1];


    
    for(Id pdeId : pdeMap.keySet()) {
        OpportunityPDERelation__c pde = pdeMap.get(pdeId);
        // Conditions Engie Pro
    

        if (codeNaf == null) {
            System.debug('Code NAF éligible pour Engie Pro : ');  
        return false;
        }
        System.debug('Code NAF éligible pour Engie Pro : ' + codeNaf.Code_NAF__c);
        System.debug('Code NAF de la PDE : ' + pde.PDE__r.EntiteJuridique__r.ELLISPHERE__Elli_code_ape08__c);
        System.debug('Segment de la PDE : ' + pde.PDE__r.Segment__c);
        System.debug('Tarif de la PDE : ' + pde.PDE__r.Tarif__c);
        if (codeNaf.Code_NAF__c.contains(pde.PDE__r.EntiteJuridique__r.ELLISPHERE__Elli_code_ape08__c)) {
            // Code NAF  éligible
            Boolean isEligible = (segmentsEligibles.contains(pde.PDE__r.Segment__c) || segmentsEligibles.contains(pde.PDE__r.Tarif__c)) && pde.PDE__r.Entite_facturation__c != 'ENGIE PRO' &&
                                (pde.PDE__r.DateEcheance__c >= Date.today().addDays(5) && pde.PDE__r.DateEcheance__c <= Date.today().addMonths(12));
            if (!isEligible) {
                System.debug('PDE ' + pdeId + ' non éligible pour Engie Pro → fournisseur non éligible');
                return false;  
            }
  
                                
        }else {
            System.debug('PDE ' + pdeId + ' non éligible pour Engie Pro → code NAF non éligible');
            return false;
        }
    }
    return true;
}

}