force-app/main/default/objects/Account/fields/Convention__c.field-meta.xml
<CustomField>
    <fullName>Convention__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Convention</label>
    <referenceTo>Convention__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/Appel_facturation__c.object-meta.xml
<CustomObject>
    <label>Appel à facturation</label>
    <nameField>
        <label>Nom de Appel à facturation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appels à facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_facturation__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <label>Contrat</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Appels à facturation</relationshipLabel>
    <relationshipName>Appels_facturation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Mois_facturation_concerne__c.field-meta.xml
<CustomField>
    <fullName>Mois_facturation_concerne__c</fullName>
    <label>Mois de facturation concerné</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Paye__c.field-meta.xml
<CustomField>
    <fullName>Paye__c</fullName>
    <label>Payé</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADE</fullName>
            </value>
            <value>
                <fullName>PEPS</fullName>
            </value>
            <value>
                <fullName>PWE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de validation ADV</fullName>
                <default>true</default>
                <label>En attente de validation ADV</label>
            </value>
            <value>
                <fullName>OK pour facturation</fullName>
            </value>
            <value>
                <fullName>Appel à facturation émis</fullName>
            </value>
            <value>
                <fullName>En attente de paiement</fullName>
                <isActive>false</isActive>
                <label>En attente de paiement</label>
            </value>
            <value>
                <fullName>Payé</fullName>
                <isActive>false</isActive>
                <label>Payé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/recordTypes/Commission.recordType-meta.xml
<RecordType>
    <fullName>Commission</fullName>
    <active>true</active>
    <label>Commission</label>
</RecordType>

force-app/main/default/objects/Chiffre_affaire__c/Chiffre_affaire__c.object-meta.xml
<CustomObject>
    <label>Chiffre d&apos;affaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chiffre d&apos;affaire</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Chiffre_affaire__c/fields/Convention__c.field-meta.xml
<CustomField>
    <fullName>Convention__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Convention</label>
    <referenceTo>Convention__c</referenceTo>
    <relationshipLabel>Chiffre d&apos;affaire</relationshipLabel>
    <relationshipName>Chiffre_affaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chiffre_affaire__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <formula>IF(
    Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier4__c,
    Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier4__c,
    IF(
        Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier3__c,
        Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier3__c,
        IF(
            Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier2__c,
            Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier2__c,
            IF(
                Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier1__c,
                Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier1__c,
                0
            )
        )
    )
)</formula>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Appel_facturation__c.field-meta.xml
<CustomField>
    <fullName>Appel_facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appel à facturation</label>
    <referenceTo>Appel_facturation__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Chiffre_affaire__c.field-meta.xml
<CustomField>
    <fullName>Chiffre_affaire__c</fullName>
    <label>Chiffre d&apos;affaire</label>
    <referenceTo>Chiffre_affaire__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions_salarie</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Budget_HTVA_annee__c.field-meta.xml
<CustomField>
    <fullName>Budget_HTVA_annee__c</fullName>
    <label>Budget HTVA sur l&apos;année</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Budget_TTC_annee__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC_annee__c</fullName>
    <label>Budget TTC sur l&apos;année</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_ADE__c.field-meta.xml
<CustomField>
    <fullName>Commission_ADE__c</fullName>
    <label>Commission ADE €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_globale__c.field-meta.xml
<CustomField>
    <fullName>Commission_globale__c</fullName>
    <inlineHelpText>Commission globale générée par le contrat (Part ADE + Part Fournisseur)</inlineHelpText>
    <label>Commission globale €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_echeance__c</fullName>
    <label>Date d&apos;échéance</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FournisseurPicklist__c.field-meta.xml
<CustomField>
    <fullName>FournisseurPicklist__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrats</relationshipLabel>
    <relationshipName>Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Type_offre__c.field-meta.xml
<CustomField>
    <fullName>Type_offre__c</fullName>
    <label>Type d&apos;offre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>Offre clique</fullName>
            </value>
            <value>
                <fullName>Prestation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Convention__c/Convention__c.object-meta.xml
<CustomObject>
    <label>Convention</label>
    <nameField>
        <label>Convention Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conventions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convention__c/fields/Date_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_debut__c</fullName>
    <label>Date de début</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Date_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_fin__c</fullName>
    <label>Date de fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Remuneration_E_NmbrCompteur__c.field-meta.xml
<CustomField>
    <fullName>Remuneration_E_NmbrCompteur__c</fullName>
    <label>Rémunération €/Nombre de compteur</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Salarie__c.field-meta.xml
<CustomField>
    <fullName>Salarie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salarié</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Type_de_remuneration__c.field-meta.xml
<CustomField>
    <fullName>Type_de_remuneration__c</fullName>
    <label>Type de rémunération</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>€/Mwh par palier</fullName>
                <default>true</default>
                <label>€/Mwh par palier</label>
            </value>
            <value>
                <fullName>€/Compteur</fullName>
            </value>
            <value>
                <fullName>Pourcentage</fullName>
            </value>
            <value>
                <fullName>€/Mwh</fullName>
                <isActive>false</isActive>
                <label>€/Mwh</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/TECH_Responsable_legal_Id__c.field-meta.xml
<CustomField>
    <fullName>TECH_Responsable_legal_Id__c</fullName>
    <description>Responsable légal de la société du commercial (Permet l&apos;attribution du chiffre d&apos;affaire pour les incubés et les partenaires)</description>
    <label>TECH_Responsable_legal_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP025_CreateCommission_TEST.cls
/*
 * Test Class for AP025_CreateCommission
 */
@isTest
public class AP025_CreateCommission_TEST {


    @testSetup
    static void makeData(){
        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        List<User> listUserToInsert = new List<User>();
        
        Contract contract = new Contract();
        contract.Name = 'Test';
        contract.AccountId = acc.Id;
        contract.Opportunity__c = opp.Id;
        contract.FournisseurPicklist__c = 'Engie';
        contract.Type_offre__c = 'PRIX FIXE';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Date_echeance__c = Date.today();
        contract.Budget_TTC_annee__c = 1000;
        contract.Budget_HTVA_annee__c = 1000;
        contract.Commission_ADE__c = 1000;
        contract.Commission_globale__c = 1000;
        insert contract;

        Appel_facturation__c AF = new Appel_facturation__c();
        AF.Contrat__c = contract.Id;
        AF.Montant__c = 1000;
        AF.paye__c = 'ADE';
        AF.Statut__c = 'En attente de validation ADV';
        AF.Mois_facturation_concerne__c = Date.newInstance(2024,6,1);
        insert AF;

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Commercial' LIMIT 1];
        UserRole incubeRole = [SELECT Id FROM UserRole WHERE Name = 'Incubé' LIMIT 1];

        User commercial = new User(
            FirstName = 'John',
            LastName = 'Doe',
            Email = 'johndoe@example.com',
            Phone = '06 06 06 06 06',
            Username = 'johndoe' + DateTime.now().getTime() + '@example.com',
            Alias = 'jdoe',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = p.Id
        );
        insert commercial;

        User currentUser = new User(Id=UserInfo.getUserId());
        System.runAs(currentUser){

    
    
            User incube = new User(
                FirstName = 'Nicole',
                LastName = 'Doe',
                Email = 'johndoe2@example.com',
                Phone = '06 06 06 06 06',
                Username = 'johndoe2' + DateTime.now().getTime() + '@example.com',
                Alias = 'jdoe',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                ProfileId = p.Id,
                UserRoleId = incubeRole.Id,
                companyName = 'TEST NOM ENTREPRISE'
            );
    
            insert incube;
    
            incube.TECH_Responsable_legal_Id__c = commercial.Id;
            update incube;
            
        }

        Id recordTypeId = [SELECT Id FROM RecordType WHERE Name ='Salarié'].Id;

        Convention__c conventionSalarie = new Convention__c(
            Name = 'CONVENTION TEST',
            Date_debut__c = Date.today(),
            Date_fin__c = Date.today().addYears(1),
            Type_de_remuneration__c = '€/Compteur',
            Salarie__c = commercial.Id,
            Remuneration_E_NmbrCompteur__c = 5
        );

        insert conventionSalarie;
    }

    @isTest
    static void testCreateCommissionSalarie() {
        // Step 1: Setup test data


        List<Appel_facturation__c> results = AP023_CheckContratsFournisseurController.getAppelFacturation('Engie','06','2024');

        User commercial = [SELECT Id FROM USER WHERE Email = 'johndoe@example.com' LIMIT 1];
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        // Simulate commission data
        WrapCommission testCommission = new WrapCommission();
        testCommission.commercial = commercial.Id;
        testCommission.moisPaiement = Date.newInstance(2024, 12, 1);
        testCommission.contrat = contract.Id;
        testCommission.montant = 1000.00;
        testCommission.appelFacturation = results.get(0).Id;
        testCommission.prenomCommercial = 'John';
        testCommission.nomCommercial = 'Doe';

        List<WrapCommission> commissionList = new List<WrapCommission>{testCommission};
        AP025_CreateCommission.FlowInputs flowInput = new AP025_CreateCommission.FlowInputs();
        flowInput.listCommissions = commissionList;

        List<AP025_CreateCommission.FlowInputs> flowInputs = new List<AP025_CreateCommission.FlowInputs>{flowInput};

        // Step 2: Invoke the method
        Test.startTest();
        List<AP025_CreateCommission.FlowOutput> outputs = AP025_CreateCommission.createCommission(flowInputs);
        Test.stopTest();

        // Step 3: Verify results
        AP025_CreateCommission.FlowOutput output = outputs.get(0);
        System.assertEquals(true, output.commissionCreated, 'Le champs commissionCreated doit être à vrai');
        System.assertEquals('Les commissions ont bien été créées', output.message, 'La fonction doit retourner un message de succès');

        // Verify that the Chiffre_affaire__c and Commission__c records are inserted
        List<Chiffre_affaire__c> caList = [SELECT Id, Name FROM Chiffre_affaire__c];
        System.assertEquals(1, caList.size(), 'La fonction doit créer un seul chiffre d\'affaire');
        System.assertEquals('J.DOE - 12/2024', caList[0].Name, 'Le nom du chiffre d\'affaire n\'est pas le bon ');

        List<Commission__c> commissionListDB = [SELECT Id, Name FROM Commission__c];
        System.assertEquals(1, commissionListDB.size(), 'La fonction doit créer une seule commission');
        System.assertEquals('Engie ADE 12-2024 TestAccount0', commissionListDB[0].Name, 'Le nom de la commission n\'est pas bon');
    }

    @isTest
    static void testCreateCommissionIncube() {
        // Step 1: Setup test data
        List<Appel_facturation__c> results = AP023_CheckContratsFournisseurController.getAppelFacturation('Engie','06','2024');        
        User incube = [SELECT Id FROM USER WHERE Email = 'johndoe2@example.com' LIMIT 1];
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        // Simulate commission data
        WrapCommission testCommission = new WrapCommission();
        testCommission.commercial = incube.Id;
        testCommission.moisPaiement = Date.newInstance(2024, 12, 1);
        testCommission.contrat = contract.Id;
        testCommission.montant = 1000.00;
        testCommission.appelFacturation = results.get(0).Id;
        testCommission.prenomCommercial = 'John';
        testCommission.nomCommercial = 'Doe';

        List<WrapCommission> commissionList = new List<WrapCommission>{testCommission};
        AP025_CreateCommission.FlowInputs flowInput = new AP025_CreateCommission.FlowInputs();
        flowInput.listCommissions = commissionList;

        List<AP025_CreateCommission.FlowInputs> flowInputs = new List<AP025_CreateCommission.FlowInputs>{flowInput};

        // Step 2: Invoke the method
        Test.startTest();
        List<AP025_CreateCommission.FlowOutput> outputs = AP025_CreateCommission.createCommission(flowInputs);
        Test.stopTest();

        // Step 3: Verify results
        AP025_CreateCommission.FlowOutput output = outputs.get(0);
        System.assertEquals(true, output.commissionCreated, 'La fonction créé bien les commissions');
        System.assertEquals('Les commissions ont bien été créées', output.message, 'La fonction retourne un message de succès');

        // Verify that the Chiffre_affaire__c and Commission__c records are inserted
        List<Chiffre_affaire__c> caList = [SELECT Id, Name FROM Chiffre_affaire__c];
        System.assertEquals(1, caList.size(), 'Création d\'un seul chffre d\'affaire');
        System.assertEquals('TEST NOM ENTREPRISE - 12/2024', caList[0].Name, 'Chiffre affaire name should match');

        List<Commission__c> commissionListDB = [SELECT Id, Name FROM Commission__c];
        System.assertEquals(1, commissionListDB.size(), 'Chiffre d\'affaire créé');
        System.assertEquals('Engie ADE 12-2024 TestAccount0', commissionListDB[0].Name, 'Commission créé');
    }

    @isTest
    static void testCreateCommissionSalarieWithoutConvention(){
        // Step 1: Setup test data
        Convention__c[] conventionToDelete = [SELECT Id FROM Convention__c ]; 
        delete conventionToDelete;
        List<Appel_facturation__c> results = AP023_CheckContratsFournisseurController.getAppelFacturation('Engie','06','2024');        
        User incube = [SELECT Id FROM USER WHERE Email = 'johndoe2@example.com' LIMIT 1];
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        // Simulate commission data
        WrapCommission testCommission = new WrapCommission();
        testCommission.commercial = incube.Id;
        testCommission.moisPaiement = Date.newInstance(2024, 12, 1);
        testCommission.contrat = contract.Id;
        testCommission.montant = 1000.00;
        testCommission.appelFacturation = results.get(0).Id;
        testCommission.prenomCommercial = 'John';
        testCommission.nomCommercial = 'Doe';

        List<WrapCommission> commissionList = new List<WrapCommission>{testCommission};
        AP025_CreateCommission.FlowInputs flowInput = new AP025_CreateCommission.FlowInputs();
        flowInput.listCommissions = commissionList;

        List<AP025_CreateCommission.FlowInputs> flowInputs = new List<AP025_CreateCommission.FlowInputs>{flowInput};

        // Step 2: Invoke the method
        Test.startTest();
        List<AP025_CreateCommission.FlowOutput> outputs = AP025_CreateCommission.createCommission(flowInputs);
        Test.stopTest();
        // Step 3: Verify results
        AP025_CreateCommission.FlowOutput output = outputs.get(0);
        System.assertEquals(false, output.commissionCreated, 'Le champs commissionCreated doit être à faux');
        System.assertEquals('Convention inexistante ou inactive', output.message, 'La fonction doit retourner un message d\'erreur');

        // Verify that the Chiffre_affaire__c and Commission__c records are inserted
        List<Chiffre_affaire__c> caList = [SELECT Id, Name FROM Chiffre_affaire__c];
        System.assertEquals(0, caList.size(), 'La fonction ne doit pas créer de chiffre d\'affaire');

        List<Commission__c> commissionListDB = [SELECT Id, Name FROM Commission__c];
        System.assertEquals(0, commissionListDB.size(), 'La fonction ne doit pas créer de commission');
    }
}