force-app/main/default/objects/Account/fields/Convention__c.field-meta.xml
<CustomField>
    <fullName>Convention__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Convention</label>
    <referenceTo>Convention__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/Appel_facturation__c.object-meta.xml
<CustomObject>
    <label>Appel à facturation</label>
    <nameField>
        <label>Nom de Appel à facturation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appels à facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_facturation__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/recordTypes/Commission.recordType-meta.xml
<RecordType>
    <fullName>Commission</fullName>
    <active>true</active>
    <label>Commission</label>
</RecordType>

force-app/main/default/objects/Chiffre_affaire__c/Chiffre_affaire__c.object-meta.xml
<CustomObject>
    <label>Chiffre d&apos;affaire</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chiffre d&apos;affaire</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Chiffre_affaire__c/fields/Commercial__c.field-meta.xml
<CustomField>
    <fullName>Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Chiffre_affaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chiffre_affaire__c/fields/Convention__c.field-meta.xml
<CustomField>
    <fullName>Convention__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Convention</label>
    <referenceTo>Convention__c</referenceTo>
    <relationshipLabel>Chiffre d&apos;affaire</relationshipLabel>
    <relationshipName>Chiffre_affaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chiffre_affaire__c/fields/Mois_paiement__c.field-meta.xml
<CustomField>
    <fullName>Mois_paiement__c</fullName>
    <label>Mois de paiement</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Chiffre_affaire__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <formula>IF(
    Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier4__c,
    Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier4__c,
    IF(
        Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier3__c,
        Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier3__c,
        IF(
            Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier2__c,
            Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier2__c,
            IF(
                Somme_commissions__c &gt;= Convention__r.Montant_declenchement_palier1__c,
                Somme_commissions__c * Convention__r.Pourcentage_remuneration_palier1__c,
                0
            )
        )
    )
)</formula>
    <label>Montant</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Commission__c/Commission__c.object-meta.xml
<CustomObject>
    <label>Commission</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commission__c/fields/Appel_facturation__c.field-meta.xml
<CustomField>
    <fullName>Appel_facturation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appel à facturation</label>
    <referenceTo>Appel_facturation__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Chiffre_affaire__c.field-meta.xml
<CustomField>
    <fullName>Chiffre_affaire__c</fullName>
    <label>Chiffre d&apos;affaire</label>
    <referenceTo>Chiffre_affaire__c</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions_salarie</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Commercial__c.field-meta.xml
<CustomField>
    <fullName>Commercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Commissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Commissions</relationshipLabel>
    <relationshipName>Commissions_salarie</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Mois_paiement__c.field-meta.xml
<CustomField>
    <fullName>Mois_paiement__c</fullName>
    <label>Mois de paiement</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Commission__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Convention__c/Convention__c.object-meta.xml
<CustomObject>
    <label>Convention</label>
    <nameField>
        <label>Convention Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conventions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Convention__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <formula>IF(ISNULL(Date_fin__c) , false, TODAY() &gt; Date_fin__c)</formula>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Convention__c/fields/Salarie__c.field-meta.xml
<CustomField>
    <fullName>Salarie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salarié</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Conventions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Convention__c/recordTypes/Partenaires.recordType-meta.xml
<RecordType>
    <fullName>Partenaires</fullName>
    <active>true</active>
    <label>Partenaires</label>
</RecordType>

force-app/main/default/objects/User/fields/TECH_Responsable_legal_Id__c.field-meta.xml
<CustomField>
    <fullName>TECH_Responsable_legal_Id__c</fullName>
    <description>Responsable légal de la société du commercial (Permet l&apos;attribution du chiffre d&apos;affaire pour les incubés et les partenaires)</description>
    <label>TECH_Responsable_legal_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP025_CreateCommission.cls
public without sharing class AP025_CreateCommission {
  @InvocableMethod(label='Create commission')
  public static List<FlowOutput> createCommission(List<FlowInputs> flowInputs) {
    FlowInputs flowInput = flowInputs.get(0);
    Set<Id> setCommerciaux = new Set<Id>();
    Map<Id, Id> mapCommercialIdResponsableLegal = new Map<Id, Id>();
    String chiffreAffaireName;
    List<Chiffre_affaire__c> listChiffreAffaire;
    Chiffre_affaire__c chiffreAffaire;
    List<FlowOutput> listOutput = new List<FlowOutput>();
    FlowOutput output = new FlowOutput();
    Map<Id, User> mapCommerciaux;
    Id conventionId;

    for (WrapCommission commission : flowInput.listCommissions) {
      setCommerciaux.add(commission.commercial);
    }

    mapCommerciaux = new Map<Id, User>(
      [
        SELECT
          Id,
          CompanyName,
          Account.Name,
          UserRole.Name,
          Profile.Name,
          TECH_Responsable_legal_Id__c
        FROM User
        WHERE Id IN :setCommerciaux
      ]
    );

    for (WrapCommission commission : flowInput.listCommissions) {
      chiffreAffaireName = generateChiffreAffaireName(commission,mapCommerciaux.get(commission.commercial));
      listChiffreAffaire = [
        SELECT Id
        FROM Chiffre_Affaire__c
        WHERE Name = :chiffreAffaireName LIMIT 1
      ];
      if(listChiffreAffaire.isEmpty()){
        chiffreAffaire = null;
      }
      else{
        chiffreAffaire = listChiffreAffaire.get(0);
      }

      if (chiffreAffaire == null) {
        conventionId = checkConvention(commission, mapCommerciaux.get(commission.commercial));
        if (conventionId == null) {
          output.message = 'Convention inexistante ou inactive';
          output.commissionCreated = false;
          listOutput.add(output);
          return listOutput;
        } else {
          //Création du CA puis de la commission
          chiffreAffaire = new Chiffre_affaire__c(
            Name = chiffreAffaireName,
            Mois_paiement__c = generateMoisChiffreAffaire(commission),
            Commercial__c = commission.commercial,
            Convention__c = conventionId
          );
          if (mapCommerciaux.get(commission.commercial).UserRole.Name == 'Incubé' || mapCommerciaux.get(commission.commercial).Profile.Name == 'Utilisateur Partenaire Communauté') {
            chiffreAffaire.ownerId = mapCommerciaux.get(commission.commercial).TECH_Responsable_legal_Id__c;
          } else {
            chiffreAffaire.ownerId = mapCommerciaux.get(commission.commercial).Id;
          }
          try {
            insert chiffreAffaire;            
          } catch (DmlException e) {
            output.message = 'Le chiffre d\'affaire} n\'a pas pu être créé '+ e.getMessage();
            output.commissionCreated = false;
            listOutput.add(output);
            return listOutput;        
          }
        }
      }

      Commission__c commissionToInsert = new Commission__c(
        Name = commission.nom,
        Mois_paiement__c = generateMoisChiffreAffaire(commission),
        Chiffre_affaire__c = chiffreAffaire.Id,
        Commercial__c = commission.commercial,
        Contract__c = commission.contrat,
        Montant__c = commission.montant,
        Appel_facturation__c = commission.appelFacturation
      );
      try {
        insert commissionToInsert; 
      } catch (DmlException e) {
        output.message = 'Les commissions n\'ont pas pu être créées '+ e.getMessage();
        output.commissionCreated = false;
        listOutput.add(output);
        return listOutput;        
      }
    }
    output.message = 'Les commissions ont bien été créées';
    output.commissionCreated = true;
    listOutput.add(output);
    return listOutput;
  }

  private static Id checkConvention(WrapCommission commission, User commercial) {
    String conventionId = null;

      try {
        if (commercial.UserRole.Name == 'Incubé') {

         //On récupère la convention du responsable légal de l'incubé
          return [
            SELECT Id
            FROM Convention__c
            WHERE
              Salarie__c = :commercial.TECH_Responsable_legal_Id__c
              AND Inactive__c = FALSE
          ].Id;
        }
        else if (commercial.Profile.Name == 'Utilisateur Partenaire Communauté') {
          return [
            SELECT Convention__c
            FROM Account
            WHERE Id = :commercial.accountId AND Convention__r.Inactive__c = FALSE
          ].Convention__c;
        }
        else {
          return [
            SELECT Id
            FROM Convention__c
            WHERE Salarie__c = :commercial.Id AND Inactive__c = FALSE
          ].Id;
        }
      } catch (Exception e) {
        System.debug('Convention introuvable '+e.getMessage());
        return null;
      }    
  }

  private static String generateChiffreAffaireName(WrapCommission commission,User commercial) {
    if (commercial.UserRole.Name == 'Incubé') {
      return commercial.CompanyName.toUpperCase() + ' - ' + commission.moisPaiement.month() + '/' + commission.moisPaiement.year();
    } else if (commercial.Profile.Name == 'Utilisateur Partenaire Communauté') {
      return commercial.Account.Name.toUpperCase() + ' - ' + commission.moisPaiement.month() + '/' + commission.moisPaiement.year();
    } else {
      return commission.prenomCommercial.substring(0, 1).toUpperCase() + '.' + commission.nomCommercial.toUpperCase() + ' - ' + commission.moisPaiement.month() + '/' + commission.moisPaiement.year();
    }
  }

  private static Date generateMoisChiffreAffaire(WrapCommission commission) {
    Date moisPaiement = commission.moisPaiement;
    return Date.newInstance(moisPaiement.year(), moisPaiement.month(), 1);
  }

  
  public static void generateAllChiffreAffaire() {
    // Déclarez une map pour stocker les Chiffre_Affaire__c par nom
    Map<String, Chiffre_Affaire__c> mapNameCA = new Map<String, Chiffre_Affaire__c>();

    // Map pour relier les salariés et partenaires aux conventions
    Map<Id, Id> mapConventionSalarie = new Map<Id, Id>();
    Map<Id, Id> mapConventionPartenaire = new Map<Id, Id>();

    // Récupérer les conventions actives et remplir la map des salariés
    for (Convention__c conv : [SELECT Id, Salarie__c FROM Convention__c WHERE Inactive__c = false]) { 
        if (conv.Salarie__c != null) {
            mapConventionSalarie.put(conv.Salarie__c, conv.Id);
        }
    }

    // Récupérer les comptes associés à des conventions actives
    for (Account acc : [SELECT Id, Convention__c FROM Account WHERE Convention__r.Inactive__c = false]) {
        if (acc.Convention__c != null) {
            mapConventionPartenaire.put(acc.Id, acc.Convention__c);
        }
    }

    // Liste des commissions
    List<Commission__c> listCommission = [
        SELECT Id, Commercial__c, 
               Commercial__r.Profile.Name,
               Commercial__r.FirstName, 
               Commercial__r.LastName, 
               Commercial__r.UserRole.Name, 
               Commercial__r.TECH_Responsable_legal_Id__c, 
               Commercial__r.AccountId,
               Commercial__r.Account.Name,
               Commercial__r.CompanyName,
               Mois_paiement__c 
        FROM Commission__c
    ];

    // Traiter chaque commission
    for (Commission__c com : listCommission) {
        String CAName;
        Id conventionId;

        // Déterminer le nom et la convention en fonction du profil ou rôle utilisateur
        if (com.Commercial__r.UserRole.Name == 'Incubé') {
            CAName = com.Commercial__r.CompanyName.toUpperCase() + ' - ' 
                     + com.Mois_paiement__c.month() + '/' 
                     + com.Mois_paiement__c.year();
            conventionId = mapConventionSalarie.get(com.Commercial__c);
        } else if (com.Commercial__r.Profile.Name == 'Utilisateur Partenaire Communauté') {
            CAName = com.Commercial__r.Account.Name.toUpperCase() + ' - ' 
                     + com.Mois_paiement__c.month() + '/' 
                     + com.Mois_paiement__c.year();
            conventionId = mapConventionPartenaire.get(com.Commercial__r.AccountId);
        } else {
            CAName = com.Commercial__r.FirstName.substring(0, 1).toUpperCase() + '.' 
                     + com.Commercial__r.LastName.toUpperCase() + ' - ' 
                     + com.Mois_paiement__c.month() + '/' 
                     + com.Mois_paiement__c.year();
            conventionId = mapConventionSalarie.get(com.Commercial__c);
        }

        // Vérifier si le Chiffre d'Affaire existe déjà
        if (!mapNameCA.containsKey(CAName)) {
            Chiffre_Affaire__c CA = new Chiffre_Affaire__c(
                Name = CAName,
                Commercial__c = com.Commercial__c,
                Convention__c = conventionId,
                Mois_paiement__c = com.Mois_paiement__c
            );
            mapNameCA.put(CAName, CA);
        }
    }

    // Insérer les Chiffre_Affaire__c en base de données
    if (!mapNameCA.isEmpty()) {
      System.debug('mapNameCA.values().size() ' + mapNameCA.values().size());
        // insert mapNameCA.values();
    }
}



  public class FlowInputs {
    @invocableVariable public List<WrapCommission> listCommissions;
  }

  public class FlowOutput {
    @invocableVariable public Boolean commissionCreated;
    @InvocableVariable public String message;
  }
}