force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Adresse_de_consommation__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_consommation__c</fullName>
    <formula>NumeroVoie__c &amp;&quot; &quot;&amp; voie__c &amp;&quot; &quot;&amp; Code_Postal__c &amp;&quot; &quot;&amp; Ville__c</formula>
    <label>Adresse de consommation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_num_compteur__c.field-meta.xml
<CustomField>
    <fullName>TECH_num_compteur__c</fullName>
    <formula>IF( NOT(ISBLANK(PCE_Refonte__c)) , PCE_Refonte__c, ReferencePointEnergie_Refonte__c)</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_SelectedPDE__c.field-meta.xml
<CustomField>
    <fullName>TECH_SelectedPDE__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Champs technique permettant de selectionner le PDE lors du renouvellement d&apos;une ACD</description>
    <label>TECH_SelectedPDE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VFC009_RenouvellementACDController.cls
public with sharing class VFC009_RenouvellementACDController {
    public List<PDE__c> listPDE { get; private set; }
    public Contact signataire { get; private set; }
    public Account account { get; private set; }
    public String nomSignataire {
        get {
            return signataire != null ? signataire.FirstName + ' ' + signataire.LastName : '';
        }
    }

    public VFC009_RenouvellementACDController() {
        String signataireId = ApexPages.currentPage().getParameters().get('signataireId');
        String accountId = ApexPages.currentPage().getParameters().get('accountId');

        account = [
            SELECT Name, SIRET__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1];

        signataire = [
            SELECT FirstName, LastName, Salutation,Title
            FROM Contact
            WHERE Id = :signataireId
            LIMIT 1];

        listPDE = [
            SELECT TECH_num_compteur__c,Adresse_de_consommation__c
            FROM PDE__c
            WHERE TECH_SelectedPDE__c = true
            AND entiteJuridique__c = :accountId];
    }
}