force-app/main/default/objects/Account/fields/Siren__c.field-meta.xml
<CustomField>
    <fullName>Siren__c</fullName>
    <label>Siren</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Siret__c.field-meta.xml
<CustomField>
    <fullName>Siret__c</fullName>
    <label>Siret</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionPrixConstates__c.field-meta.xml
<CustomField>
    <fullName>SectionPrixConstates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Prix Constatés</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionPropositionRenouvellement__c.field-meta.xml
<CustomField>
    <fullName>SectionPropositionRenouvellement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Proposition de renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerHandler_Test.cls
@isTest
public with sharing class OpportunityTriggerHandler_Test {
  @isTest(SeeAllData=false)
  private static void structureTest() {
    Test.startTest();
    String triggerContext = String.valueOf(
      TriggerHandler.TriggerContext.BEFORE_INSERT
    );
    TriggerHandler.TriggerHandlerException handlerException = new TriggerHandler.TriggerHandlerException();
    OpportunityTriggerHandler handler = new OpportunityTriggerHandler();
    TriggerHandler.LoopCount count = new TriggerHandler.LoopCount();
    count = new TriggerHandler.LoopCount(2);
    count.increment();
    count.exceeded();
    count.getMax();
    count.setMax(3);
    handler.beforeInsert();
    handler.beforeUpdate();
    handler.beforeDelete();
    handler.afterInsert();
    handler.afterDelete();
    handler.afterUndelete();
    OpportunityTriggerHandler.resetBypass();
    handler.setMaxLoopCount(3);
    handler.clearMaxLoopCount();
    OpportunityTriggerHandler.isBypassed('OpportunityTriggerHandler');
    OpportunityTriggerHandler.clearAllBypasses();
    Test.stopTest();
  }

  @isTest(SeeAllData=false)
  private static void afterUpdate() {
    Pricebook2 standardPricebook = new Pricebook2(
      Id = Test.getStandardPricebookId(),
      IsActive = true
    );
    update standardPricebook;

    //Create Pricebook
    Pricebook2 pricebook = new Pricebook2(
      Name = 'AllianceDesEnergies',
      IsActive = true
    );
    insert pricebook;

    //Create Product
    Product2 productElec = new Product2(
      Name = 'ELEC',
      Family = '',
      IsActive = true
    );
    insert productElec;
    Product2 productGaz = new Product2(
      Name = 'GAZ',
      Family = '',
      IsActive = true
    );
    insert productGaz;

    //Create PricebookEntry
    PricebookEntry pbeElecStandard = new PricebookEntry(
      Pricebook2Id = standardPricebook.Id,
      Product2Id = productElec.Id,
      UnitPrice = 0,
      IsActive = true
    );
    insert pbeElecStandard;
    PricebookEntry pbeElec = new PricebookEntry(
      Pricebook2Id = pricebook.Id,
      Product2Id = productElec.Id,
      UnitPrice = 0,
      IsActive = true
    );
    insert pbeElec;

    PricebookEntry pbeGazStandard = new PricebookEntry(
      Pricebook2Id = standardPricebook.Id,
      Product2Id = productGaz.Id,
      UnitPrice = 0,
      IsActive = true
    );
    insert pbeGazStandard;
    PricebookEntry pbeGaz = new PricebookEntry(
      Pricebook2Id = pricebook.Id,
      Product2Id = productGaz.Id,
      UnitPrice = 0,
      IsActive = true
    );
    insert pbeGaz;

    Account account = new Account();
    account.Name = 'Name';
    account.Siren__c = '123456789';
    account.Siret__c = '12345678912345';
    insert account;

    Contact contact = new Contact();
    contact.AccountId = account.Id;
    contact.FirstName = 'FirstName';
    contact.LastName = 'LastName';
    contact.Email = 'email@activ7.com';
    insert contact;

    Opportunity opportunity = new Opportunity();
    opportunity.Name = 'Opportunity Name';
    opportunity.AccountId = account.Id;
    opportunity.StageName = 'Attente de validation';
    opportunity.CloseDate = Date.today().addDays(30);
    opportunity.TemplateCotation__c = 'C1/C2/C3/C4';
    insert opportunity;

    PDE__c pde = new PDE__c();
    pde.Name = 'PDE1';
    pde.EntiteJuridique__c = account.Id;
    pde.fournisseur__c = 'Engie';
    pde.DateEcheance__c = Date.today();
    insert pde;

    OpportunityPDERelation__c opr = new OpportunityPDERelation__c();
    opr.pde__c = pde.Id;
    opr.opportunity__c = Opportunity.Id;
    insert opr;

    opportunity.Liste_Fournisseurs__c = 'Axpo;Edenkia;EDF Entreprises';
    opportunity.SectionSituationActuelle__c = true;
    opportunity.SectionPrixConstates__c = true;
    opportunity.SectionPropositionRenouvellement__c = true;
    update opportunity;
  }
}