force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_Owner_Manger_Mail__c.field-meta.xml
<CustomField>
    <fullName>TECH_Owner_Manger_Mail__c</fullName>
    <formula>Owner.Manager.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manager Mail</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Canal_vente__c.field-meta.xml
<CustomField>
    <fullName>Canal_vente__c</fullName>
    <formula>TEXT(Owner:User.Canal_vente__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal de vente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Concurrence_identifiee__c.field-meta.xml
<CustomField>
    <fullName>Concurrence_identifiee__c</fullName>
    <label>Concurrence identifiée</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
            <value>
                <fullName>Ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Duree_offre__c.field-meta.xml
<CustomField>
    <fullName>Duree_offre__c</fullName>
    <label>Durée de l&apos;offre souhaitée</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 mois</fullName>
            </value>
            <value>
                <fullName>24 mois</fullName>
            </value>
            <value>
                <fullName>36 mois</fullName>
            </value>
            <value>
                <fullName>Durée max</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Infos_complementaires__c.field-meta.xml
<CustomField>
    <fullName>Infos_complementaires__c</fullName>
    <label>Infos complémentaires</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Marge_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Marge_souhaitee__c</fullName>
    <label>Marge souhaitée</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marge minimale</fullName>
            </value>
            <value>
                <fullName>Marge moyenne</fullName>
            </value>
            <value>
                <fullName>Marge maximale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Offre_Renouvellement__c.field-meta.xml
<CustomField>
    <fullName>Offre_Renouvellement__c</fullName>
    <label>Offre de renouvellement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Plus_1_Giga__c.field-meta.xml
<CustomField>
    <fullName>Plus_1_Giga__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plus 1 Giga</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Souhaite_offre_TURPE__c.field-meta.xml
<CustomField>
    <fullName>Souhaite_offre_TURPE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Souhaite offre TURPE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Specificite_offre__c.field-meta.xml
<CustomField>
    <fullName>Specificite_offre__c</fullName>
    <label>Spécificité de l&apos;offre</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/TECH_Owner_Manger_Mail__c.field-meta.xml
<CustomField>
    <fullName>TECH_Owner_Manger_Mail__c</fullName>
    <label>Manager Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP003_DemandeCotationFromFlow.cls
public class AP003_DemandeCotationFromFlow {

    @invocableMethod(label='Créer Demande de Cotation depuis Apex')
    public static List<FlowOutput> createDemandeCotation(List<FlowInputs> params) {
        List<String> listCanauxDeVenteCreationTask = new List<String>{'Vente terrain','Vente terrain Lyon'};

        FlowInputs param = params[0];
        FlowOutput output = new FlowOutput();
        List<FlowOutput> outputs = new List<FlowOutput>();
        List<User> managerList = [SELECT Email FROM User WHERE Id = :param.ManagerId];
        
        String managerEmail = '';
        if (!managerList.isEmpty()) {
            managerEmail = managerList[0].Email;
        }

        Demande_Cotation__c demandeCotation = new Demande_Cotation__c();
        if(param.Account.Name.length() > 80)    {
            demandeCotation.Name = param.Account.Name.substring(0, 80);
        }
        else {
            demandeCotation.Name = param.Account.Name;
        }
        
        demandeCotation.Account__c = param.Account.Id;
        demandeCotation.Date_RDV_Client__c = param.DateRDVClient;
        demandeCotation.Signataire__c = param.SignataireId;
        demandeCotation.Charge_affaire__c = param.ChargeAffaireId;
        demandeCotation.Infos_complementaires__c = param.InfosComplementaires;
        demandeCotation.Statut__c = 'En attente de traitement';
        demandeCotation.Date_demande_cotation__c = Datetime.now();
        demandeCotation.TECH_Owner_Manger_Mail__c = managerEmail;
        demandeCotation.Marge_souhaitee__c = param.MargeSouhaitee;
        demandeCotation.Duree_offre__c = param.DureeOffre;
        demandeCotation.Offre_Renouvellement__c = param.OffreRenouvellement;
        demandeCotation.Concurrence_identifiee__c = param.ConcurrenceIdentifiee;
        demandeCotation.Specificite_offre__c = param.SpecificiteOffre;
        demandeCotation.Plus_1_Giga__c = param.PlusDe1Giga == null ? false : param.PlusDe1Giga;
        demandeCotation.Souhaite_offre_TURPE__c = param.SouhaiteOffreTURPE == null ? false : param.SouhaiteOffreTURPE;

        Database.SaveResult sr = Database.insert(demandeCotation);

        if (sr.isSuccess()) {
            output.DMLSuccess = true;
            output.ErrorMessage = null;
            outputs.add(output);
        } else {
            output.DMLSuccess = false;
            output.ErrorMessage = sr.getErrors()[0].getMessage();
            outputs.add(output);
            return outputs;
        }

        Id runningFlowUserId = UserInfo.getUserId();
        String companyName = [SELECT CompanyName FROM User WHERE Id = :runningFlowUserId  LIMIT 1][0].CompanyName;
        Demande_Cotation__c insertedDemandeCotation = [SELECT Canal_vente__c FROM Demande_Cotation__c WHERE Id = :demandeCotation.Id LIMIT 1][0];
        if(companyName <> 'ADE'){ // Rendre cette partie dynamique plus tard
            User assistanteVI = [SELECT Id FROM User WHERE Name = 'Elisa Diaz' LIMIT 1]; // Rendre cette partie dynamique plus tard
            Task task = new Task();
            task.WhatId = demandeCotation.Id;
            task.Subject = 'Prélecture de la Demande de Cotation '+demandeCotation.Name+ ' du '+param.DateRDVClient;
            task.OwnerId = assistanteVI.Id;
            task.Priority = 'Haute';
            task.Status = 'Ouverte';
            task.ActivityDate = Date.today();
            insert task;
        }
        else if (listCanauxDeVenteCreationTask.contains(insertedDemandeCotation.Canal_Vente__c)) {
            Task task = new Task();
            task.WhatId = demandeCotation.Id;
            task.Subject = 'Prélecture de la Demande de Cotation '+demandeCotation.Name+ ' du '+param.DateRDVClient;
            task.OwnerId = param.chargeAffaireId;
            task.Priority = 'Haute';
            task.Status = 'Ouverte';
            task.ActivityDate = Date.today();
            insert task;
        }
        
        for (PDE__c pde : param.SelectedPDEs) {
            pde.Demande_Cotation__c = demandeCotation.Id;
        }
        
        Database.update(param.SelectedPDEs);

        return outputs;
    }

    public class FlowInputs {
        @invocableVariable public Account Account;
        @invocableVariable public DateTime DateRDVClient;
        @invocableVariable public String DateEcheance;
        @invocableVariable public String SignataireId;
        @invocableVariable public String ChargeAffaireId;
        @invocableVariable public String ManagerId;
        @invocableVariable public String InfosComplementaires;
        @invocableVariable public List<PDE__c> SelectedPDEs;
        @invocableVariable public String MargeSouhaitee;
        @invocableVariable public String DureeOffre;
        @invocableVariable public String OffreRenouvellement;
        @invocableVariable public String ConcurrenceIdentifiee;
        @invocableVariable public String SpecificiteOffre;
        @invocableVariable public Boolean plusde1Giga;
        @invocableVariable public Boolean souhaiteOffreTURPE;
    }
    
    public class FlowOutput {
        @InvocableVariable
        public Boolean DMLSuccess;
        @InvocableVariable
        public String ErrorMessage;
    }
}