force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/Appel_facturation__c.object-meta.xml
<CustomObject>
    <label>Appel à facturation</label>
    <nameField>
        <label>Nom de Appel à facturation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appels à facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_facturation__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <label>Contrat</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Appels à facturation</relationshipLabel>
    <relationshipName>Appels_facturation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Mois_facturation_concerne__c.field-meta.xml
<CustomField>
    <fullName>Mois_facturation_concerne__c</fullName>
    <label>Mois de facturation concerné</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Paye__c.field-meta.xml
<CustomField>
    <fullName>Paye__c</fullName>
    <label>Payé</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADE</fullName>
            </value>
            <value>
                <fullName>PEPS</fullName>
            </value>
            <value>
                <fullName>PWE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de validation ADV</fullName>
                <default>true</default>
                <label>En attente de validation ADV</label>
            </value>
            <value>
                <fullName>OK pour facturation</fullName>
            </value>
            <value>
                <fullName>Appel à facturation émis</fullName>
            </value>
            <value>
                <fullName>En attente de paiement</fullName>
                <isActive>false</isActive>
                <label>En attente de paiement</label>
            </value>
            <value>
                <fullName>Payé</fullName>
                <isActive>false</isActive>
                <label>Payé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Budget_HTVA_annee__c.field-meta.xml
<CustomField>
    <fullName>Budget_HTVA_annee__c</fullName>
    <label>Budget HTVA sur l&apos;année</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Budget_TTC_annee__c.field-meta.xml
<CustomField>
    <fullName>Budget_TTC_annee__c</fullName>
    <label>Budget TTC sur l&apos;année</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_ADE__c.field-meta.xml
<CustomField>
    <fullName>Commission_ADE__c</fullName>
    <label>Commission ADE €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_globale__c.field-meta.xml
<CustomField>
    <fullName>Commission_globale__c</fullName>
    <inlineHelpText>Commission globale générée par le contrat (Part ADE + Part Fournisseur)</inlineHelpText>
    <label>Commission globale €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Date_echeance__c.field-meta.xml
<CustomField>
    <fullName>Date_echeance__c</fullName>
    <label>Date d&apos;échéance</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/FournisseurPicklist__c.field-meta.xml
<CustomField>
    <fullName>FournisseurPicklist__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunité</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrats</relationshipLabel>
    <relationshipName>Contrats</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Type_offre__c.field-meta.xml
<CustomField>
    <fullName>Type_offre__c</fullName>
    <label>Type d&apos;offre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>Offre clique</fullName>
            </value>
            <value>
                <fullName>Prestation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP023_CheckContratsFournisseur_Test.cls
@isTest
private class AP023_CheckContratsFournisseur_Test {

    @testSetup
    static void makeData(){
        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        Contract contract = new Contract();
        contract.Name = 'Test';
        contract.AccountId = acc.Id;
        contract.Opportunity__c = opp.Id;
        contract.FournisseurPicklist__c = 'Engie';
        contract.Type_offre__c = 'PRIX FIXE';
        contract.StartDate = Date.today();
        contract.ContractTerm = 12;
        contract.Date_echeance__c = Date.today();
        contract.Budget_TTC_annee__c = 1000;
        contract.Budget_HTVA_annee__c = 1000;
        contract.Commission_ADE__c = 1000;
        contract.Commission_globale__c = 1000;
        insert contract;

        Appel_facturation__c AF = new Appel_facturation__c();
        AF.Contrat__c = contract.Id;
        AF.Montant__c = 1000;
        AF.paye__c = 'ADE';
        AF.Statut__c = 'En attente de validation ADV';
        AF.Mois_facturation_concerne__c = Date.newInstance(2024,6,1);
        insert AF;
    }

    @isTest
    static void getAppelFacturation() {
        Test.startTest();
        List<Appel_facturation__c> results = AP023_CheckContratsFournisseurController.getAppelFacturation('Engie','06','2024');
        Test.stopTest();
        Assert.isTrue(results.size() == 1);
    }

    @isTest
    static void updateAppelFacturation() {
        Test.startTest();
        Date moisFacturation = Date.newInstance(2024,6,1);
        Boolean result = AP023_CheckContratsFournisseurController.updateAppelFacturation('Engie','06','2024');
        Appel_facturation__c AF = [SELECT Id,Statut__c FROM Appel_facturation__c WHERE Mois_facturation_concerne__c = :moisFacturation][0];
        Test.stopTest();
        Assert.isTrue(result == true);
        Assert.isTrue(AF.Statut__c == 'OK pour facturation');
    }
}