force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Duree_offre__c.field-meta.xml
<CustomField>
    <fullName>Duree_offre__c</fullName>
    <label>Durée de l&apos;offre souhaitée</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 mois</fullName>
            </value>
            <value>
                <fullName>24 mois</fullName>
            </value>
            <value>
                <fullName>36 mois</fullName>
            </value>
            <value>
                <fullName>Durée max</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP031_GetDateIndispo_TEST.cls
@isTest
private class AP031_GetDateIndispo_TEST {

    @testSetup
    static void makeData(){
        TestDataFactory.createAccountsWithOppsAndPointDenergie(1,1,1,1,1);
        String uniqueString = String.valueOf(Datetime.now()).right(5).replace(':','');

        User user = new User(
            Alias = 'mgr2',
            Email='manager2221154785'+uniqueString+'@example.com',
            EmailEncodingKey='UTF-8',
            LastName='Manager2',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId=UserInfo.getProfileId(),
            TimeZoneSidKey='Europe/Paris',
            Username='manager2221154785'+uniqueString+'@example.com',
            CompanyName = 'notADE',
            Phone = '06 41 23 56 87'
        );

        insert user;

        Account acc = new Account(Name = 'TestAccount_KO', OwnerId = user.Id);
        insert acc;

        DateTime rdvDate = DateTime.now();
        Date targetDate = rdvDate.date();
        Contact c = new Contact(FirstName='Test', LastName='Contact', AccountId=acc.Id);
        insert c;

        Integer limite = AP028_CheckNbDemandeCotationFromFlow.getLimiteNbDossier(targetDate);

        System.debug('limite '+limite);

        List<Demande_Cotation__c> demandes = new List<Demande_Cotation__c>();
        for (Integer i = 0; i < limite + 1; i++) {
            demandes.add(new Demande_Cotation__c(
                Account__c = acc.Id,
                Date_RDV_Client__c = rdvDate,
                Statut__c = 'En attente de traitement',
                Date_demande_cotation__c = Date.today(),
                Duree_offre__c = '12 mois',
                Charge_affaire__c = UserInfo.getUserId(),
                Signataire__c = c.Id
            ));
        }
        insert demandes;
    }

    @isTest
    static void testGetDatesIndisponiblesKO() {

        AP031_GetDateIndispo.FlowInputs input = new AP031_GetDateIndispo.FlowInputs();
        input.UserCompany = 'notADE';

        Test.startTest();
        List<AP031_GetDateIndispo.FlowOutput> result = AP031_GetDateIndispo.GetDatesIndisponibles(new List<AP031_GetDateIndispo.FlowInputs>{input});
        Test.stopTest();

        //System.assertEquals(true, result[0].DMLSuccess, 'Le DML doit échouer car le nombre de DC dépasse la limite');
    }

    @isTest
    static void testGetDatesIndisponiblesOK() {

        List<Demande_Cotation__c> ddc = [Select Id, Name From Demande_Cotation__c Limit 3];

        AP031_GetDateIndispo.FlowInputs input = new AP031_GetDateIndispo.FlowInputs();
        input.UserCompany = 'notADE';

        Test.startTest();
        delete ddc;
        List<AP031_GetDateIndispo.FlowOutput> result = AP031_GetDateIndispo.GetDatesIndisponibles(new List<AP031_GetDateIndispo.FlowInputs>{input});
        Test.stopTest();

        System.assertEquals(false, result[0].DMLSuccess, 'Le DML doit réussir car le nombre de DC ne dépasse pas la limite');
    }


}