force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/Appel_facturation__c.object-meta.xml
<CustomObject>
    <label>Appel à facturation</label>
    <nameField>
        <label>Nom de Appel à facturation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appels à facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_facturation__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <label>Contrat</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Appels à facturation</relationshipLabel>
    <relationshipName>Appels_facturation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Mois_facturation_concerne__c.field-meta.xml
<CustomField>
    <fullName>Mois_facturation_concerne__c</fullName>
    <label>Mois de facturation concerné</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de validation ADV</fullName>
                <default>true</default>
                <label>En attente de validation ADV</label>
            </value>
            <value>
                <fullName>OK pour facturation</fullName>
            </value>
            <value>
                <fullName>Appel à facturation émis</fullName>
            </value>
            <value>
                <fullName>En attente de paiement</fullName>
                <isActive>false</isActive>
                <label>En attente de paiement</label>
            </value>
            <value>
                <fullName>Payé</fullName>
                <isActive>false</isActive>
                <label>Payé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/recordTypes/Commission.recordType-meta.xml
<RecordType>
    <fullName>Commission</fullName>
    <active>true</active>
    <label>Commission</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Siret_payeur__c.field-meta.xml
<CustomField>
    <fullName>Siret_payeur__c</fullName>
    <inlineHelpText>Si plusieurs SIRET payeur renseigner &apos;MULTI-PAYEUR&apos;</inlineHelpText>
    <label>Siret payeur</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/TECH_Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>TECH_Fournisseur__c</fullName>
    <formula>IF(ISBLANK(TEXT(Entite_facturation__c)),TEXT(FournisseurPicklist__c),TEXT(Entite_facturation__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_Fournisseur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP023_CheckContratsFournisseurController.cls
public with sharing class AP023_CheckContratsFournisseurController {
    @AuraEnabled
    public static List<Appel_facturation__c> getAppelFacturation(String fournisseur,String mois,String annee){
        Date dateMin = Date.newInstance(Integer.valueOf(annee),Integer.valueOf(mois),1);
        Date dateMax = dateMin.addMonths(1);
        return [SELECT  Id,
                        Contrat__r.Name,
                        Contrat__r.Account.Name,
                        Montant__c,
                        Contrat__r.Charge_affaire__r.Name,
                        Contrat__r.Siret_payeur__c
                    FROM Appel_facturation__c 
                    WHERE Contrat__r.TECH_Fournisseur__c = :fournisseur 
                    AND Mois_facturation_concerne__c >= :dateMin
                    AND Mois_facturation_concerne__c < :dateMax
                    AND recordType.Name = 'Commission'];
    }

    @AuraEnabled
    public static Boolean updateAppelFacturation(String fournisseur,String mois,String annee){
        List<Appel_facturation__c> listAFToUpdate = getAppelFacturation(fournisseur,mois,annee);
        for(Appel_facturation__c af : listAFToUpdate){
            af.Statut__c = 'OK pour facturation';
        }
        List<Database.SaveResult> listSR = Database.update(listAFToUpdate,false);
        for(Database.SaveResult sr : listSR){
            if (!sr.isSuccess()) {
                System.debug(sr.getErrors());
                return false;
            }
        }
        return true;
    }

    
}