force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Syndic.recordType-meta.xml
<RecordType>
    <fullName>Syndic</fullName>
    <active>true</active>
    <label>Syndic</label>
</RecordType>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Liste_fournisseurs__c.field-meta.xml
<CustomField>
    <fullName>Liste_fournisseurs__c</fullName>
    <label>Choix fournisseurs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Simple_C1C2C3C4.recordType-meta.xml
<RecordType>
    <fullName>Simple_C1C2C3C4</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <description>Opportunités possédant peu de points d&apos;énergie C1C2C3C4</description>
    <label>Simple C1C2C3C4</label>
</RecordType>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/PCE_Refonte__c.field-meta.xml
<CustomField>
    <fullName>PCE_Refonte__c</fullName>
    <label>PCE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_num_compteur__c.field-meta.xml
<CustomField>
    <fullName>TECH_num_compteur__c</fullName>
    <formula>IF( NOT(ISBLANK(PCE_Refonte__c)) , PCE_Refonte__c, ReferencePointEnergie_Refonte__c)</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/DureeEngagement__c.field-meta.xml
<CustomField>
    <fullName>DureeEngagement__c</fullName>
    <label>Durée d&apos;engagement (en mois)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Nouvelle_Echeance__c.field-meta.xml
<CustomField>
    <fullName>Nouvelle_Echeance__c</fullName>
    <label>Nouvelle échéance</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP014_APIEndesa_Test.cls
@isTest
public class AP014_APIEndesa_Test {

    @TestSetup
    static void makeData(){
        TestDataFactory.createAccountsWithOppsAndPointDenergie(1,1,1,1,1);
    }

	@isTest
    static void getPrixGazEndesaEntiteJuridiquePrincipale(){
        Test.setMock(HttpCalloutMock.class, new API_EndesaCalloutMock());
        Account acc = [SELECT Id,Name FROM Account];
        RecordType rt = [SELECT Id from RecordType WHERE DeveloperName = 'Simple_C1C2C3C4'];

        //Demande de cotation avec signataire
        Contact con  = [SELECT Id from Contact WHERE AccountId=: acc.Id limit 1];
        Demande_Cotation__c DDC = new Demande_Cotation__c();
        DDC.Name = acc.Name;
        DDC.Account__c = acc.Id;
        DDC.Date_RDV_Client__c = Date.today();
        DDC.Signataire__c = con.Id;
        DDC.Charge_affaire__c = UserInfo.getUserId()    ;
        DDC.Statut__c = 'Gagnée';
        DDC.Date_demande_cotation__c = Datetime.now();

        Database.SaveResult sr = Database.insert(ddc);

        //opp
        Opportunity opp = [SELECT Id FROM Opportunity];
        opp.RecordTypeId = rt.Id;
        opp.Liste_Fournisseurs__c = 'Endesa';
        opp.Demande_Cotation__c = DDC.ID;
        update opp;

        
        //listOPR
        List<OpportunityPDERelation__c> listOPR = [SELECT Id FROM OpportunityPDERelation__c WHERE Opportunity__c =: opp.Id];
        
        //listSites
        List<PDE__c> listPDE = [SELECT Id,TECH_num_compteur__c FROM PDE__c WHERE EntiteJuridique__c =:acc.Id AND TypePDE__c ='Gaz'];
        for(PDE__c pde: listPDE){
            pde.DateEcheance__c = Date.today().addYears(1);
            pde.PCE_Refonte__c = 'GI010111';
        }
        update listPDE;

        List<WrapSitesAPIEndesa> listPDEInput = new List<WrapSitesAPIEndesa>();
        for(PDE__c pde: listPDE){
            WrapSitesAPIEndesa tmp = new WrapSitesAPIEndesa();
            tmp.pce = pde.PCE_Refonte__c;
            tmp.mandat_grdf = true;
            tmp.commission = 1;
            listPDEInput.add(tmp);
        }

        System.debug('listPDEInput '+ listPDEInput);
        //quote
        Quote quoteEndesa = [SELECT Id FROM Quote WHERE OpportunityId =: opp.Id AND Fournisseur__c = 'Endesa'];
        List<QuoteLineItem> listQLIToUpdate = new List<QuoteLineItem>([SELECT Id FROM QuoteLineItem WHERE QuoteId=:quoteEndesa.Id]); 
        for(QuoteLineItem qli : listQLIToUpdate){
            qli.DureeEngagement__c = 12;
            qli.Nouvelle_Echeance__c =  Date.today().addYears(1);
        }
        update listQLIToUpdate;
        //typeOffre
        String typeOffre = 'A1';


        List<AP014_APIEndesa.FlowInput> flowInputs = new list<AP014_APIEndesa.FlowInput>();
        AP014_APIEndesa.FlowInput flowInput = new AP014_APIEndesa.FlowInput();
        flowInput.quote = quoteEndesa;
        flowInput.acc = acc;
        flowInput.opp = opp;
        flowInput.listOPR = listOPR;
        flowInput.listSites = listPDEInput;
        flowInput.type_offre = typeOffre;
        flowInput.duree_offre = string.valueOf(Date.today());
        flowInput.type_paiement = 1;
        flowInput.recordId = quoteEndesa.Id;
        flowInputs.add(flowInput);
        Test.startTest();
        List<AP014_APIEndesa.FlowOutput> outputs = AP014_APIEndesa.GET_PrixGaz(flowInputs);
        Test.stopTest();
    }

    @isTest
    static void getPrixGazEndesaSyndic(){
        Test.setMock(HttpCalloutMock.class, new API_EndesaCalloutMock());
        RecordType rtSyndic,rtCopro;
        rtSyndic = [SELECT Id FROM RecordType WHERE DeveloperName = 'Syndic'];
        rtCopro = [SELECT Id FROM RecordType WHERE DeveloperName = 'Copropriete'];

        Account syndic = new Account(Name='Syndic');
        syndic.RecordTypeId = rtSyndic.Id;
        insert syndic;

        Account acc = [SELECT Id,Name FROM Account WHERE Name <> 'Syndic'];
        acc.RecordTypeId = rtCopro.Id;
        acc.Syndic__c = syndic.Id;
        update acc;

        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Simple_C1C2C3C4'];

        //Demande de cotation avec signataire
        Contact con  = [SELECT Id from Contact WHERE AccountId=: acc.Id limit 1];
        Demande_Cotation__c DDC = new Demande_Cotation__c();
        DDC.Name = acc.Name;
        DDC.Account__c = acc.Id;
        DDC.Date_RDV_Client__c = Date.today();
        DDC.Signataire__c = con.Id;
        DDC.Charge_affaire__c = UserInfo.getUserId()    ;
        DDC.Statut__c = 'Gagnée';
        DDC.Date_demande_cotation__c = Datetime.now();

        Database.SaveResult sr = Database.insert(ddc);

        //opp
        Opportunity opp = [SELECT Id FROM Opportunity];
        opp.RecordTypeId = rt.Id;
        opp.Liste_Fournisseurs__c = 'Endesa';
        opp.Demande_Cotation__c = DDC.ID;
        update opp;

        //listOPR
        List<OpportunityPDERelation__c> listOPR = [SELECT Id FROM OpportunityPDERelation__c WHERE Opportunity__c =: opp.Id];
        
        //listSites
        List<PDE__c> listPDE = [SELECT Id,TECH_num_compteur__c FROM PDE__c WHERE EntiteJuridique__c =:acc.Id AND TypePDE__c ='Gaz'];
        for(PDE__c pde: listPDE){
            pde.DateEcheance__c = Date.today().addYears(1);
            pde.PCE_Refonte__c = 'GI010111';
        }
        update listPDE;

        List<WrapSitesAPIEndesa> listPDEInput = new List<WrapSitesAPIEndesa>();
        for(PDE__c pde: listPDE){
            WrapSitesAPIEndesa tmp = new WrapSitesAPIEndesa();
            tmp.pce = pde.PCE_Refonte__c;
            tmp.mandat_grdf = true;
            tmp.commission = 1;
            listPDEInput.add(tmp);
        }

        System.debug('listPDEInput '+ listPDEInput);
        //quote
        Quote quoteEndesa = [SELECT Id FROM Quote WHERE OpportunityId =: opp.Id AND Fournisseur__c = 'Endesa'];
        List<QuoteLineItem> listQLIToUpdate = new List<QuoteLineItem>([SELECT Id FROM QuoteLineItem WHERE QuoteId=:quoteEndesa.Id]); 
        for(QuoteLineItem qli : listQLIToUpdate){
            qli.DureeEngagement__c = 12;
            qli.Nouvelle_Echeance__c =  Date.today().addYears(1);
        }
        update listQLIToUpdate;
        //typeOffre
        String typeOffre = 'A1';


        List<AP014_APIEndesa.FlowInput> flowInputs = new list<AP014_APIEndesa.FlowInput>();
        AP014_APIEndesa.FlowInput flowInput = new AP014_APIEndesa.FlowInput();
        flowInput.quote = quoteEndesa;
        flowInput.acc = acc;
        flowInput.opp = opp;
        flowInput.listOPR = listOPR;
        flowInput.listSites = listPDEInput;
        flowInput.type_offre = typeOffre;
        flowInput.duree_offre = string.valueOf(Date.today());
        flowInput.type_paiement = 1;
        flowInput.recordId = quoteEndesa.Id;
        flowInputs.add(flowInput);
        Test.startTest();
        List<AP014_APIEndesa.FlowOutput> outputs = AP014_APIEndesa.GET_PrixGaz(flowInputs);
        Test.stopTest();
    }

    @isTest
    static void getPrixGazEndesaError(){
        Test.setMock(HttpCalloutMock.class, new API_EndesaCalloutMockError());
        Account acc = [SELECT Id,Name FROM Account];
        RecordType rt = [SELECT Id from RecordType WHERE DeveloperName = 'Simple_C1C2C3C4'];

        //Demande de cotation avec signataire
        Contact con  = [SELECT Id from Contact WHERE AccountId=: acc.Id limit 1];
        Demande_Cotation__c DDC = new Demande_Cotation__c();
        DDC.Name = acc.Name;
        DDC.Account__c = acc.Id;
        DDC.Date_RDV_Client__c = Date.today();
        DDC.Signataire__c = con.Id;
        DDC.Charge_affaire__c = UserInfo.getUserId()    ;
        DDC.Statut__c = 'Gagnée';
        DDC.Date_demande_cotation__c = Datetime.now();

        Database.SaveResult sr = Database.insert(ddc);

        //opp
        Opportunity opp = [SELECT Id FROM Opportunity];
        opp.RecordTypeId = rt.Id;
        opp.Liste_Fournisseurs__c = 'Endesa';
        opp.Demande_Cotation__c = DDC.ID;
        update opp;

        
        //listOPR
        List<OpportunityPDERelation__c> listOPR = [SELECT Id FROM OpportunityPDERelation__c WHERE Opportunity__c =: opp.Id];
        
        //listSites
        List<PDE__c> listPDE = [SELECT Id,TECH_num_compteur__c FROM PDE__c WHERE EntiteJuridique__c =:acc.Id AND TypePDE__c ='Gaz'];
        for(PDE__c pde: listPDE){
            pde.DateEcheance__c = Date.today().addYears(1);
            pde.PCE_Refonte__c = 'GI010111';
        }
        update listPDE;

        List<WrapSitesAPIEndesa> listPDEInput = new List<WrapSitesAPIEndesa>();
        for(PDE__c pde: listPDE){
            WrapSitesAPIEndesa tmp = new WrapSitesAPIEndesa();
            tmp.pce = pde.PCE_Refonte__c;
            tmp.mandat_grdf = true;
            tmp.commission = 1;
            listPDEInput.add(tmp);
        }

        System.debug('listPDEInput '+ listPDEInput);
        //quote
        Quote quoteEndesa = [SELECT Id FROM Quote WHERE OpportunityId =: opp.Id AND Fournisseur__c = 'Endesa'];
        List<QuoteLineItem> listQLIToUpdate = new List<QuoteLineItem>([SELECT Id FROM QuoteLineItem WHERE QuoteId=:quoteEndesa.Id]); 
        for(QuoteLineItem qli : listQLIToUpdate){
            qli.DureeEngagement__c = 12;
            qli.Nouvelle_Echeance__c =  Date.today().addYears(1);
        }
        update listQLIToUpdate;
        //typeOffre
        String typeOffre = 'A1';


        List<AP014_APIEndesa.FlowInput> flowInputs = new list<AP014_APIEndesa.FlowInput>();
        AP014_APIEndesa.FlowInput flowInput = new AP014_APIEndesa.FlowInput();
        flowInput.quote = quoteEndesa;
        flowInput.acc = acc;
        flowInput.opp = opp;
        flowInput.listOPR = listOPR;
        flowInput.listSites = listPDEInput;
        flowInput.type_offre = typeOffre;
        flowInput.duree_offre = string.valueOf(Date.today());
        flowInput.type_paiement = 1;
        flowInput.recordId = quoteEndesa.Id;
        flowInputs.add(flowInput);
        Test.startTest();
        List<AP014_APIEndesa.FlowOutput> outputs = AP014_APIEndesa.GET_PrixGaz(flowInputs);
        Test.stopTest();
    }
}