force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Syndic.recordType-meta.xml
<RecordType>
    <fullName>Syndic</fullName>
    <active>true</active>
    <label>Syndic</label>
</RecordType>

force-app/main/default/objects/Config_Endesa_API_Elec__c/Config_Endesa_API_Elec__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Config Endesa API Elec</label>
</CustomObject>

force-app/main/default/objects/Config_Endesa_API_Elec__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config_Endesa_API_Elec__c/fields/URL_Callback__c.field-meta.xml
<CustomField>
    <fullName>URL_Callback__c</fullName>
    <label>URL Callback</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP022_GetEndesaElecPrice_TEST.cls
@isTest
private class AP022_GetEndesaElecPrice_TEST {
    
    @TestSetup
    static void makeData(){
        Config_Endesa_API_Elec__c config = new Config_Endesa_API_Elec__c(Timeout__c=12000, Username__c='test', Password__c='test',URL_Callback__c='https://test.com');
        insert config;

        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);

        Contact signataire = [SELECT Id FROM Contact LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Demande_Cotation__c dc = new Demande_Cotation__c();
        dc.Account__c = acc.Id;
        dc.Signataire__c = signataire.Id;
        dc.Name = 'Test DC';
        dc.Date_demande_cotation__c = Date.today();
        dc.Statut__c = 'En attente de traitement';
        dc.Charge_affaire__c = UserInfo.getUserId();
        insert dc;

        opp.Demande_Cotation__c = dc.Id;
        update opp;
    }

    @isTest
    static void testGetPricesEntreprise() {
        List<AP022_GetEndesaElecPriceController.FlowInput> inputs = new List<AP022_GetEndesaElecPriceController.FlowInput>();
        
        WrapSiteElecEndesa site = new WrapSiteElecEndesa();
        site.prm = '123456780';
        site.nom = '123456780';
        site.abonnement = 10;
        site.commission = 10;
        site.date_debut = Date.today().format();
        site.date_fin = Date.today().format();
        
        AP022_GetEndesaElecPriceController.FlowInput input = new AP022_GetEndesaElecPriceController.FlowInput();
        input.quote = [SELECT Id FROM Quote LIMIT 1];
        input.sites = new List<WrapSiteElecEndesa>{site};
        input.type_offre = 'Sérénité-1';
        input.date_validite_offre = Date.today().addDays(2);

        inputs.add(input);

        // Créez un mock pour simuler la réponse HTTP de getPrices
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseAPIEndesaElec());

        Test.startTest();
        List<AP022_GetEndesaElecPriceController.FlowOutput> result = AP022_GetEndesaElecPriceController.getPrices(inputs);
        Test.stopTest();

        // Effectuez des assertions pour vérifier le comportement attendu
        System.assertNotEquals(null, result);
    }

    @isTest
    static void testGetPricesCopro() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        RecordType rtSyndic = [SELECT Id FROM RecordType WHERE Name = 'Syndic' LIMIT 1];
        RecordType rtCopro = [SELECT Id FROM RecordType WHERE Name = 'Copropriété' LIMIT 1];
        
        Account syndic = New Account(Name = 'TestSyndic', RecordTypeId = rtSyndic.Id);
        insert syndic;

        acc.RecordTypeId = rtCopro.Id;
        acc.Syndic__c = syndic.Id;
        update acc;

        List<AP022_GetEndesaElecPriceController.FlowInput> inputs = new List<AP022_GetEndesaElecPriceController.FlowInput>();
        
        WrapSiteElecEndesa site = new WrapSiteElecEndesa();
        site.prm = '123456780';
        site.nom = '123456780';
        site.abonnement = 10;
        site.commission = 10;
        site.date_debut = Date.today().format();
        site.date_fin = Date.today().format();
        
        AP022_GetEndesaElecPriceController.FlowInput input = new AP022_GetEndesaElecPriceController.FlowInput();
        input.quote = [SELECT Id FROM Quote LIMIT 1];
        input.sites = new List<WrapSiteElecEndesa>{site};
        input.type_offre = 'Sérénité-1';
        input.date_validite_offre = Date.today().addDays(2);

        inputs.add(input);

        // Créez un mock pour simuler la réponse HTTP de getPrices
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseAPIEndesaElec());

        Test.startTest();
        List<AP022_GetEndesaElecPriceController.FlowOutput> result = AP022_GetEndesaElecPriceController.getPrices(inputs);
        Test.stopTest();

        // Effectuez des assertions pour vérifier le comportement attendu
        System.assertNotEquals(null, result);
    }
}