force-app/main/default/objects/Account/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Ancien client</fullName>
            </value>
            <value>
                <fullName>Perdu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Infos_complementaires__c.field-meta.xml
<CustomField>
    <fullName>Infos_complementaires__c</fullName>
    <label>Infos complémentaires</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP004_ShowOppOnDemandeCotation_TEST.cls
@isTest
private class AP004_ShowOppOnDemandeCotation_TEST {
    
    @testSetup
    static void makeData(){

        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        Contact contact = new Contact();
        contact.LastName = 'Test Contact';
        insert contact;

        Demande_Cotation__c dc = new Demande_Cotation__c();
        dc.Name = acc.Name;
        dc.Account__c = acc.Id;
        dc.Date_RDV_Client__c = null;
        dc.Signataire__c = contact.Id;
        dc.Charge_affaire__c = UserInfo.getUserId();
        dc.Infos_complementaires__c = '';
        dc.Statut__c = 'En attente de traitement';
        dc.Date_demande_cotation__c = Datetime.now();
        insert dc;
    }


    @isTest
    static void testGetOppList(){
        Demande_Cotation__c dc = [SELECT Id FROM Demande_Cotation__c];

        Test.startTest();
        List<Opportunity> oppList = AP004_ShowOppOnDemandeCotationController.getOppList(dc.Id);
        Test.stopTest();

        Assert.areEqual(0, oppList.size());
    }

    @isTest
    static void testGetQuoteList(){
        Demande_Cotation__c dc = [SELECT Id FROM Demande_Cotation__c];

        Test.startTest();
        List<Quote> quoteList = AP004_ShowOppOnDemandeCotationController.getQuoteList(dc.Id);
        Test.stopTest();

        Assert.areEqual(0, quoteList.size());
    }
}