force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Copropriete.recordType-meta.xml
<RecordType>
    <fullName>Copropriete</fullName>
    <active>true</active>
    <label>Copropriété</label>
</RecordType>

force-app/main/default/objects/Config_Endesa_API_Elec__c/Config_Endesa_API_Elec__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Config Endesa API Elec</label>
</CustomObject>

force-app/main/default/objects/Config_Endesa_API_Elec__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config_Endesa_API_Elec__c/fields/URL_Callback__c.field-meta.xml
<CustomField>
    <fullName>URL_Callback__c</fullName>
    <label>URL Callback</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TECH_Account_Siret__c.field-meta.xml
<CustomField>
    <fullName>TECH_Account_Siret__c</fullName>
    <formula>Account.Siret__c</formula>
    <label>Siret</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Api_error_message__c.field-meta.xml
<CustomField>
    <fullName>Api_error_message__c</fullName>
    <label>Message d&apos;erreur API</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Api_status__c.field-meta.xml
<CustomField>
    <fullName>Api_status__c</fullName>
    <label>API Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demande de prix reçue chez le fournisseur</fullName>
            </value>
            <value>
                <fullName>Demande de prix rejetée par le fournisseur</fullName>
            </value>
            <value>
                <fullName>Demande de prix validée par le fournisseur</fullName>
            </value>
            <value>
                <fullName>Erreur Process Mulesoft</fullName>
            </value>
            <value>
                <fullName>Demande de prix envoyée par Salesforce</fullName>
            </value>
            <value>
                <fullName>Demande de prix en attente d&apos;action manuelle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Maximum_date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Maximum_date_de_fin__c</fullName>
    <label>Maximum date de fin</label>
    <summarizedField>QuoteLineItem.Nouvelle_Echeance__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Minimum_date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Minimum_date_de_debut__c</fullName>
    <label>Minimum date de début</label>
    <summarizedField>QuoteLineItem.DebutDeFourniture__c</summarizedField>
    <summaryForeignKey>QuoteLineItem.QuoteId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Numero_Dossier_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Numero_Dossier_API_Endesa_Elec__c</fullName>
    <label>Numero Dossier API Endesa Elec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Numero_Offre_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Numero_Offre_API_Endesa_Elec__c</fullName>
    <label>Numero Offre API Endesa Elec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TypeOffre__c.field-meta.xml
<CustomField>
    <fullName>TypeOffre__c</fullName>
    <label>Type d&apos;Offre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
                <default>true</default>
                <label>PRIX FIXE</label>
            </value>
            <value>
                <fullName>ARENH</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>SWAP ARENH</fullName>
                <isActive>false</isActive>
                <label>SWAP ARENH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Abonnement_Endesa_Elec_Souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Abonnement_Endesa_Elec_Souhaitee__c</fullName>
    <label>Abonnement Endesa Elec souhaitée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Commission_Endesa_Elec_Souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Commission_Endesa_Elec_Souhaitee__c</fullName>
    <label>Commission Endesa Elec souhaitée</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TECH_PdeReference__c.field-meta.xml
<CustomField>
    <fullName>TECH_PdeReference__c</fullName>
    <formula>PDE__r.TECH_num_compteur__c</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP022_GetEndesaElecPriceController.cls
public with sharing class AP022_GetEndesaElecPriceController {
    private static Config_Endesa_API_Elec__c config = Config_Endesa_API_Elec__c.getInstance();

    @invocableMethod(callout=true label='GET Prix Elec Endesa')
    public static List<FlowOutput> getPrices(List<FlowInput> params) {

        List<FlowOutput> outputs = new List<FlowOutput>();
        FlowOutput output = new FlowOutput();
        FlowInput param = params.get(0);

        // Send the AccessToken request
        String accessToken = getAccessToken();

        // Check the response
        if(accessToken != null) {

            // Get Quote Info
            Quote quote = [ SELECT  Id,
                                    Minimum_date_de_debut__c,
                                    Maximum_date_de_fin__c,
                                    Opportunity.TECH_Account_Siret__c,
                                    Opportunity.Account.Name,
                                    Opportunity.Account.RecordType.Name,
                                    Opportunity.Account.Syndic__r.Name,
                                    Opportunity.Demande_Cotation__r.Signataire__r.Title,
                                    Opportunity.Demande_Cotation__r.Signataire__r.Salutation,
                                    Opportunity.Demande_Cotation__r.Signataire__r.Name,
                                    Opportunity.Demande_Cotation__r.Signataire__r.FirstName,
                                    Opportunity.Demande_Cotation__r.Signataire__r.LastName,
                                    Opportunity.Demande_Cotation__r.Signataire__r.Email,
                                    Opportunity.Demande_Cotation__r.Signataire__r.Phone
                            FROM Quote
                            WHERE Id = :param.quote.Id
                            LIMIT 1];

            // Construct the JSON Body
            Map<String, Object> bodyMap = new Map<String, Object>();
            bodyMap.put('callback_url', config.URL_Callback__c + quote.Id);
            bodyMap.put('siret_siren', quote.Opportunity.TECH_Account_Siret__c);
            bodyMap.put('type_offre', param.type_offre);           
            bodyMap.put('date_debut', quote.Minimum_date_de_debut__c.format());          
            bodyMap.put('date_fin', quote.Maximum_date_de_fin__c.format());        
            bodyMap.put('date_fin_validite', param.date_validite_offre.format());       
            bodyMap.put('prix_unique', 'true');

            // Check RecordTypeName
            if (getTypeProspect(quote.Opportunity.Account.RecordType.Name) == 'Entreprise'){
                Map<String, String> entitePrincipaleMap = new Map<String, String>();
                entitePrincipaleMap.put('raison_sociale', quote.Opportunity.Account.Name);
                entitePrincipaleMap.put('secteur_activite', 'tertiaire');
                entitePrincipaleMap.put('representant_legal', quote.Opportunity.Demande_Cotation__r.Signataire__r.Name + ' - ' + quote.Opportunity.Demande_Cotation__r.Signataire__r.Title);
                entitePrincipaleMap.put('contact_commercial_titre', getContactCommercialTitre(quote.Opportunity.Demande_Cotation__r.Signataire__r.Salutation));
                entitePrincipaleMap.put('contact_commercial_nom', quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName);
                entitePrincipaleMap.put('contact_commercial_prenom', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName);
                entitePrincipaleMap.put('contact_commercial_email', quote.Opportunity.Demande_Cotation__r.Signataire__r.Email);
                entitePrincipaleMap.put('contact_commercial_phone', quote.Opportunity.Demande_Cotation__r.Signataire__r.Phone.deleteWhitespace());

                bodyMap.put('type_prospect', 'Entreprise'); 
                bodyMap.put('entite_principale', entitePrincipaleMap);
            } else {
                Map<String, String> entitePrincipaleMap = new Map<String, String>();
                entitePrincipaleMap.put('raison_sociale', quote.Opportunity.Account.Syndic__r.Name);
                entitePrincipaleMap.put('secteur_activite', 'tertiaire');
                entitePrincipaleMap.put('representant_legal', quote.Opportunity.Demande_Cotation__r.Signataire__r.Name + ' - ' + quote.Opportunity.Demande_Cotation__r.Signataire__r.Title);
                entitePrincipaleMap.put('contact_commercial_titre', getContactCommercialTitre(quote.Opportunity.Demande_Cotation__r.Signataire__r.Salutation));
                entitePrincipaleMap.put('contact_commercial_nom', quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName);
                entitePrincipaleMap.put('contact_commercial_prenom', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName);
                entitePrincipaleMap.put('contact_commercial_email', quote.Opportunity.Demande_Cotation__r.Signataire__r.Email);
                entitePrincipaleMap.put('contact_commercial_phone', quote.Opportunity.Demande_Cotation__r.Signataire__r.Phone.deleteWhitespace());

                Map<String, String> entiteSecondaireMap = new Map<String, String>();
                entiteSecondaireMap.put('raison_sociale', quote.Opportunity.Account.Name);
                entiteSecondaireMap.put('secteur_activite', 'tertiaire');
                entiteSecondaireMap.put('representant_legal', quote.Opportunity.Demande_Cotation__r.Signataire__r.Name + ' - ' + quote.Opportunity.Demande_Cotation__r.Signataire__r.Title);
                entiteSecondaireMap.put('contact_commercial_titre', getContactCommercialTitre(quote.Opportunity.Demande_Cotation__r.Signataire__r.Salutation));
                entiteSecondaireMap.put('contact_commercial_nom', quote.Opportunity.Demande_Cotation__r.Signataire__r.LastName);
                entiteSecondaireMap.put('contact_commercial_prenom', quote.Opportunity.Demande_Cotation__r.Signataire__r.FirstName);
                entiteSecondaireMap.put('contact_commercial_email', quote.Opportunity.Demande_Cotation__r.Signataire__r.Email);
                entiteSecondaireMap.put('contact_commercial_phone', quote.Opportunity.Demande_Cotation__r.Signataire__r.Phone.deleteWhitespace());

                bodyMap.put('type_prospect', 'Copropriete'); 
                bodyMap.put('entite_principale', entitePrincipaleMap);
                bodyMap.put('entite_secondaire', entiteSecondaireMap);
            }

            bodyMap.put('sites', param.sites);

            // Price callout
            HttpRequest req = new HttpRequest();
            HttpResponse res = new HttpResponse();
            Http http = new Http();

            // Setup Request
            req.setEndpoint('callout:Endesa_Elec/api/api-offre-elec/2.0/');
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json');
            req.setHeader('Accept', 'application/json');
            req.setHeader('Authorization', 'Bearer ' + accessToken);
            req.setTimeout((Integer)config.Timeout__c);
            req.setBody(JSON.serialize(bodyMap));

            System.debug('bodyMap ' + JSON.serialize(bodyMap));
            try {
                // Send the Price request
                res = http.send(req);
            
                // Check the response
                if (res.getStatusCode() == 200) {
                    System.debug('response ' + res.getBody());
                    // Infos demandée à Endesa
                    wrapperPrice response = (wrapperPrice)JSON.deserialize(res.getBody(), wrapperPrice.class);
                    output.StatusCode = res.getStatusCode();
                    output.response = updateQliWithApiResponse(response, param);
                } else {
                    output.StatusCode = res.getStatusCode();
                    output.response = res.getBody();
                }
            } catch (Exception e) {
                output.StatusCode = null;
                output.response = 'Erreur ' + e.getMessage();
            }
        } else {
            output.StatusCode = null;
            output.response = 'Erreur accessToken';
        }
        outputs.add(output);
        return outputs;
    }

    /*
    * Helpers
    */
    public static String getAccessToken() {
        // AccessToken callout
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();

        req.setEndpoint('callout:Endesa_Elec/api/login/');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept', 'application/json');
        req.setTimeout((Integer)config.Timeout__c);

        Map<String, String> bodyMap = new Map<String, String>();
        bodyMap.put('username', config.Username__c);
        bodyMap.put('password', config.Password__c);

        req.setBody(JSON.serialize(bodyMap));

        try {
            // Send the AccessToken request
            res = http.send(req);
        
            // Check the response
            if (res.getStatusCode() == 200) {
                // Request was successful
                API_Endesa_Elec_Token resToken = (API_Endesa_Elec_Token)JSON.deserialize(res.getBody(), API_Endesa_Elec_Token.class);
                return resToken.login.access_token;
            } else {
                return null;
            }
        } catch (Exception e) {
            return null;
        }
    }

    private static String getTypeProspect(String recordTypeName) {
        return recordTypeName == 'Entité Juridique Principale' ? 'Entreprise' : 'Copropriete';
    }

    private static String getContactCommercialTitre(String Salutation) {
        return Salutation == 'Monsieur' ? 'Mr' : 'Mme';
    }

    private static String updateQliWithApiResponse(wrapperPrice apiResponse, FlowInput param) {

        List<QuoteLineItem> qliToUpdate = new List<QuoteLineItem>();
        
        Quote quoteToUpdate = new Quote();
        quoteToUpdate.Id = param.quote.Id;
        quoteToUpdate.Numero_Dossier_API_Endesa_Elec__c = apiResponse.num_dossier;
        quoteToUpdate.Numero_Offre_API_Endesa_Elec__c = '';
        quoteToUpdate.Api_status__c = 'Demande de prix envoyée par Salesforce';
        quoteToUpdate.Api_error_message__c = '';

        if (param.type_offre == 'Prix fixe marché-1')  {
            quoteToUpdate.TypeOffre__c = 'PRIX FIXE';
        } else if (param.type_offre == 'Simplicité-1' || param.type_offre == 'Sérénité-1') {
            quoteToUpdate.TypeOffre__c = 'ARENH SANS ÉCRÊTEMENT';
        } else {
            quoteToUpdate.TypeOffre__c = 'ARENH AVEC ÉCRÊTEMENT';
        }

        // Infos demandée à Endesa
        Map<String,WrapSiteElecEndesa> mapSiteFromFlow = new Map<String,WrapSiteElecEndesa>();
        for (WrapSiteElecEndesa siteFromFlow : param.sites) {
            mapSiteFromFlow.put(siteFromFlow.prm, siteFromFlow);
        }

        for (QuoteLineItem qli : [SELECT Id, TECH_PdeReference__c FROM QuoteLineItem WHERE QuoteId = :param.quote.Id]) {

            // Update QLI
            QuoteLineItem newQLI = new QuoteLineItem();
            newQLI.Id = qli.Id;
            newQLI.Abonnement_Endesa_Elec_Souhaitee__c = mapSiteFromFlow.get(qli.TECH_PdeReference__c).abonnement;
            newQLI.Commission_Endesa_Elec_Souhaitee__c = mapSiteFromFlow.get(qli.TECH_PdeReference__c).commission;

            qliToUpdate.add(newQLI);
        }

        // Update QLI
        List<Database.SaveResult> listSRQLI = Database.update(qliToUpdate);
        for(Database.SaveResult sr : listSRQLI){
            if (!sr.isSuccess()) {
                for(Database.Error err : sr.getErrors()){
                    System.debug(err);
                }
                return 'Erreur Update QLI';
            }
        }

        // Update Quote
        Database.SaveResult srQuote = Database.update(quoteToUpdate);
        if (!srQuote.isSuccess()) {
            for(Database.Error err : srQuote.getErrors()){
                System.debug(err);
            }
            return 'Erreur Update Quote';
        }

        return 'Demande de prix envoyée avec succes !';
    }

    /*
    * Wrappers
    */
    private class API_Endesa_Elec_Token {
        public String last_name;
	    public String first_name;
	    public String email;
	    public Login login;
    }

    private class Login {
        public String access_token;
        public String client_id;
        public String client_secret;
        public String refresh_token;
    }

    private class wrapperPrice {
        public String num_dossier;
        public String message;
        public String code;
    }

    public class FlowInput {
        @invocableVariable public Quote quote;
        @invocableVariable public List<WrapSiteElecEndesa> sites;
        @invocableVariable public String type_offre;
        @invocableVariable public Date date_validite_offre;
    }

    public class FlowOutput {
        @InvocableVariable public Integer StatusCode;
        @InvocableVariable public String response;
    }
}