force-app/main/default/objects/Account/fields/Syndic__c.field-meta.xml
<CustomField>
    <fullName>Syndic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Syndic</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Copropriétés</relationshipLabel>
    <relationshipName>Coproprietes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Consommation_Annuelle_de_R_f_rence_Elec__c.field-meta.xml
<CustomField>
    <fullName>Consommation_Annuelle_de_R_f_rence_Elec__c</fullName>
    <label>CAR Elec</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Contrat_actif__c.field-meta.xml
<CustomField>
    <fullName>Contrat_actif__c</fullName>
    <formula>IF(AND(NOT(ISNULL(DateEcheanceContract__c)), TODAY()&lt;= DateEcheanceContract__c), true, false)</formula>
    <inlineHelpText>Ce champs signifie que le PDE est associé à un contrat signé par ADE/PWE dont la date de fin de contrat n&apos;est pas encore dépassée.</inlineHelpText>
    <label>Contrat actif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/EntiteJuridique__c.field-meta.xml
<CustomField>
    <fullName>EntiteJuridique__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Un pde ne peut pas être rattaché à un Syndic</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>notEqual</operation>
            <value>Syndic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>PDE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Siret_payeur__c.field-meta.xml
<CustomField>
    <fullName>Siret_payeur__c</fullName>
    <label>Siret payeur</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_num_compteur__c.field-meta.xml
<CustomField>
    <fullName>TECH_num_compteur__c</fullName>
    <formula>IF( NOT(ISBLANK(PCE_Refonte__c)) , PCE_Refonte__c, ReferencePointEnergie_Refonte__c)</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShowPDECoproController.cls
public with sharing class ShowPDECoproController {
  @AuraEnabled
  public static List<PDE__c> retrievePDE(String recordId) {
    List<Id> listCopros = new List<Id>();
    for (Account acc : [SELECT Id FROM Account WHERE Syndic__c = :recordId]) {
      listCopros.add(acc.Id);
    }
    return [
      SELECT
        Id,
        Name,
        Siret_payeur__c,
        EntiteJuridique__c,
        EntiteJuridique__r.Name,
        Contrat_actif__c,
        CARGaz__c,
        TECH_num_compteur__c,
        Consommation_Annuelle_de_R_f_rence_Elec__c,
        TypePDE__c,
        DateEcheance__c
      FROM PDE__c
      WHERE EntiteJuridique__c IN :listCopros
    ];
  }

  @AuraEnabled
  public static Boolean deletePDERowAction(List<String> listPDEId) {
    List<PDE__c> listPDEToDelete = [
      SELECT Id, EntiteJuridique__r.Syndic__c
      FROM PDE__c
      WHERE Id IN :listPDEId
    ];
    System.debug('listToDElete '+listPDEToDelete.size());
    if (listPDEToDelete.size() > 0) {
      Database.DeleteResult[] srList = Database.delete(listPDEToDelete, false);
      for (Database.DeleteResult sr : srList) {
        if (!sr.isSuccess()) {
          return false;
        }
      }
      return true;
    }
    return false;
  }
}