force-app/main/default/objects/Config_Endesa_API_Elec__c/Config_Endesa_API_Elec__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Config Endesa API Elec</label>
</CustomObject>

force-app/main/default/objects/Config_Endesa_API_Elec__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config_Endesa_API_Elec__c/fields/URL_Callback__c.field-meta.xml
<CustomField>
    <fullName>URL_Callback__c</fullName>
    <label>URL Callback</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Numero_Offre_API_Endesa_Elec__c.field-meta.xml
<CustomField>
    <fullName>Numero_Offre_API_Endesa_Elec__c</fullName>
    <label>Numero Offre API Endesa Elec</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP022_ValidEndesaEllecOffer_TEST.cls
@isTest
private class AP022_ValidEndesaEllecOffer_TEST {
    
    @TestSetup
    static void makeData(){
        Config_Endesa_API_Elec__c config = new Config_Endesa_API_Elec__c(Timeout__c=12000, Username__c='test', Password__c='test', URL_Callback__c='https://test.com');
        insert config;

        TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);

        Quote quote = [SELECT Id, Numero_Offre_API_Endesa_Elec__c FROM Quote LIMIT 1];
        quote.Numero_Offre_API_Endesa_Elec__c = '202404273814'; 
        update quote;
    }

    @isTest
    static void testValidOffer() {

        // Créez un mock pour simuler la réponse HTTP de validOffer
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseAPIEndesaElec());

        Test.startTest();
        List<AP022_ValidEndesaElecOfferController.FlowOutput> result = AP022_ValidEndesaElecOfferController.validOffer(new List<String>{'202404273821'});
        Test.stopTest();

        System.debug('result ' + result);

        // Effectuez des assertions pour vérifier le comportement attendu
        System.assertNotEquals(null, result);
    
    }
}