force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_Cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Charge_affaire__c.field-meta.xml
<CustomField>
    <fullName>Charge_affaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chargé d&apos;affaire</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Administrateur Système, Cotation User</value>
        </filterItems>
        <filterItems>
            <field>User.FirstName</field>
            <operation>contains</operation>
            <value>Shai</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Concurrence_identifiee__c.field-meta.xml
<CustomField>
    <fullName>Concurrence_identifiee__c</fullName>
    <label>Concurrence identifiée</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
            <value>
                <fullName>Ne sais pas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_demande_cotation__c.field-meta.xml
<CustomField>
    <fullName>Date_demande_cotation__c</fullName>
    <label>Date de demande de cotation</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_Client__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_Client__c</fullName>
    <label>Date RDV Client</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Date_RDV_reactualisation__c.field-meta.xml
<CustomField>
    <fullName>Date_RDV_reactualisation__c</fullName>
    <description>Date de RDV pour la réactualisation d&apos;un dossier</description>
    <label>Date RDV de réactualisation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Duree_offre__c.field-meta.xml
<CustomField>
    <fullName>Duree_offre__c</fullName>
    <label>Durée de l&apos;offre souhaitée</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12 mois</fullName>
            </value>
            <value>
                <fullName>24 mois</fullName>
            </value>
            <value>
                <fullName>36 mois</fullName>
            </value>
            <value>
                <fullName>Durée max</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Infos_complementaires__c.field-meta.xml
<CustomField>
    <fullName>Infos_complementaires__c</fullName>
    <label>Infos complémentaires</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Infos_reactualisation__c.field-meta.xml
<CustomField>
    <fullName>Infos_reactualisation__c</fullName>
    <label>Infos réactualisation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Marge__c.field-meta.xml
<CustomField>
    <fullName>Marge__c</fullName>
    <label>Rémunération</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Marge_souhaitee__c.field-meta.xml
<CustomField>
    <fullName>Marge_souhaitee__c</fullName>
    <label>Marge souhaitée</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Marge minimale</fullName>
            </value>
            <value>
                <fullName>Marge moyenne</fullName>
            </value>
            <value>
                <fullName>Marge maximale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Offre_Renouvellement__c.field-meta.xml
<CustomField>
    <fullName>Offre_Renouvellement__c</fullName>
    <label>Offre de renouvellement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oui</fullName>
            </value>
            <value>
                <fullName>Non</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Signataire__c.field-meta.xml
<CustomField>
    <fullName>Signataire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Signataire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Demandes de cotation</relationshipLabel>
    <relationshipName>Demandes_de_cotation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Specificite_offre__c.field-meta.xml
<CustomField>
    <fullName>Specificite_offre__c</fullName>
    <label>Spécificité de l&apos;offre</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/TECH_Owner_Manger_Mail__c.field-meta.xml
<CustomField>
    <fullName>TECH_Owner_Manger_Mail__c</fullName>
    <label>Manager Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Demande_Cotation__c.field-meta.xml
<CustomField>
    <fullName>Demande_Cotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demande de cotation</label>
    <referenceTo>Demande_Cotation__c</referenceTo>
    <relationshipLabel>Points d&apos;énergie</relationshipLabel>
    <relationshipName>Points_energie</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP007_CloneDemandeCotationController.cls
public without sharing class AP007_CloneDemandeCotationController {
    
    @AuraEnabled(cacheable=true)
    public static Demande_Cotation__c getDemandeCotation(Id demandeCotationId){
        // list<Demande_Cotation__c> demandeCotations = [SELECT Name FROM Demande_Cotation__c WHERE Id = :demandeCotationId];
        // return demandeCotations.size() > 0 ? demandeCotations : null;
        return [SELECT Name,Date_RDV_reactualisation__c FROM Demande_Cotation__c WHERE Id = :demandeCotationId][0];
    }

    @AuraEnabled
    public static Demande_Cotation__c cloneDemandeCotation(Id demandeCotationId, String newName, Datetime newDateRDV){
        try {
            System.debug('newRDV '+newDateRDV);
            List<PDE__c> listPDEs = [SELECT Id FROM PDE__c WHERE Demande_Cotation__c = :demandeCotationId];
            List<Opportunity> listOpps = [SELECT Id FROM Opportunity WHERE Demande_Cotation__c = :demandeCotationId];

            Demande_Cotation__c dcPerimee = [SELECT OwnerId, 
                                                    Name, 
                                                    RecordTypeId, 
                                                    CreatedDate, 
                                                    CreatedById,
                                                    Concurrence_identifiee__c,
                                                    Duree_offre__c,
                                                    Date_RDV_Client__c,
                                                    LastModifiedDate, 
                                                    LastModifiedById, 
                                                    LastActivityDate, 
                                                    Charge_affaire__c, 
                                                    Infos_complementaires__c,
                                                    Infos_reactualisation__c,
                                                    Statut__c, 
                                                    Account__c, 
                                                    Date_demande_cotation__c, 
                                                    Marge__c,
                                                    Marge_souhaitee__c,
                                                    Offre_Renouvellement__c,
                                                    Specificite_offre__c, 
                                                    Signataire__c,
                                                    TECH_Owner_Manger_Mail__c
                                            FROM Demande_Cotation__c 
                                            WHERE Id = :demandeCotationId][0];
            
            Demande_Cotation__c dcClone = dcPerimee.clone(false, true, true, true);
            dcClone.Name= newName;
            dcClone.Statut__c = 'En cours de traitement';
            dcClone.Date_demande_cotation__c = Datetime.now();
            dcClone.Date_RDV_Client__c = newDateRDV;

            Database.SaveResult sr = Database.insert(dcClone, true);

            if(sr.isSuccess()) {
                if (!listOpps.isEmpty()) {
                    for (Opportunity opp : listOpps) {
                        opp.Demande_Cotation__c = dcClone.Id;
                    }
                    update listOpps;
                }
                
                if (!listPDEs.isEmpty()) {
                    for (PDE__c pde : listPDEs) {
                        pde.Demande_Cotation__c = dcClone.Id;
                    }
                    update listPDEs;
                }

                dcPerimee.Statut__c = 'Clonée';
                update dcPerimee;
            }


            return dcClone;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}