force-app/main/default/objects/Demande_Cotation__c/Demande_Cotation__c.object-meta.xml
<CustomObject>
    <label>Demande de cotation</label>
    <nameField>
        <label>Demande de cotation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demandes de cotation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demande_Cotation__c/fields/Societe_du_commercial__c.field-meta.xml
<CustomField>
    <fullName>Societe_du_commercial__c</fullName>
    <formula>Owner:User.CompanyName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Société du commercial</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En attente de traitement</fullName>
            </value>
            <value>
                <fullName>Validée</fullName>
            </value>
            <value>
                <fullName>En cours de traitement</fullName>
            </value>
            <value>
                <fullName>Comparatif prêt</fullName>
                <label>Comparatif(s) prêt(s)</label>
            </value>
            <value>
                <fullName>En attente de retour client</fullName>
            </value>
            <value>
                <fullName>Demande de réactualisation</fullName>
            </value>
            <value>
                <fullName>Refusée</fullName>
            </value>
            <value>
                <fullName>Clonée</fullName>
            </value>
            <value>
                <fullName>Perdue</fullName>
                <label>DDC Perdue</label>
            </value>
            <value>
                <fullName>Client Perdu</fullName>
            </value>
            <value>
                <fullName>En attente validation fournisseur</fullName>
            </value>
            <value>
                <fullName>Gagnée</fullName>
            </value>
            <value>
                <fullName>Périmée</fullName>
                <isActive>false</isActive>
                <label>Périmée</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demande_Cotation__c/fields/TECH_Date_RDV_Reactu__c.field-meta.xml
<CustomField>
    <fullName>TECH_Date_RDV_Reactu__c</fullName>
    <formula>IF(ISNULL(Date_RDV_reactualisation__c),Date_RDV_Client__c,Date_RDV_reactualisation__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de RDV ou de réactualisation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Limite_Defaut_DDC__c/Limite_Defaut_DDC__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Limite Defaut DDC</label>
</CustomObject>

force-app/main/default/objects/Limite_Defaut_DDC__c/fields/max_dossier_defaut__c.field-meta.xml
<CustomField>
    <fullName>max_dossier_defaut__c</fullName>
    <label>max dossier defaut</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limite_DemandeCotation__mdt/Limite_DemandeCotation__mdt.object-meta.xml
<CustomObject>
    <label>Limite DemandeCotation</label>
    <pluralLabel>Limite DemandeCotations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limite_DemandeCotation__mdt/fields/date_debut__c.field-meta.xml
<CustomField>
    <fullName>date_debut__c</fullName>
    <label>date debut</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Limite_DemandeCotation__mdt/fields/date_fin__c.field-meta.xml
<CustomField>
    <fullName>date_fin__c</fullName>
    <label>date fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Limite_DemandeCotation__mdt/fields/nb_dossier__c.field-meta.xml
<CustomField>
    <fullName>nb_dossier__c</fullName>
    <label>nb dossier</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partenaires_hors_limite_DDC_par_jour__mdt/Partenaires_hors_limite_DDC_par_jour__mdt.object-meta.xml
<CustomObject>
    <description>Liste des partenaires qui ne comptent pas dans le calcul du nombre de cotation par jour</description>
    <label>Partenaire hors limite DDC par jour</label>
    <pluralLabel>Partenaires hors limite DDC par jour</pluralLabel>
</CustomObject>

force-app/main/default/classes/AP028_CheckNbDemandeCotationFromFlow.cls
public without sharing class AP028_CheckNbDemandeCotationFromFlow {

    public static Integer getLimiteNbDossier(Date dateCible) {

        Integer retour = 200;
        List<Limite_DemandeCotation__mdt> limites = [
            SELECT Nb_dossier__c, Date_debut__c, Date_fin__c
            FROM Limite_DemandeCotation__mdt
            WHERE Date_debut__c <= :dateCible AND Date_fin__c >= :dateCible
            ];

        if (!limites.isEmpty()) {
            System.debug('limite trouvée ');
            System.debug('Integer.valueOf(limites[0].Nb_dossier__c)  '+Integer.valueOf(limites[0].Nb_dossier__c));

            return Integer.valueOf(limites[0].Nb_dossier__c);
        }

        Limite_Defaut_DDC__c config = Limite_Defaut_DDC__c.getInstance();

        if (config != null && config.max_dossier_defaut__c != null) {
            retour = Integer.valueOf(config.max_dossier_defaut__c);
        }

        return retour;
    }
    
    @invocableMethod(label='Vérification nombre de dossier vente indirecte')
    public static List<FlowOutput> checkNbDossier(List<FlowInputs> params) {
        System.debug('### LIGOT' + params);
        FlowInputs param = params[0];
        FlowOutput output = new FlowOutput();
        List<FlowOutput> outputs = new List<FlowOutput>();

        Date targetDate = param.DateRDVClient.date();
        DateTime startOfDay = DateTime.newInstanceGMT(targetDate, Time.newInstance(0, 0, 0, 0));
        DateTime endOfDay = startOfDay.addDays(1);

        Integer limiteNbDossier = getLimiteNbDossier(targetDate);
        Set<String> setPartenairesExclus = new Set<String>();
        
        for (Partenaires_hors_limite_DDC_par_jour__mdt partenaire : [SELECT Label
            FROM Partenaires_hors_limite_DDC_par_jour__mdt ]) {
            setPartenairesExclus.add(partenaire.Label);
        }
        setPartenairesExclus.add('ADE');

        if (param.UserCompany != 'ADE') {

            List<AggregateResult> demandes = [
                SELECT count(id) NombreDeDDCPourleJour
                FROM Demande_Cotation__c
                WHERE 
                    TECH_Date_RDV_Reactu__c >= :startOfDay
                AND TECH_Date_RDV_Reactu__c <= :endOfDay
                AND Societe_du_commercial__c NOT IN :setPartenairesExclus
                AND Statut__c <> 'Refusée'
            ];

            Integer nbDossiersLeJour = Integer.valueOf(demandes.get(0).get('NombreDeDDCPourleJour'));
            System.debug('### nbDossiersLeJour ' + nbDossiersLeJour);
            System.debug('### limiteDossiersLeJour ' + limiteNbDossier);
            
            if (nbDossiersLeJour >= limiteNbDossier) {
                output.DMLSuccess = false;
                output.ErrorMessage = 'Notre planning est complet, Veuillez choisir une autre date pour le rendez-vous client';
            } else {
                output.DMLSuccess = true;
            }

            outputs.add(output);
            return outputs;
        }

        return null;
    
    }



    public class FlowInputs {
        @invocableVariable public String UserCompany;
        @invocableVariable public DateTime DateRDVClient;

    }
    
    public class FlowOutput {
        @InvocableVariable
        public Boolean DMLSuccess;
        @InvocableVariable
        public String ErrorMessage;
    }

}