force-app/main/default/objects/Appel_facturation__c/Appel_facturation__c.object-meta.xml
<CustomObject>
    <label>Appel à facturation</label>
    <nameField>
        <label>Nom de Appel à facturation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appels à facturation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appel_facturation__c/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <label>Contrat</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Appels à facturation</relationshipLabel>
    <relationshipName>Appels_facturation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Mois_facturation_concerne__c.field-meta.xml
<CustomField>
    <fullName>Mois_facturation_concerne__c</fullName>
    <label>Mois de facturation concerné</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/fields/Montant__c.field-meta.xml
<CustomField>
    <fullName>Montant__c</fullName>
    <label>Montant</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Appel_facturation__c/recordTypes/Commission.recordType-meta.xml
<RecordType>
    <fullName>Commission</fullName>
    <active>true</active>
    <label>Commission</label>
</RecordType>

force-app/main/default/objects/Contract/fields/CAR__c.field-meta.xml
<CustomField>
    <fullName>CAR__c</fullName>
    <label>CAR</label>
    <summarizedField>Prix_contrat_PDE__c.CAR__c</summarizedField>
    <summaryForeignKey>Prix_contrat_PDE__c.Contract__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_ADE__c.field-meta.xml
<CustomField>
    <fullName>Commission_ADE__c</fullName>
    <label>Commission ADE €</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Entite_facturation__c.field-meta.xml
<CustomField>
    <fullName>Entite_facturation__c</fullName>
    <label>Entité de facturation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FournisseurPicklist__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENGIE E &amp; C</fullName>
            </value>
            <value>
                <fullName>ENGIE GC PRIVE</fullName>
            </value>
            <value>
                <fullName>ENGIE GC PUBLIC</fullName>
            </value>
            <value>
                <fullName>ENGIE PRO</fullName>
            </value>
            <value>
                <fullName>SEFE Energy</fullName>
            </value>
            <value>
                <fullName>SEFE INCUBATEUR</fullName>
            </value>
            <value>
                <fullName>PRIMEO ENERGIE PEF</fullName>
            </value>
            <value>
                <fullName>PRIMEO ENERGIE PEGC</fullName>
            </value>
            <value>
                <fullName>Endesa</fullName>
            </value>
            <value>
                <fullName>ENDESA GC</fullName>
            </value>
            <value>
                <fullName>TOTAL HORIZON</fullName>
            </value>
            <value>
                <fullName>TOTAL GC</fullName>
            </value>
            <value>
                <fullName>VATTENFALL BLEU PRO</fullName>
            </value>
            <value>
                <fullName>VATTENFALL GC</fullName>
            </value>
            <value>
                <fullName>OHM Grille</fullName>
            </value>
            <value>
                <fullName>OHM Mid Market</fullName>
            </value>
            <value>
                <fullName>OHM GC</fullName>
            </value>
            <value>
                <fullName>Gaz Européen	Paris</fullName>
            </value>
            <value>
                <fullName>Gaz Européen	Lyon</fullName>
            </value>
            <value>
                <fullName>Gaz Européen	Sud</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Sud-Ouest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/FournisseurPicklist__c.field-meta.xml
<CustomField>
    <fullName>FournisseurPicklist__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Marge_Mwh_T1__c.field-meta.xml
<CustomField>
    <fullName>Marge_Mwh_T1__c</fullName>
    <label>Marge globale €/Mwh T1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Marge_Mwh_T2__c.field-meta.xml
<CustomField>
    <fullName>Marge_Mwh_T2__c</fullName>
    <label>Marge globale €/Mwh T2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Marge_Mwh_T3__c.field-meta.xml
<CustomField>
    <fullName>Marge_Mwh_T3__c</fullName>
    <label>Marge globale €/Mwh T3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Marge_Mwh_T4__c.field-meta.xml
<CustomField>
    <fullName>Marge_Mwh_T4__c</fullName>
    <label>Marge globale €/Mwh T4</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Adresse_de_consommation__c.field-meta.xml
<CustomField>
    <fullName>Adresse_de_consommation__c</fullName>
    <formula>NumeroVoie__c &amp;&quot; &quot;&amp; voie__c &amp;&quot; &quot;&amp; Code_Postal__c &amp;&quot; &quot;&amp; Ville__c</formula>
    <label>Adresse de consommation</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Entite_facturation__c.field-meta.xml
<CustomField>
    <fullName>Entite_facturation__c</fullName>
    <label>Entité de facturation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fournisseur__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ENGIE E &amp; C</fullName>
            </value>
            <value>
                <fullName>ENGIE GC PRIVE</fullName>
            </value>
            <value>
                <fullName>ENGIE GC PUBLIC</fullName>
            </value>
            <value>
                <fullName>ENGIE PRO</fullName>
            </value>
            <value>
                <fullName>SEFE Energy</fullName>
            </value>
            <value>
                <fullName>SEFE INCUBATEUR</fullName>
            </value>
            <value>
                <fullName>PRIMEO ENERGIE PEF</fullName>
            </value>
            <value>
                <fullName>PRIMEO ENERGIE PEGC</fullName>
            </value>
            <value>
                <fullName>Endesa</fullName>
            </value>
            <value>
                <fullName>ENDESA GC</fullName>
            </value>
            <value>
                <fullName>TOTAL HORIZON</fullName>
            </value>
            <value>
                <fullName>TOTAL GC</fullName>
            </value>
            <value>
                <fullName>VATTENFALL BLEU PRO</fullName>
            </value>
            <value>
                <fullName>VATTENFALL GC</fullName>
            </value>
            <value>
                <fullName>OHM Grille</fullName>
            </value>
            <value>
                <fullName>OHM Mid Market</fullName>
            </value>
            <value>
                <fullName>OHM GC</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Paris</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Lyon</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Sud</fullName>
            </value>
            <value>
                <fullName>Gaz Européen Sud-Ouest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/Prix_contrat_PDE__c.object-meta.xml
<CustomObject>
    <label>Prix contrat PDE</label>
    <nameField>
        <label>Nom de Prix contrat PDE</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prix contrat PDE</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/CAR__c.field-meta.xml
<CustomField>
    <fullName>CAR__c</fullName>
    <label>CAR</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Prix contrat PDE</relationshipLabel>
    <relationshipName>Prix_contrat_PDE</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/Numero_compteur__c.field-meta.xml
<CustomField>
    <fullName>Numero_compteur__c</fullName>
    <label>Numéro de compteur</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/fields/Point_energie__c.field-meta.xml
<CustomField>
    <fullName>Point_energie__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Prix contrat PDE</relationshipLabel>
    <relationshipName>Prix_contrat_PDE</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prix_contrat_PDE__c/recordTypes/Gaz.recordType-meta.xml
<RecordType>
    <fullName>Gaz</fullName>
    <active>true</active>
    <label>Gaz</label>
</RecordType>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP035_FacturationGazEuroCSVController.cls
public with sharing class AP035_FacturationGazEuroCSVController {
    public class CsvResult {
        @AuraEnabled
        public String csv;
        @AuraEnabled
        public Boolean hasData;

        public CsvResult(String csv, Boolean hasData) {
            this.csv = csv;
            this.hasData = hasData;
        }
    }

    @AuraEnabled(cacheable=false)
    public static CsvResult generateCSV(
        Integer monthNumber,
        Integer yearNumber
    ) {
        List<Appel_facturation__c> lstAAF;

        if (monthNumber == 0) {
            lstAAF = [
                SELECT
                    Id,
                    Name,
                    Montant__c,
                    Contrat__c,
                    Contrat__r.Name,
                    Contrat__r.Account.Name,
                    Contrat__r.Entite_facturation__c,
                    Contrat__r.StartDate,
                    Contrat__r.ContractTerm,
                    Contrat__r.CAR__c,
                    Contrat__r.Marge_Mwh_T1__c,
                    Contrat__r.Marge_Mwh_T2__c,
                    Contrat__r.Marge_Mwh_T3__c,
                    Contrat__r.Marge_Mwh_T4__c,
                    Contrat__r.Commission_ADE__c,
                    Contrat__r.FournisseurPicklist__c
                FROM Appel_facturation__c
                WHERE
                    CALENDAR_YEAR(Mois_facturation_concerne__c) = :yearNumber
                    AND Contrat__r.FournisseurPicklist__c = 'Gaz Européen'
            ];
        } else {
            lstAAF = [
                SELECT
                    Id,
                    Name,
                    Montant__c,
                    Contrat__c,
                    Contrat__r.Name,
                    Contrat__r.Account.Name,
                    Contrat__r.Entite_facturation__c,
                    Contrat__r.StartDate,
                    Contrat__r.ContractTerm,
                    Contrat__r.CAR__c,
                    Contrat__r.Marge_Mwh_T1__c,
                    Contrat__r.Marge_Mwh_T2__c,
                    Contrat__r.Marge_Mwh_T3__c,
                    Contrat__r.Marge_Mwh_T4__c,
                    Contrat__r.Commission_ADE__c,
                    Contrat__r.FournisseurPicklist__c
                FROM Appel_facturation__c
                WHERE
                    CALENDAR_MONTH(Mois_facturation_concerne__c) = :monthNumber
                    AND CALENDAR_YEAR(
                        Mois_facturation_concerne__c
                    ) = :yearNumber
                    AND Contrat__r.FournisseurPicklist__c = 'Gaz Européen'
            ];
        }

        if (lstAAF.isEmpty()) {
            return new CsvResult(buildHeader(), false);
        }

        Set<Id> setContractIds = new Set<Id>();
        for (Appel_facturation__c aaf : lstAAF) {
            if (aaf.Contrat__c != null) setContractIds.add(aaf.Contrat__c);
        }

        Map<Id, Prix_contrat_PDE__c> pdeByContract = new Map<Id, Prix_contrat_PDE__c>();
        if (!setContractIds.isEmpty()) {
            for (Prix_contrat_PDE__c p : [
                SELECT
                    Id,
                    Contract__c,
                    Numero_compteur__c,
                    Point_energie__r.Adresse_de_consommation__c
                FROM Prix_contrat_PDE__c
                WHERE Contract__c IN :setContractIds
            ]) {
                if (!pdeByContract.containsKey(p.Contract__c)) {
                    pdeByContract.put(p.Contract__c, p);
                }
            }
        }

        String csv = buildHeader();

        for (Appel_facturation__c aaf : lstAAF) {
            Prix_contrat_PDE__c pde = pdeByContract.get(aaf.Contrat__c);

            if (pde == null) {
                continue;
            }

            csv +=
                safe(aaf.Contrat__r.Entite_facturation__c) + ';' +                          // Entité de facturation
                safe(aaf.Contrat__r.Account.Name) + ';' +                                   // Nom du représentant
                safe(pde.Numero_compteur__c) + ';' +                                        // PDE
                safe(pde.Point_energie__r.Adresse_de_consommation__c) + ';' +               // Adresse du site
                safe(aaf.Contrat__r.CAR__c) + ';' +                                         // Volume prévisionnel
                safe(formatDate(aaf.Contrat__r.StartDate)) + ';' +                          // Début contrat
                safe(aaf.Contrat__r.ContractTerm) + ';' +                                   // Durée
                ((aaf.Contrat__r.Marge_Mwh_T1__c == null) ? '' :
                    String.valueOf(aaf.Contrat__r.Marge_Mwh_T1__c / 2)) + ';' +             // Marge T1                                                                                                                           
                ((aaf.Contrat__r.Marge_Mwh_T2__c == null) ? '' :
                    String.valueOf(aaf.Contrat__r.Marge_Mwh_T2__c / 2)) + ';' +             // Marge T2
                ((aaf.Contrat__r.Marge_Mwh_T3__c == null) ? '' :
                    String.valueOf(aaf.Contrat__r.Marge_Mwh_T3__c / 2)) + ';' +             // Marge T3
                ((aaf.Contrat__r.Marge_Mwh_T4__c == null) ? '' :
                    String.valueOf(aaf.Contrat__r.Marge_Mwh_T4__c / 2)) + ';' +             // Marge T4
                safe(aaf.Montant__c) + ';' +                                                // Montant
                safe(aaf.Contrat__r.Commission_ADE__c) + ';' +                              // Commission ADE
                safe(aaf.Contrat__r.Name) +                                                 // Numéro contrat
                '\n';
        }

        return new CsvResult(csv, true);
    }

    private static String buildHeader() {
        return 'Entité de facturation;Nom du représentant;PDE;Adresse du site;Volume (prévisionnel);' +
               'Date de démarrage du contrat;Durée du contrat;Marge T1;Marge T2;Marge T3;Marge T4;' +
               'Montant;Commission ADE;Numéro de contrat\n';
    }

    private static String safe(Object v) {
        return v == null ? '' : String.valueOf(v);
    }

    private static String formatDate(Date d) {
        return d == null ? '' : d.format(); 
    }
}