force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>L&apos;objet Log__c permet de suivre et d&apos;enregistrer les mises à jour des points d&apos;énergie, ainsi que d&apos;identifier la personne ayant effectué la mise à jour.</description>
    <label>Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/ActionDate__c.field-meta.xml
<CustomField>
    <fullName>ActionDate__c</fullName>
    <label>ActionDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ce champs contient l&apos;id de l&apos;user courant</description>
    <label>CurrentUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Date_ACD__c.field-meta.xml
<CustomField>
    <fullName>Date_ACD__c</fullName>
    <label>Date ACD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/NumeroCompteur__c.field-meta.xml
<CustomField>
    <fullName>NumeroCompteur__c</fullName>
    <label>NumeroCompteur</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SGE</fullName>
            </value>
            <value>
                <fullName>HOMEYS_TURPE</fullName>
                <label>HOMEYS TURPE</label>
            </value>
            <value>
                <fullName>GAZEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Utils.cls
public class Utils {

  public static String toCurrency(Decimal p_ammount) {
    if(p_ammount == null){
      return '0 €';
    }
    List<String> args = new List<String>{ '0', 'number', '###,###,##0.00' };
    List<String> argsNegative = new List<String>{ '- 0', 'number', '###,###,##0.00' };
    String result = '';
    try {
      if( p_ammount < 0 ){
        result = String.format(p_ammount.format(), argsNegative) + ' €';
      }
      else{
        result = String.format(p_ammount.format(), args) + ' €';
      }
    } catch (Exception error) {
    }

    return result;
  }

  @AuraEnabled
  public static boolean isCommunity(){
    Id siteId = Site.getSiteId(); // take a look at the apex class Site, you may find more useful method concerning site/community
    if (siteId != null) {
        return true;
    }
    return false;
  }
    /*
     *La méthode logSGE crée et enregistre un enregistrement Log__c pour suivre une mise à jour d’un point d'énergie,
     *en associant le numéro de compteur, les dates d’action, l’utilisateur actuel et l’identifiant du point d’énergie concerné. 
     */
  @future
  public static void logSGE(String numeroCompteur, Date DateACD, Datetime ActionDate,Id idPDE){
      
      Log__c log = new Log__c();
      log.Name = 'LOG SGE '+ UserInfo.getLastName() + ' ' + UserInfo.getFirstName() + ' '+ numeroCompteur;
      log.NumeroCompteur__c = numeroCompteur;
      log.currentUser__c = UserInfo.getUserId();
      log.Date_ACD__c = DateACD;
      log.Type__c= 'SGE';
      log.ActionDate__c = ActionDate;
      log.Pde__c = idPDE;
      System.debug(' The current user is : '+log.currentUser__r.Name);
      Database.SaveResult result = Database.insert(log, false);

      if (!result.isSuccess()) {
          System.debug(' Erreur lors de l’insertion du log : ' + result.getErrors()[0].getMessage());
      }else {
            System.debug('insertion reussi');
      }

    }
  
  public static void logSGEDocusign(String numeroCompteur, Date DateACD, Datetime ActionDate,Id idPDE,Id ownerId){
    System.debug('logSGEDocusign');
    Log__c log = new Log__c();
    log.Name = 'LOG SGE Signature ACD Docusign ' + numeroCompteur;
    log.NumeroCompteur__c = numeroCompteur;
    log.currentUser__c = ownerId;
    log.Date_ACD__c = DateACD;
    log.Type__c= 'SGE';
    log.ActionDate__c = ActionDate;
    log.Pde__c = idPDE;
    Database.SaveResult result = Database.insert(log, false);

    if (!result.isSuccess()) {
        System.debug(' Erreur lors de l’insertion du log : ' + result.getErrors()[0].getMessage());
    }else {
          System.debug('insertion reussi');
    }
  }


  public static String generateCodePartenaire() {
    Blob b = Crypto.GenerateAESKey(128);
    String s = EncodingUtil.ConvertTohex(b);
    String code = s.SubString(0,8)+ '-' + s.SubString(8,15);
    return code;
  }

  @AuraEnabled
  public static String getSobjectTypeName(Id id){
    return id.getSobjectType().getDescribe().getName();
  }
}