force-app/main/default/objects/ApiLogEvent__e/ApiLogEvent__e.object-meta.xml
<CustomObject>
    <label>ApiLogEvent</label>
    <pluralLabel>ApiLogEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApiLogEvent__e/fields/ApexMethod__c.field-meta.xml
<CustomField>
    <fullName>ApexMethod__c</fullName>
    <label>ApexMethod</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiLogEvent__e/fields/CurrentUser__c.field-meta.xml
<CustomField>
    <fullName>CurrentUser__c</fullName>
    <label>CurrentUser</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiLogEvent__e/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApiLogEvent__e/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <label>ResponseBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ApiLogEvent__e/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApiLogEvent__e/fields/Verb__c.field-meta.xml
<CustomField>
    <fullName>Verb__c</fullName>
    <label>Verb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApiLogger.cls
public class ApiLogger {
    public static void publish(String method, String type, String endpoint, String reqBody, String resBody, Integer status, String verb, String recordId) {
        
        EventBus.publish(new ApiLogEvent__e(
            ApexMethod__c = method,
            CurrentUser__c = UserInfo.getUserId(),
            Endpoint__c = endpoint,
            RequestBody__c = reqBody?.left(131072),
            ResponseBody__c = resBody?.left(131072),
            StatusCode__c = status,
            Type__c = type,
            Verb__c = verb,
            RecordId__c = recordId
        ));
    }
}