force-app/main/default/objects/Opportunity/fields/Nombre_de_PDE__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_PDE__c</fullName>
    <label>Nombre de PDE</label>
    <summaryForeignKey>OpportunityPDERelation__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityPDERelTriggerHandler_Test.cls
@isTest
public with sharing class OpportunityPDERelTriggerHandler_Test {
  @TestSetup
  static void makeData() {
    TestDataFactory.createAccountsWithOppsAndPointDenergie(1, 1, 1, 1, 1);
  }
  @isTest
  private static void AfterCreateTest() {
    Test.startTest();
    Opportunity opp = [
      SELECT Id, Nombre_de_PDE__c
      FROM Opportunity
      LIMIT 1
    ];
    Test.stopTest();
    System.assertEquals(3, opp.Nombre_de_PDE__c);
  }

  @isTest
  private static void testAfterDelete() {
    Test.startTest();
    delete [SELECT Id FROM OpportunityPDERelation__c];
    Test.stopTest();
    System.assertEquals(
      0,
      [SELECT Nombre_de_PDE__c FROM Opportunity].Nombre_de_PDE__c
    );
    System.assertEquals(0, [SELECT COUNT() FROM QuoteLineItem]);
  }
}