force-app/main/default/objects/Opportunity/fields/SectionPrixConstates__c.field-meta.xml
<CustomField>
    <fullName>SectionPrixConstates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Prix Constatés</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionPropositionRenouvellement__c.field-meta.xml
<CustomField>
    <fullName>SectionPropositionRenouvellement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Proposition de renouvellement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SectionSituationActuelle__c.field-meta.xml
<CustomField>
    <fullName>SectionSituationActuelle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Section : Situation Actuelle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/Calendrier_fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Calendrier_fournisseur__c</fullName>
    <label>Calendrier fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>HP/HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TypePDE__c.field-meta.xml
<CustomField>
    <fullName>TypePDE__c</fullName>
    <formula>IF(OR(RecordType.DeveloperName=&apos;Elec_C1C2&apos;,RecordType.DeveloperName=&apos;PDE_ElecC5&apos;,
RecordType.DeveloperName=&apos;Elec_C3_C4&apos;), TEXT(Segment__c) ,
IF(RecordType.DeveloperName=&apos;PDE_Gaz&apos;,&apos;Gaz&apos;,null))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type PDE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityPDERelationTriggerHandler.cls
public with sharing class OpportunityPDERelationTriggerHandler extends TriggerHandler {
  private static final String CLASS_NAME = OpportunityPDERelationTriggerHandler.class
    .getName();

  public override void afterInsert() {
    //On ne garde que les opportunités qui ont au moins un devis
    Map<Id, OpportunityPDERelation__c> mapOPRLigneDevis = new Map<Id, OpportunityPDERelation__c>(
      [
        SELECT
          Opportunity__c,
          Opportunity__r.SectionPrixConstates__c,
          Opportunity__r.SectionPropositionRenouvellement__c,
          Opportunity__r.SectionSituationActuelle__c,
          Pde__c,
          Pde__r.DateEcheance__c,
          Pde__r.TypePDE__c,
          Pde__r.ConsoHC__c,
          Pde__r.ConsoHP__c,
          Pde__r.Conso_Base__c,
          Pde__r.Conso_HCE__c,
          Pde__r.Conso_HCH__c,
          Pde__r.Conso_HPE__c,
          Pde__r.Conso_HPH__c,
          Pde__r.Conso_Pointe__c,
          Pde__r.Puissance_souscrite__c,
          Pde__r.CARGaz__c,
          Pde__r.Tarif__c,
          Pde__r.Calendrier_fournisseur__c,
          PDE__r.Segment__c
        FROM OpportunityPDERelation__c
        WHERE
          Id IN :Trigger.New
          AND Opportunity__c IN (SELECT OpportunityId FROM Quote)
      ]
    );
    
    if (!mapOPRLigneDevis.isEmpty()) {
      SM001_GestionDevis.addLigneDevis(mapOPRLigneDevis);
    }
  }

  public override void beforeDelete() {
    Map<Id, OpportunityPDERelation__c> mapOPRLigneDeDevisToDelete = new Map<Id, OpportunityPDERelation__c>(
      [
        SELECT PDE__c, Opportunity__c
        FROM OpportunityPDERelation__c
        WHERE
          Id IN :Trigger.old
          AND Opportunity__c IN (SELECT OpportunityId FROM Quote)
      ]
    );
    if (!mapOPRLigneDeDevisToDelete.isEmpty()) {
      SM001_GestionDevis.deleteLigneDevis(mapOPRLigneDeDevisToDelete);
    }
  }
}