force-app/main/default/objects/Opportunity/fields/TemplateCotation__c.field-meta.xml
<CustomField>
    <fullName>TemplateCotation__c</fullName>
    <label>Template Cotation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C5 4 postes</fullName>
            </value>
            <value>
                <fullName>C1/C2/C3/C4</fullName>
            </value>
            <value>
                <fullName>Gaz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/OpportunityPDERelation__c.object-meta.xml
<CustomObject>
    <description>Objet de jonction entre les objets opportunités et PDE</description>
    <label>Opportunity PDE Relationship</label>
    <nameField>
        <displayFormat>OPR-{0000000}</displayFormat>
        <label>Opportunity PDE Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity PDE Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityPDERelation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityPDERelation__c/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <label>Point d&apos;énergie</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Opportunity PDE Relationships</relationshipLabel>
    <relationshipName>OpportunityPDERelationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PDE__c/PDE__c.object-meta.xml
<CustomObject>
    <description>Point d&apos;Energie</description>
    <label>Point d&apos;énergie</label>
    <nameField>
        <label>Nom du Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Points d&apos;énergie</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PDE__c/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR Gaz</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Consommation_Annuelle_de_R_f_rence_Elec__c.field-meta.xml
<CustomField>
    <fullName>Consommation_Annuelle_de_R_f_rence_Elec__c</fullName>
    <label>CAR Elec</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/DateEcheance__c.field-meta.xml
<CustomField>
    <fullName>DateEcheance__c</fullName>
    <description>Date d&apos;échéance du compteur</description>
    <label>Date d&apos;échéance actuelle</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fournisseur</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <description>ELEC</description>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>C5</fullName>
            </value>
            <value>
                <fullName>C4</fullName>
            </value>
            <value>
                <fullName>C3</fullName>
            </value>
            <value>
                <fullName>C2</fullName>
            </value>
            <value>
                <fullName>C1</fullName>
            </value>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
            <value>
                <fullName>Aucun</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/Tarif__c.field-meta.xml
<CustomField>
    <fullName>Tarif__c</fullName>
    <description>GAZ</description>
    <label>Tarif</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>T1</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>T3</fullName>
            </value>
            <value>
                <fullName>T4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PDE__c/fields/TECH_num_compteur__c.field-meta.xml
<CustomField>
    <fullName>TECH_num_compteur__c</fullName>
    <formula>IF( NOT(ISBLANK(PCE_Refonte__c)) , PCE_Refonte__c, ReferencePointEnergie_Refonte__c)</formula>
    <label>Numéro de compteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fournisseur__c.field-meta.xml
<CustomField>
    <fullName>Fournisseur__c</fullName>
    <label>Fournisseur</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TypeOffre__c.field-meta.xml
<CustomField>
    <fullName>TypeOffre__c</fullName>
    <label>Type d&apos;Offre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRIX FIXE</fullName>
                <default>true</default>
                <label>PRIX FIXE</label>
            </value>
            <value>
                <fullName>ARENH</fullName>
            </value>
            <value>
                <fullName>ARENH AVEC ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>ARENH SANS ÉCRÊTEMENT</fullName>
            </value>
            <value>
                <fullName>PEG</fullName>
            </value>
            <value>
                <fullName>TRV</fullName>
            </value>
            <value>
                <fullName>SWAP ARENH</fullName>
                <isActive>false</isActive>
                <label>SWAP ARENH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/AbonnementMois__c.field-meta.xml
<CustomField>
    <fullName>AbonnementMois__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Abonnement (€/mois)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_Base__c.field-meta.xml
<CustomField>
    <fullName>Capa_Base__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité Base (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HC__c.field-meta.xml
<CustomField>
    <fullName>Capa_HC__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HC (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HCE__c.field-meta.xml
<CustomField>
    <fullName>Capa_HCE__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HCE (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HCH__c.field-meta.xml
<CustomField>
    <fullName>Capa_HCH__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HCH (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HP__c.field-meta.xml
<CustomField>
    <fullName>Capa_HP__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HP (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HPE__c.field-meta.xml
<CustomField>
    <fullName>Capa_HPE__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HPE (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_HPH__c.field-meta.xml
<CustomField>
    <fullName>Capa_HPH__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité HPH (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Capa_Pointes__c.field-meta.xml
<CustomField>
    <fullName>Capa_Pointes__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Capacité Pointes (en €/MWh)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CAR_New__c.field-meta.xml
<CustomField>
    <fullName>CAR_New__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CAR</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CARGaz__c.field-meta.xml
<CustomField>
    <fullName>CARGaz__c</fullName>
    <label>CAR</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Base__c.field-meta.xml
<CustomField>
    <fullName>Conso_Base__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Base</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HCH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HCH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HCH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HPE__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPE__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPE</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_HPH__c.field-meta.xml
<CustomField>
    <fullName>Conso_HPH__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HPH</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Conso_Pointe__c.field-meta.xml
<CustomField>
    <fullName>Conso_Pointe__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso Pointe</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHC__c.field-meta.xml
<CustomField>
    <fullName>ConsoHC__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HC</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ConsoHP__c.field-meta.xml
<CustomField>
    <fullName>ConsoHP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Conso HP</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/PDE__c.field-meta.xml
<CustomField>
    <fullName>PDE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PDE</label>
    <referenceTo>PDE__c</referenceTo>
    <relationshipLabel>Éléments de devis</relationshipLabel>
    <relationshipName>elements_de_devis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Puissance_souscrite__c.field-meta.xml
<CustomField>
    <fullName>Puissance_souscrite__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Puissance souscrite</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Fournisseur.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Dyneff</fullName>
    </customValue>
    <customValue>
        <fullName>Endesa</fullName>
    </customValue>
    <customValue>
        <fullName>Engie</fullName>
    </customValue>
    <customValue>
        <fullName>Enovos</fullName>
    </customValue>
    <customValue>
        <fullName>Gazel Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Gaz Européen</fullName>
    </customValue>
    <customValue>
        <fullName>MET Energie</fullName>
    </customValue>
    <customValue>
        <fullName>OHM Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Picoty</fullName>
    </customValue>
    <customValue>
        <fullName>Primeo Energie</fullName>
    </customValue>
    <customValue>
        <fullName>Save energies</fullName>
    </customValue>
    <customValue>
        <fullName>SEFE Energy</fullName>
    </customValue>
    <customValue>
        <fullName>TotalEnergies</fullName>
    </customValue>
    <customValue>
        <fullName>Vattenfall</fullName>
    </customValue>
    <customValue>
        <fullName>Alpiq</fullName>
    </customValue>
    <customValue>
        <fullName>Alterna</fullName>
    </customValue>
    <customValue>
        <fullName>Antargaz</fullName>
    </customValue>
    <customValue>
        <fullName>Axpo</fullName>
    </customValue>
    <customValue>
        <fullName>Butagaz</fullName>
    </customValue>
    <customValue>
        <fullName>Dalkia</fullName>
    </customValue>
    <customValue>
        <fullName>Edenkia</fullName>
    </customValue>
    <customValue>
        <fullName>EDF Entreprises</fullName>
    </customValue>
    <customValue>
        <fullName>Ekwateur</fullName>
    </customValue>
    <customValue>
        <fullName>élecocité</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Provence</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Savoie</fullName>
    </customValue>
    <customValue>
        <fullName>Electricité de Strasbourg</fullName>
    </customValue>
    <customValue>
        <fullName>Elmy</fullName>
    </customValue>
    <customValue>
        <fullName>Enercoop</fullName>
    </customValue>
    <customValue>
        <fullName>énergem</fullName>
    </customValue>
    <masterLabel>Fournisseur</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AP009_AddPriceFromExcelFileController.cls
public with sharing class AP009_AddPriceFromExcelFileController {
    @AuraEnabled(cacheable=true)
    public static List<Quote> retrieveQuote(String recordId) {
        return [
            SELECT
                Id,
                Fournisseur__c,
                TypeOffre__c
            FROM 
                Quote
            WHERE
            OpportunityId = :recordId
          ];
    }

    @AuraEnabled(cacheable=true)
    public static List<OpportunityPDERelation__c> retrieveOPR(String recordId){
        System.Debug('recordId');
        return [
            SELECT
                PDE__c,
                PDE__r.Consommation_Annuelle_de_R_f_rence_Elec__c,
                PDE__r.CARGaz__c,
                PDE__r.Conso_Base__c,
                PDE__r.ConsoHC__c,
                PDE__r.ConsoHP__c,
                PDE__r.Conso_HCE__c,
                PDE__r.Conso_HCH__c,
                PDE__r.Conso_HPE__c,
                PDE__r.Conso_HPH__c,
                PDE__r.Conso_Pointe__c,
                PDE__r.DateEcheance__c,
                PDE__r.Puissance_souscrite__c,
                PDE__r.TECH_num_compteur__c,
                toLabel(PDE__r.Tarif__c),
                PDE__r.Segment__c,
                Opportunity__r.TemplateCotation__c
            FROM
                OpportunityPDERelation__c
            WHERE
                Opportunity__c =: recordId
        ];
    }

@AuraEnabled(cacheable=true)
    public static List<QuoteLineItem> retrievePriceQLI(String recordId){
        System.Debug('recordId');
        return [
            SELECT
                Id,
                AbonnementMois__c,
                CARGaz__c,
                CAR_New__c,
                Capa_Base__c,
                Capa_Pointes__c,
                Capa_HC__c,
                Capa_HCE__c,
                Capa_HCH__c,
                Capa_HP__c,
                Capa_HPE__c,
                Capa_HPH__c,
                CeeMwh__c,

                Conso_Base__c,
                Conso_Pointe__c,
                ConsoHC__c,
                Conso_HCE__c,
                Conso_HCH__c,
                ConsoHP__c,
                Conso_HPE__c,
                Conso_HPH__c,
                CoutDeCapacite__c,

                DebutDeFourniture__c,


                Puissance_souscrite__c,

                TECH_Segment__c,
                TECH_IdentifiantPDE__c,
                TECH_Tarif__c,
                TECH_fournisseur__c,
                TECH_TypeOffre__c,

                Nouvelle_Echeance__c,

                PointesMWh__c,
                PrixBase__c,
                PrixHC__c,
                PrixHceMwh__c,
                PrixHchMwh__c,
                PrixHP__c,
                PrixHpeMwh__c,
                PrixHphMwh__c,
                PrixMolecule__c,

                QuoteId,
                Quote.Name, 
                Quote.OpportunityId,
                Quote.Opportunity.Name,
                Quote.Opportunity.TemplateCotation__c,

                PDE__c,
                PDE__r.DateEcheance__c

            FROM
                QuoteLineItem
            WHERE
                Quote.OpportunityId =: recordId
        ];
    }


    @AuraEnabled
    public static Boolean insertListQLI(List<QuoteLineItem> qlis,String oppId){
        Boolean allSuccess = true;
        delete [SELECT Id from QuoteLineItem where TECH_OpportunityId__c=: oppId];
        // Insérer les nouvelles QLI
        Database.SaveResult[] srList = Database.insert(qlis, true);
        for (Database.SaveResult sr : srList) {
            if (!sr.isSuccess()) {
                allSuccess = false;
                return allSuccess;
            }
        }
        return allSuccess;
    }

    @AuraEnabled
    public static PricebookEntry getPriceBookEntryGaz(){
        Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
        return [SELECT Product2Id FROM PricebookEntry WHERE Name = 'GAZ' AND Pricebook2Id = :pb.Id LIMIT 1];
    }

    @AuraEnabled
    public static PricebookEntry getPriceBookEntryElec(){
        Pricebook2 pb = [SELECT Id, IsActive, Name FROM Pricebook2 WHERE IsActive = TRUE AND Name = 'AllianceDesEnergies' LIMIT 1];
        return [SELECT Product2Id FROM PricebookEntry WHERE Name = 'ELEC' AND Pricebook2Id = :pb.Id LIMIT 1];
    }
}